### ISSUE TITLE
v5 Notary Allocator Application:

### ISSUE THREAD

**Issue by FroghubMan** [filecoin-project/notary-governance#1003]
# v5 Notary Allocator Application

To apply to be an allocator, organizations will submit one application for each proposed pathway to DataCap. If you will be designing multiple specific pathways, you will need to submit multiple applications. 

Please complete the following steps:
# 1. Fill out the information below and create a new GitHub Issue

1. Notary Allocator Pathway Name (This can be your name, or the name of your pathway/program. For example "E-Fil+"): FrogHub Tech.
3. Organization Name: FrogHub
4. On-chain address for Allocator (Provide a NEW unique address. During ratification, you will need to initialize this address on-chain): f1a7ngs2e6vb2mlwjqjazk44c7dzck5yuslb5tgcy
5. Country of Operation (Where your organization is legally based):  Singapore
6. Region of Operation (What region will you serve?): Asia
7. Type of Allocator, diligence process: (Automated/programmatic, Market-based, or Manual (human-in-the-loop at some phase):  Automated and Market based
9. DataCap requested for allocator for 12 months of activity (This should be an estimate of overall expected activity. Estimate the total amount of DataCap you will be distributing to clients in 12 months, in TiB or PiB): 50Pib

# 2. Access allocator application (download to save answers)
Click link below to access a Google doc version of the allocator application that can be used to save your answers if you are not prepared to fully submit the application in Step 3. https://docs.google.com/document/d/1-Ze8bo7ZlIJe8qX0YSFNPTka4CMprqoNB1D6V7WJJjo/copy

# 3. Submit allocation application 
Clink link below to access full allocator questionnaire and officially submit your answers:
https://airtable.com/appvyE0VHcgpAkt4Z/shrQxaAIsD693e1ns

Note: Sections of your responses WILL BE posted back into the GitHub issue tracking your application. 
The final section (Additional Disclosures) will NOT be posted to GitHub, and will be maintained by the Filecoin Foundation. 
Application information for notaries not accepted and ratified in this round will be deleted.

**Comment by Kevin-FF-USA** [comment]
Hi @FroghubMan 
Wanted to let you know this application has been received. Also verifying you have submitted the Airtable form with your detailed Allocator plan - the public answers will be posted in a thread below soon. If you have any questions - please let me know.

**Comment by Filplus-govteam** [comment]
Providing the information shared in Application for Public Review/Comment.

Basic Info

**1. Pathway Name:**
FrogHub

**2. Organization:**
FrogHub Tech

**3. Allocator's On-chain addresss:**
f1a7ngs2e6vb2mlwjqjazk44c7dzck5yuslb5tgcy

**4. Country of Operation:**
Singapore

**5. Region(s) of operation:**
Asia minus GCR,Greater China,Japan,Europe,North America,Africa

**6. Type of allocator: What is your overall diligence process? Automated (programmatic), Market-based, or Manual (human-in-the-loop at some phase). Initial allocations to these pathways will be capped.**
Manual

**7. Amount of DataCap Requested for allocator for 12 months:**
50Pib

**8. Is your allocator providing a unique, new, or diverse pathway to DataCap? How does this allocator differentiate itself from other applicants, new or existing?**
We use advanced AI data analysis tools to mark all applicants. Delay the allocation speed for some applicants with bad credit. Overall, our configurator is more than just a product; it is a dynamic and evolving solution capable of adapting to today's complex environment.

**9. As a member in the Filecoin Community, I acknowledge that I must adhere to the Community Code of Conduct, as well other End User License Agreements for accessing various tools and services, such as GitHub and Slack. Additionally, I will adhere to all local & regional laws & regulations that may relate to my role as a business partner, organization, notary, or other operating entity.  You can read the Filecoin Code of Conduct here: https://github.com/filecoin-project/community/blob/master/CODE_OF_CONDUCT.md**
Acknowledgment: Acknowledge

**Comment by Filplus-govteam** [comment]
Client Diligence

**10. Who are your target clients?**
Enterprise Data Clients,Small-scale developers or data owners

**11. Describe in as much detail as possible how you will perform due diligence on clients.**
	•	I will determine the authenticity and legality of the client entity.
	•	I will determine whether the customer is the data owner or the data preparer.
	•	I will look at the data sample to check if the data is consistent with the application description.
	•	I will review the number of SP entities and the distribution of data storage.
	•	I will evaluate the client's historical performance.

**12. Please specify how many questions you'll ask, and provide a brief overview of the questions.**
	•	Organization name
	•	Region
	•	Organization type, whether it is a Filecoin miner
	•	Contact information such as slack, telegram, wechat, gmail etc.
	•	Describe how to do the work
	•	Provide information related to cooperative SPs
	•	Whether to use VPN

**13. Will you use a 3rd-party "Know your client" (KYC) service?**
It may be used in the future, but not yet. But I still have some conditions for selecting clients. I would allow new clients to start with fewer applications. For clients with good historical performance, we will support their large-amount applications and strictly review them.

**14. Can any client apply to your pathway, or will you be closed to only your own internal clients? (eg: bizdev or self-referral)**
Of course, I welcome all new clients to join and contribute to Filecoin's storage of real data. At the same time, I will guide them and provide help with issues such as application, data preparation, and data distribution. I hope to help onboard new clients with complete tutorial documentation.

**15. How do you plan to track the rate at which DataCap is being distributed to your clients?**
I considered using a mature, open source client quota monitoring tool to monitor the client's distribution rate. If there is no useful tool, we will develop and open source a monitoring tool to regularly detect the client's distribution rate.

**Comment by Filplus-govteam** [comment]
Data Diligence

**16. As an operating entity in the Filecoin Community, you are required to follow all local & regional regulations relating to any data, digital and otherwise. This may include PII and data deletion requirements, as well as the storing, transmitting, or accessing of data.**
Acknowledgement: Acknowledge

**17. What type(s) of data would be applicable for your pathway?**
Public Open Dataset (Research/Non-Profit),Private Non-Profit/Social Impact,Public Open Commercial/Enterprise,Private Commercial/Enterprise

**18. How will you verify a client's data ownership? Will you use 3rd-party KYB (know your business) service to verify enterprise clients?**
Currently I prefer to authenticate clients storing public datasets. For Clients who store their own private data, I will strictly review the legality of entities (Related entity files may be required), data legality, and data sources. Clients need to provide proof of the number of users and data volume. I will experience the customer's product and guarantee that I will not be cheated.

**19. How will you ensure the data meets local & regional legal requirements?**
I think it is difficult to 100% supervise whether the data complies with the laws of each region. I think I might be more concerned about whether the data is illegal in most places. (For example, I will strictly prohibit data containing pornography, gambling, drugs, etc.)

**20. What types of data preparation will you support or require?**
We have extensive experience in data preparation. Therefore, I can help customers in need in this aspect. I would recommend customers to use the singularity open source tool to complete the data cutting work. We have also customized some functions based on this tool, which I am happy to provide to customers. Hope this helps them.

**21. What tools or methodology will you use to sample and verify the data aligns with your pathway?**
We will verify whether the commp results of different miners refer to the same order under the same LDN are consistent. If singularity is required for data cutting, the cut cars will be consistent. (CIDcommD= PieceCID = Rroposa.RiegeGID in Publish message)

**Comment by Filplus-govteam** [comment]
Data Distribution

**22. How many replicas will you require to meet programmatic requirements for distribution?**
5+

**23. What geographic or regional distribution will you require?**
No less than 5 physical locations. no less than 2 separate geopolitical regions. No less than 3 or more SP entities. Less VPN usage

**24. How many Storage Provider owner/operators will you require to meet programmatic requirements for distribution?**
3+

**25. Do you require equal percentage distribution for your clients to their chosen SPs? Will you require preliminary SP distribution plans from the client before allocating any DataCap?**
I will ask for a preliminary SP allocation plan. But considering the unpredictable factors, I will not force SPs to be allocated in equal percentages, and I am willing to accept clients to add new SPs. The premise is that they must meet the rules of FIL+ and complete KYC.At the same time, it must meet the data distribution requirements I mentioned above.

**26. What tooling will you use to verify client deal-making distribution?**
The existing datacapstats.io tooling

**27. How will clients meet SP distribution requirements?**
I will fully understand the customer's needs for data distribution. If the customer lacks SP in some regions. I will provide customers with a list of some well-performing SPs to promote cooperation. I will maintain a table of SPs, and the data comes from SPs that are already cooperating, or SPs that have performed well in historical audits.

**28. As an allocator, do you support clients that engage in deal-making with SPs utilizing a VPN?**
Before starting, I ask the client if they are using a VPN and I support their use of one. If using a VPN, customers will need to provide documentation proving that the physical devices are not in the same region.

**Comment by Filplus-govteam** [comment]
DataCap Allocation Strategy

**29. Will you use standardized DataCap allocations to clients?**
Yes, standardized

**30. Allocation Tranche Schedule to clients:**
I will divide it into 3 stages. For new clients, allocation of 100-500Tib per LDN is allowed. Good performing clients are allowed to allocate 1-5Pib per LDN. clients with excellent reputation are allowed to allocate 5-15Pib per LDN. The maximum does not exceed 75Pib.

**31. Will you use programmatic or software based allocations?**
Yes, standardized and software based

**32. What tooling will you use to construct messages and send allocations to clients?**
Notary Registry

**33. Describe the process for granting additional DataCap to previously verified clients.**
Use the Subsequent Allocation (SA) bot, manual review

**Comment by Filplus-govteam** [comment]
Tools and Bookkeeping

**34. Describe in as much detail as possible the tools used for: • client discoverability & applications • due diligence & investigation • bookkeeping • on-chain message construction • client deal-making behavior • tracking overall allocator health • dispute discussion & resolution • community updates & comms.**
I will use Google Online Document Classification Records • Due Diligence and Investigation • Bookkeeping • On-chain message construction • Customer trading behavior • Track overall dispenser health and other information.  Dispute discussion & resolution will be conducted directly on github.  community updates & comms *use slack Because we believe that Google Docs, GitHub, and Slack are the tools that community members are most familiar with. If everyone uses their own tools, it will only increase the cost of learning.

**35. Will you use open-source tooling from the Fil+ team?**
Sure, but currently I only use singularity and Notary Registry. If there is a new useful tool. I will use it too.

**36. Where will you keep your records for bookkeeping? How will you maintain transparency in your allocation decisions?**
In order to be responsible for user information, I will disclose the review results of the information provided by customers, the reasons for consent/rejection and other relevant information through Google documents. If a dispute arises, I will provide more details in the google documentation and github.

**Comment by Filplus-govteam** [comment]
Risk Mitigation, Auditing, Compliance

**37. Describe your proposed compliance check mechanisms for your own clients.**
	•	Through the current robot report, first exclude necessary conditions such as CID sharing, number of copies, and repetition rate.
	•	Mark the customer's credit and enter all customer SP nodes into our database. Perform SP scoring based on factors such as retrieval success rate, geographical distribution, number of copies, etc.
	•	Tolerance: Description: relax a little in the first round, and close it in the second round if there is no sign of correction.

**38. Describe your process for handling disputes. Highlight response times, transparency, and accountability mechanisms.**
If there is any dispute, I will respond within 1-2 days (taking into account some uncontrollable factors). I hope that all discussions will be conducted directly under a specific issue. Both the challenger and the person being challenged need to provide comprehensive evidence.

**39. Detail how you will announce updates to tooling, pathway guidelines, parameters, and process alterations.**
Considering that FIL+ applications are all processed on github, I will maintain a public folder under the github account to disclose information such as tooling, pathway guidelines, parameters, and process alterations. Once there is any update, I will append the new file and keep the old file content. It is convenient for anyone to find the previous public information.

**40. How long will you allow the community to provide feedback before implementing changes?**
Once there is an update, I will launch a proposal in the public announcement file I maintain and notify everyone in the slack channel. Community members can discuss different opinions on github. Our department will complete the collection of suggestions and start implementation within 7-10 days.

**41. Regarding security, how will you structure and secure the on-chain notary address? If you will utilize a multisig, how will it be structured? Who will have administrative & signatory rights?**
Consider that rights are not transferred at will like tokens. Also take into account unnecessary multi-party signature confirmation. I would use a hardware wallet(Ledger) to manage it instead of multi-signature. The hardware wallet is kept by the team and signatures are completed by specialists who review the client's application.

**42. Will you deploy smart contracts for program or policy procedures? If so, how will you track and fund them?**
If necessary, I will develop simple smart contracts. But there are currently no plans to do so.

**Comment by Filplus-govteam** [comment]
Monetization

**43. Outline your monetization models for the services you provide as a notary allocator pathway.**
There are currently no plans for monetization.

**44. Describe your organization's structure, such as the legal entity and other business & market ventures.**
Our team is registered in Singapore and is a development team focusing on technology output.

**45. Where will accounting for fees be maintained**
None

**Comment by Filplus-govteam** [comment]
Past Experience, Affiliations, Reputation

**46. If you've received DataCap allocation privileges before, please link to prior notary applications.**
None

**47. How are you connected to the Filecoin ecosystem? Describe your (or your organization's) Filecoin relationships, investments, or ownership.**
Froghub is a completely technical team and an early participant and ecological builder of Filecoin. We have started to understand and participate in Filecoin in 2020, providing technical support for Filecoin mining to many customers and helping them become a qualified storage provider. At the same time, we are also working hard to build ecological projects and provide free and open source tools for community developers.

**48. How are you estimating your client demand and pathway usage? Do you have existing clients and an onboarding funnel?**
We connect with many storage providers and developers. We encourage them to store valuable public data sets on Filecoin. We were proficient in this process, but we hadn’t established an onboarding pipeline yet

**Comment by galen-mcandrew** [comment]
## Datacap Request for Allocator
#### Address
> f2lamsg3cw5d4akdzwxiugwxh4ayk4rxaji7pcsaq
#### Datacap Allocated
> 5PiB
