### ISSUE TITLE
v5 Notary Allocator Application: Starlight

### ISSUE THREAD

**Issue by likkhai-nebula** [filecoin-project/notary-governance#1005]
# v5 Notary Allocator Application

To apply to be an allocator, organizations will submit one application for each proposed pathway to DataCap. If you will be designing multiple specific pathways, you will need to submit multiple applications. 

Please complete the following steps:
# 1. Fill out the information below and create a new GitHub Issue
1. Notary Allocator Pathway Name (This can be your name, or the name of your pathway/program. For example "E-Fil+"):
Starlight (Enterprise Data Management System)

2. Organization Name:
Nebula Data Pte. Ltd.

3. On-chain address for Allocator (Provide a NEW unique address. During ratification, you will need to initialize this address on-chain): 
f1x2dxgsklcbphzup6k5d7ds3ysitez7plxtbyd6a

4. Country of Operation (Where your organization is legally based): 
Singapore

5. Region of Operation (What region will you serve?): 
Worldwide, SEA region in the initial phase.

6. Type of Allocator, diligence process: (Automated/programmatic, Market-based, or Manual (human-in-the-loop at some phase):
Most of our DataCap requests are expected to be initiated from the Starlight Enterprise Data Management System. This system allows enterprises to store their corporate data for extended periods of time for archival and compliance purpose.  
All onboarded enterprise clients will go through our internal KYB process. 
Our clients are charged for all data stored through our platform and DataCap requests are initiated by these enterprise clients through us as their proxy.  

7. DataCap requested for allocator for 12 months of activity (This should be an estimate of overall expected activity. Estimate the total amount of DataCap you will be distributing to clients in 12 months, in TiB or PiB):
5 PiB

# 2. Access allocator application (download to save answers)
Click link below to access a Google doc version of the allocator application that can be used to save your answers if you are not prepared to fully submit the application in Step 3. https://docs.google.com/document/d/1-Ze8bo7ZlIJe8qX0YSFNPTka4CMprqoNB1D6V7WJJjo/copy

# 3. Submit allocation application 
Clink link below to access full allocator questionnaire and officially submit your answers:
https://airtable.com/appvyE0VHcgpAkt4Z/shrQxaAIsD693e1ns

Note: Sections of your responses WILL BE posted back into the GitHub issue tracking your application. 
The final section (Additional Disclosures) will NOT be posted to GitHub, and will be maintained by the Filecoin Foundation. 
Application information for notaries not accepted and ratified in this round will be deleted.

**Comment by likkhai-nebula** [comment]
Please update item 3 (wallet address) to:
f156aar7hywagok2o23bzepkinnl5q2z4vhqdpgmi

**Comment by likkhai-nebula** [comment]
Hi, I have submitted the AirTable form too

**Comment by Kevin-FF-USA** [comment]
Hi @likkhai-nebula,
Wanted to let you know this application has been received. Once you complete and submit the include Airtable (form) information - the public answers will be posted in a thread below soon. If you have any questions - please let me know.

**Comment by likkhai-nebula** [comment]
> Hi @likkhai-nebula, Wanted to let you know this application has been received. Once you complete and submit the include Airtable (form) information - the public answers will be posted in a thread below soon. If you have any questions - please let me know.

Hi @Kevin-FF-USA, Thanks for the notification. We have already completed and submitted the Airtable form. Do let us know of any clarification you have.

**Comment by Filplus-govteam** [comment]
### Basic Information
**1. Notary Allocator Pathway Name:**
Starlight (Enterprise Data Management System)

**2. Organization:**
Nebula Data Pte. Ltd.

**3. On Chain Address for Allocator:**
f156aar7hywagok2o23bzepkinnl5q2z4vhqdpgmi

**4. Country of Operation:**
Singapore

**5. Region(s) of operation:**
Asia minus GCR, Greater China, Africa , Europe, Oceania, Japan, North America, South America, Other

**6. Type of Allocator:**
Automatic

**7. DataCap requested for allocator for 12 months of activity:**
5 PiB

**8. Is your allocator providing a unique, new, or diverse pathway to DataCap? How does this allocator differentiate itself from other applicants, new or existing?:**
As Starlight is an enterprise data management platform, all data stored on the platform belongs to and are paid for by enterprise clients.  

Since these enterprise data can be confidential and sensitive in nature, we are taking additional steps to protect these data: 
- all SPs storing data from Starlight has to be certified by Starlight through an assessment process. Startlight will work out storage fees and workflow with certified SPs 

- all data designated for DataCap allocation will first be uploaded to our cloud servers for encryption.  

- After encryption, we will proceed with data preparation, converting them to CAR files. 

- Finally, based on client requirements, we will select the certified SPs and make the CAR file available for them for sealing and storage 

Due to the enterprise nature of our business, we need to be certain that any data that our clients need to store in the network can be fulfilled. Hence our application to be an allocator for more secure allocation of DataCap. 

**9. As a member in the Filecoin Community, I acknowledge that I must adhere to the Community Code of Conduct, as well other End User License Agreements for accessing various tools and services, such as GitHub and Slack.:**
Acknowledge
### Client Diligence
**10. Who are your target clients?:**
Enterprise Data Clients

**11. Describe in as much detail as possible how you will perform due diligence on clients.  If you are proposing an automated pathway, what diligence mechanism will you use to determine client eligibility?:**
When enterprises sign up for a Starlight account, they have to first onboard their company information to the platform.  

We can have a high degree of certainty that data is relevant since: 

1. During Client onboarding, clients have to first agree to our terms and policies 

2. We will then carry out internal KYB after the clients have registered their business details 

3. Upon successful registration, Clients are also required to provide payment details and purchase storage packages with us  

4. Data are uploaded by Starlight’s enterprise clients to our cloud servers for encryption and data preparation  

5. Storage of data are charged and paid by the enterprise clients  

6. Although, due to confidentiality issue we are not able to read the uncrypted data uploaded, points #1 - #3 would ensure that these data are enterprise data since they are uploaded and paid for by enterprises. 

**12. Please specify how many questions you’ll ask, and provide a brief overview of the questions.:**
Client onboarding info to be collected:  
- Company name 
- Address 
- Registration number 
- Industry 
- Nature of business 
- Contact person  
- Contact number 
- Email Address 
- Payment Information 

* Enterprises are also required to purchase storage plans from Starlight before they are able to upload data into the system. 

**13. Will you use a 3rd-party Know your client (KYC) service?:**
Currently, we feel that our internal KYC process should be adequate.  

However, if we feel that our processes are insufficient in future, we may consider engaging third party KYC services from reputable partners like Regtank. 

**14. Can any client apply to your pathway, or will you be closed to only your own internal clients? (eg: bizdev or self-referral):**
In order to ensure the authenticity of  data to be stored, we will only accept storage requests from enterprises that have gone through Starlight platform’s registration, KYC, and storage request process.  

**15. How do you plan to track the rate at which DataCap is being distributed to your clients?:**
This can be tracked automatically via the Starlight system. 
### Data Diligence
**16. As an operating entity in the Filecoin Community, you are required to follow all local & regional regulations relating to any data, digital and otherwise. This may include PII and data deletion requirements, as well as the storing, transmit:**
Acknowledge

**17. What type(s) of data would be applicable for your pathway?:**
Private Commercial/Enterprise

**18. How will you verify a client’s data ownership? Will you use 3rd-party KYB (know your business) service to verify enterprise clients?:**
We provide paid data storage service for enterprise clients.  

- We will require all our clients to officially agree to our usage terms (e.g. include certifying that any data they store legally belongs to them, and that the data do not contain content that are illegal in their jurisdiction)  

- We also ensure that all our clients are legally registered and operational via internal KYC, 

- Should there be cases were our client’s data is reported and proven to not belong to them, we reserve the rights to take legal actions against them  

**19.  How will you ensure the data meets local & regional legal requirements?:**
As pointed out in point #18, enterprice clients must first agree to our terms and conditions which includes their compliance with local and regional legal requirements.   Should there be cases where clients are reported to have data that do not meet these requirements, we reserve the rights to take legal actions against them. 

**20. What types of data preparation will you support or require?:**
Yes, we will help client to do the data encyption, CAR file preparation and selection and distribution of clients’ data to qualified SPs. 

**21. What tools or methodology will you use to sample and verify the data aligns with your pathway?:**
As mentioned previously, all storage cost are paid by clients themselves,    This provides motivation for them to make sure the data size is as compact as possible, otherwise they need to pay a lot more to the storage bills.    Furthermore, enterprise will only pay for storage of their data (with a relatively lower price compared to regular hot storage), they do not receive any rewards via the Filecoin system for their storage. Hence they will not be incentivised to do such irregularities. 
### Data Distribution
**22. How many replicas will you require to meet programmatic requirements for distribution?:**
5+

**23. What geographic or regional distribution will you require?:**
3 physical locations. 3 geopolitical regions preferred. At least 1 copy needs to be stored in the original geopolical regions as per clients request.  

**24. How many Storage Provider owner/operators will you require to meet programmatic requirements for distribution?:**
3+

**25. Do you require equal percentage distribution for your clients to their chosen SPs? Will you require preliminary SP distribution plans from the client before allocating any DataCap?:**
All SPs that are certified and onboarded to Starlight platform have been pre-selected based on certain criteria (e.g. performance history, scale, location, IDC Tier level, etc ) to ensure that they are suitable for our enterprise clients.   The onboarding process also requires us to conduct and store SP KYB information and miner IDs of the SPs.   Final SP selection done programmatically by Starlight system based on storage criteria and restrictions 

**26. What tooling will you use to verify client deal-making distribution?:**
As the custodian for enterprise clients’ data, the Starlight system ensures that all deal making decisions are done programmatically based on the required business and legal criteria and restrictions.    All deal-making and distribution details are also stored and tracked in the system to ensure compliance, facilitate audit and verification of clients’ deal-making distribution. 

**27. How will clients meet SP distribution requirements?:**
Since we are dealing with enterprise data which may be sensitive and possibly subject to government or corporate regulations, we have to be more stringent with SP distribution. As such, all SPs that we work with has to be certified and onboarded by Starlight.  All the data clients need to pay for storage services they select to use.   SP selection will be done programatically based on factors that include clients data storage restrictions, quality of Data Centres hosting SP’s nodes, geographical location of data centre, storage budget etc. 

**28. As an allocator, do you support clients that engage in deal-making with SPs utilizing a VPN?:**
We will be allocating all the deals via Starlight so this would not be an issue that we need to be concerned about. We’d require clients to use Starlight platform to manage all the data storage issues, including data uploading, deal making, CAR file downloading and etc,  no matter where their locations are. 
### DataCap Allocation Strategy
**29. Will you use standardized DataCap allocations to clients?:**
No, client specific

**30. Allocation Tranche Schedule to clients::**
• First:10% 
• Second:15% 
• Third:25% 
• Fourth:50% 
• Max per client overall: 30% 

**31. Will you use programmatic or software based allocations?:**
Yes, standardized and software based

**32. What tooling will you use to construct messages and send allocations to clients?:**
Due to the nature of our business, Starlight represents our clients in receiving the datacaps. These are all done programmatically to prevent tampering.    At this point, we are not sure how this allocation should be sent but will work with Filecoin on developing the right mechanism. We will also be happy to release an open source version for sharing. 

**33. Describe the process for granting additional DataCap to previously verified clients.:**
DataCap requirements are calculated and requested automatically via the Starlight system based on actual data storage required by enterprise clients. All additional allocations are calculated, requested and granted via an automated programmatic process.

**34. Describe in as much detail as possible the tools used for: • client discoverability & applications • due diligence & investigation • bookkeeping • on-chain message construction • client deal-making behavior • tracking overall allocator health • disput:**
Starlight platform will have purpose built tools for client onboarding, data storage and usage logs and records.
### Tools and Bookkeeping
**35. Will you use open-source tooling from the Fil+ team?:**
We will be happy to use relevant tools from Fil+ team. Will work with team to discover how we can best tap into these tools. 

**36. Where will you keep your records for bookkeeping? How will you maintain transparency in your allocation decisions?:**
We will keep all the records in the Starlight platform, including all the clients information, bill & payment history, data onboarding history, deal-making history and log for the DataCap useage and districution. 

For the public disclosure requirements, there will be a report about the DataCap distribution periodically as per requested by the Governance team. We will also provide private communication method to help the team reach more relavant information when needed. 
### Risk Mitigation, Auditing, Compliance
**37. Describe your proposed compliance check mechanisms for your own clients.:**
We can have a high degree of certainty that DataCap is properly distributed and used, and it is easy to check up since: 

1. During Client onboarding, clients have to first being a legally registered entity and agree to our terms and policies; 

2. We will then carry out internal KYC after the clients have provide their business details including govenment issued certificates, bank statements and etc.; 

3. Upon successful registration, Clients are also required to provide payment details and purchase storage packages with us to ensure it is under normal business; 

4. Data are uploaded by clients to Starlight platform’s cloud servers for encryption and data preparation; 

5. Storage of data are charged and paid by the enterprise clients, this approach can guarantee the data are real and valuable;  

6. When the client choose to store their data, they can operate on the Starlight platform to decide what kind of data and amount of data to be stored by consuming DataCap, to be noted that the clients need to pay for the storage service, but the DataCap is free to use. 

7 . As we take charge of the data encryption and CAR file preparation accompanied by the DataCap allocation, the new DataCap will be allocated only if the existing quantity is consumed , no matter whether they are new clients or not. 

**38. Describe your process for handling disputes. Highlight response times, transparency, and accountability mechanisms.:**
In terms of the disputes, our clients will not have too much concerns on the use of DataCap, as they are mainly care about the SLA we offered, they will not get any rewards neither on the DataCap allocation or the block rewards from the Filecoin network, it is only considered as an supplement to allow their data store on the Filecoin network efficiently.  

However, if disputes do arise, no matter internally or externally, we have a consolidate system log to show the usage details of all the DataCap and also the payment history to prove they are all paying clients, the allocation of DataCap and distribution of clients’ data are all from clients’ real request that is paid by client.  If there is a need to provide such evidence to solve the dispute, will be able to provide these logs and evidences upon request from Fil+ Governance Team. 

**39. Detail how you will announce updates to tooling, pathway guidelines, parameters, and process alterations.:**
Firstly, we will announce all the main updates of Starlight platform on our websites;   Second, if such updates is related to DataCap allocation or distribution pathway, we will also keep it updated on GitHub and/or Fil+ Slack channel, or other channels required.   Third, beside the public announcement methods, we will also keep the Fil+ Governance Team updated on major updates by email. 

**40. How long will you allow the community to provide feedback before implementing changes?:**
For our clients, we encourage them to provide feedback within the Starlight system; 

At the same time, we will monitor and participate in the Fil+ Slack channel to receive and respond to any feedback related to us; 

We will seriously consider the feedback from these channels and engage in constructive dialogue with the community when weighing and deciding on relevant changes.

**41. Regarding security, how will you structure and secure the on-chain notary address? If you will utilize a multisig, how will it be structured? Who will have administrative & signatory rights?:**
We plan to initialize a multisig address to be administered by CEO, CTO, COO. 

**42. Will you deploy smart contracts for program or policy procedures? If so, how will you track and fund them?:**
Currently we plan to use Starlight system for programs and policies. 
### Monetization
**43. Outline your monetization models for the services you provide as a notary allocator pathway.:**
First, our main business model is to assist the enterprise clients to manage their data storage demands by utilising the web2 and web3 storage method to balance and optimize the cost of data storage.  

After assessing current Web3 storage options, we have select FileCoin is our preferred storage platform.  

To ensure data security and privacy, Starlight system shall perform data encryption and data preparation before handing over to selected SPs.  

The following are our monetization structure: 
1. From Enterprise Clients 
 - We collect fees from our clients for data excryption and storage 

2. From SPs 
 - As we provide data preparation services, we will negotiate with certified SPs on charges for that 
- We will also negotiate with SPs for discounted storage price or/and reward incentive for auditing the clients and allocating storage deals to them  

**44. Describe your organization's structure, such as the legal entity and other business & market ventures.:**
Nebula Data Pte Ltd is a private limited company incorporated in Singapore. We provide data management services for corporate clients.

**45. Where will accounting for fees be maintained?:**
Since we are based in Singapore, accounting for fees will be maintained in Singapore following local judiciary guidelines. 
### Past Experience, Affiliations, Reputation
**46. If you've received DataCap allocation privileges before, please link to prior notary applications.:**
NA

**47. How are you connected to the Filecoin ecosystem? Describe your (or your organization's) Filecoin relationships, investments, or ownership.:**
1. Founders of Nebula Data have attended ESPA (2022) and DSPA ASIA (2023)   2. We have strong connections of some of the SPs in the community e.g. PIKNIK, GreaterHeat, Origin Storage and etc.   3. We have attended FIL Singapore Summit 2022   4. We have regular close contact with PL (Qing Yuan Warthen, Stefaan Vervaet) and FF (Yan Bo, Paul Wagner) for consulation on our technical and business development of our web3 Storage services 

**48. How are you estimating your client demand and pathway usage? Do you have existing clients and an onboarding funnel?:**
We are in the process of complete the initial phase of Starlight Enterprise Data Management System and should be ready for initial rollout in Q1 2024   At the moment, we have quite a few number of potential clients who have expressed their interest in using our services, including industries form Media, Education, Fintech, Biotech, and Social Media platforms   We plan to start off with our client from Biotech and Education first as they already have data waiting for our archival

**Comment by likkhai-nebula** [comment]
Hi @Kevin-FF-USA , would like to following up on the progress for this.  
Do let us know if you have any clarification on our application.

**Comment by likkhai-nebula** [comment]
Hi @Kevin-FF-USA , our multisig address is f23pcmi23ftg3hv6yknw6teq4wexzzsh2jynccp3y

**Comment by likkhai-nebula** [comment]
@Kevin-FF-USA seems the airtable form is no longer accepting submissions. 
Our new multisig address is f2ilxgyvzgfynkxhoof4fnk4gsrtn72fa6mn2b5cy

ID address is f03019671

Ledger address: f1adtbrt6sjwlg6iartalccragv74fadmr6nv6r2a

GitHub Repo is https://github.com/nebuladata-starlight/edms

**Comment by galen-mcandrew** [comment]
## Datacap Request for Allocator
#### Address
> f2pk34lqjjck5jgsbtd2dnvu5z6pm7tiuujvv6cuy
#### Datacap Allocated
> 5PiB

**Comment by likkhai-nebula** [comment]
> ## Datacap Request for Allocator
> #### Address
> > f2pk34lqjjck5jgsbtd2dnvu5z6pm7tiuujvv6cuy
> 
> #### Datacap Allocated
> > 5PiB

Hi @galen-mcandrew , this does not seem to be our multisig address.  Appreciate if you can help advice us on how we can access the datacap.

Thank you.
