### ISSUE TITLE
v5 Notary Allocator Application: OpenGate Datacap Allocator 

### ISSUE THREAD

**Issue by OpenGate01** [filecoin-project/notary-governance#1020]
# v5 Notary Allocator Application

To apply to be an allocator, organizations will submit one application for each proposed pathway to DataCap. If you will be designing multiple specific pathways, you will need to submit multiple applications. 

Please complete the following steps:
# 1. Fill out the information below and create a new GitHub Issue

1. Notary Allocator Pathway Name: OpenGate  
2. Organization Name: OpenGate
3. On-chain address for Allocator: f1mcbkmojzegd3rgm4aphdha7dukxbqhwhwbrnwfq
4. Country of Operation: Australia
5. Region of Operation : All regions
6. Type of Allocator, diligence process:  Manual
7. DataCap requested for allocator for 12 months of activity: 100P

# 2. Access allocator application (download to save answers)
Click link below to access a Google doc version of the allocator application that can be used to save your answers if you are not prepared to fully submit the application in Step 3. https://docs.google.com/document/d/1-Ze8bo7ZlIJe8qX0YSFNPTka4CMprqoNB1D6V7WJJjo/copy

# 3. Submit allocation application 
Clink link below to access full allocator questionnaire and officially submit your answers:
https://airtable.com/appvyE0VHcgpAkt4Z/shrQxaAIsD693e1ns

Note: Sections of your responses WILL BE posted back into the GitHub issue tracking your application. 
The final section (Additional Disclosures) will NOT be posted to GitHub, and will be maintained by the Filecoin Foundation. 
Application information for notaries not accepted and ratified in this round will be deleted.

**Comment by Kevin-FF-USA** [comment]
Hi @OpenGate01 
Wanted to let you know this application has been received. After you complete and submit the Airtable form with your detailed Allocator plan - the public answers will be posted in a thread below. If you have any questions - please let me know.

**Comment by Filplus-govteam** [comment]
### Basic Information
**1. Notary Allocator Pathway Name:**
OpenGate Datacap Allocator

**2. Organization:**
OpenGate

**3. On Chain Address for Allocator:**
f1mcbkmojzegd3rgm4aphdha7dukxbqhwhwbrnwfq

**4. Country of Operation:**
AUS

**5. Region(s) of operation:**
Africa , Asia minus GCR, Greater China, Europe, Oceania, Japan, North America, South America

**6. Type of Allocator:**
Manual

**7. DataCap requested for allocator for 12 months of activity:**
100P

**8. Is your allocator providing a unique, new, or diverse pathway to DataCap? How does this allocator differentiate itself from other applicants, new or existing?:**
Our allocator distinguishes itself by implementing a rigorous customer review process before allocation to prevent abuse. Here is an overview of our allocation process:
Client KYC Review:
We conduct thorough KYC checks for both individual and corporate clients. This ensures the authenticity and validity of their identity information. We examine their previous allocation history, community participation, and adherence to Filecoin standards and ethical behavior. This scrutiny guarantees fairness, transparency, and responsible allocation.Application Review:
Upon successful completion of the KYC process, we employ different allocation and review criteria based on the customer type. Each allocation stage has specific quotas and evaluation procedures. Approved DataCap is allocated in batches to allow continuous monitoring of its proper utilization.For applicants who do not meet the initial review criteria, we request additional information to reassess their eligibility. Applicants who fail the re-evaluation or refuse to provide supplemental materials will not receive an allocation.

**9. As a member in the Filecoin Community, I acknowledge that I must adhere to the Community Code of Conduct, as well other End User License Agreements for accessing various tools and services, such as GitHub and Slack.:**
Acknowledge
### Client Diligence
**10. Who are your target clients?:**
Individuals learning about Filecoin, Small-scale developers or data owners, Enterprise Data Clients

**11. Describe in as much detail as possible how you will perform due diligence on clients.  If you are proposing an automated pathway, what diligence mechanism will you use to determine client eligibility?:**
For all applying clients, a stringent KYC process must be completed to qualify. In addition to gathering relevant information from the Filecoin community, we also conduct client identity verification through the following procedures:
1.Entity Information:
Establishment documents, including registration/company/information certificates.
Government-issued entity identification number.
Company equity information and any related entities with significant interests.
2.Authorized Signatory Information:
Direct relationship evidence between the authorized signatory and the company.
Evidence of the signatory's identity, such as passport/residence permit/identity card.
3.Company Operations and Revenue:
Legal company name, primary business direction, and team size.
Official website/social media presence that demonstrates the company's business.
Local business registry website where company information can be verified.
After the KYC review, we conduct a detailed examination of the allocation process for the applying clients. This includes but is not limited to the following checklist of questions:
1.Please provide project-related information, including organization name, business scale, social media accounts, and followers, as well as the business license (to be sent via official email). If you are an individual, please provide your identity information and active account in the Filecoin network (GitHub/Slack/Twitter).
2.How did you learn about the Filecoin network? When did you join the Filecoin network? What is your reason for storing data in the Filecoin network?
3.Where does your stored data come from? What is the data size, type, and format? Please provide three or more sample data types.
4.Does your company have ownership rights over the stored data? Are there any other stakeholders or related disputes? Please explain.
5.How many SPs do you intend to select for data storage? How much DataCap will be allocated to each SP?

**12. Please specify how many questions you’ll ask, and provide a brief overview of the questions.:**
1.Please provide project-related information, including organization name, business scale, social media accounts, and followers, as well as the business license (to be sent via official email). If you are an individual, please provide your identity information and active account in the Filecoin network (GitHub/Slack/Twitter).
2.How did you learn about the Filecoin network? When did you join the Filecoin network? What is your reason for storing data in the Filecoin network?
3.Where does your stored data come from? What is the data size, type, and format? Please provide three or more sample data types.
4.Does your company have ownership rights over the stored data? Are there any other stakeholders or related disputes? Please explain.
5.How many SPs do you intend to select for data storage? How much DataCap will be allocated to each SP?


**13. Will you use a 3rd-party Know your client (KYC) service?:**
Toggle

**14. Can any client apply to your pathway, or will you be closed to only your own internal clients? (eg: bizdev or self-referral):**
 Our pathway is open to all clients, regardless of whether they are internal or external. We welcome applications from anyone interested in utilizing our services.

**15. How do you plan to track the rate at which DataCap is being distributed to your clients?:**
We maintain detailed records of all our allocation activities and conduct regular audits to verify data allocation and its authenticity. Using datacapstats.io、CID checker、AC Bot
### Data Diligence
**16. As an operating entity in the Filecoin Community, you are required to follow all local & regional regulations relating to any data, digital and otherwise. This may include PII and data deletion requirements, as well as the storing, transmit:**
Acknowledge

**17. What type(s) of data would be applicable for your pathway?:**
Public Open Dataset (Research/Non-Profit), Public Open Commercial/Enterprise, Private Commercial/Enterprise, Private Non-Profit/Social Impact

**18. How will you verify a client’s data ownership? Will you use 3rd-party KYB (know your business) service to verify enterprise clients?:**
We have developed a preliminary verification approach:
1.Public Data:
--Source Confirmation: For public data such as publicly released government reports, news articles, public databases, etc., verifying the source and credibility of the data is typically straightforward. Official channels or recognized data resources can be consulted to confirm the legality and authenticity of the data.
--Data Usage Permissions: Although public data is generally freely available for use, it is still necessary to consider whether there are specific usage licenses or legal restrictions. Ensure compliance with relevant regulations when using public data.
2.Private Data:
--Compliance Review: For data containing personal or sensitive information, a compliance review regarding privacy regulations is necessary. Ensure compliance with applicable privacy laws, such as the European GDPR (General Data Protection Regulation) or other relevant laws in different countries/regions.
--Data Processing Authorization: Confirm whether explicit authorization or consent has been obtained from the data subjects for the use of their personal data. Request clients to provide relevant authorization or consent documents and verify their legality.
3.Enterprise Data:
--Business Identity Verification: For enterprise data, conduct verification of the business identity and background. Verify the company's registration information, business license, shareholder structure, etc., to ensure that the data originates from a legitimate corporate entity.
--Third-Party Verification: Utilize third-party KYB  services or commercial investigation agencies to verify the legitimacy, reputation, and business background of the company. This can provide more comprehensive data validation and investigative reports.

**19.  How will you ensure the data meets local & regional legal requirements?:**
Legal requirements may vary across different jurisdictions, and we will seek advice from community members in relevant regions or legal professionals familiar with local and regional laws to ensure compliance. Additionally: 1.Familiarize with Applicable Laws: Understand local and regional laws and regulations related to data protection, privacy, and data usage. This includes laws and regulations from different continents or other relevant laws applicable to the location of data processing. 2.Conduct Legal Assessments: Perform comprehensive legal assessments to identify specific legal requirements applicable to the data involved. This assessment should consider data protection obligations, consent requirements, data transfer restrictions, data retention periods, and applicable industry-specific regulations, among other factors. 3.Regular Review and Updating of Compliance Practices: Stay informed about changes in local and regional laws and regulations. Conduct regular reviews and updates of compliance practices to ensure ongoing compliance with legal requirements. 

**20. What types of data preparation will you support or require?:**
Public Open Dataset (Research/Non-Profit) Public Open Commercial/Enterprise Private Commercial/Enterprise Private Non-Profit/Social Impact

**21. What tools or methodology will you use to sample and verify the data aligns with your pathway?:**
We primarily use official tools provided  for conducting retrieval checks and verifying data authenticity.
### Data Distribution
**22. How many replicas will you require to meet programmatic requirements for distribution?:**
5+

**23. What geographic or regional distribution will you require?:**
THREE OR MORE regions including unique geopolitical/language coverage, each replica at different physical location, no or minimal VPN,different SP owner operators

**24. How many Storage Provider owner/operators will you require to meet programmatic requirements for distribution?:**
5+

**25. Do you require equal percentage distribution for your clients to their chosen SPs? Will you require preliminary SP distribution plans from the client before allocating any DataCap?:**
We have an executable allocation plan rather than distributing resources evenly. Clients are required to provide an initial credible SP distribution plan. However, it's important to note that the plan is subject to change, and clients are expected to promptly update it with reasonable justifications.

**26. What tooling will you use to verify client deal-making distribution?:**
datacapstats.io、CID chcker

**27. How will clients meet SP distribution requirements?:**
 Communicate with clients and provide corresponding support.

**28. As an allocator, do you support clients that engage in deal-making with SPs utilizing a VPN?:**
Willing to support clients who work with SPs that utilize VPNs, but requires additional KYB checks 
### DataCap Allocation Strategy
**29. Will you use standardized DataCap allocations to clients?:**
Yes, standardized

**30. Allocation Tranche Schedule to clients::**
https://docs.google.com/spreadsheets/d/1D3w7ack2qEo-LeafMcAMuuh9tSnoW9vHRcvzo_iooW4/edit?usp=sharing


**31. Will you use programmatic or software based allocations?:**
Yes, standardized and software based

**32. What tooling will you use to construct messages and send allocations to clients?:**
Open-sourced tools

**33. Describe the process for granting additional DataCap to previously verified clients.:**
Due to your previous request for DataCap, I have some questions regarding your previous DataCap allocation: How many miners did you allocate DataCap to? In which SP region(s) do they belong? How much DataCap will you be requesting in the future? Is the data retrievable without any issues? Gathering this information will help me verify that clients have not misused the DataCap previously granted to them. We encourage clients to allocate DataCap to five or more different miners, as it not only increases storage redundancy but also helps maintain decentralization and reduce the potential for misuse.

**34. Describe in as much detail as possible the tools used for: • client discoverability & applications • due diligence & investigation • bookkeeping • on-chain message construction • client deal-making behavior • tracking overall allocator health • disput:**
N/A
### Tools and Bookkeeping
**35. Will you use open-source tooling from the Fil+ team?:**
 Fully utilize well-documented open-source tools for documentation purposes.

**36. Where will you keep your records for bookkeeping? How will you maintain transparency in your allocation decisions?:**
All information is accessible for querying on datacapstats.io. Communication records with clients during the due diligence process will be evaluated on a case-by-case basis to determine whether they should be made public.


### Risk Mitigation, Auditing, Compliance
**37. Describe your proposed compliance check mechanisms for your own clients.:**
Tracking record sheet.
https://docs.google.com/spreadsheets/d/1D7q_lv3bCXxTC4u546Ot5SwBqWsbvoWYqU8Ztdz0xw4/edit?usp=sharing


**38. Describe your process for handling disputes. Highlight response times, transparency, and accountability mechanisms.:**
The dispute resolution process is as follows:
Communication and Understanding:
1.Gather all relevant information about the dispute, communicate with the involved parties, and address any misunderstandings.
2.Providing Evidence:
Present supporting evidence and materials related to the current issue for scrutiny by the disputing parties and community members.
3.Seeking Assistance:
If a dispute cannot be resolved due to response times or other reasons, seek assistance from the community or a dispute resolution committee. This may involve methods such as conference calls, voting for arbitration, or other fair, impartial, and transparent processes to ensure a fair resolution.Typically, we aim to respond to disputes or feedback messages within 3 business days. 


**39. Detail how you will announce updates to tooling, pathway guidelines, parameters, and process alterations.:**
N/A

**40. How long will you allow the community to provide feedback before implementing changes?:**
Provide timely notifications through GitHub, Slack channels, and set timelines to give everyone ample time for understanding and discussion. We will also update information on these channels, provide prompt feedback, offer opinions and suggestions, and actively collaborate with the official team for implementing updates.


**41. Regarding security, how will you structure and secure the on-chain notary address? If you will utilize a multisig, how will it be structured? Who will have administrative & signatory rights?:**
By using Ledger Nano X wallet.

**42. Will you deploy smart contracts for program or policy procedures? If so, how will you track and fund them?:**
N/A
### Monetization
**43. Outline your monetization models for the services you provide as a notary allocator pathway.:**
N/A

**44. Describe your organization's structure, such as the legal entity and other business & market ventures.:**
OpenGate was co-invested by the Australian Gold and Silver Exchange (AGSX) and the Australian International Digital Currency Exchange (ADCX) in 2018. And OpenGate was founded with the mission to create a decentralized, efficient and low-cost NFT marketplace.By building a reliable Web 3. retrieval storage network for NFT,we hope it can protect the rights of creators and investors  We have built the world's first NFT market based on Filecoin ecosystem, and established a mature NFT collection, auction and purchase process. We will continue to grow it rapidly with the support of the community,and now it have over 30,000 registered members. At present,our company have signed up 168 famous artists including Tian Liusha , and 10 famous musicians including Joseph Feng.  And we have many popular NFT IP series on the platform, including the crypto bear club series, Earth and Dreams series, Bored Ape Filecoin series, and the famous Asian animation ""Pleasant Goat and Big Big Wolf"" series. In addition,we also have partnered with the famous footballer Fabio Cannavaro to create his own NFT series and sale on our platform. Here are our social media website: Official website address: https://www.opengatenft.com/ Twitter address: https://twitter.com/OpenGateNFT  Discord: https://discord.com/invite/tWjC9YQeSv

**45. Where will accounting for fees be maintained?:**
N/A
### Past Experience, Affiliations, Reputation
**46. If you've received DataCap allocation privileges before, please link to prior notary applications.:**
https://github.com/filecoin-project/notary-governance/issues/673

**47. How are you connected to the Filecoin ecosystem? Describe your (or your organization's) Filecoin relationships, investments, or ownership.:**
OpenGate joined the Filecoin network in March 2021 and has been working on building the Filecoin community and developing the ecosystem all the  time. During the participation, we co-host an informative AMA with the Filecoin Foundation in August 2022,aiming to further discuss the Orbit Community Initiative and the future of the Filecoin ecosystem. This conference event was held on Discord and had over 1,000 attendees. The Filecoin official covered this event : https://filecoin.io/blog/posts/the-filecoin-orbit-community-s-growth-around-the-globe/ Besides, our team will routinely host OpenGate Community Call to propagate  Filecoin better. Our first call focusing on ""why Filecoin can be an infrastructure layer for NFT""was hosted in Australia in March 2022 and spread to global. In May 2022, we held our second community event in Vancouver and the session on how to use IPFS URLs and CIDs in NFT and metadata to ensure that NFT always references the expected data! Check here:https://mp.weixin.qq.com/s/EKx8NRDdU2CJgQFFWM9KKQ In July 2022, we also hosted a workshop on ""Best Practices for Storing NFT Data with IPFS"" More than these, we will constantly host a series of events related to these and build the Filecoin community better.

**48. How are you estimating your client demand and pathway usage? Do you have existing clients and an onboarding funnel?:**
NOT YET

**Comment by galen-mcandrew** [comment]
## Datacap Request for Allocator
#### Address
> f2chmjasnwjwbmtbasoipel6xzhyex5deyawg2lsq
#### Datacap Allocated
> 5PiB

**Comment by galen-mcandrew** [comment]
## DataCap Request for Allocator
#### Address
> f2chmjasnwjwbmtbasoipel6xzhyex5deyawg2lsq
#### Datacap Allocated
> 2.5PiB

**Comment by galen-mcandrew** [comment]
https://filfox.info/en/message/bafy2bzaced2wp3vuw62irv4jkqkygyhibegpdtdr77welig32sq2yls5ag2ss
