### ISSUE TITLE
v5 Notary Allocator Application: NonEntropy

### ISSUE THREAD

**Issue by joshua-ne** [filecoin-project/notary-governance#1022]
# v5 Notary Allocator Application

To apply to be an allocator, organizations will submit one application for each proposed pathway to DataCap. If you will be designing multiple specific pathways, you will need to submit multiple applications. 

Please complete the following steps:
# 1. Fill out the information below and create a new GitHub Issue

1. Notary Allocator Pathway Name (This can be your name, or the name of your pathway/program. For example "E-Fil+"): NonEntropy
3. Organization Name: NonEntropy Technology Pte. Ltd. 
4. On-chain address for Allocator (Provide a NEW unique address. During ratification, you will need to initialize this address on-chain): f1sfffys4o2w64rdpd3alpmvpvj4ik6x2iyjsjmry (revised on 3-15-2024) 
5. Country of Operation (Where your organization is legally based): Singapore
6. Region of Operation (What region will you serve?): Asia & Great China
7. Type of Allocator, diligence process: (Automated/programmatic, Market-based, or Manual (human-in-the-loop at some phase): a combination of automated/programmatic and manual
9. DataCap requested for allocator for 12 months of activity (This should be an estimate of overall expected activity. Estimate the total amount of DataCap you will be distributing to clients in 12 months, in TiB or PiB): 200PiB

# 2. Access allocator application (download to save answers)
Click link below to access a Google doc version of the allocator application that can be used to save your answers if you are not prepared to fully submit the application in Step 3. https://docs.google.com/document/d/1-Ze8bo7ZlIJe8qX0YSFNPTka4CMprqoNB1D6V7WJJjo/copy

# 3. Submit allocation application 
Clink link below to access full allocator questionnaire and officially submit your answers:
https://airtable.com/appvyE0VHcgpAkt4Z/shrQxaAIsD693e1ns

Note: Sections of your responses WILL BE posted back into the GitHub issue tracking your application. 
The final section (Additional Disclosures) will NOT be posted to GitHub, and will be maintained by the Filecoin Foundation. 
Application information for notaries not accepted and ratified in this round will be deleted.

**Comment by Kevin-FF-USA** [comment]
Hi @joshua-ne 
Wanted to let you know this application has been received along with the Airtable detailed answers - the public answers will be posted in a thread below soon. If you have any questions - please let me know.

**Comment by Filplus-govteam** [comment]
### Basic Information
**1. Notary Allocator Pathway Name:**
NonEntropy

**2. Organization:**
NonEntropy Technology Pte. Ltd.

**3. On Chain Address for Allocator:**
f1uzljppxtnmsekck6jt5lmuwxtzo3u5s2udizsai

**4. Country of Operation:**
Singapore

**5. Region(s) of operation:**
Greater China, Asia minus GCR, Japan

**6. Type of Allocator:**
Manual

**7. DataCap requested for allocator for 12 months of activity:**
20 PiB

**8. Is your allocator providing a unique, new, or diverse pathway to DataCap? How does this allocator differentiate itself from other applicants, new or existing?:**
We use an Application Form to collect the initial information of clients, and our scripts will deal with the information automatically to differentiate clients from new and existing.
We also have a completed mechanism to collect data about clients’ past behavior, and reputation, check if they ever made self-deals, or their cooperative miners ever use VPN.

**9. As a member in the Filecoin Community, I acknowledge that I must adhere to the Community Code of Conduct, as well other End User License Agreements for accessing various tools and services, such as GitHub and Slack.:**
Acknowledge
### Client Diligence
**10. Who are your target clients?:**
Individuals learning about Filecoin, Small-scale developers or data owners, Enterprise Data Clients

**11. Describe in as much detail as possible how you will perform due diligence on clients.  If you are proposing an automated pathway, what diligence mechanism will you use to determine client eligibility?:**
We collect the following information to determine eligibility:
1. Registered capital of the company(for business firm), establishment time, team/personal background, and reputation.
2. Project planning and project progress.
3. Data scale and data redundancy strategy.
4. The type of data stored.
5. Applicant's understanding of the impact of DataCap distribution on the Filecoin network (as a supporting reference).


**12. Please specify how many questions you’ll ask, and provide a brief overview of the questions.:**
Our questionnaire:
1. Please introduce yourself and leave reliable contact information so that we can communicate with you when needed.
2. Name, nature, place of registration, date of establishment, position you hold in your entity (if any), and provide relevant documents of the entity (legally effective documents that can prove the existence of the entity) and authorized signatory information.
3. Please describe the basic information of the data you plan to use DataCap to store, including but not limited to the source, size and type of the data.
4. Please introduce the development status of the application project supported by your data, including but not limited to: project start time, project running time, number of users, and user activity.
5. Where do you plan to use DataCap?
6. Which SPs do you plan to store the data with? What are your criteria for selecting an SP? How do you ensure that the SP you choose meets your needs and the spirit of Filecoin's data decentralization?
7. Have you used DataCap before? If yes, please provide the address you use to manage the DataCap and a brief description of the number and distribution of data stores.
8. How will you disclose your use of DataCap to us or the community to ensure that DataCap is not misused or unfairly traded?
9. How many DataCaps have you requested? 

**13. Will you use a 3rd-party Know your client (KYC) service?:**
Yes, and we are seeking the proper vendor for KYC service. We will pay attention to the actual operations of clients to confirm the authenticity of clients and data.

**14. Can any client apply to your pathway, or will you be closed to only your own internal clients? (eg: bizdev or self-referral):**
Our DataCap application is open to anyone.

**15. How do you plan to track the rate at which DataCap is being distributed to your clients?:**
We have developed an auto-run on-chain data collecting and analyzing platform to track the DataCap statues we allocated. It can show the client, amount, miner, signature time, and sealing situation about our DataCap allocation. We also made a bot to check if the data storage with our DataCap is retrievable.
### Data Diligence
**16. As an operating entity in the Filecoin Community, you are required to follow all local & regional regulations relating to any data, digital and otherwise. This may include PII and data deletion requirements, as well as the storing, transmit:**
Acknowledge

**17. What type(s) of data would be applicable for your pathway?:**
Public Open Dataset (Research/Non-Profit), Public Open Commercial/Enterprise, Private Commercial/Enterprise, Private Non-Profit/Social Impact

**18. How will you verify a client’s data ownership? Will you use 3rd-party KYB (know your business) service to verify enterprise clients?:**
We are happy to work with 3rd-party for the KYB verification of data ownership if there is any proper cooperator.
Before collaboration, clients must prove their identity via their official site email, and phone.
We also require clients to deposit a certain amount of FIL collateral as a margin. If there is disputation about the data ownership and the client is verified abusing, the collateral would be deducted as compensation for the victim.

**19.  How will you ensure the data meets local & regional legal requirements?:**
- We will verify that the data content is legal through spot checks. - We require the client to ensure that the data is legal, and we also require the client to deposit a certain amount of FIL as collateral based on the amount of data. If illegal data appears, access to the data will be restricted or deleted, and the collateral will not be retrieved.

**20. What types of data preparation will you support or require?:**
We have provided data packaging services before, and may further provide case-by-case customized data processing services based on the specific needs of clients.

**21. What tools or methodology will you use to sample and verify the data aligns with your pathway?:**
Clients must offer their data CID list(may generated by script from us). This will almost solidify the data, and we can randomly choose some data to check. For the confirmed data amount, we can estimate the DC quantity the client needs easily(Knapsack Problem Algorithm). We allow the gap between actual DC consumption and the optimal solution less than 20%.
### Data Distribution
**22. How many replicas will you require to meet programmatic requirements for distribution?:**
5+

**23. What geographic or regional distribution will you require?:**
2 continents and 3 countries or regions at least.

**24. How many Storage Provider owner/operators will you require to meet programmatic requirements for distribution?:**
4+

**25. Do you require equal percentage distribution for your clients to their chosen SPs? Will you require preliminary SP distribution plans from the client before allocating any DataCap?:**
- We ask clients to provide their cooperative miner IDs and require the percentage distribution among different storage providers to be generally equal but allow a gap of 10% of the total amount. - We collect this information from the blockchain directly by the scripts embedded in our monitor platform mentioned above and analyze it automatically and periodically.

**26. What tooling will you use to verify client deal-making distribution?:**
Sometimes, we used datacapstats.io for a fast viewing of some statures. We also collect and analyze additional data via our scripts.

**27. How will clients meet SP distribution requirements?:**
Won't. We consider ourselves purely a notary within the DataCap management process and do not participate in distribution efforts. We just verify and make sure the results meet our requirements.

**28. As an allocator, do you support clients that engage in deal-making with SPs utilizing a VPN?:**
We do not support VPN utilization, but we understand that some miners have to use VPN to keep communicating signals for some reason. These miners must pre-claim that and provide convicted evidence, otherwise, we will stop the DC supplements as soon as we detect the situation via some network tools.
### DataCap Allocation Strategy
**29. Will you use standardized DataCap allocations to clients?:**
Yes, standardized

**30. Allocation Tranche Schedule to clients::**
• First: 50 TB
• Second: 100 TB
• Third: 500 TB
• Fourth: 1000 TB
• Max per client overall: 5000 TB

**31. Will you use programmatic or software based allocations?:**
Yes, standardized and software based

**32. What tooling will you use to construct messages and send allocations to clients?:**
We use the site for some of its features and use tools developed ourselves for other functions.

**33. Describe the process for granting additional DataCap to previously verified clients.:**
- Get the additional allocating application.  - Check the consumption of the past allocation.  - Determine if to approve the new application.  We will consider the remaining and the consumption speed to determine whether, when, and how much of the additional allocation.

**34. Describe in as much detail as possible the tools used for: • client discoverability & applications • due diligence & investigation • bookkeeping • on-chain message construction • client deal-making behavior • tracking overall allocator health • disput:**
• client discoverability & applications
Github, Slack.
• due diligence & investigation
Github, Google Doc.
• bookkeeping
Github, Google Doc.
• on-chain message construction
Filplus.fil.org
• client deal-making behavior
Scripts and platform developed ourselves.
• tracking overall allocator health
Scripts and platform developed ourselves.
• dispute discussion & resolution
Github.
• community updates & comms *
Github.
### Tools and Bookkeeping
**35. Will you use open-source tooling from the Fil+ team?:**
We use the tools sometimes. We also use our database containing all the on-chain data to help our DataCap management.

**36. Where will you keep your records for bookkeeping? How will you maintain transparency in your allocation decisions?:**
We use Github for the open applicants. For the private applicants, we provide a pathway that is based on our Gitlab repository.
Private applicants' data could be desensitized and offered to the governance group for audit under some conditions.
### Risk Mitigation, Auditing, Compliance
**37. Describe your proposed compliance check mechanisms for your own clients.:**
As mentioned above, direct access to on-chain data, real-time monitoring and early warning, and regular summary scripts are important auxiliary tools for us to perform our duties as notaries. Through the script we can focus on these indicators:
- Historical distribution of DataCap that we allocated to clients.
- The distribution of our DataCap among different clients and miners.
- Our DataCap order cycle status and multi-copy backup status.
Based on these core indicators above, we have set early warning thresholds, and can promptly send SMS reminders when abnormal conditions occur.

For new clients, if an abnormality occurs, we will communicate with them and ask them for an explanation. We will disqualify them if one of the following occurs:
- No reasonable explanation.
- Abnormality occurred 3 times within 2 months.
- The number of abnormal DataCaps reaches 20% or more of the amount he owns.


**38. Describe your process for handling disputes. Highlight response times, transparency, and accountability mechanisms.:**
From our DataCap allocation strategy, I believe you already have an idea about our thinking and efforts to fulfill the notary work. Based on our understanding of the Filecoin ecosystem, we have designed a highly original and perfect system to ensure that all matters are completed openly, fairly and justly.
In terms of audit/dispute resolution, we have also set up a rigorous system and process, and the whole process follows the principles and standards described in the Allocation Strategy. It will also rely on the applicant information collected during the Client Due Diligence process and the record information retained by the Bookkeeping Plan.
At the same time, our team has also established a ""Notary Performance Working Group"" composed of 4 people, and I will lead the team to complete the relevant work as the leader of the group.
I will show the details below.

Audit/Dispute
In our management of DataCap, Audits fall into two categories: our audits of applicants' qualifications and their applications for DataCap, and audits from the Filecoin community to our assignments. Disputes are also divided into two categories: the handling of applicants' objections to our scores and DataCap assignments, and the handling of disputes in which applicants submit their objections to us to the community. We will elaborate them one by one:
 
Our audit of applicant qualifications and their application for DataCap
- Our audits of clients will be conducted in strict accordance with our rules (see Allocation Strategy below);
- If the applicant makes a reasonable suggestion to improve our rules, we will adopt the suggestion and publish and adopt the new DataCap management method in time after this DataCap allocation;
- We will focus on reviewing the applicant's interests;
- For the address provided by the applicant that has been used for DataCap management, we will use the script to collect the past deal information from the chain and analyze whether there is a centralized transaction with a single SP entity;
- If we find that a applicant has improperly used DataCap, we will report it to Notary's governing body, seek the assistance of the governing body to make a correct judgment, discuss whether to cancel its DataCap, and alert other Notaries to the applicant;
- We will also analyze the applicant's DataCap usage cycle and discuss with them regularly to help them develop a more scientific and reasonable DataCap usage plan.

Audit of community objections to our distribution
- When this objection arises, we will apply to the Notary Governance Body for an audit;
- We will request the Notary Governance Body to appoint an auditor to direct our audit;
- Our audit application form contains the following contents: the objector, the description of the objection, the description of the infringement of interests, the statement of the objector, the evidence information of the objector and our evidence information;
- When necessary, we will initiate an open online arbitration meeting so that the community can understand the real process and outcome of the incident.

Handling of applicant objections to our ratings and DataCap allocation
- We will display the contact details of the Notary governance body on the page of the DataCap allocation rules to ensure that the applicant has the right to request arbitration;
- We will demonstrate the process of dispute resolution. Once the applicant raises an objection, we will first negotiate with the applicant. If the applicant is strongly dissatisfied with the result, the dispute will be submitted to Notary Governance for arbitration;
- Except for a small number of data that must be kept private, the whole communication of dispute settlement is presented in the form of issues on Github to ensure that the whole process is open and transparent;
- We will use the data collected and retained by the Client Due Diligence and Bookkeeping Plan described below in the dispute resolution process.


**39. Detail how you will announce updates to tooling, pathway guidelines, parameters, and process alterations.:**
- We will publish our new ideas for DataCap governance rules in the form of issues on our Github and conduct community discussions. - We will revise the governance rules based on the results of the discussion. - All new rules will be announced in advance and notified to the Notary Governance Group and clients via email. - During the publicity period, as long as someone puts forward sufficient reasons to prove that the rule is unreasonable, we will extend, change, or cancel the rule.

**40. How long will you allow the community to provide feedback before implementing changes?:**
During the public notice period, there will be one month for the community to discuss the new rules.
The community can interact with us and post comments, suggestions, etc. on the DataCap governance page we established on Github.

**41. Regarding security, how will you structure and secure the on-chain notary address? If you will utilize a multisig, how will it be structured? Who will have administrative & signatory rights?:**
We have developed a Filecoin portable cold wallet that supports multi-sig for Send, Withdrawal, DataCap allocation, etc. We will use this wallet to sign the DataCap allocation.
Multi-sig strategy: we will set a 2/3 multi-sig address. All 3 private keys will be encoded and written on paper which is held in a locked safe deposit box. 2 private keys are held by 2 signature operators, and another one is stored in a laptop-type cold wallet. The 2 operators can sign messages by portable cold wallet, but can not export the private keys.



**42. Will you deploy smart contracts for program or policy procedures? If so, how will you track and fund them?:**
We have not yet planned to do this due to it is not necessary by now. But we will keep paying close attention to the further development of both FVM and FIL+, and will use smart contracts if the conditions and demands are proper.
### Monetization
**43. Outline your monetization models for the services you provide as a notary allocator pathway.:**
We have not applied any monetization measures yet and have no similar plan for the coming year.

**44. Describe your organization's structure, such as the legal entity and other business & market ventures.:**
We are a firm registered and based in Singapore. Most of our team members are technical staff. All of our businesses are collaborating with organizations, so we have no scaled specialized marketing team.

**45. Where will accounting for fees be maintained?:**
Singapore
### Past Experience, Affiliations, Reputation
**46. If you've received DataCap allocation privileges before, please link to prior notary applications.:**
https://github.com/filecoin-project/notary-governance/issues/700

**47. How are you connected to the Filecoin ecosystem? Describe your (or your organization's) Filecoin relationships, investments, or ownership.:**
We have been with IPFS/Filecoin since 2017. Initially, we were studying IPFS and trying to let more people be aware of them by hosting meetups, translating related materials, and publishing blogs.  We built our company both in China and Japan to promote IPFS/Filecoin and cooperate with governments, enterprises, and colleges. Our China team moved to Singapore in 2021. Then we also actively took part in testnest, spacerace, and mainnet as a miner. Besides those, we participated in slingshots (music prize, ranking 11) and Filecoin Frontier Accelerate to seek the ecology applications landing. We have been actively participating in various community governance efforts, including code debugging, miner working group meetings, Notary calls, etc..

**48. How are you estimating your client demand and pathway usage? Do you have existing clients and an onboarding funnel?:**
Clients must offer their data CID list(may generated by script from us). This will almost solidify the data, and we can randomly choose some data to check. For the confirmed data amount, we can estimate the DC quantity the client needs easily(Knapsack Problem Algorithm).

**Comment by kevzak** [comment]
## Datacap Request for Allocator
#### Address
> f2qdxvqizz6fqoongs65l4eswodf6zm7g3wr6dt3y
#### Datacap Allocated
> 5PiB

**Comment by kevzak** [comment]
## Datacap Request for Allocator
#### Address
> f2qdxvqizz6fqoongs65l4eswodf6zm7g3wr6dt3y
#### Datacap Allocated
> 5PiB

**Comment by galen-mcandrew** [comment]
## Datacap Request for Allocator
#### Address
> f2qdxvqizz6fqoongs65l4eswodf6zm7g3wr6dt3y
#### Datacap Allocated
> 5PiB

**Comment by galen-mcandrew** [comment]
https://filfox.info/en/message/bafy2bzaceaxvn6hvtkoewxxi2evxvvwszonpb23ljvgirgvwgy5wbvsp4g4ba?t=2

**Comment by galen-mcandrew** [comment]
## Datacap Request for Allocator
#### Address
> f2qdxvqizz6fqoongs65l4eswodf6zm7g3wr6dt3y
#### Datacap Allocated
> 10PiB

**Comment by galen-mcandrew** [comment]
## Datacap Request for Allocator
#### Address
> f2qdxvqizz6fqoongs65l4eswodf6zm7g3wr6dt3y
#### Datacap Allocated
> 20PiB

**Comment by galen-mcandrew** [comment]
Approval: bafy2bzaced5dxibmazzjmp2y3xexpcfpabn3oncjzskoteaue3o3imtlsexyi
