### ISSUE TITLE
v5 Notary Allocator Application: Fatman13 (FIP-0078 Pathway)

### ISSUE THREAD

**Issue by Fatman13** [filecoin-project/notary-governance#1023]
# v5 Notary Allocator Application

To apply to be an allocator, organizations will submit one application for each proposed pathway to DataCap. If you will be designing multiple specific pathways, you will need to submit multiple applications. 

Please complete the following steps:
# 1. Fill out the information below and create a new GitHub Issue

1. Notary Allocator Pathway Name (This can be your name, or the name of your pathway/program. For example "E-Fil+"): Fatman13
3. Organization Name: Guazi Dynamic 
4. On-chain address for Allocator (Provide a NEW unique address. During ratification, you will need to initialize this address on-chain): f1j3u7crhjzwb2cj5mq7vodlt4o66yoyci7lhcauy
5. Country of Operation (Where your organization is legally based): China
6. Region of Operation (What region will you serve?): Asia
7. Type of Allocator, diligence process: (Automated/programmatic, Market-based, or Manual (human-in-the-loop at some phase): Automated/programmatic
9. DataCap requested for allocator for 12 months of activity (This should be an estimate of overall expected activity. Estimate the total amount of DataCap you will be distributing to clients in 12 months, in TiB or PiB): 300 PiB

# 2. Access allocator application (download to save answers)
Click link below to access a Google doc version of the allocator application that can be used to save your answers if you are not prepared to fully submit the application in Step 3. https://docs.google.com/document/d/1-Ze8bo7ZlIJe8qX0YSFNPTka4CMprqoNB1D6V7WJJjo/copy

# 3. Submit allocation application 
Clink link below to access full allocator questionnaire and officially submit your answers:
https://airtable.com/appvyE0VHcgpAkt4Z/shrQxaAIsD693e1ns

Note: Sections of your responses WILL BE posted back into the GitHub issue tracking your application. 
The final section (Additional Disclosures) will NOT be posted to GitHub, and will be maintained by the Filecoin Foundation. 
Application information for notaries not accepted and ratified in this round will be deleted.

**Comment by Kevin-FF-USA** [comment]
Hi @Fatman13 

Wanted to let you know this application has been received along with the Airtable detailed answers - the public answers will be posted in a thread below soon. If you have any questions - please let me know.

**Comment by Filplus-govteam** [comment]
### Basic Information
**1. Notary Allocator Pathway Name:**
Fatman13 (FIP-0078 Pathway)

**2. Organization:**
Guazi Dynamic

**3. On Chain Address for Allocator:**
f1j3u7crhjzwb2cj5mq7vodlt4o66yoyci7lhcauy

**4. Country of Operation:**
China

**5. Region(s) of operation:**
Greater China, Asia minus GCR, Japan

**6. Type of Allocator:**
Automatic

**7. DataCap requested for allocator for 12 months of activity:**
100 PiB

**8. Is your allocator providing a unique, new, or diverse pathway to DataCap? How does this allocator differentiate itself from other applicants, new or existing?:**
The overall diligence process will be automated with minimal manual interventions and falls in line with the ideology presented by FIP-0078 https://fips.filecoin.io/FIPS/fip-0078.html. We believe the proposed type of allocator will be first of its kind and will set a new standard for allocator models with exceptional features that address unmet needs in the ecosystem.

**9. As a member in the Filecoin Community, I acknowledge that I must adhere to the Community Code of Conduct, as well other End User License Agreements for accessing various tools and services, such as GitHub and Slack.:**
Acknowledge
### Client Diligence
**10. Who are your target clients?:**
Other (specified above), Enterprise Data Clients

**11. Describe in as much detail as possible how you will perform due diligence on clients.  If you are proposing an automated pathway, what diligence mechanism will you use to determine client eligibility?:**
Performing due diligence on storage clients is a crucial process for the success of our allocator. Here's a comprehensive guide on how our allocator wll be performing due diligence on clients:

Collect Basic Information:
- Personal Information: Gather basic personal details such as the client's full name and contact information.
- Business Information: If the client represents a business, collect details such as the company name, registration number, and business address.
Verify Identity:
- Verification Services: We will be using Wechat as our identity verification services to double check client identity.
Assess Sample Data:
- Data sampling: Request samples of the data that client is going to on-board  to assess the client's data quality.
Risk Assessment:
- Risk Profiling: Assess the client's risk profile based on its track record on Slack and Github.
- Adverse Media Checks: Conduct checks for adverse media coverage that may indicate potential risks or legal issues associated with the client.
Site Visits (if applicable):
- On-Site Inspection: In some cases, conduct on-site visits to the client's business premises to verify its existence and operations.
Ongoing Monitoring:
- Continuous Monitoring: Establish a channel for ongoing monitoring of the client relationship, including regular updates of client information and Datacap consumptions.
- Event-Driven Monitoring: Monitor for any significant events or changes that may impact the client's Datacap consumption capabilities..
Document Everything:
- Record Keeping: Maintain detailed records of all due diligence activities, communications, and documentation related to the client.
- Audit Trail: Create an audit trail to demonstrate compliance with due diligence procedures.
Client Training:
- Training Programs: Train the client involved in the due diligence process to ensure a consistent and thorough approach.


**12. Please specify how many questions you’ll ask, and provide a brief overview of the questions.:**
The questionnaire would include collecting basic information like names, company names, Slack / Github / Wechat handle and etc. And then the client will be asked to provide some sample data for this allocator to evaluate. Lastly client will be presented with FIP-0078 and feebacks on the subject will be collected.

**13. Will you use a 3rd-party Know your client (KYC) service?:**
Yes. Wechat or Alipay accounts will be used as this allocator’s KYC services as these accounts are mandated by the government to have legit personale behind each account. Additionally WeChat and Alipay KYC service ensures client eligibility, checks against known sanctions lists, and mitigates sybil risk.

**14. Can any client apply to your pathway, or will you be closed to only your own internal clients? (eg: bizdev or self-referral):**
Client application to this allocator is fully open and enjoy inclusive access. We will have an open application process with robust support systems (mikeCRM) and will actively encourage diversity through outreach and community engagement.

**15. How do you plan to track the rate at which DataCap is being distributed to your clients?:**
All DataCap distributions can be tracked on filscan blockchain explorer, but we would also have our own internal bookkeeping spreadsheet (Feishu document) to track all progress with Real-time distribution. 
### Data Diligence
**16. As an operating entity in the Filecoin Community, you are required to follow all local & regional regulations relating to any data, digital and otherwise. This may include PII and data deletion requirements, as well as the storing, transmit:**
Acknowledge

**17. What type(s) of data would be applicable for your pathway?:**
Public Open Dataset (Research/Non-Profit), Public Open Commercial/Enterprise, Private Commercial/Enterprise, Private Non-Profit/Social Impact

**18. How will you verify a client’s data ownership? Will you use 3rd-party KYB (know your business) service to verify enterprise clients?:**
Documentation:
- Request official documentation that proves the client's ownership or authorization to act on behalf of a business entity. This may include business registration documents, certificates of incorporation, and other legal documents.
Legal Agreements:
- Review and sign legally binding agreements that confirm the client's ownership and grant the necessary permissions for the business relationship.
Corporate Resolutions:
- Obtain corporate resolutions or other internal documents that authorize individuals within the organization to engage in specific transactions or partnerships.
Authorized Signatories:
- Verify the identity and authorization of individuals acting as signatories on behalf of the business through official identification documents and corporate resolutions.
Ownership Structure:
- Understand the ownership structure of the client's business, including beneficial owners, major stakeholders, and corporate hierarchy.

Additionally, we will use QCC https://www.qcc.com/ KYB service as a complement to our own KYB service. The process will be applied to all public, private and enterprise data type.


**19.  How will you ensure the data meets local & regional legal requirements?:**
Ensuring that data meets local and regional legal requirements is crucial for compliance and risk mitigation. Here are some general steps that our allocator take to address this: Legal Consultation: Seek advice from our own legal team or legal professionals with expertise in data protection and privacy laws specific to the local and regional jurisdictions where the business operates. Legal experts can provide insights into the applicable laws and help design compliance strategies. Data Mapping: Conduct a thorough data mapping exercise to understand the types of data collected, processed, and stored. Identify the jurisdictions associated with each type of data to assess the legal implications. Privacy Impact Assessments (PIA): Conduct Privacy Impact Assessments to evaluate the potential risks and impacts of data processing activities on individuals' privacy. PIAs help in identifying and mitigating privacy-related issues. Data Classification: Classify data based on sensitivity and regulatory requirements. Different categories of data may have different legal considerations and compliance obligations. Consent Mechanisms: Implement robust consent mechanisms for data collection and processing. Ensure that the organization has obtained valid and informed consent from individuals as required by local regulations. Data Transfer Mechanisms: Chinese regulation mandates that data is never to be transferred across borders. This allocator will implement legal mechanisms to ensure compliance with data transfer regulations.  Data Retention Policies: Establish clear data retention policies in accordance with local laws. Define the duration for which data can be retained and the procedures for secure data disposal. Data Security Measures: Implement robust data security measures to protect data against unauthorized access, breaches, or other security incidents. Ensure compliance with local and regional cybersecurity laws and standards. Client Training: Train clients and relevant stakeholders on data protection laws, privacy policies, and compliance requirements. This helps in creating awareness and fostering a culture of data protection within the organization. Regular Audits and Assessments: Conduct regular audits and assessments to ensure ongoing compliance with local and regional data protection laws. Stay informed about any updates or changes in regulations that may impact data management practices. Data Subject Rights: Establish procedures for handling data subject rights requests, including the right to access, rectification, erasure, and data portability. Ensure that the organization can respond to these requests in a timely manner. Incident Response Plan: Develop an incident response plan to address data breaches or security incidents promptly and in compliance with local breach notification requirements. Monitor Changes in Regulations: Stay informed about changes or updates in local and regional data protection regulations. Regularly review and update data protection practices to align with evolving legal requirements.

**20. What types of data preparation will you support or require?:**
This allocator will fully support DP’s needs on its data distribution requirement. Toolings that we are fully proficient with includes but not limited to Droplet, Singularity, Boost, Graphsplit, etc which we have the technical capacity to train DPs to fulfill their requirements. 

**21. What tools or methodology will you use to sample and verify the data aligns with your pathway?:**
Again this allocator recognize the fact that all data are real (https://github.com/filecoin-project/FIPs/discussions/774#discussioncomment-6631403) as Marko Vukolić puts it in the github discussion and being championed by FIP-0078 https://fips.filecoin.io/FIPS/fip-0078.html.
### Data Distribution
**22. How many replicas will you require to meet programmatic requirements for distribution?:**
5+

**23. What geographic or regional distribution will you require?:**
3+ regions including unique geopolitical / language coverage (NA, EU, Asia), each replica will be at different physical location. This allocator seeks to have minimal VPN and different SP owner operators

**24. How many Storage Provider owner/operators will you require to meet programmatic requirements for distribution?:**
5+

**25. Do you require equal percentage distribution for your clients to their chosen SPs? Will you require preliminary SP distribution plans from the client before allocating any DataCap?:**
Yes. This allocator requires equal percentage from client distribution plan, following our own standardized template, with quantitative (minerID & percentage distribution) and qualitative (SP KYB info collected from before) details about SP prior to initial allocation

**26. What tooling will you use to verify client deal-making distribution?:**
This allocator will incorporate open-sourced tools available to community (AC Bot, CID Checker, etc) to automatically check and report on client deal-making distribution prior to subsequent allocations

**27. How will clients meet SP distribution requirements?:**
This allocator will have a backend to track all deal distribution to a set of vetted and reputable SPs.

**28. As an allocator, do you support clients that engage in deal-making with SPs utilizing a VPN?:**
This allocator is willing to support clients who work with SPs that utilize VPNs, but requires additional KYB checks and still enforces distribution, even if utilizing VPN. For example, we will check the actual deployment plan of SP’s storage system to ensure that VPNs are used just to protect their business. 
### DataCap Allocation Strategy
**29. Will you use standardized DataCap allocations to clients?:**
Yes, standardized

**30. Allocation Tranche Schedule to clients::**
1st: 100 TiB
2nd: 500 TiB
3rd: 1 PiB
4th: 1.5 PiB

Max per client overall depends on the clients track record to follow the distribution rules defined by this allocator. 

**31. Will you use programmatic or software based allocations?:**
Yes, standardized and software based

**32. What tooling will you use to construct messages and send allocations to clients?:**
Yes. We will be using a combination of existing open source toolings (like Notary Registry) and home brew tooling for allocations.

**33. Describe the process for granting additional DataCap to previously verified clients.:**
Yes. The criteria for subsequent allocation requests won’t be approved unless tooling we use in questionnaire No. 26 gives the backend greenlight. Client distribution behavior will be tracked in our system and repetitive offenses will be denied allocation. We will be using a combination of open source toolings such as SA bot and our own home brew solution to automate all datacap requests.

**34. Describe in as much detail as possible the tools used for: • client discoverability & applications • due diligence & investigation • bookkeeping • on-chain message construction • client deal-making behavior • tracking overall allocator health • disput:**
Client applications will be going through our own account based Webpage portal which is built by Pyhon Django powered by unicorn / nginx and hosted on aliCloud with basic UX which is similar to current Github LDN application flow. Due diligence will be submitted through the said webpage portal and prompt for the allocator team to review and reach out to the client. All client information will be stored in a SQLite database with schemas that are in accordance with our KYC, KYB process. On-chain message construction will be using a combination of fiveToken and current opensourced Notary dashboard code to allow datacap allocations. Client deal-making behavior will be checked by AC bot and CID checkers to ensure proper deal distribution. Overall allocator health will be shown in the admin dashboard of the Webpage portal. The web portal will have a dedicated section for disputes and announcements / updates of resolution. Community updates and comms will be conducted on Filecoin Slack.


### Tools and Bookkeeping
**35. Will you use open-source tooling from the Fil+ team?:**
Most if not all of open source tooling from fil+ team will be adopted by this allocator’s custom solution. It’s a matter of integration of f+ tooling with this allocator’s own backend.

**36. Where will you keep your records for bookkeeping? How will you maintain transparency in your allocation decisions?:**
All allocation and checker data we stored in our allocator backend database can be requested and shared by any entities. 
### Risk Mitigation, Auditing, Compliance
**37. Describe your proposed compliance check mechanisms for your own clients.:**
The team behind this allocator will perform regular check-ins, tracking dataCap distribution metrics and understand client demographics, time metrics, trust evaluations with the help of open source tools like CID checker and AC bots. Again all allocation data and checker data from this allocator’s backend database can be shared upon requests from community.

**38. Describe your process for handling disputes. Highlight response times, transparency, and accountability mechanisms.:**
Disputes will be taken with absolute seriousness, which can be either filed on this allocator’s web portal or on Slack. The steps need to be taken are the following…

Establish Clear Policies:
- We will develop and communicate clear policies outlining the dispute resolution process. Ensure that clients, SPs and stakeholders are aware of the steps to follow when a dispute arises.
Accessible Communication Channels:
- We provide accessible communication channels (Slack, emails) for reporting disputes. Ensure that these channels are well-publicized and easily accessible.
Acknowledgment and Initial Response:
- We aim to acknowledge receipt of a dispute promptly, within 24 to 48 hours. The initial response will reassure the parties involved that their concerns are being taken seriously and provide an estimated timeline for resolution.
Designated Point of Contact:
- We will be assigning a designated point of contact or a dedicated team to handle disputes. Clearly communicate who individuals should contact for updates and assistance throughout the resolution process.
Investigation and Fact-Finding:
- We will initiate a thorough investigation into the dispute. Gather relevant information, facts, and evidence to understand the context and complexities of the issue. This may involve interviewing involved parties and reviewing relevant data from AC and CID bots.
Transparency in Communication:
- We will maintain transparency in communication with the parties involved. Provide regular updates on the progress of the investigation, including any challenges encountered or additional information needed. Clearly communicate anticipated timelines for resolution.
Mediation or Resolution Attempt:
- Depending on the nature of the dispute, consider offering mediation or alternative dispute resolution mechanisms. These methods aim to facilitate dialogue and reach a mutually agreeable resolution without formal escalation.
Escalation Procedures:
- If an amicable resolution cannot be achieved, clearly define escalation procedures. Outline the steps for involving fil+ governance or external mediators, if applicable.
Timely Resolution:
- We strive for timely resolution based on the complexity of the dispute. Communicate expected resolution times to the involved parties and adhere to those timelines as closely as possible.
Accountability Mechanisms:
- We will establish accountability mechanisms within the team. This may include reviewing the dispute resolution process periodically, identifying areas for improvement, and holding individuals accountable for the fair and effective resolution of disputes.
Feedback Collection:
- After resolution, we will collect feedback from the involved parties regarding their satisfaction with the process. Use this feedback to continually improve the dispute resolution process.
Documentation:
- We will maintain detailed documentation of the dispute resolution process, including findings, actions taken, and resolutions achieved. This documentation can serve as a reference for future improvements and, if necessary, as evidence of compliance with allocator’s policies.


**39. Detail how you will announce updates to tooling, pathway guidelines, parameters, and process alterations.:**
Announcing updates to tooling, pathway guidelines, parameters, and process alterations is a crucial aspect of maintaining transparency of our allocator and ensuring that users are informed about changes. Here's a detailed plan for making such announcements: Establish a Communication Plan: We will develop a clear communication plan that outlines the channels, frequency, and methods for announcing updates. Consider using a combination of written communication, email, notifications within our allocator webpage portal. Dedicated Communication Channels: We will create dedicated communication channels for updates, such as a Slack announcement, or a section on the allocator’s webpage portal. Ensure that users know where to find the latest information. Regular Release Notes: We will publish regular release notes summarizing the updates, improvements, and alterations made to the tooling, pathway guidelines, parameters, and processes. Include details on bug fixes, new features, and any changes that might impact user interactions. Documentation Updates: We will ensure that documentation is kept up-to-date. If there are alterations to pathway guidelines, parameters, or processes, update relevant documentation promptly. This documentation can be accessible online or within the allocator’s webpage portal.

**40. How long will you allow the community to provide feedback before implementing changes?:**
User Feedback Mechanism:
- We will establish a mechanism for users to provide feedback on updates. Encourage users to share their thoughts, report any issues, or suggest improvements. This feedback loop can be invaluable for continuous improvement.
Feedback Implementation:
- We will act on user feedback received during the announcement phase. If users raise concerns or suggest improvements, acknowledge their input and communicate how this allocator team plans to address or incorporate the feedback.
- Depending on the scope of the feedback, we expect 1 to 2 business week to complete the implementation.
Feedback Loop Closure:
- Once updates have been in place for a reasonable period, provide a follow-up communication summarizing the impact of the changes, improvements made based on user feedback, and plans for future updates.


**41. Regarding security, how will you structure and secure the on-chain notary address? If you will utilize a multisig, how will it be structured? Who will have administrative & signatory rights?:**
The address will be securely stored in a Ledger wallet and only the owner of this allocator can have access to this wallet.

**42. Will you deploy smart contracts for program or policy procedures? If so, how will you track and fund them?:**
Yes. Smart contracts will be deployed. We will adopt a combination of the following open source solution with our own backend portal. https://github.com/dataswap/core https://github.com/dataswap/specs https://github.com/dataswap/go-metadata
### Monetization
**43. Outline your monetization models for the services you provide as a notary allocator pathway.:**
We will not monetize this allocator project. Our vision for Filecoin project aligns with the Filecoin mission https://github.com/filecoin-project/FIPs/blob/master/mission.md , which is described as a decentralized storage chain.

**44. Describe your organization's structure, such as the legal entity and other business & market ventures.:**
Guazi Dynamic has been a Filecoin mining technology service provider since early testnet. Company has since established a robust business model centered around mining Filecoin and helping SPs to serve their storage to clients.  Details on teams commitment and achievements can be found on the last round of notary application here https://github.com/filecoin-project/notary-governance/issues/670

**45. Where will accounting for fees be maintained?:**
Since all services provided are free for this allocator. No accounting will be maintained.
### Past Experience, Affiliations, Reputation
**46. If you've received DataCap allocation privileges before, please link to prior notary applications.:**
https://github.com/filecoin-project/notary-governance/issues/670

**47. How are you connected to the Filecoin ecosystem? Describe your (or your organization's) Filecoin relationships, investments, or ownership.:**
All can be found in https://github.com/filecoin-project/notary-governance/issues/670 On going client applications: None

**48. How are you estimating your client demand and pathway usage? Do you have existing clients and an onboarding funnel?:**
At this point it is very hard to forecast as we don’t know how many allocators will be on-boarded, but we don’t expect high traffic at the beginning.  Yes, we have existing clients we have worked with before and an onboarding funnel associated with these clients.

**Comment by galen-mcandrew** [comment]
## Datacap Request for Allocator
#### Address
> f2ie5kumtwqhhelv5evb6iyqxguveucupaiyhkwvi
#### Datacap Allocated
> 5PiB
