### ISSUE TITLE
v5 Notary Allocator Application: BDE Allocator

### ISSUE THREAD

**Issue by cryptoAmandaL** [filecoin-project/notary-governance#1027]
# v5 Notary Allocator Application

To apply to be an allocator, organizations will submit one application for each proposed pathway to DataCap. If you will be designing multiple specific pathways, you will need to submit multiple applications. 

Please complete the following steps:
# 1. Fill out the information below and create a new GitHub Issue

1. Notary Allocator Pathway Name (This can be your name, or the name of your pathway/program. For example "E-Fil+"):BDE Fil+ Allocator
3. Organization Name: BigData Exchange
4. On-chain address for Allocator (Provide a NEW unique address. During ratification, you will need to initialize this address on-chain): f1sj3dlgezobhqrozumf6x3bjr6cjyynnwck2vwpi
5. Country of Operation (Where your organization is legally based): Singapore
6. Region of Operation (What region will you serve?): All Regions
7. Type of Allocator, diligence process: (Automated/programmatic, Market-based, or Manual (human-in-the-loop at some phase): Market-based
9. DataCap requested for allocator for 12 months of activity (This should be an estimate of overall expected activity. Estimate the total amount of DataCap you will be distributing to clients in 12 months, in TiB or PiB): 200PiB

# 2. Access allocator application (download to save answers)
Click link below to access a Google doc version of the allocator application that can be used to save your answers if you are not prepared to fully submit the application in Step 3. https://docs.google.com/document/d/1-Ze8bo7ZlIJe8qX0YSFNPTka4CMprqoNB1D6V7WJJjo/copy

# 3. Submit allocation application 
Clink link below to access full allocator questionnaire and officially submit your answers:
https://airtable.com/appvyE0VHcgpAkt4Z/shrQxaAIsD693e1ns

Note: Sections of your responses WILL BE posted back into the GitHub issue tracking your application. 
The final section (Additional Disclosures) will NOT be posted to GitHub, and will be maintained by the Filecoin Foundation. 
Application information for notaries not accepted and ratified in this round will be deleted.

**Comment by Kevin-FF-USA** [comment]
Hi @cryptoAmandaL 

Wanted to let you know this application has been received along with the Airtable detailed answers - the public answers will be posted in a thread below soon. If you have any questions - please let me know.

**Comment by Filplus-govteam** [comment]
### Basic Information
**1. Notary Allocator Pathway Name:**
BDX Fil+ Allocator

**2. Organization:**
BigData Exchange

**3. On Chain Address for Allocator:**
f1sj3dlgezobhqrozumf6x3bjr6cjyynnwck2vwpi

**4. Country of Operation:**
Singapore

**5. Region(s) of operation:**
Africa , Asia minus GCR, Greater China, Europe, Oceania, Japan, North America, South America, Other

**6. Type of Allocator:**
Market-based

**7. DataCap requested for allocator for 12 months of activity:**
200PiB

**8. Is your allocator providing a unique, new, or diverse pathway to DataCap? How does this allocator differentiate itself from other applicants, new or existing?:**
Our allocator provides a unique pathway to DataCap by focusing on small businesses and startups, enhancing Filecoin network participation and supporting emerging markets. 
We've innovated with a smart contract-based allocation process for transparency and efficiency, reducing bias and abuse risks. Additionally, we emphasize data compliance and security, implementing a thorough review process for all applicants and offering data security consultations. 


**9. As a member in the Filecoin Community, I acknowledge that I must adhere to the Community Code of Conduct, as well other End User License Agreements for accessing various tools and services, such as GitHub and Slack.:**
Acknowledge
### Client Diligence
**10. Who are your target clients?:**
Individuals learning about Filecoin, Small-scale developers or data owners, Enterprise Data Clients

**11. Describe in as much detail as possible how you will perform due diligence on clients.  If you are proposing an automated pathway, what diligence mechanism will you use to determine client eligibility?:**
Our due diligence process for clients is comprehensive, encompassing various measures to ensure responsible DataCap allocation and maintain the integrity of the Filecoin network. 
It includes a thorough review of client applications, covering their business information, data storage needs, and technical capabilities. We conduct background checks for legitimacy and legal compliance, verify adherence to data protection laws, and assess their technical infrastructure. 
The process also involves evaluating their proposed use case for DataCap to align with Filecoin's goals, conducting direct interviews with key personnel, and implementing ongoing monitoring post-allocation. 


**12. Please specify how many questions you’ll ask, and provide a brief overview of the questions.:**
We will make sure that clients provide the on-chain address for which the datacap is currently requested, as well as addresses that have been used in the past. Many data clients have use [bigdataexchange.io](https://www.bigdataexchange.io/) to source for a diverse range of storage providers.
During our daily operations, we check in regularly on the on-chain transactions based on wallet addresses and CIDs and ensure that the allocated DataCaps are not abused. Therefore, it’s highly likely that we will help detect any abnormal or potential abusive behaviors.

We will condcut due diligence on clients with the following questions:

**Client background**
- The nature of the clients’ organisation, project, or use case. 
- Please link to relevant website, Github repos, or social media links
- Please include as much relevant external media to provide contextual information

**Track record**
- Have you been approved for a DataCap previously? If so, can you share the details of the last allocation decision (who approved your DataCap, what your plan was for spending it, and how you executed that plan)?
- How do you plan on securing the DataCap to ensure your organisation (and its delegated members) are the ones allocating the DataCap?

**Reputation**
- Are there any disputes open against you from your previous DataCap allocations?
- Have you ever previously violated: Your own attested allocation/audit plan? Been found to be in violation of the Principles of Filecoin Plus?
- Do you agree to use the DataCap to only store data that abides by local regulations and is in compliance with the recipient miner’s terms of service?

**Network alignment**
- Do you intend to store your data in a single geography or many?



**13. Will you use a 3rd-party Know your client (KYC) service?:**
Yes, we use https://www.advomi.com.sg/  as third-party KYC service to enhance our due diligence process. The chosen service specializes in identity verification and compliance checks, covering a wide range of regions globally. 
They perform thorough checks, including identity verification, financial background analysis, and legal compliance assessment. Their process involves collecting essential information such as legal name, organizational details, financial history, and compliance status. 
The data obtained from this service will be integrated into our pathway through a secure, automated system. It allows us to cross-reference the KYC data with our own evaluations, ensuring a comprehensive and robust vetting process for all clients.


**14. Can any client apply to your pathway, or will you be closed to only your own internal clients? (eg: bizdev or self-referral):**
Our pathway is open to all clients, not limited to internal clients or self-referrals. We aim to serve a diverse range of users, including external businesses and individual clients. This inclusivity aligns with our objective to broaden access to DataCap and support the growth of the Filecoin network.  While we do not operate a 'white label' service where we apply on behalf of our clients, we provide comprehensive support to guide applicants through the application process, ensuring clarity and accessibility for all potential clients.

**15. How do you plan to track the rate at which DataCap is being distributed to your clients?:**
We plan to track the distribution of DataCap to our clients using a combination of automated monitoring systems and manual oversight. Our system will record each allocation of DataCap in real-time, allowing us to monitor the rate and volume of distribution closely.  We'll also integrate this data with our client management system to maintain a comprehensive view of each client's DataCap usage and needs. Regular audits and reports will be conducted to ensure transparency and adherence to our distribution guidelines, enabling us to adjust our allocation strategies as needed to meet client demand effectively and maintain network integrity.
### Data Diligence
**16. As an operating entity in the Filecoin Community, you are required to follow all local & regional regulations relating to any data, digital and otherwise. This may include PII and data deletion requirements, as well as the storing, transmit:**
Acknowledge

**17. What type(s) of data would be applicable for your pathway?:**
Private Non-Profit/Social Impact, Private Commercial/Enterprise, Public Open Commercial/Enterprise, Public Open Dataset (Research/Non-Profit)

**18. How will you verify a client’s data ownership? Will you use 3rd-party KYB (know your business) service to verify enterprise clients?:**
To verify a client's data ownership, we will implement a multifaceted approach. For individual clients, we will require documentation that establishes their rights to the data, such as contracts, licenses, or proof of creation. For enterprise clients, we plan to utilize a third-party KYB service. 
This service specializes in verifying business entities and their legal rights to data, ensuring the authenticity and legal standing of the client's claim to the data they wish to store. The KYB process will include checks on corporate documentation, legal data ownership rights, and compliance with relevant laws. 
We will cross-reference this information with our internal checks to ensure the data's provenance is legitimate and the client has the rightful authority to store it on the Filecoin network. 


**19.  How will you ensure the data meets local & regional legal requirements?:**
To ensure the data meets local and regional legal requirements, we will establish a robust compliance framework. This includes conducting thorough legal assessments for each client, focusing on the specific laws and regulations relevant to their data and region. We will collaborate with legal experts to stay updated on evolving data protection and privacy laws.  Additionally, our due diligence process will incorporate checks for regional compliance, where clients must provide evidence of their adherence to local data laws. We will also integrate a periodic review system to reevaluate existing clients' compliance in response to any changes in legal standards. 

**20. What types of data preparation will you support or require?:**
We will support and require specific types of data preparation to ensure optimal storage and retrieval efficiency on the Filecoin network. Our support includes guidance on data formatting, encryption for security, and metadata tagging for easier retrieval and management. We also use instant communication tools such as Emails, Telegram and Slack to keep efficiency commucation with DP.  Additionally, we will recommend, and in some cases require, data sharding for larger datasets. Sharding helps in optimizing storage and retrieval processes, enhancing data redundancy, and ensuring better overall performance and security of the data stored. 

**21. What tools or methodology will you use to sample and verify the data aligns with your pathway?:**
To sample and verify client data, we will use a combination of automated tools and manual inspection methods. Our approach includes using software tools to randomly sample data, ensuring it aligns with the client's claims regarding type and preparation. This will involve checking data formats, metadata consistency, and encryption standards. We will also conduct spot checks where our team manually reviews selected data samples to confirm their authenticity and compliance with our pathway requirements.  To prevent sector-size abuse like sector padding, we will implement strict monitoring protocols, employing algorithms to detect anomalies indicative of padding practices. If such practices are detected, we will take appropriate action as per our compliance policies. 
### Data Distribution
**22. How many replicas will you require to meet programmatic requirements for distribution?:**
5+

**23. What geographic or regional distribution will you require?:**
We will require data to be stored in at least 5 physical locations, spread across a minimum of 4 separate geopolitical regions. This approach ensures not only geographical diversity but also mitigates risks associated with data storage concentrated in a single region. While we aim to be inclusive, we will comply with all applicable international regulations and may exclude certain geopolitical regions if they are subject to international sanctions or pose significant legal or operational risks. 

**24. How many Storage Provider owner/operators will you require to meet programmatic requirements for distribution?:**
5+

**25. Do you require equal percentage distribution for your clients to their chosen SPs? Will you require preliminary SP distribution plans from the client before allocating any DataCap?:**
In our allocation strategy, we do not mandate equal percentage distribution to SPs by our clients. Different data storage needs may require varied distribution approaches. However, we do require clients to submit a preliminary SP distribution plan before allocating any DataCap to them. This plan should outline their intended distribution strategy, including the chosen SPs and the rationale for their selection. To streamline this process and ensure consistency in the information provided, we have developed a standardized template for clients to fill out.  This template is designed to capture all necessary details about their distribution strategy, including percentages, SPs' capabilities, and the data types to be stored. https://docs.google.com/document/d/1sVD9QPwJapGPC_aeKHStZ9iz-_n8npGNbYueFz7G7c0/edit

**26. What tooling will you use to verify client deal-making distribution?:**
We will use exsiting tooling such as datacapstats.io , AC Bot and CID checker. Besides that, we are also in the process of developing a custom analytics dashboard. This dashboard will integrate advanced data visualization tools and machine learning algorithms to analyze distribution patterns, flagging any anomalies or deviations from the planned allocation.  This allows us to not only react to data but to predict and prevent potential issues. 

**27. How will clients meet SP distribution requirements?:**
We will use Fil+ client onboarding tool, also implement a hybrid approach combining manual oversight with advanced software solutions base on reputation of SPs. This software not only automates the distribution process but also ensures compliance and efficiency, reducing the risk of concentration and promoting decentralization. In addition to this, our team will conduct regular manual reviews and audits to oversee the automated process, ensuring that any anomalies or unique cases are addressed promptly.

**28. As an allocator, do you support clients that engage in deal-making with SPs utilizing a VPN?:**
As an allocator, our stance on clients engaging in deal-making with SPs using a VPN is one of cautious approval, provided it adheres to the principles and security standards of the Filecoin network. We recognize that VPNs can be a legitimate tool for enhancing privacy and security, especially for clients in regions with restrictive internet policies or those handling sensitive data.  However, to maintain transparency and compliance, we will implement a monitoring system to track and report VPN usage among our clients. This will involve a combination of software tools that can detect and log VPN connections during deal-making processes.  We will also require clients to disclose their VPN usage as part of their deal-making disclosures, detailing the reasons for VPN use and the measures taken to ensure it does not compromise data integrity or the equitable distribution of DataCap. Regular audits and reviews will be conducted to ensure that VPN usage is in line with Filecoin's guidelines and does not obscure or hinder the fair and decentralized nature of data storage on the network.
### DataCap Allocation Strategy
**29. Will you use standardized DataCap allocations to clients?:**
Yes, standardized

**30. Allocation Tranche Schedule to clients::**
• First: Upon initial approval, clients receive 20% of their total requested DataCap. .
• Second:After successful utilization of at least 70% of the first tranche and a compliance review, clients are eligible for an additional 30% of their total requested DataCap. 
• Third:After successful utilization of at least 70% of the second tranche and a compliance review, clients are eligible for an additional 30% of their total requested DataCap.
• Fourth:The final tranche, providing the remaining 20% of the total requested DataCap, is allocated upon 70% utilization of the third tranche and a comprehensive audit of all previous allocations.
• Max per client overall: 10PiB

**31. Will you use programmatic or software based allocations?:**
Yes, standardized and software based

**32. What tooling will you use to construct messages and send allocations to clients?:**
Except for using exsting notary registry tooling at https://filplus.fil.org/#/, We also  plan to utilize a custom-built allocation management system, developed in-house, to construct messages and send allocations to clients. Such as Lotus and Boost.

**33. Describe the process for granting additional DataCap to previously verified clients.:**
Our process for granting additional DataCap to previously verified clients is structured and criteria-based. Initially, we assess the percentage of DataCap already utilized by the client. A subsequent allocation request is considered when a client has responsibly used at least 70% of their previous allocation. In addition, we will leverage open-source tooling, particularly the Subsequent Allocation (SA) bot, to automate and streamline this process. The SA bot aids in efficiently managing allocation requests, tracking usage, and ensuring compliance with Filecoin's standards. It also provides transparency and consistency in how additional DataCaps are allocated.  Our team will also conduct a manual review of each request to confirm the client’s adherence to their initial allocation agreement and the overall Filecoin principles.

**34. Describe in as much detail as possible the tools used for: • client discoverability & applications • due diligence & investigation • bookkeeping • on-chain message construction • client deal-making behavior • tracking overall allocator health • disput:**
We use a suite of essential automated tools, each specializing in distinct areas: SEO and CRM software for customer discoverability and application processing, AML and KYC software for due diligence and investigation, automated accounting software for bookkeeping, blockchain-specific tools for on-chain message construction, analytics software for monitoring customer transaction behavior, real-time health tracking systems for the allocator, communication and ticketing platforms for dispute resolution, and community engagement tools like newsletters and social media management. All these tools are open-source with robust automation capabilities, compliance and due diligence alert systems, and be characterized by excellent UI/UX and comprehensive documentation, ensuring a streamlined, compliant, and user-friendly management experience.
### Tools and Bookkeeping
**35. Will you use open-source tooling from the Fil+ team?:**
Key tools from the Fil+ suite we intend to use include the Fil+ client onboarding tool for initial client assessments and the Subsequent Allocation (SA) bot for managing ongoing DataCap allocations. of couse we are also going to use Github, Google spreadsheet and MongoDB.  GitHub repository for tracking changes, feedback, and updates to our allocation strategy and processes. For data management and reporting, we will employ a combination of Google Spreadsheets and MongoDB.  Google Spreadsheets will be used for real-time data tracking and collaboration, while MongoDB will serve as our primary database for storing detailed client and allocation records. 

**36. Where will you keep your records for bookkeeping? How will you maintain transparency in your allocation decisions?:**
We plan on keeping a publicly accessible record of all our allocation decisions in collaborative and shareable docs, which would be published via GitHub.

We plan on documenting and providing the following details:
- Name
- Application #
- GitHub application link
- Website
- Social media
- Contact information
- Sample data address
- Requested amount
- First allocation date & amount
- Allocation progress (%)
- Last allocation date & amount

### Risk Mitigation, Auditing, Compliance
**37. Describe your proposed compliance check mechanisms for your own clients.:**
Our compliance strategy includes regular quarterly check-ins with clients, enhanced monthly monitoring for new clients, and the use of tools like the CID Checker and Retrievability Bot to track DataCap distribution and usage. We will gather metrics on DataCap utilization, client demographics, and storage behaviors to ensure adherence to Filecoin's protocols. While we offer some tolerance for new clients as they adapt, strict compliance with network standards is mandatory, with adjustments made as necessary based on ongoing evaluations.


**38. Describe your process for handling disputes. Highlight response times, transparency, and accountability mechanisms.:**
Our dispute resolution process is designed for promptness, transparency, and accountability. In case of a dispute, we aim to respond within 48 hours. The initial step involves an internal review to understand the nature and specifics of the dispute, whether it's related to DataCap distribution, data compliance, or storage deal execution. We maintain detailed records to facilitate this process.  In cases involving other notaries or the Fil+ Governance Team, we will provide a detailed account of our decisions and actions, supported by our records. 


**39. Detail how you will announce updates to tooling, pathway guidelines, parameters, and process alterations.:**
We will announce updates to our tooling, pathway guidelines, and process alterations through a combination of public channels, including our GitHub repository, official email communications, and a dedicated section on our website. These updates will be scheduled on a quarterly basis to maintain consistency and minimize disruption, except in cases of urgent security or compliance needs.  We will provide clear documentation of each update, ensuring our clients and the Fil+ Governance Team are well-informed. Significant programmatic changes that might require reapplication will be thoroughly reviewed internally before announcement and implementation, to align with Fil+ guidelines and minimize scope creep. 

**40. How long will you allow the community to provide feedback before implementing changes?:**
We will allow a minimum period of two weeks for the community to provide feedback before implementing any major changes. This timeline ensures ample opportunity for diverse input while maintaining the efficiency of our operations. We will engage the community through forums, GitHub discussions, and dedicated Slack channels. Moderation and facilitation will be managed by our team to ensure constructive and relevant discussions. 
Feedback will be weighed based on its impact, feasibility, and alignment with Filecoin's principles and our strategic goals. We commit to considering all perspectives, with a focus on decisions that best serve the broader objectives of the Filecoin ecosystem. 


**41. Regarding security, how will you structure and secure the on-chain notary address? If you will utilize a multisig, how will it be structured? Who will have administrative & signatory rights?:**
We will secure our on-chain notary address through a multisig setup, ensuring enhanced security and operational integrity. The multisig will involve two signatories, selected from our senior management and IT security team, to provide checks and balances. Each signatory will have equal administrative and signatory rights, with a policy requiring at least two signatures for any transaction, aligning with best practices in security and governance. 
Additional IT and operational security (OpSec) guardrails will include regular security audits, encrypted communication channels, and strict access controls to sensitive systems and information. This structured approach ensures robust security for our on-chain activities while maintaining transparency and accountability. 


**42. Will you deploy smart contracts for program or policy procedures? If so, how will you track and fund them?:**
Yes. We plan to deploy smart contracts for certain programmatic procedures to automate and enforce policy compliance. These contracts will be primarily used for tracking DataCap allocations and ensuring adherence to distribution guidelines. The development, testing, and deployment of these smart contracts will be managed through a dedicated GitHub repository, allowing for transparent version control and community input.  We will fund the deployment and operation of these contracts through a designated budget allocated for IT and blockchain operations. Any existing drafts of these smart contracts will be made publicly available in the repository for review and feedback.
### Monetization
**43. Outline your monetization models for the services you provide as a notary allocator pathway.:**
We will charge fees for specific services: 1024 FIL for every 1PiB of data preparation and management, 2000 FIL per data clearinghouse distribution transaction.
 These fees are set to cover service costs and fund ongoing improvements, ensuring our services remain accessible and high-quality, while upholding transparency and fairness within the Filecoin ecosystem.


**44. Describe your organization's structure, such as the legal entity and other business & market ventures.:**
BigData Exchange is a Filecoin data storage auction house and marketplace that connects clients with valuable public data and storage providers with storage capacity. We aim to provide liquidity for data storage services and have a fair and transparent price discovery process, determined by market participants. We are registered and headquartered in Singapore. Our team comprises of 6 members globally.  - With the current demand for Filecoin plus deals, there are several benefits that BigData Exchange brings to the Filecoin network: - An innovative storage platform to incentivize more people to source, migrate, and store valuable public data on Filecoin - A transparent marketplace to connect storage providers with data communities, which adds visibility to the SP selection process and prevents potential self-dealing activities

**45. Where will accounting for fees be maintained?:**
Our fee accounting, including staking, burning, and releasing mechanisms, will be tracked in a secure, cloud-based ledger, ensuring precise and transparent records. We'll use smart contracts on the Filecoin network for immutable recording of transactions, providing clear audit trails for Fil+ Governance and stakeholders. Quarterly financial reports detailing these activities will be published on our website and GitHub, offering transparency and ease of auditing for all monetization processes.
### Past Experience, Affiliations, Reputation
**46. If you've received DataCap allocation privileges before, please link to prior notary applications.:**
https://github.com/filecoin-project/notary-governance/issues/703

**47. How are you connected to the Filecoin ecosystem? Describe your (or your organization's) Filecoin relationships, investments, or ownership.:**
BigData Exchange is a data storage marketplace connecting Filecoin storage providers with data communities.  We aim for liquidity and a fair price discovery process for data storage services. In 18 months, we have facilitated more than over 100 PiB of data transactions between data clients and SPs , as shown on https://www.bigdataexchange.io/.  As transactions are on chain, our marketplace offers visibility and transparency of payment and verified deals flows, which we hope can help with governance.  We have also participated extensively in ecosystem events, including FIL Austin （June 2023), FIL Singapore (September 2023), and FIL Istanbul (November 2023) Through our social media presence, we are also actively promoting Filecoin’s mission and value propositions, broadcasting and educating the broader community on data onboarding initiatives and ecosystem work groups.

**48. How are you estimating your client demand and pathway usage? Do you have existing clients and an onboarding funnel?:**
As of the current quarter, BDX serves 50+ active clients, with an additional 30+ clients in various stages of the onboarding funnel. Our market research indicates a growing demand for decentralized storage solutions, with a projected annual increase of 20% in client acquisitions. This is supported by an estimated 15% quarterly growth in pathway usage, driven by both existing and new clients. Our revenue has an average monthly growth rate of 10%. This growth is attributed to a combination of increased client usage and the introduction of new monetization structures, such as staking and service fees. Our estimates for client demand and pathway usage are based on a combination of market analysis and our existing client base.  We also conduct regular market research to understand trends and potential demands in the blockchain and decentralized storage sectors. Our onboarding funnel is structured and efficient, involving initial consultations, detailed needs assessments, and customized service proposals, ensuring a steady stream of clients transitioning into our pathway.  This dual approach of leveraging existing relationships and proactively identifying market opportunities allows us to accurately forecast and meet client demand.

**Comment by kevzak** [comment]
## Datacap Request for Allocator
#### Address
> f2puyjzpbpgzgizmjt4uwjmajsjfqlfmhaidrvfpi 
#### Datacap Allocated
> 5PiB

**Comment by Kevin-FF-USA** [comment]
Hi @cryptoAmandaL

On the next Fil+ Allocator meeting we will be going over each refill application. Wanted to ensure you were tracking the review discussion taking place in https://github.com/filecoin-project/Allocator-Governance/issues/20.

If your schedule allows, recommend coming to the May 28th meeting to answer/discuss the issues raised in the recent distributions. This will allow you to faster address - or, the issue in Allocator Governance for ongoing written discussion.

Warmly,
-Kevin
https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles

**Comment by galen-mcandrew** [comment]
## Datacap Request for Allocator
#### Address 
> f2puyjzpbpgzgizmjt4uwjmajsjfqlfmhaidrvfpi
#### Datacap Allocated
> 2.5PiB

**Comment by galen-mcandrew** [comment]
[bafy2bzacedf3xpfrfnjykabky2lw7mbitveqizupjo3ehwf3xctqbc42bdc7m](https://filfox.info/en/message/bafy2bzacedf3xpfrfnjykabky2lw7mbitveqizupjo3ehwf3xctqbc42bdc7m?t=4)

**Comment by galen-mcandrew** [comment]
## DataCap Request for Allocator
#### Address
> f2puyjzpbpgzgizmjt4uwjmajsjfqlfmhaidrvfpi
#### Datacap Allocated
> 2.5PiB

**Comment by galen-mcandrew** [comment]
https://filfox.info/en/message/bafy2bzacebkyewh6ubbjl76slq3igkv3m2pyohyylg2vcotvdiuuxqwccsic2

**Comment by galen-mcandrew** [comment]
## Datacap Request for Allocator
#### Address
> f2puyjzpbpgzgizmjt4uwjmajsjfqlfmhaidrvfpi 
#### Datacap Allocated
> 2.5PiB

**Comment by galen-mcandrew** [comment]
bafy2bzacedph7q7s6qfp5bffyoxvjp72tphrt3equq6f3ypkaxzoix7xyacm4

**Comment by galen-mcandrew** [comment]
## Datacap Request for Allocator
#### Address
> f2puyjzpbpgzgizmjt4uwjmajsjfqlfmhaidrvfpi 
#### Datacap Allocated
> 0PiB

**Comment by galen-mcandrew** [comment]
Approval: bafy2bzacedw76vp6r5zkn6wuocupucs5ewtjrpvr2wihhzlhnna6zjcgtjqxa
