### ISSUE TITLE
v5 Notary Allocator Application: SXX Future Data

### ISSUE THREAD

**Issue by sxxfuture-official** [filecoin-project/notary-governance#1028]
# v5 Notary Allocator Application

To apply to be an allocator, organizations will submit one application for each proposed pathway to DataCap. If you will be designing multiple specific pathways, you will need to submit multiple applications. 

Please complete the following steps:
# 1. Fill out the information below and create a new GitHub Issue

1. Notary Allocator Pathway Name (This can be your name, or the name of your pathway/program. For example "E-Fil+"): SXX Future Data
3. Organization Name: SXX Future Data Technology Co., Ltd.
4. On-chain address for Allocator (Provide a NEW unique address. During ratification, you will need to initialize this address on-chain):f13r7vha3bwdmupibamyr34sg653abb3ayfre2apq     
5. Country of Operation (Where your organization is legally based): China
6. Region of Operation (What region will you serve?): Asia, Greater China Region (GCR) 
7. Type of Allocator, diligence process: (Automated/programmatic, Market-based, or Manual (human-in-the-loop at some phase): Manual
9. DataCap requested for allocator for 12 months of activity (This should be an estimate of overall expected activity. Estimate the total amount of DataCap you will be distributing to clients in 12 months, in TiB or PiB): 150PiB

# 2. Access allocator application (download to save answers)
Click link below to access a Google doc version of the allocator application that can be used to save your answers if you are not prepared to fully submit the application in Step 3. https://docs.google.com/document/d/1-Ze8bo7ZlIJe8qX0YSFNPTka4CMprqoNB1D6V7WJJjo/copy

# 3. Submit allocation application 
Clink link below to access full allocator questionnaire and officially submit your answers:
https://airtable.com/appvyE0VHcgpAkt4Z/shrQxaAIsD693e1ns

Note: Sections of your responses WILL BE posted back into the GitHub issue tracking your application. 
The final section (Additional Disclosures) will NOT be posted to GitHub, and will be maintained by the Filecoin Foundation. 
Application information for notaries not accepted and ratified in this round will be deleted.

**Comment by Kevin-FF-USA** [comment]
Hi @sxxfuture-official 

Wanted to let you know this application has been received along with the Airtable detailed answers - the public answers will be posted in a thread below soon. If you have any questions - please let me know.

**Comment by Filplus-govteam** [comment]
### Basic Information
**1. Notary Allocator Pathway Name:**
SXX Future Data

**2. Organization:**
SXX Future Data Technology Co., Ltd.

**3. On Chain Address for Allocator:**
f13r7vha3bwdmupibamyr34sg653abb3ayfre2apq

**4. Country of Operation:**
China

**5. Region(s) of operation:**
Greater China, Asia minus GCR, Japan, North America

**6. Type of Allocator:**
Manual

**7. DataCap requested for allocator for 12 months of activity:**
150PiB

**8. Is your allocator providing a unique, new, or diverse pathway to DataCap? How does this allocator differentiate itself from other applicants, new or existing?:**
The general distribution way remains unchanged, but we will make some optimization in details.
For example:
1. We will indicate the name of the distributor in github application to distinguish the Datacap applications of other distributors.
2. We will provide a special SPs disclosure portal without comments, and the background will record data through the database as a basis for judgment.

**9. As a member in the Filecoin Community, I acknowledge that I must adhere to the Community Code of Conduct, as well other End User License Agreements for accessing various tools and services, such as GitHub and Slack.:**
Acknowledge
### Client Diligence
**10. Who are your target clients?:**
Individuals learning about Filecoin, Small-scale developers or data owners, Enterprise Data Clients, Other (specified above)

**11. Describe in as much detail as possible how you will perform due diligence on clients.  If you are proposing an automated pathway, what diligence mechanism will you use to determine client eligibility?:**
We divide client information into individual users and enterprise users.
We will work closely with clients when they implement DataCap and support them to complete every step. In order for clients to use DataCap, they must change and agree to certain restrictions and uses. If they don't agree with this, or don't meet any criteria in the initial final review stage, we will suspend the allocation. We will follow the process listed above to audit my clients. Will the client's performance be recorded and recorded? Any unacceptable behavior will be recorded and blacklisted.
We have established an independent online and offline application process. If the application is larger than 50TiB, we will add offline review based on online survey method (visiting clients on business trip or inviting clients to SXX).
In addition, we may ask some further questions to give the applicant an accurate score.
In order to get more clients involved in the Filecoin network, we're not going to ask too many complicated questions, but focus on questions about the validity of clients.
Question List:
1. Please provide the organization name, business scale, social media account number, followers and business license (which can be sent by email); If you are an individual, please provide your name, date of birth, work unit and size, employment certificate, social media account number and followers, and ID card (which can be sent by email);
2. When did you get to know Filecoin? Please describe the project you participated in. What do you want from Filecoin? Do you have any suggestions or expectations for the Filecoin network?
3. Is there any legal risk? What percentage of your questions are there?
4. Please describe your organization, such as the time of establishment, the number of employees, the number of users, and the number of social media followers.
5. What is your data volume, source and later planning? Please describe the type, format, source, storage capacity and openness of the data to be stored in Filecoin (and if the data can be made public, how can others retrieve it? )
6. In which area do you plan to store the data? How many miners are you looking for? Please list SP ID. What is the storage ratio of each mining machine? What are the requirements for miners? Finally, please explain your layoff plan.
7. Do you agree to disclose trading information? If you get the DataCap, please disclose the transaction information in time.
We may add additional questions and requests based on responses and client due diligence.

**12. Please specify how many questions you’ll ask, and provide a brief overview of the questions.:**
Client information and application purpose are one of the important standards of our audit.
1. Study the company's entity information
2. investigate the company
3. Sign a cooperation agreement
We will ask the following questions:
What kind of data do you want to store and for what purpose?
What is your plan for the number of SP's to store data, the area and the number of miners allocated to each SP?
What security measures do you have?
Do you abide by local laws and regulations and accept SP's terms of service?
We regularly check users to see if they are as good as they say.

**13. Will you use a 3rd-party Know your client (KYC) service?:**
Yes, because our client that distributes services is mainly aimed at Chinese mainland, we adopt diversified third-party channels for KYC in Chinese mainland.
1. Enterprise survey: used to investigate the business information, enterprise relationship and equity structure of enterprises or individuals.
https://www.qcc.com/
https://www.tianyancha.com/
2. Credit inquiry
https://ipcrs.pbccrc.org.cn/
3. Patent inquiry
https://www.cnipa.gov.cn/

**14. Can any client apply to your pathway, or will you be closed to only your own internal clients? (eg: bizdev or self-referral):**
Any client

**15. How do you plan to track the rate at which DataCap is being distributed to your clients?:**
We will develop a testing program for the distribution of Datacap, and inquire about the balance and addition of datacap of each client address through lotus-api. And the information obtained by api is rendered and displayed through Grafana, and our staff will inspect the progress every day. The main purpose is to ensure that the allocation frequency of data caps is carried out according to the rules, and to avoid unreasonable allocation of a large number of data caps to client accounts or untimely allocation of data caps when bugs occur.
### Data Diligence
**16. As an operating entity in the Filecoin Community, you are required to follow all local & regional regulations relating to any data, digital and otherwise. This may include PII and data deletion requirements, as well as the storing, transmit:**
Acknowledge

**17. What type(s) of data would be applicable for your pathway?:**
Public Open Dataset (Research/Non-Profit), Public Open Commercial/Enterprise, Private Commercial/Enterprise, Private Non-Profit/Social Impact, Other (specified elsewhere)

**18. How will you verify a client’s data ownership? Will you use 3rd-party KYB (know your business) service to verify enterprise clients?:**
To verify a client's data ownership, our notary service will employ a rigorous process. We will utilize a combination of on-chain and off-chain methods to confirm the provenance of the claimed data. This process involves examining the client's data storage requests, verifying data integrity through cryptographic proofs, and cross-referencing with off-chain evidence.
For the verification of data ownership and use right, there is no good universal third-party service to use, and we will conduct different degrees of review according to the data type.
Public Open Dataset: We will ask for open source or public file or webpage URL.
Private or Commercial Dataset: We will ask for proof of ownership and use of data with legal benefits.

**19.  How will you ensure the data meets local & regional legal requirements?:**
Ensuring compliance with local and regional legal requirements is a priority for our notary service. We will implement a robust system that involves thorough legal research to understand the specific data storage regulations and requirements in each jurisdiction where our clients operate. Our approach includes: 1. Legal Expertise: We will engage legal experts with knowledge of local and regional laws to ensure a comprehensive understanding of the legal landscape. 2. Regular Compliance Audits: Periodic audits will be conducted to ensure ongoing compliance with any changes in local or regional regulations. 3. Client Education: We will educate clients about local and regional legal requirements, providing guidance on best practices to maintain compliance. 4. Documentation: All data storage agreements will be documented and structured to align with the legal requirements of the respective jurisdictions. Our commitment is to establish a transparent and legally sound process that safeguards both clients and the network.

**20. What types of data preparation will you support or require?:**
We are committed to supporting a wide range of data preparation methods to cater to diverse client needs. Our approach includes: 1. Flexible Data Formats: We will support various data formats to accommodate different types of data, ensuring flexibility for our clients. 2. Data Encryption Standards: To enhance security, we will encourage and support data encryption before submission, following industry best practices. 3. Integration Support: While we may not provide specific data preparation services, we will offer integration support for popular data preparation tools or services that clients prefer to use. 4. Guidelines for Sharding: We will provide guidelines and best practices for data sharding, allowing clients to optimize their data for efficient storage on the Filecoin network.

**21. What tools or methodology will you use to sample and verify the data aligns with your pathway?:**
To sample and verify data alignment with our pathway, we will employ a combination of tools and methodologies: 1. Data Retrieval Tools: We will use tools such as curl, lotus, and boost to download the data locally from the Filecoin network. 2. Data Decompression: After retrieval, we will use lotus tools to decompress the data to its original form. 3. Manual Verification: A crucial step involves manual verification, where our team will cross-check the downloaded and decompressed data against the information provided in the client's application. This verification process ensures alignment with the claimed data type and preparation requirements. 4. Prevention of Sector-Size Abuse: To prevent sector-size abuse, including sector padding, we will implement thorough checks during the verification process. This includes scrutinizing the size of the data sectors to ensure they align with the expected standards and do not involve any form of manipulation.
### Data Distribution
**22. How many replicas will you require to meet programmatic requirements for distribution?:**
5+

**23. What geographic or regional distribution will you require?:**
We will require a diverse geographic or regional distribution of nodes. Our principle is to have nodes distributed across at least four different countries or regions, spanning at least two different continents. During the initial three rounds of allocation, we will apply a more lenient approach to this check. However, after the third round, we will enforce strict adherence to this requirement. Considering the varying distribution of Filecoin nodes worldwide, we acknowledge that certain regions may be more popular for node deployment. Therefore, we allow a relatively larger proportion of nodes from these popular regions. Nevertheless, we will maintain a commitment to achieving a broad and balanced global distribution of nodes.

**24. How many Storage Provider owner/operators will you require to meet programmatic requirements for distribution?:**
5+

**25. Do you require equal percentage distribution for your clients to their chosen SPs? Will you require preliminary SP distribution plans from the client before allocating any DataCap?:**
Yes, we do require an equal percentage distribution for our clients to their chosen Storage Providers (SPs). We will request preliminary SP distribution plans from the client before allocating any DataCap. The information will be collected using a template that outlines the client's proposed distribution strategy. To monitor the DataCap allocation ratios, we will continue to utilize the automated monitoring tool CID Checker Bot. Our allocation principles include: 1. No single Storage Provider should exceed 25% of the total DataCap. 2. Storage Providers should not store duplicate data for more than 20%. After three rounds of DataCap allocation, we will rigorously enforce these standards to ensure a balanced and efficient use of resources.

**26. What tooling will you use to verify client deal-making distribution?:**
datacapstats.io ,  CID checker bot , retrievalbot-dashboard , https://filecoin.tools/

**27. How will clients meet SP distribution requirements?:**
Clients are expected to meet SP distribution requirements through a combination of education on the established rules and guidelines. SP distribution is a crucial metric in our assessment of client work. We will provide clear instructions to clients regarding our expectations for SP distribution. The specific implementation of SP distribution is the responsibility of the client, and they are encouraged to address it on their own. We will offer guidance and suggestions to clients, and they can choose to create distribution plans manually or by using record-keeping tools like spreadsheets. While we will educate clients on the rules, the actual process of achieving SP distribution compliance is delegated to the client.

**28. As an allocator, do you support clients that engage in deal-making with SPs utilizing a VPN?:**
Yes, as an allocator, we support clients engaging in deal-making with Storage Providers (SPs) utilizing a VPN. We understand that in certain regions, SPs may need to navigate legal scrutiny, and the use of VPNs can be deemed reasonable. However, it is imperative for clients to publicly disclose such information. To track and report on VPN usage, we will implement monitoring mechanisms. Clients are required to transparently communicate their use of VPNs during deal-making processes with SPs. This information will be recorded and reported in our system to ensure accountability and compliance with disclosure standards.
### DataCap Allocation Strategy
**29. Will you use standardized DataCap allocations to clients?:**
No, client specific

**30. Allocation Tranche Schedule to clients::**
• First: 20% of the allocated DataCap
• Second: 30% of the allocated DataCap
• Third: 30% of the allocated DataCap
• Fourth: 20% of the allocated DataCap
• Max per client overall: The maximum overall DataCap allocation per client will be determined based on a comprehensive evaluation of their performance, adherence to guidelines, and overall contribution to the network.

**31. Will you use programmatic or software based allocations?:**
No, manually calculated & determined

**32. What tooling will you use to construct messages and send allocations to clients?:**
https://filplus.fil.org/#/

**33. Describe the process for granting additional DataCap to previously verified clients.:**
The process for granting additional DataCap to previously verified clients involves the following steps: 1. Assessment Criteria:  First allocation: lesser of 5% of total DataCap requested or 50% of weekly allocation rate Second allocation: lesser of 10% of total DataCap requested or 100% of weekly allocation rate Third allocation: lesser of 20% of total DataCap request or 200% of weekly allocation rate Fourth allocation: lesser of 40% of total DataCap requested or 400% of weekly allocation rate Fifth allocation onwards: lesser of 60% of total DataCap request or 600% of weekly allocation rate Application Submission: Clients submit an application for additional DataCap, detailing the reasons and providing any necessary supporting documentation. Review and Evaluation: The allocation request undergoes a thorough review and evaluation process to ensure compliance with program principles and guidelines. Tooling Usage: We may utilize open-source tooling, such as the Subsequent Allocation (SA) bot or other automated tools, to facilitate the process efficiently. Decision and Notification: Based on the review, a decision is made regarding the additional DataCap allocation. Clients are promptly notified of the outcome.

**34. Describe in as much detail as possible the tools used for: • client discoverability & applications • due diligence & investigation • bookkeeping • on-chain message construction • client deal-making behavior • tracking overall allocator health • disput:**
- client discoverability & applications ： github，slack，X, wechat, FILFI DAO
- due diligence & investigation : github, mail, google forms
- bookkeeping: Microsoft Office, google forms, Youdao
- on-chain message construction : filplus.fil.org , lotus wallet CLI
- client deal-making behavior : datacapstats.io ,filfox explorer  , https://filecoin.tools/
- tracking overall allocator health : CID checker bot , retrievalbot-dashboard
- dispute discussion & resolution : github , slack, wechat ,Telegram
- community updates & comms : github, slack, Telegram
### Tools and Bookkeeping
**35. Will you use open-source tooling from the Fil+ team?:**
Yes, we plan to leverage open-source tooling provided by the Fil+ team. The specific tools we intend to utilize include the Subsequent Allocation (SA) bot and any other relevant tools that facilitate the allocation process efficiently. The process involves interacting with these tools through their respective GitHub repositories. Clients can initiate allocation requests, provide necessary documentation, and track the status of their requests through these tools. The use of open-source tools enhances transparency and efficiency in managing DataCap allocations.

**36. Where will you keep your records for bookkeeping? How will you maintain transparency in your allocation decisions?:**
In our GitHub repository, the information disclosed publicly by the client will include details such as the client's name, applicant information summary, project overview, Datacap application size, weekly allocation quota, and other non-sensitive information. It will also include continuous disclosure of SP-related information, such as minerID, IP address, location, and SP name.
For more confidential aspects of due diligence, such as investigating client subjects or reviewing supporting documents and business licenses of SP subjects, we will use secure email communication. The internal audit process will involve information that remains private and will not be disclosed publicly.
### Risk Mitigation, Auditing, Compliance
**37. Describe your proposed compliance check mechanisms for your own clients.:**
We propose a comprehensive compliance check mechanism to ensure the integrity and responsible distribution of DataCap to our clients. This mechanism will involve regular check-ins, ongoing tracking of DataCap distribution metrics, understanding client demographics, evaluating time metrics, assessing trust, and leveraging tools such as CID Checker and Retrievability Bot.
Regular Check-ins:
-Scheduled and unscheduled check-ins with clients to assess ongoing project status and compliance.
-Periodic reviews to ensure that clients are aligning with the principles of the program.
DataCap Distribution Metrics:
-Continuous monitoring of DataCap distribution to track adherence to predetermined limits and guidelines.
-Utilization of automated tools, such as CID Checker, to verify and audit DataCap allocations.
Understanding Client Demographics:
-Gathering and analyzing demographic data to ensure a diverse and inclusive client base.
-Evaluating whether DataCap is allocated across various projects and sectors.
Time Metrics:
-Evaluating the speed at which clients utilize allocated DataCap.
-Setting benchmarks for reasonable DataCap utilization over specific time frames.
Trust Evaluations:
-Implementing a phased approach where trust and DataCap allocation increase over time based on good-faith execution of responsibilities.
-Utilizing client transparency and responsiveness as key indicators of trustworthiness.
Tools:
-Leveraging CID Checker and Retrievability Bot for automated checks on deal-making and data retrievability.
-Implementing these tools as part of a broader strategy to ensure compliance and responsible usage.
Tolerance for New Clients:
-Implementing a cautious approach for new clients with an initial limited DataCap allocation.
-Gradually increasing DataCap based on successful compliance, transparency, and responsible usage.
This compliance check mechanism aims to strike a balance between facilitating the growth of the ecosystem and ensuring responsible and transparent use of DataCap resources.

**38. Describe your process for handling disputes. Highlight response times, transparency, and accountability mechanisms.:**
In the event of a dispute related to DataCap allocation, we have established a structured process designed to address contentions promptly, transparently, and accountably. The key elements of our dispute resolution process are as follows:
Initiation:
-Disputes can be initiated by any involved party, including clients or storage providers, by submitting a formal complaint detailing the nature of the dispute.
-Disputes can be raised through a designated channel, such as a dedicated email address or an online form.
Investigation:
-Upon receipt of a dispute, we commit to conducting a thorough and impartial investigation to gather all relevant information.
-This involves reviewing transaction records, communication logs, and any other pertinent documentation.
Response Times:
-We prioritize timely resolution and commit to acknowledging the dispute within a specified timeframe (e.g., 72 hours).
-A detailed investigation will be completed within an agreed-upon period (e.g., 14 days) to provide a comprehensive response.
Transparency:
-Throughout the dispute resolution process, we maintain transparent communication with the involved parties.
-Regular updates will be provided on the status of the investigation and the expected timeline for resolution.
Accountability Mechanisms:
-We are committed to taking responsibility for fair and just resolution based on the merits of the dispute.
-The resolution may involve corrective actions, adjustments in DataCap allocation, or other appropriate measures.
Appeals Process:
-If any party is dissatisfied with the resolution, we offer an appeals process allowing them to present additional evidence or arguments.
-The appeals process will be conducted by an impartial third party if necessary.

**39. Detail how you will announce updates to tooling, pathway guidelines, parameters, and process alterations.:**
To ensure transparency and keep stakeholders informed, we have established a structured approach to announce updates to tooling, pathway guidelines, parameters, and process alterations. The key elements of our announcement strategy are as follows: 1. Communication Channels: Updates will be communicated through multiple channels, including official announcements on our designated platform (e.g., GitHub repository), direct communication to clients via email, and community forums. 2. Frequency and Timing: Updates will occur as necessary for security, compliance needs, or significant improvements to the program.We recognize the importance of avoiding excessive frequency to prevent thrash or scope creep, ensuring that changes are well-considered and necessary. 3. Documentation: Detailed documentation outlining the changes, rationale, and potential impacts will accompany each update.Clients and stakeholders will have access to comprehensive guides or FAQs to facilitate a smooth transition and understanding of the updates. 4. Notification Period: Depending on the nature of the update, a notification period will be provided to clients before the changes take effect.Significant alterations, especially those impacting client interactions, will have a longer notification period to allow for adaptation. 5. Feedback Mechanism: We encourage feedback from clients and the community regarding updates. A designated channel, such as an email address or forum thread, will be available for stakeholders to express concerns, seek clarifications, or provide suggestions.

**40. How long will you allow the community to provide feedback before implementing changes?:**
Our approach to community feedback implementation is adaptable, considering factors like change urgency, community complexity, and stakeholder impact. We commit to active engagement through diverse channels, employing a dedicated moderation team to ensure constructive discussions. The feedback duration will vary, with urgent changes having shorter windows, while major changes allow for extended community input. Transparent decision-making processes will guide implementations, with outcomes communicated comprehensively. This strategy balances the need for timely action, community involvement, and clear communication, fostering an open and collaborative environment.

**41. Regarding security, how will you structure and secure the on-chain notary address? If you will utilize a multisig, how will it be structured? Who will have administrative & signatory rights?:**
We currently use an f1 address created with a Ledger hardware wallet.
 
In the future, we may transition to a multisig address. Our existing non-open-source multisig wallet project, sxxfWallet, supports multisignature commands, and we plan to adapt it for this purpose.

**42. Will you deploy smart contracts for program or policy procedures? If so, how will you track and fund them?:**
Not currently
### Monetization
**43. Outline your monetization models for the services you provide as a notary allocator pathway.:**
We will not adopt a monetization model until the entire process has stabilized.
All clients that meet the requirements can participate for free, which is also beneficial to the construction of the ecosystem.

**44. Describe your organization's structure, such as the legal entity and other business & market ventures.:**
We are doing counseling before listing in China, and we are a service provider with professional investment institutions participating in the construction. Cooperate with the government, and receive leaders to make announcements for many times. https://twitter.com/sxxfuture/status/1591012090776813569 https://twitter.com/sxxfuture/status/1591011276016476160 https://twitter.com/sxxfuture/status/1591010988199120896 https://twitter.com/sxxfuture/status/1591010604042842115 https://twitter.com/sxxfuture/status/1591010063078273024 https://twitter.com/sxxfuture/status/1591009464953733121 https://twitter.com/sxxfuture/status/1591008850983137280 https://twitter.com/sxxfuture/status/1591008350376198145  In terms of green energy, SXX's Three Gorges Dongyue Temple data center is located in the Three Gorges dam area, where the world's largest hydropower station is located. Our data center plans to build a total of 10,000 cabinets, with a current capacity of 15PiB. We currently have 42 server racks with a storage capacity of 8.2P. In March, 2022, the Three Gorges Dongyue Temple data center was listed as a new data center in the State Council, People's Republic of China (PRC), which is also a green and low-carbon data center. It can cooperate with the transmission of each node, collect node data sharing nodes, reduce data delay and transmission cost, and make full use of clean energy. Our team has been in close contact with Marc and Brain of the green team, and is applying for green's sustainability statement. It has been reviewed twice by video conference and submitted relevant materials. At present, it is in the final stage of review, and the audit is expected to be completed by the end of November. https://drive.google.com/drive/folders/1bABToZeTG3BrosK2rR2agSDicTb2lnCC? usp=sharing  SXX Future team is the most active service provider in the Asia-Pacific region. At present, it has more than 30 members and more than 200 reserve members. It has invested nearly 100 million yuan and deployed more than 700 storage and computing servers. We are committed to the development of web3 industry. At present, filecoin&ipfs is the representative infrastructure of web3, and we believe in and hope to join the assistance of official team work. At present, we have helped Hekou to provide some contribution codes, and also helped in the construction of filecoin index, and established a friendly cooperative relationship. At the same time, we are actively establishing cooperation with fil+/green/ Search/Virtual Machine /orbit and other projects. https://docs.google.com/presentation/d/1vKO6N6jeGhX42qUW8-SGAq4Xl7yhVPEZLKC8_YNMKrA/edit#slide=id.g1f87997393_0_782  In the whole industrial chain, it is a whole industrial chain process from the production of distributed storage server equipment to the infrastructure of data center to the operation and maintenance of distributed storage technology and the ecological development of storage products in the later stage. At present, we have more than 60 operators in Yichang, China, Beijing and Shenzhen. Shenzhen is mainly responsible for the construction of IPFS and FILE underlying protocols and node construction. Beijing is mainly responsible for the application ecological products developed based on IPFS,FILE and LIBP2P. Yichang is our important infrastructure base, which includes IPFS cluster, server production center, equipment testing center and other important deployments. At present, the production scale of servers can reach 500+ units per day. In the cooperative organization, we have obtained the core partner of Seagate Headquarters in Singapore. In addition, we have very close cooperation with INTER amd and Samsung. In the field of data storage, we also joined most computer and data storage associations in China to discuss the construction of feasible distributed storage. SXX has established a joint laboratory with Seagate Technology, the world's leading technology, and is a core partner. Jointly develop web3 applications with xiaoyi robot, the top AI algorithm team in China. https://docs.google.com/document/d/1--xCRhTBU-ugBHejQrgwSoM40aQolPX3J3MOtDh1oC4/edit  Obtained 7 national software patents in the field of blockchain distributed storage, including value-added telecom service business license and intellectual property management system certification. https://docs.google.com/document/d/16SSh-RX_mVlWbHaZPwHtQ7lbHNrzW1vnYnMnhCTQivs/edit  About filecoin products developed by sxx team: Up to today, we have developed a cold data storage product-data cold storage by using IPFS&FILECOIN technology. It is an application platform that can provide customers with massive data storage. At the same time, we also developed a C-end user product-Web 3 cloud disk. This is a data storage product that can be used by all Internet of Things users, and supports cold and hot storage. We use IPFS network protocol for transmission protocol and FILECOIN storage protocol for data uplink. In November, we will push this product to the application market of Android and Apple. It is a standard product for benchmarking Baidu network disk, but it is based on distributed storage. In the third quarter of 2022 to the fourth quarter of 2023, our product development routes include Three Gorges Nebula, NFT storage, Nebula CDN, digital safe, IPFS pin. Cross-chain technology and other product strategies. In the construction of storage providers, we have been pursuing real and effective data. Data cold storage download link: https://clove.cold-storage.sxxfuture.com/ Web3 Cloud Disk Download Link: https://app.cloud-drive.sxxfuture.com/  We have carried out joint laboratories with Three Gorges University and Wuhan University in China. In addition, we are also actively developing some high-security data needed by the government and introducing them. Large-scale real and effective data will be introduced through our own developed products. Because we think that there is a need to store the data, there is a need to take it out. Therefore, we prefer the customers who need distributed storage. We will also devote ourselves to distributed storage and step into the field of WEB3. Be able to occupy a certain market share of infrastructure in the era of wbe3. https://docs.google.com/document/d/1FDbR0ikfZcc06u29gdoXXlyiMpbe1aM30wGu3v14PFM/edit  As the newest ambassador to the orbit community, we have carried out very professional and close gathering activities in the promotion of web3 distributed storage. We hope that more people can learn about distributed storage and get in touch with web3 through open source technologies such as IPFS, FILECOIN and libp2p. We have held 10 orbit parties, and the activities of these parties have been shared to platforms such as Twitter. One or three large-scale summits will be held regularly every month to share the IPFS&Filecoin project. In order to let customers see the real distributed storage clusters and equipment, we set up a monthly open day, inviting everyone to visit the IDC computer room and production testing center in the Three Gorges, where we also show various application products and benchmark centralized storage tools. Everyone has a high love and interest in distributed storage. As the promoter of IPFS/Filecoin, Sanxiaxing actively carries out knowledge popularization, organizes technical evaluation, outputs various analysis reports to the industry and holds industry activities. In order to enhance the understanding of IPFS&filecoin among high-quality customers, we will have an online round-table meeting with the founder of the company at 20 o'clock every Thursday. Here, we are working hard and actively. (See Organizational Reparation & Individual Reparation for details.)  In order to let more users know about the government, we have set up a special promotion working group, all of whom are very professional and excellent bloggers of the Ministry of Science and Technology. Through this self-media approach, it brings the latest official information and product principles to Internet users and fans. At present, it has been actively preached and promoted in today's headlines in China, bilibili, Baidu, Zhihu, and YOUTUBE, TIKTOK,INS, Twitter and other foreign countries, hoping to help the distributed storage and web3 industries. Through the online distributed storage course, we also established a WeChat community to answer some SPs questions in the community and WeChat group with our professional knowledge. At present, there are 50,000+fans who regularly study and pay attention to the IPFS&FILECOIN ecology. (See Organizational Reparation & Individual Reparation for details.)  We are committed to building a validated data store for Filecoin. As quasi-notaries, we have been promoting the Filecoin plus project to the outside world, and contacting companies applying for data verification to understand their storage intentions. We have established data storage cooperation with many domestic enterprises, and the stored data has reached 45PiB, which is being uploaded. With the large-scale promotion of SXX in the coming year, we expect that more than 1PiB of valid data will be stored through SXX. In addition, we also released a brief introduction about sxx on Slack fil channel, so that more industries can participate in our service.

**45. Where will accounting for fees be maintained?:**
China
### Past Experience, Affiliations, Reputation
**46. If you've received DataCap allocation privileges before, please link to prior notary applications.:**
https://github.com/filecoin-project/notary-governance/issues/680

**47. How are you connected to the Filecoin ecosystem? Describe your (or your organization's) Filecoin relationships, investments, or ownership.:**
Since 2014, our team and founders have focused on blockchain and encryption. The core members of the team have more than ten years of experience in blockchain industry. Paying attention to WEB3, IPFS, distributed storage, Fil and other fields is early and persistent. Ipfs technology has been started since 2016. In 2018, Filecoin 2020-9-27 (before the main online line) has built the first node f022820. After that, the following nodes have been added continuously, and some nodes are listed for reference. Node number: f022820 f099239 f0815838 f081977 f081978 f081979 f081986 f081995 f0408629 f0753569 f01178141 f01741924 f01771695 f01753006 f01782338 f01801587 f01822335 f01919535 f01964215 f02188888 f02189999 f02229951 f02233355 f02234567 f02191111 f02222321  In July 2021, we formally established a distributed storage brand SXX based on ipfs and filecoin open source technology in Yichang, Beijing and Shenzhen. We focus on the ecological development of IPFS&Filecoin technology and the construction of storage providers. We plan to enter the door of WEB3 through distributed storage technology, and we will focus on developing a series of ecological applications to serve a large number of Internet users. At present, it has more than 30 members, has invested about 100 million yuan, and has completed the deployment of more than 700 storage and computing servers. The contracts to be performed exceed 100 million yuan, and it has a super-large market in China. SXX aims to build a safer, more efficient and freer Web3.0.  The promotion working group promoted IPFS&Filecoin on social media, which attracted more than 50,000 people's attention and influenced 2 million encrypted digital currency investors. (See Organizational Reparation & Individual Reparation for details.) We also built FilFi platform-Filcoin's 100% intelligent contract management storage node co-construction solution. FilFi aims to realize the free integration of resources of storage providers, miners and currency holders with decentralized smart contracts; Realize the rapid flow of filcoin pledged currency by innovative computing power transaction; Efficient agreement to promote mortgage lending of cross-chain assets. Platform link: https://filfi.io/ At the same time, we are also concerned about some SPs problems in China. Therefore, the SXX team set up a set of promotion system to help the official preach and promote ipfs&filecoin on social media. For example: translate official documents or video conferences into Chinese and publish them; Push a lot of latest information about IPFS/Filecoin on major platforms (WeChat WeChat official account, Headline, Twitter, etc.); Create a WeChat group; Establish a training camp; Hold offline meetings and webcasts, round tables, etc. We have always been committed to contributing to the filecoin ecosystem in any way we can. (See Organizational Reparation & Individual Reparation for details.)  Technically, we have carried out community technology development, community project construction (Saturn node L1, index node), ecological construction (data cold storage and WEB3 cloud disk, defi project based on FVM, etc.) and edge data center construction. We independently developed an efficient data formatting tool and a decentralized multi-signature wallet sxxfMsig-wallet. In terms of node operation and maintenance, we independently developed a graphics card cluster system, which greatly improved the utilization rate of graphics cards. Data cold storage download link: https://clove.cold-storage.sxxfuture.com/ Web3 Cloud Disk Download Link: https://app.cloud-drive.sxxfuture.com/ Construction of Saturn L1 node and official feedback: https://app.slack.com/client/tehtvs1l6/c03dhbl02e/thread/c03dhbl02e-16666.100088080806  In terms of green nodes, we have built zero-carbon green energy nodes on a large scale. The Three Gorges Dam Power Plant is the largest hydropower project in the world today. The data center of the Three Gorges Dongyue Temple in SXX is a supporting project for the construction of the Three Gorges Dam Hydropower Station, which is less than three kilometers away from the Three Gorges Dam Hydropower Station. The water source is natural Yangtze River water and is supplied by 100% green hydropower energy. At present, we have more than 2000 cabinets, and large-scale construction of zero-carbon green energy nodes. https://en.wikipedia.org/wiki/Three_Gorges_Dam Our team has been in close contact with Marc and Brain of green team, and has completed the sustainability statement audit in the first quarter of 2023. https://drive.google.com/drive/folders/1bABToZeTG3BrosK2rR2agSDicTb2lnCC? usp=sharing  We hold three orbit parties in different large and medium-sized cities in China every month. So far, we have held more than 20 activities. The following are some links. https://twitter.com/sxxfuture/status/1582919205976145920? s=20&t=AroDceiLw8FarxfBXpZptA https://twitter.com/sxxfuture/status/1584359720814804993? s=20&t=AroDceiLw8FarxfBXpZptA https://twitter.com/sxxfuture/status/1575780709792612355? s=20&t=AroDceiLw8FarxfBXpZptA

**48. How are you estimating your client demand and pathway usage? Do you have existing clients and an onboarding funnel?:**
We already have a relatively large Filecoin community - FILFI. We will regularly conduct some questionnaire surveys and random interviews in the community to estimate customer needs and path usage. We will make our onboarding channels public in the future, and use relevant KYC tools and standardized manual review processes to achieve a reliable onboarding method.

**Comment by kevzak** [comment]
## Datacap Request for Allocator
#### Address
> f2pwkfr26r7h6db5laiwapjrs6f32sxkq2t65b75i
#### Datacap Allocated
> 5PiB

**Comment by galen-mcandrew** [comment]
## Datacap Request for Allocator
#### Address
> f2pwkfr26r7h6db5laiwapjrs6f32sxkq2t65b75i
#### Datacap Allocated
> 10PiB

**Comment by galen-mcandrew** [comment]
[bafy2bzaceanzw4xhhxj52huyefkrau5t4sb7z5whnamrduzkq7wb7rbtbdyzu](https://filfox.info/en/message/bafy2bzaceanzw4xhhxj52huyefkrau5t4sb7z5whnamrduzkq7wb7rbtbdyzu?t=4)

**Comment by galen-mcandrew** [comment]
## Datacap Request for Allocator
#### Address
> f2pwkfr26r7h6db5laiwapjrs6f32sxkq2t65b75i
#### Datacap Allocated
> 5PiB

**Comment by galen-mcandrew** [comment]
Approval: bafy2bzacedftubcnxt6lepwp2mc7zgf2a3waxbjkntueup5aagb64k5krvdt2
