### ISSUE TITLE
v5 Notary Allocator Application: Venus Fil+ Datacap Allocator (VFDA)

### ISSUE THREAD

**Issue by Joss-Hua** [filecoin-project/notary-governance#1035]
# v5 Notary Allocator Application

To apply to be an allocator, organizations will submit one application for each proposed pathway to DataCap. If you will be designing multiple specific pathways, you will need to submit multiple applications. 

Please complete the following steps:
# 1. Fill out the information below and create a new GitHub Issue

1. Notary Allocator Pathway Name (This can be your name, or the name of your pathway/program. For example "E-Fil+"): Venus Fil+ Datacap Allocator (VFDA)
2. Organization Name: Venus Team
3. On-chain address for Allocator (Provide a NEW unique address. During ratification, you will need to initialize this address on-chain): f1wdnx2g2rffbg2pmu2ilguedw2oxg25ettfjl5fy
4. Country of Operation (Where your organization is legally based): PRC
5. Region of Operation (What region will you serve?): Asia
6. Type of Allocator, diligence process: (Automated/programmatic, Market-based, or Manual (human-in-the-loop at some phase): Market-based 
7. DataCap requested for allocator for 12 months of activity (This should be an estimate of overall expected activity. Estimate the total amount of DataCap you will be distributing to clients in 12 months, in TiB or PiB): 200 PiB; 

# 2. Access allocator application (download to save answers)
Click link below to access a Google doc version of the allocator application that can be used to save your answers if you are not prepared to fully submit the application in Step 3. https://docs.google.com/document/d/1-Ze8bo7ZlIJe8qX0YSFNPTka4CMprqoNB1D6V7WJJjo/copy

# 3. Submit allocation application 
Clink link below to access full allocator questionnaire and officially submit your answers:
https://airtable.com/appvyE0VHcgpAkt4Z/shrQxaAIsD693e1ns

Note: Sections of your responses WILL BE posted back into the GitHub issue tracking your application. 
The final section (Additional Disclosures) will NOT be posted to GitHub, and will be maintained by the Filecoin Foundation. 
Application information for notaries not accepted and ratified in this round will be deleted.

**Comment by Joss-Hua** [comment]
Airtable submitted

**Comment by Joss-Hua** [comment]
hi @Kevin-FF-USA , please check the slack dm from me, Venus allocator application issue submission failed. (Automatically hidden ##1036、#1037)

**Comment by Joss-Hua** [comment]
are u here sir? @Kevin-FF-USA

**Comment by Joss-Hua** [comment]
> hi @Kevin-FF-USA , please check the slack dm from me, Venus allocator application issue submission failed. (Automatically hidden ##1036、#1037)

If #1036 is normal display, please refer to #1036.

**Comment by Kevin-FF-USA** [comment]
Hi @Joss-Hua  - yes, confirming I can see the Airtable form submitted for 1036.  Will review and post the responses in this issue shorty

**Comment by Filplus-govteam** [comment]
### Basic Information
**1. Notary Allocator Pathway Name:**
Venus Fil+ Datacap Allocator (VFDA)

**2. Organization:**
Venus Team

**3. On Chain Address for Allocator:**
f1wdnx2g2rffbg2pmu2ilguedw2oxg25ettfjl5fy

**4. Country of Operation:**
PRC

**5. Region(s) of operation:**
Asia minus GCR, Greater China, Japan, Other

**6. Type of Allocator:**
Market-based

**7. DataCap requested for allocator for 12 months of activity:**
200 PiB; 1) In 2023, we distributed over 20 PiB of data (DC) through Venus Hub, which was only as a client; 2) Currently, Venus has over 15% of users (QAP) in the network; 3) In 2023, over 1EiB of data (DC) was distributed across the entire network; 4) Expected to distribute over 2EiB of data (DC) across the entire network by 2024 So we expect that when we become an allocator, we can distribute 10% of the DC by 2024, approximately 200 PiB;

**8. Is your allocator providing a unique, new, or diverse pathway to DataCap? How does this allocator differentiate itself from other applicants, new or existing?:**
Process
1)Client submits application
2)KYC/KYB validates
3)Allocator Check information
4)Process continues if it is compliant
5)Allocator distributes manually for round 1
6)SP sealing
7)Allocation Check storage compliance
8)Process continues if it is compliant
9)Allocation for round 2
10)SP sealing
11)Allocation Check storage compliance
12)Process continues if it is not compliant
13)Closed

Help to resolve regional disputs
- Only the clients and SPs in Asia are supported ;
- Notary is not involved;
Helps to improve efficiency
- Cold storage for data is  supported. Data volume is  unlimited. And the data is retrieved at least once a year;
- KYB requires a valid email address of company or a valid copy of personal ID;
Help to attract new users
- Limited DataCap can be opened to public for the trial;
- DataCap can be used in some incentive programs for online or offline events.

**9. As a member in the Filecoin Community, I acknowledge that I must adhere to the Community Code of Conduct, as well other End User License Agreements for accessing various tools and services, such as GitHub and Slack.:**
Acknowledge
### Client Diligence
**10. Who are your target clients?:**
Individuals learning about Filecoin, Small-scale developers or data owners, Other (specified above), Enterprise Data Clients

**11. Describe in as much detail as possible how you will perform due diligence on clients.  If you are proposing an automated pathway, what diligence mechanism will you use to determine client eligibility?:**
The following channels can help us to reach and understand Client more effectively within the assoigned area:
1)KYC/KYB
2)Self-introduction of client
3)Confirmation of the actual business
4)Estimation of DC requirement.
In addition to the regular information filled by clients,  we can further collect the information in face-to-face interview or through other channels such as third-party platforms or search engines etc.

**12. Please specify how many questions you’ll ask, and provide a brief overview of the questions.:**
A. Applicant identification details.
1)Name, e-mail address, and Wechat account
2)Github, Slack, Discord, Telegram account
3)Details of residence
B. Questions on data
4)Request form number #xxxxx
5)Frequency of data retrieval
6)The data ownership
7)Co-owner of the data and/or LDN address
C. SP related questions (no more than 5 copies should be stored using the same SP ID; no restrictions on the number of regions, service providers, or Datacap allocation ratio)
8)Request of referring more SPs
9) Confirmation letter with the applicant’s email address.

**13. Will you use a 3rd-party Know your client (KYC) service?:**
Agrees to use a system, but does not yet know which provider or how integration will be handled for their pathway and tooling；

**14. Can any client apply to your pathway, or will you be closed to only your own internal clients? (eg: bizdev or self-referral):**
Any client can apply the pathway

**15. How do you plan to track the rate at which DataCap is being distributed to your clients?:**
Tool Glif and/or filplus.info is used for the weekly review of timely LDN distribution. The summary report for analysis and tracking is generated based on the information from the tool. This process is appllied to most members of the community to synchronize the data.
### Data Diligence
**16. As an operating entity in the Filecoin Community, you are required to follow all local & regional regulations relating to any data, digital and otherwise. This may include PII and data deletion requirements, as well as the storing, transmit:**
Acknowledge

**17. What type(s) of data would be applicable for your pathway?:**
Public Open Dataset (Research/Non-Profit), Public Open Commercial/Enterprise, Private Commercial/Enterprise, Private Non-Profit/Social Impact, Other (specified elsewhere)

**18. How will you verify a client’s data ownership? Will you use 3rd-party KYB (know your business) service to verify enterprise clients?:**
Proof of ownership of the data is provided by the applicant and verified on the basis of the previously established procedure. There are no restrictions on the method of verification.

**19.  How will you ensure the data meets local & regional legal requirements?:**
One of the reasons why this pathway restricts the service area is precisely to avoid the unknown legal risks and policy complexity of data going abroad.  In the area where we apply for the Pathway, we are familiar with local legal requirements, including the Voviol Code, the Constitution and many guilelines issues by government. This can help us avoid unknown legal risks and complicated policies.  It is client’s liablity if some illegal data is stored. And the data will be deleted immediately if it does not comply with the regulations.

**20. What types of data preparation will you support or require?:**
We have rich experience in Deal. And we can help applicants on the entir data preparation process; In addition, we recommend applicants to use tool Droplet to process the data as we can directly contact the developers to provide further suppport if required.

**21. What tools or methodology will you use to sample and verify the data aligns with your pathway?:**
Based on our experience, applicants need us to provide early assistance, and we can avoid wrongdoing during this step; We can also retrieve client data through Venus(droplet) and check it; But this pathway does not want to impose too many specific restrictions on data types; Sector padding is indeed an objective phenomenon that existed before, and we believe that quick spot checks are the most cost-effective way to minimize such cheating behavior. The cost invested in solving such phenomena 100% is not necessary;
### Data Distribution
**22. How many replicas will you require to meet programmatic requirements for distribution?:**
2+

**23. What geographic or regional distribution will you require?:**
Two geopolitical regions, multiple physical locations, VPNs supported, 2+ SP owner operators；

**24. How many Storage Provider owner/operators will you require to meet programmatic requirements for distribution?:**
4+

**25. Do you require equal percentage distribution for your clients to their chosen SPs? Will you require preliminary SP distribution plans from the client before allocating any DataCap?:**
Requires some initial client SP distribution plan, very flexible and non-standardized, allows client to update between allocations Provide a plan to manage client and DC balances; Yes, provide templates to collect information, but not publicly available to the community at the moment;

**26. What tooling will you use to verify client deal-making distribution?:**
 CID Checker Bot + filplus.info

**27. How will clients meet SP distribution requirements?:**
Some support provided to clients to assist in SP discovery & deal-making； When we have a clear understanding of who the client is, who the SP is, data requirements, and storage capabilities, we can try to avoid joint wrongdoing by the applicant and SP.

**28. As an allocator, do you support clients that engage in deal-making with SPs utilizing a VPN?:**
Although we do not support it, we accept that some of its nodes use VPN. However, excessive use will affect our evaluation of SP and even blacklist it. Mainly because many service providers use VPNs to solve problems such as networks and firewalls, it cannot be completely denied.
### DataCap Allocation Strategy
**29. Will you use standardized DataCap allocations to clients?:**
Yes, standardized

**30. Allocation Tranche Schedule to clients::**
• First: 1/4
• Second: 1/4
• Third: 1/4
• Fourth: 1/4
• Max per client overall: 5 PiB

**31. Will you use programmatic or software based allocations?:**
No, manually calculated & determined

**32. What tooling will you use to construct messages and send allocations to clients?:**
filplus.fil.org or Venus

**33. Describe the process for granting additional DataCap to previously verified clients.:**
When DataCap is less than 20%. Will not use current tools. Based on previous experience, tools can sometimes lead to errors and reduce efficiency, making manual labor more efficient and accurate in limited needs.

**34. Describe in as much detail as possible the tools used for: • client discoverability & applications • due diligence & investigation • bookkeeping • on-chain message construction • client deal-making behavior • tracking overall allocator health • disput:**
• client discoverability & applications：
bigdataexchange.io
Community
Offline
filplus.storage
Github
• due diligence & investigation
qcc.com
Official Website
Social Medium
Offline
• bookkeeping
TBD
• on-chain message construction
Venus CLI
• client deal-making behavior
Venus CLI
filecoin.tools
• tracking overall allocator health
 filplus.info
datacapstats.io
• dispute discussion & resolution
Github proposal
Slack Channel
• community updates & comms *
Address all the tools & software platforms in your process.
Slack
Wechat
Telegram
Github
### Tools and Bookkeeping
**35. Will you use open-source tooling from the Fil+ team?:**
Retrieval Checker Bot CIDChecker Bot datacapstats.io filplus.storage filecoin.tools , etc Majority of tools are open source with regular contributions to the community; well-documented；

**36. Where will you keep your records for bookkeeping? How will you maintain transparency in your allocation decisions?:**
Cloud Notes；
Digital record-keeping with good standards, metrics, visuals, etc that is open sourced and documented
### Risk Mitigation, Auditing, Compliance
**37. Describe your proposed compliance check mechanisms for your own clients.:**

Client submits application ->KYC/KYB ->Allocation Check information ->Passed ->Manual allocation for round 1->SP sealing ->Allocation Check storage compliance ->OK ->Allocation for round 2->SP sealing ->Allocation Check storage compliance ->Not OK ->Close

Use tools such as Glif and filplus.info to check weekly whether LDN is distributed as expected, and regularly summarize and analyze to form reports;
When the client's data distribution encounters 2 exceptions, it will be immediately shut down;

**38. Describe your process for handling disputes. Highlight response times, transparency, and accountability mechanisms.:**
SP storage ->Distribution may be abnormal/cheating ->Public channels raise doubts and gain community recognition ->Specific doubts require clients to collect and publicly disclose information within 7 days ->Governance team&Allocator&community discussion ->Continue/Closed

**39. Detail how you will announce updates to tooling, pathway guidelines, parameters, and process alterations.:**
We have social medium and community that can effectively communicate to any community member who guides us. We can consider further organizing and publishing information such as tools, guidelines, parameters, etc;

**40. How long will you allow the community to provide feedback before implementing changes?:**
Based on our experience, we can gradually receive feedback within 2-6 weeks;

**41. Regarding security, how will you structure and secure the on-chain notary address? If you will utilize a multisig, how will it be structured? Who will have administrative & signatory rights?:**
I can build and protect addresses through Ledger wallet, and only I can manage and sign them. If the manager is changed in the future, this information will also be synchronized with the governance team.

**42. Will you deploy smart contracts for program or policy procedures? If so, how will you track and fund them?:**
Not for now, but it may be considered in the future.
### Monetization
**43. Outline your monetization models for the services you provide as a notary allocator pathway.:**
As a long-term participant in the Filecoin ecosystem and FIL+project, we currently plan to provide free time to review DC applications; In addition, as mentioned earlier, if participants require it, we can provide data processing and other technical support, and the cost of this part needs to be shared by the participants. Specifically, we may charge Max (1FIL/TiB (based on quotes from platforms such as BigDataExchange, we only need less than 50%), or an equal amount of storage fee (FIL paid by the client to SP);

**44. Describe your organization's structure, such as the legal entity and other business & market ventures.:**
The main body is Shanghai Kunyao Network Technology Co., Ltd., with a team consisting of development, marketing, operation and maintenance, testing, personnel, finance, and research personnel. Currently, the team focuses on distributed storage, mainly focusing on Filecoin and ecological construction, and also spending some time on ecological project research and development;

**45. Where will accounting for fees be maintained?:**
We have dedicated financial personnel responsible for expense accounting, who will use specialized financial tools to complete such tasks;
### Past Experience, Affiliations, Reputation
**46. If you've received DataCap allocation privileges before, please link to prior notary applications.:**
Notary v3: https://github.com/filecoin-project/notary-governance/issues/431 Notary v4: https://github.com/filecoin-project/notary-governance/issues/645

**47. How are you connected to the Filecoin ecosystem? Describe your (or your organization's) Filecoin relationships, investments, or ownership.:**
1) The management team for Filecoin Venus implementation, including development and marketing work; 2) Develop on FVM, including GO-FVM-SDK, etc; 3) Provide technical support for nodes, including f0121788, etc; 4) LDN application and distribution, obtaining more SPs, and providing assistance to community users, all from the VenusHub (Venus Deal Accelerator) project; Overall, the Venus team has been deeply involved in ecological construction since the Filecoin Test network;

**48. How are you estimating your client demand and pathway usage? Do you have existing clients and an onboarding funnel?:**
The number of DCs applied by the client mainly consists of the number of datasets and replicas, followed by the storage resources of the SP and the number of pledged tokens. The ratio of DCs to the dataset is required to be between x1 and x100, which needs to be determined according to the client's plan description. However, during the process, expectations can be adjusted in a timely manner based on allocating speed and quality to maximize value and avoid wrongdoing. VDA is an existing client, uses' filplus.storage ',' Graphsync ',' Venus', and other tools.

**Comment by Joss-Hua** [comment]
Looking forward to the next step

**Comment by galen-mcandrew** [comment]
## Datacap Request for Allocator
#### Address
> f2hxivxs3we5afsuyx32lwwn44evopz7yea2fsmhy
#### Datacap Allocated
> 5PiB

**Comment by Joss-Hua** [comment]
On-chain address for Allocator (Provide a NEW unique address. During ratification, you will need to initialize this address on-chain): **f1mkeafrmvg3tiuugtcwpyumjbuyeoey3t2exa4ba**

This address is the one submitted in the form(https://airtable.com/appvyE0VHcgpAkt4Z/shrCXDEP8PMXm08cK).

**Comment by galen-mcandrew** [comment]
## Datacap Request for Allocator
#### Address
> f2hxivxs3we5afsuyx32lwwn44evopz7yea2fsmhy
#### Datacap Allocated
> 5PiB

**Comment by VenusOfficial** [comment]
@galen-mcandrew 
I apologize for the unclear request. As mentioned in the issue [#128](https://github.com/filecoin-project/Allocator-Registry/issues/128), the new address f1wzmrjlhu244jyjlpsjlyhp7en35ue4wpwbfsv3y needs to be added to the signer. Could you please support this change?
<img width="412" alt="image" src="https://github.com/user-attachments/assets/0997a91f-7ac5-4e02-a242-55bbecb160f4">

Thank you.

**Comment by Kevin-FF-USA** [comment]
Hi @VenusOfficial  - thanks for flagging.  I have pushed this change back to the holders of the multisig how can help ensure it doesnt roll back.  Confirming the address should be: 1wzmrjlhu244jyjlpsjlyhp7en35ue4wpwbfsv3y

<img width="711" alt="image" src="https://github.com/user-attachments/assets/f470396a-9b2e-4124-a51e-6af49a8b317b">

**Comment by VenusOfficial** [comment]
Hi @Kevin-FF-USA 

The address f1wzmrjlhu244jyjlpsjlyhp7en35ue4wpwbfsv3y is correct. Thank you.

**Comment by VenusOfficial** [comment]
Hi @Kevin-FF-USA 
As explained in [this issue](https://github.com/fidlabs/allocator-tooling/issues/91), could you please add it to the chain? Thank you!
