### ISSUE TITLE
v5 Notary Allocator Application:NewHuoPool

### ISSUE THREAD

**Issue by NewHuoPool** [filecoin-project/notary-governance#1040]
# v5 Notary Allocator Application

To apply to be an allocator, organizations will submit one application for each proposed pathway to DataCap. If you will be designing multiple specific pathways, you will need to submit multiple applications. 

Please complete the following steps:
# 1. Fill out the information below and create a new GitHub Issue

1. Notary Allocator Pathway Name (This can be your name, or the name of your pathway/program. For example "E-Fil+"):NewHuoPool
3. Organization Name:NewHuoPool
4. On-chain address for Allocator (Provide a NEW unique address. During ratification, you will need to initialize this address on-chain): f1svmuvsv2nnd6ilxihuokkxu6veagv7ppgubyq5y
5. Country of Operation (Where your organization is legally based): US
6. Region of Operation (What region will you serve?): All regions.
7. Type of Allocator, diligence process: (Automated/programmatic, Market-based, or Manual (human-in-the-loop at some phase): Market-based or Manual
9. DataCap requested for allocator for 12 months of activity (This should be an estimate of overall expected activity. Estimate the total amount of DataCap you will be distributing to clients in 12 months, in TiB or PiB):100P

# 2. Access allocator application (download to save answers)
Click link below to access a Google doc version of the allocator application that can be used to save your answers if you are not prepared to fully submit the application in Step 3. https://docs.google.com/document/d/1-Ze8bo7ZlIJe8qX0YSFNPTka4CMprqoNB1D6V7WJJjo/copy

# 3. Submit allocation application 
Clink link below to access full allocator questionnaire and officially submit your answers:
https://airtable.com/appvyE0VHcgpAkt4Z/shrQxaAIsD693e1ns

Note: Sections of your responses WILL BE posted back into the GitHub issue tracking your application. 
The final section (Additional Disclosures) will NOT be posted to GitHub, and will be maintained by the Filecoin Foundation. 
Application information for notaries not accepted and ratified in this round will be deleted.

**Comment by Kevin-FF-USA** [comment]
Hi @NewHuoPool 
Wanted to let you know this application has been received. Also verifying you have submitted the Airtable form with your detailed Allocator plan - the public answers will be posted in a thread below soon. If you have any questions - please let me know.

**Comment by Filplus-govteam** [comment]
### Basic Information
**1. Notary Allocator Pathway Name:**
NewHuoPool

**2. Organization:**
NewHuoPool

**3. On Chain Address for Allocator:**
f1svmuvsv2nnd6ilxihuokkxu6veagv7ppgubyq5y

**4. Country of Operation:**
US

**5. Region(s) of operation:**
Africa , Asia minus GCR, Greater China, Europe, Oceania, Japan, North America, South America, Other

**6. Type of Allocator:**
Manual

**7. DataCap requested for allocator for 12 months of activity:**
100PiB

**8. Is your allocator providing a unique, new, or diverse pathway to DataCap? How does this allocator differentiate itself from other applicants, new or existing?:**
Our allocator will primarily conduct manual audits for two stages: pre-allocation evaluation and follow-up audit during the allocation process.
1.Prior to approving the allocation, an evaluation of the client's principal name, principal jurisdiction, registration number, business location, contact person and title, email address, description of main business, requested DataCap allocation amount, data sample link, proof of ownership or authorization for data sources, confidentiality status of the data (industry secrets, state secrets, or national security), list of storage providers (SPs) for distributing storage deals, storage location and allocation ratio, principles for selecting SPs, and the wallet address for DataCap application will be required. This information will be made public on GitHub and monitored by the governance team and community.
2.During the allocation process, continuous tracking of the client's DataCap distribution records, related SP addresses, storage providers, and other information will be carried out to ensure consistency. This includes maintaining a list of consolidated content identifiers (CIDs) for verified transactions, including transaction CIDs and SP IDs that demonstrate the usage of the allocated DataCap. Clients will be required to provide a description of the stored data and how it is handled. Random spot checks of stored data will be conducted, and appropriate warnings or restrictions on subsequent DataCap allocations will be implemented if the stored data does not comply with Filecoin Plus principles and the initial allocation plan. The credit rating of clients who have successfully allocated DataCap will affect their next DataCap application, with a possibility of increased DataCap for users with a good credit rating.


**9. As a member in the Filecoin Community, I acknowledge that I must adhere to the Community Code of Conduct, as well other End User License Agreements for accessing various tools and services, such as GitHub and Slack.:**
Acknowledge
### Client Diligence
**10. Who are your target clients?:**
Individuals learning about Filecoin, Small-scale developers or data owners, Enterprise Data Clients

**11. Describe in as much detail as possible how you will perform due diligence on clients.  If you are proposing an automated pathway, what diligence mechanism will you use to determine client eligibility?:**
The specific due diligence process: We will evaluate the client's principal name, principal jurisdiction, registration number, business location, contact person and title, email address, description of the main business, requested DataCap allocation, data sample link, data source for storage, proof of ownership or authorization, confidentiality status of the data (industry secrets, state secrets, or national security), list of service providers for distributing storage deals, storage location and allocation ratio, principles for selecting the aforementioned service providers, and the wallet address for DataCap application. This information will be made public on GitHub and monitored by the governance team and community. The client due diligence form can be accessed at the following link: https://github.com/NewHuoPool/DataCap-Application//issues/new?template=Client-Due-Diligence-Form.yml.
Additionally, other sensitive information, including but not limited to registration certificates and proof of main business address, will be sent via email to 
(NewHuoPool@hotmail.com). These confidential materials, such as registration certificates and proof of main business address, will be used solely for New Huo Pool's due diligence on the client, and will be disclosed to the governance team under a confidentiality agreement and supervised by the governance team.
During the allocation process, we will continuously track the client's DataCap distribution records, relevant service provider addresses, storage providers, and other information to ensure consistency. This includes maintaining a consolidated list of verified transactions' content identifiers (""CIDs""), including transaction CIDs and SP IDs that demonstrate the usage of the allocated DataCap. Clients are required to provide a description of the stored data and its handling. Random spot checks will be conducted on the stored data, and appropriate actions will be taken if it does not comply with Filecoin Plus principles and the initial allocation plan. Warnings or restrictions may be imposed on subsequent DataCap allocations in such cases.
The credit rating of clients who have successfully allocated DataCap will impact their next DataCap application, with the possibility of increased DataCap for users with a good credit rating.
Regular and continuous checks will be performed using various statistical tools such as https://filplus.d.interplanetary.one/ and filfox.info to ensure that the allocated DataCap is not being abused or misused.
DataCap will be allocated in stages. If improper use or abuse of allocated DataCap is identified, we will immediately contact the client and may reduce or even cancel the unallocated DataCap, depending on the circumstances.


**12. Please specify how many questions you’ll ask, and provide a brief overview of the questions.:**
Due Diligence Form：https://github.com/NewHuoPool/DataCap-Application//issues/new?template=Client-Due-Diligence-Form.yml


**13. Will you use a 3rd-party Know your client (KYC) service?:**
yes，such as Toggle

**14. Can any client apply to your pathway, or will you be closed to only your own internal clients? (eg: bizdev or self-referral):**
 Any client 

**15. How do you plan to track the rate at which DataCap is being distributed to your clients?:**
Manual tracking
### Data Diligence
**16. As an operating entity in the Filecoin Community, you are required to follow all local & regional regulations relating to any data, digital and otherwise. This may include PII and data deletion requirements, as well as the storing, transmit:**
Acknowledge

**17. What type(s) of data would be applicable for your pathway?:**
Public Open Dataset (Research/Non-Profit), Public Open Commercial/Enterprise, Private Commercial/Enterprise, Private Non-Profit/Social Impact

**18. How will you verify a client’s data ownership? Will you use 3rd-party KYB (know your business) service to verify enterprise clients?:**
Request for Proof Associated with Data from the Client, such as Copyright Information or Documentation Related to Data Ownership.


**19.  How will you ensure the data meets local & regional legal requirements?:**
N/A

**20. What types of data preparation will you support or require?:**
Public Open Dataset (Research/Non-Profit) Public Open Commercial/Enterprise Private Commercial/Enterprise Private Non-Profit/Social Impact

**21. What tools or methodology will you use to sample and verify the data aligns with your pathway?:**
We utilize official tools provided by the platform, such as oneoff, booster-bitswap, and ipfs-car. As a result, we have allocated sufficient bandwidth for node retrieval, data downloading, and data verification.
### Data Distribution
**22. How many replicas will you require to meet programmatic requirements for distribution?:**
5+

**23. What geographic or regional distribution will you require?:**
THREE OR MORE regions including unique geopolitical/language coverage, each replica at different physical location, no or minimal VPN,different SP owner operators

**24. How many Storage Provider owner/operators will you require to meet programmatic requirements for distribution?:**
5+

**25. Do you require equal percentage distribution for your clients to their chosen SPs? Will you require preliminary SP distribution plans from the client before allocating any DataCap?:**
We will execute the allocation plan based on your instructions, which means it will not be distributed evenly.

**26. What tooling will you use to verify client deal-making distribution?:**
We  have been using datacapstats.io, CID checker 

**27. How will clients meet SP distribution requirements?:**
We will provide assistance if the client requires it，and remind and document the specific details of the service providers (SPs) disclosed by the client, as this is crucial during the audit process.

**28. As an allocator, do you support clients that engage in deal-making with SPs utilizing a VPN?:**
We support clients who use VPNs for legitimate purposes.
### DataCap Allocation Strategy
**29. Will you use standardized DataCap allocations to clients?:**
Yes, standardized

**30. Allocation Tranche Schedule to clients::**
The detailed scoring criteria is attached below：https://docs.google.com/spreadsheets/d/18GZoSt1xDTrlu0oO1fJbmyyNalha0rA-JWYgdCFos1M/edit#gid=0

**31. Will you use programmatic or software based allocations?:**
Yes, standardized and software based

**32. What tooling will you use to construct messages and send allocations to clients?:**
Open-sourced tools (UX/UI),e.g.https://filplus.fil.org/#/

**33. Describe the process for granting additional DataCap to previously verified clients.:**
1. Regular and continuous checks are performed using various statistical tools such as https://filplus.d.interplanetary.one/ and filfox.info to ensure that the allocated DataCap has not been abused or misused. 2. DataCap will be allocated in stages. If any improper use or abuse of the allocated DataCap is detected, we will immediately contact the clients and may reduce or even cancel the unallocated DataCap depending on the circumstances.

**34. Describe in as much detail as possible the tools used for: • client discoverability & applications • due diligence & investigation • bookkeeping • on-chain message construction • client deal-making behavior • tracking overall allocator health • disput:**
client discoverability & applications：By utilizing the official GitHub application database, we discover and review client applications.
due diligence & investigation：By organizing, analyzing, and evaluating the information submitted by clients through the issue form, we conduct due diligence and investigations.
https://github.com/NewHuoPool/DataCap-Application//issues/new?template=Client-Due-Diligence-Form.yml
on-chain message construction&community updates & comms：github、slack
client deal-making behavior& tracking overall allocator health：CID checker、AC Bot dispute discussion & resolution：notion、github
### Tools and Bookkeeping
**35. Will you use open-source tooling from the Fil+ team?:**
datacapstats.io 、https://filplus.fil.org/、 GitHub repo, Google spreadsheet

**36. Where will you keep your records for bookkeeping? How will you maintain transparency in your allocation decisions?:**
 In addition to keep records in GitHub, we also plan to cast all distribution records as NFT or use smart contract backup storage when FVM launch in the future. Considering the diligence data that clients don't wanna to go public, we will create a special database to store for data auditing and analysis, and we will be welcome to any auditing.

### Risk Mitigation, Auditing, Compliance
**37. Describe your proposed compliance check mechanisms for your own clients.:**
We track client transactions and distributions through datacapstats.io, guiding clients to transact and distribute according to the guidelines. We supervise using tools such as CID Checker/Retrievability Bot. As the number of allocation batches increases, the rules require clients to meet higher standards.


**38. Describe your process for handling disputes. Highlight response times, transparency, and accountability mechanisms.:**
The following are our practices:
Response Time: We are committed to promptly responding to and resolving disputes. Upon receiving a complaint or dispute, we will initiate an investigation process within three working days and provide an initial response within a reasonable timeframe. We strive to resolve disputes as quickly as possible, minimizing the impact on the entire situation.
Transparency: We prioritize transparency to ensure that all relevant parties are informed about the progress and outcome of the dispute resolution process. We engage in active communication with the parties involved, providing necessary information and explanations. Throughout the dispute resolution process, our goal is to maintain transparency by disclosing relevant data and documents, enabling stakeholders to understand and evaluate the basis of our decisions.


**39. Detail how you will announce updates to tooling, pathway guidelines, parameters, and process alterations.:**
N/A

**40. How long will you allow the community to provide feedback before implementing changes?:**
Before implementing changes, we will allow the community to provide feedback for a duration that depends on the specific circumstances. We aim to give enough time for expressing opinions, providing suggestions, and offering feedback. This may involve open discussions, online surveys, community meetings, or other forms of participatory mechanisms.
1.Communication channels: We will use platforms such as Slack and GitHub to facilitate continuous contact and feedback from the community.
2.Regular updates and reports: We will provide regular updates and reports to the community regarding project progress, decision-making processes, and feedback responses. This will ensure transparency and help the community understand how their feedback influences the decisions.
3.Community engagement: We will actively participate in community activities, including online discussions, Q&A sessions, and other interactive events, to engage directly with community members, address their questions, and explain the decisions.
4.Considering feedback: We will take into account the feedback provided by the community and incorporate it into the decision-making process. After considering different perspectives, interests, and suggestions, we will strive to find the best possible solution.


**41. Regarding security, how will you structure and secure the on-chain notary address? If you will utilize a multisig, how will it be structured? Who will have administrative & signatory rights?:**
We will specifically use the offline hardware wallet Ledger to verify accounts related to DataCap allocation. As we have more clients in the future, we will utilize a multi-signature wallet for added security.


**42. Will you deploy smart contracts for program or policy procedures? If so, how will you track and fund them?:**
N/A
### Monetization
**43. Outline your monetization models for the services you provide as a notary allocator pathway.:**
N/A

**44. Describe your organization's structure, such as the legal entity and other business & market ventures.:**
New Huo Pool (former HuobiPool) belongs to  frontier technology business segment  of New Huo Technology (HK1611) (former Huobi Technology) ,our major business is mining and mining-pool development.. New Huo Pool is committed to a comprehensive service platform for blockchain infrastructure construction and operation. Relying on its own hardware and software technology and professional operation and maintenance team, New Huo Pool provides mine construction, mining machine sales, mining machine hosting, mining pool operation, wallet scheme, mining machine maintenance and other businesses. The team has been deeply engaged in BTC and FIL mining, and continues to pay attention to other innovative projects. Website：[https://pool.newhuotech.com/](https://pool.newhuotech.com/home) twitter：@Huobi_pool Facebook：Huobi Pool instagram：huobipool YouTube：https://www.youtube.com/channel/UCNM-cVsa41TDdKv2IMBZRPw

**45. Where will accounting for fees be maintained?:**
N/A
### Past Experience, Affiliations, Reputation
**46. If you've received DataCap allocation privileges before, please link to prior notary applications.:**
https://github.com/filecoin-project/notary-governance/issues/708

**47. How are you connected to the Filecoin ecosystem? Describe your (or your organization's) Filecoin relationships, investments, or ownership.:**
The Huobi Group, in collaboration with Protocol Labs, has announced the launch of the Huobi Filecoin Incubation Center with a $10M USD fund dedicated to supporting the Filecoin ecosystem. The center will focus on three main areas: incubation, investment, and community development. It will support promising Filecoin developers, promote Filecoin-related academic research, and foster ecosystem development. Both Huobi and Protocol Labs believe that IPFS and Filecoin will be the foundation of the next generation of internet, creating a safer, more equal, and accessible system to distribute and store data - our most valuable asset in the 21st century. Seeing the Filecoin ecosystem’s enormous potential, Huobi believes that similar to decentralized finance, decentralized storage solutions such as Filecoin will lead a new wave of blockchain revolution and bring more innovation opportunities to developers. With Protocol Labs as the technical advisor to the investment fund, the incubation center will provide support for Filecoin developers and the community. The launch of the Huobi Filecoin Incubation Center and the ecosystem fund mark an important collaboration between the Filecoin community and a digital asset services provider. The two together will promote academic research and technical development of Filecoin and foster a stronger Filecoin ecosystem globally,” Wu added. To help develop Filecoin globally, the Huobi Filecoin Incubation Center and ecosystem fund will focus on the following key areas: Incubation. Collaborate with existing Filecoin accelerators and incubators, providing additional courses leveraging Huobi’s advantages in exchange solutions and Asia community. Investment. Huobi would provide funding to promising projects in the Filecoin ecosystem, with Protocol Labs providing technical guidance and support. Community development. Huobi and Protocol Labs will co-host annual summits and quarterly meetups globally, creating more cross border connections and communications among developers, miners, users, and token holders. This incubation center is the second of its kind following the Huobi DeFi Labs and will help Huobi Group conduct research, investment, incubation, and community building in the Filecoin ecosystem. URL:https://filecoin.io/blog/posts/huobi-group-launches-filecoin-incubation-center/

**48. How are you estimating your client demand and pathway usage? Do you have existing clients and an onboarding funnel?:**
N/A

**Comment by NewHuoPool** [comment]
Hi Kevin，
We are writing this letter to confirm that we have received the
notification of our selection as an Allocator in the Filecoin Plus program.
Additionally, this is to confirm our organization's email address.
If you have any further inquiries or require additional information, please
do not hesitate to contact us.

Warmly,
NewHuoPool

Kevin ***@***.***> 于2024年1月9日周二 01:27写道：

**Comment by galen-mcandrew** [comment]
## Datacap Request for Allocator
#### Address
> f2a7f7rocg4yh7nc2fnfxqulzxk2yohrb63yqevcy
#### Datacap Allocated
> 5PiB

**Comment by NewHuoPool** [comment]
Hi, Galen
We have received the message, thank you for your reminder!

Warmly,
NewHuoPool

Galen ***@***.***> 于2024年3月18日周一 12:13写道：

**Comment by galen-mcandrew** [comment]
Two proposals, needs RKH approval. TxID 577 or 578

**Comment by galen-mcandrew** [comment]
## Datacap Request for Allocator
#### Address
> f2a7f7rocg4yh7nc2fnfxqulzxk2yohrb63yqevcy
#### Datacap Allocated
> 5PiB

**Comment by galen-mcandrew** [comment]
## DataCap Request for Allocator
#### Address
> f2a7f7rocg4yh7nc2fnfxqulzxk2yohrb63yqevcy
#### Datacap Allocated
> 5PiB

**Comment by galen-mcandrew** [comment]
https://filfox.info/en/message/bafy2bzacea4334xu4c7ap26lsudpkehbbslfe5ovflldk4yrgzd4e2pgmh4xw
