### ISSUE TITLE
v5 Notary Allocator Application:FILWALLET

### ISSUE THREAD

**Issue by a1991car** [filecoin-project/notary-governance#1044]
# v5 Notary Allocator Application

To apply to be an allocator, organizations will submit one application for each proposed pathway to DataCap. If you will be designing multiple specific pathways, you will need to submit multiple applications. 

Please complete the following steps:
# 1. Fill out the information below and create a new GitHub Issue

1. Notary Allocator Pathway Name (This can be your name, or the name of your pathway/program. For example "E-Fil+"):FILWALLET
3. Organization Name:FILWALLET
4. On-chain address for Allocator (Provide a NEW unique address. During ratification, you will need to initialize this address on-chain):  f14r3uqsnxj22zzzkojqpdh6n62tg75vbx5wl72vi
5. Country of Operation (Where your organization is legally based): China
6. Region of Operation (What region will you serve?): Greater China、Asia minus GCR、Europe、North America
7. Type of Allocator, diligence process: (Automated/programmatic, Market-based, or Manual (human-in-the-loop at some phase): Manual
9. DataCap requested for allocator for 12 months of activity (This should be an estimate of overall expected activity. Estimate the total amount of DataCap you will be distributing to clients in 12 months, in TiB or PiB):120PiB

# 2. Access allocator application (download to save answers)
Click link below to access a Google doc version of the allocator application that can be used to save your answers if you are not prepared to fully submit the application in Step 3. https://docs.google.com/document/d/1-Ze8bo7ZlIJe8qX0YSFNPTka4CMprqoNB1D6V7WJJjo/copy

# 3. Submit allocation application 
Clink link below to access full allocator questionnaire and officially submit your answers:
https://airtable.com/appvyE0VHcgpAkt4Z/shrQxaAIsD693e1ns

Note: Sections of your responses WILL BE posted back into the GitHub issue tracking your application. 
The final section (Additional Disclosures) will NOT be posted to GitHub, and will be maintained by the Filecoin Foundation. 
Application information for notaries not accepted and ratified in this round will be deleted.

**Comment by Kevin-FF-USA** [comment]
Hi @a1991car 
Wanted to let you know this application has been received. Also verifying you have submitted the Airtable form with your detailed Allocator plan - the public answers will be posted in a thread below soon. If you have any questions - please let me know.

**Comment by Filplus-govteam** [comment]
### Basic Information
**1. Notary Allocator Pathway Name:**
FILWALLET

**2. Organization:**
FILWALLET

**3. On Chain Address for Allocator:**
f14r3uqsnxj22zzzkojqpdh6n62tg75vbx5wl72vi

**4. Country of Operation:**
China

**5. Region(s) of operation:**
Greater China, Europe, Asia minus GCR, North America

**6. Type of Allocator:**
Manual

**7. DataCap requested for allocator for 12 months of activity:**
120PiB

**8. Is your allocator providing a unique, new, or diverse pathway to DataCap? How does this allocator differentiate itself from other applicants, new or existing?:**
FILWALLET DataCap Allocator provides unique, innovative, and diverse approaches to support different types of applicants.

Combined manual and automated assessment process: Customers submit their applications on Github（https://github.com/a1991car/FILWALLET/issues/new/choose）, and during the review phase, we primarily use a manual process for verification of customer identity, evaluation of customer data, assessment of customer reputation, etc. During the customer's usage of DataCap, we automate the checking of customer data using the filplus-checker tool developed by our governance team. We also incorporate manual processes, such as random checks on retrieval data and comparison with metadata, to verify the authenticity of the data.

Innovative risk assessment model: We employ advanced risk assessment models that combine automated data analysis with expert reviews. For example, we assign a score to each customer, and after a customer has used 500T DC, our team assesses their honesty and trustworthiness through a combination of manual and automated methods. This enhances our ability to identify and manage potential risks.

Diverse DataCap options: We offer a variety of DataCap options, catering to enterprise customers, customers with public datasets, and individual customers with larger amounts of data. All of them are welcome to submit their applications.

Transparency and traceability: We emphasize transparency and traceability throughout the allocation process. To achieve this, we create a Github project where customers can submit their applications. Our governance team and the community can review customer usage at any time, ensuring high transparency and traceability.


**9. As a member in the Filecoin Community, I acknowledge that I must adhere to the Community Code of Conduct, as well other End User License Agreements for accessing various tools and services, such as GitHub and Slack.:**
Acknowledge
### Client Diligence
**10. Who are your target clients?:**
Small-scale developers or data owners, Enterprise Data Clients

**11. Describe in as much detail as possible how you will perform due diligence on clients.  If you are proposing an automated pathway, what diligence mechanism will you use to determine client eligibility?:**
Our due diligence process takes into account several key factors, including the client's establishment time and primary business, assessment of client data volume, business compliance, client's geographical distribution, and initial allocation plans. This process consists of several main stages:

Preliminary data collection (Client submits Github application form): We first gather basic information about the client, including detailed company registration information, financial reports, market share data, etc.

In-depth data analysis (Team members initiate investigations on clients): Team members conduct investigations on clients based on the information provided, including materials provided on GitHub and business licenses and identity information submitted via Slack. We use tools like WikiGloba and x315 to check the client's situation and verify their data using third-party business databases like Twitteraudit, Dun & Bradstreet, Bloomberg, Hoover's, etc.

Compliance checks (Third-party KYB): We collaborate with third-party organizations to investigate the client's compliance, including anti-money laundering (AML), counter-terrorism financing (CFT), and international sanction checks. This ensures a comprehensive understanding and assessment of the client's risk profile. We do not wish to store sensitive data.

Interactions (Manual phase): Due diligence involves direct interactions with the client, such as face-to-face meetings, phone inquiries, or on-site visits. This stage aims to verify the collected information and gain deeper insights into the client's business operations, management team, and company culture.

Ongoing monitoring and evaluation (Combination of automated and manual processes): As we enter the DC distribution phase, we maintain high vigilance to identify any new risks or opportunities.

**12. Please specify how many questions you’ll ask, and provide a brief overview of the questions.:**
https://github.com/a1991car/FILWALLET/issues/new/choose

Can you introduce yourself?
What is your official website or media?
What industry does your company belong to?
Can you provide a data case ?
Is your data sensitive or special?
How do you verify your identity?
Is the data public and searchable?
Provide the F1 address accepting DataCap.
Request the total amount of DataCap.
How much DataCap is allocated per week?
Which region do you plan to use DataCap in?
How many SPs do you plan to allocate?
List the cooperating SPs.
Do the SPs support retrieval?
How long is the data expected to be stored?
What is the retrieval frequency of the data?
Do you accept SPs using VPN, and how will you verify?
How did you find out about us?
Has the data been stored on the Filecoin network before?
How will you handle the data?
List the data processing platforms.
Do you need us to provide assistance?
Can you confirm that you will follow the Fil+ guideline

**13. Will you use a 3rd-party Know your client (KYC) service?:**
We have a compliance department and a customized KYC process in place. Customers are required to complete our designated compliance process, and we will conduct due diligence on the customer based on the information submitted on GitHub.

Once the customer has completed the due diligence process on GitHub, we will use tools such as LexisNexis、Twitter, Facebook, Toggle, Namescan, LinkedIn, and others to verify the customer. This includes verifying the authenticity and operation of the company, as well as reviewing updates through websites, social media, and portals to confirm if the company is still in operation.

This stage includes reviewing the types of data to be stored. We will query large databases to check if the submitted data cases are from the customer's company and whether the data is sensitive or not.

**14. Can any client apply to your pathway, or will you be closed to only your own internal clients? (eg: bizdev or self-referral):**
Any customer can apply

**15. How do you plan to track the rate at which DataCap is being distributed to your clients?:**
We proactively determine the client's usage speed, and when approving the next round of allocations, we perform checks.  Strictly speaking, with the integration of filplus-ssa-bot and filplus-checker, according to the current rules of the bot, the next round of bot requests is triggered when the available balance of the previous round's DataCap is below 25%.  At this point, we can use filplus-checker to check the client's data, including retrieval rate, SP quantity and distribution, CID sharing, backup status, etc. Additionally, it is important to verify the client's initial allocation plan and ensure that the actual allocation matches the initial plan.  Overall, filplus-checker and datacapstats.io will serve as our primary tools for tracking the rate at which DataCap is distributed to clients.
### Data Diligence
**16. As an operating entity in the Filecoin Community, you are required to follow all local & regional regulations relating to any data, digital and otherwise. This may include PII and data deletion requirements, as well as the storing, transmit:**
Acknowledge

**17. What type(s) of data would be applicable for your pathway?:**
Public Open Dataset (Research/Non-Profit), Public Open Commercial/Enterprise, Private Commercial/Enterprise, Private Non-Profit/Social Impact

**18. How will you verify a client’s data ownership? Will you use 3rd-party KYB (know your business) service to verify enterprise clients?:**
After the client's onboarding, we conduct continuous audits and reviews, which include our own verification as well as the use of third-party KYB checks. We utilize third-party KYB tools to verify the authenticity of the company, confirm the data's correspondence with the client, and assess the accuracy of the information. The following outlines how we use KYB to validate clients:

Key Steps:

1. Document Verification: Clients are required to submit official documents, including government-issued identification, business licenses, and other relevant legal documents.

2. Digital Signatures and Authentication: We employ advanced digital signature and authentication methods to verify the authenticity and source of the submitted documents.

3. Domain Email Verification: Confirmation codes and automated calls are used to validate the accuracy of the provided domain email addresses.

4. Preliminary Validation of Data Ownership: We request clients to provide proof of data ownership or legal rights, such as acquisition contracts, licenses, or legal certificates. For internally generated data, we ask for supporting documents like organizational charts or process descriptions to demonstrate how the data is generated and used within their business.

Key Tools:

1. For global enterprise information searches:
   - WikiGlobal: www.wikiglobal.com
   - x315: https://www.x315.cn/searchworld

2. For information searches in specific countries:
   - China:
     - National Enterprise Credit Information Publicity System: http://gsxt.saic.gov.cn
     - QCC: https://www.qcc.com/
     - Tianyancha: https://www.tianyancha.com
     - Hong Kong Companies Registry Integrated Companies Registry Information System: http://www.icris.cr.gov.hk/csci/
   - United States:
     - Wysk B2B Hub: http://www.wysk.com/index/
   - Singapore:
     - ACRA Website: https://www.acra.gov.sg/home/
   - United Kingdom:
     - BVI Financial Services Commission: http://www.bvifsc.vg/en-gb/regulatedentities.aspx
   - Australia:
     - Australian Business Register: http://abr.business.gov.au
   - India:
     - Ministry of Corporate Affairs: http://www.mca.gov.in
   - Germany:
     - Firmenwissen: http://www.firmenwissen.de/index.html

**19.  How will you ensure the data meets local & regional legal requirements?:**
To ensure that customer data complies with regional and local legal standards, our process includes filling out a GitHub application form, customer commitments, legal team assessments, and employee legal awareness training.  User commitment and transparent communication: We list the question ""Is your data sensitive or special? Please provide detailed explanation"" in the GitHub application form. We prioritize the client's commitment, as they are the primary stakeholders of the data. We require clients to commit that the data stored on the Filecoin network is public, compliant, and accessible to everyone.  Legal expertise and assessment: We have a comprehensive legal team with expertise in data protection and privacy laws relevant to each operating region. We conduct a thorough assessment of the data protection laws in the collaborating client's region to understand specific requirements and any updates. We formulate our policies to reject application forms categorized as ""sensitive data.""  Data classification and localization: We classify data based on its sensitivity and the legal requirements of different jurisdictions. This enables us to implement appropriate safeguards and controls to meet specific legal standards in each region.  Employee training and awareness: We conduct regular training programs for our employees to educate them about local and regional legal requirements. This ensures that our team members understand their role in maintaining compliance throughout the data processing journey.

**20. What types of data preparation will you support or require?:**
If the client has a mature technical team, we would instruct them to cut, package, and compress the client data into a zip file of 28-32 GiB. We would then use programs such as go-car code library to convert these files into car files.  If the client does not have a mature technical team or lacks technical capabilities, our team can provide all the necessary technical assistance. This includes offering our data processing programs for the client's use or sending colleagues to the client's location to provide guidance.  Our technical solution can achieve data sharding, but the specifics of data processing would be determined through communication with the client.

**21. What tools or methodology will you use to sample and verify the data aligns with your pathway?:**
Our data validation method involves randomly selecting a record for inspection. This process helps confirm that the data aligns with the client's statements regarding its type and preparation. Additionally, we will gradually allocate DataCap to the client based on our verification of the data and its efficient utilization of space, thereby mitigating the risk of sector abuse.
### Data Distribution
**22. How many replicas will you require to meet programmatic requirements for distribution?:**
5+

**23. What geographic or regional distribution will you require?:**
We hope SPs to be distributed in three different regions

**24. How many Storage Provider owner/operators will you require to meet programmatic requirements for distribution?:**
5+

**25. Do you require equal percentage distribution for your clients to their chosen SPs? Will you require preliminary SP distribution plans from the client before allocating any DataCap?:**
We will require clients to provide an equal percentage allocation to their Service Providers (SPs). Having each SP store the same data is crucial for data backup purposes. We strive for clients' data to have optimal backup, as data backup is an important criterion for the checker-bot's checks. Therefore, we expect clients to allocate the data to SPs in an equal proportion, with a maximum deviation of 20%.

**26. What tooling will you use to verify client deal-making distribution?:**
Datacapstats.io and Bot

**27. How will clients meet SP distribution requirements?:**
We have developed our own solution. The core idea of ​​the solution is to help customers distribute SP through API/SDK, which is efficient. Of course, we are also familiar with other tools. If customers have their own ideas for technology, we will also help customers develop new solutions.

**28. As an allocator, do you support clients that engage in deal-making with SPs utilizing a VPN?:**
MaxMind is an industry-leading IP geolocation and online fraud prevention platform. We utilize external platforms to determine whether storage providers are using VPN services. One key tool in this process is the VPN/IP address check provided by IPQualityScore, which can be accessed at https://www.ipqualityscore.com/vpn-ip-address-check. Additionally, we leverage tools like MaxMind to enhance our verification capabilities.
### DataCap Allocation Strategy
**29. Will you use standardized DataCap allocations to clients?:**
Yes, standardized

**30. Allocation Tranche Schedule to clients::**
Initial Allocation: 5% of the requested DataCap total or 50% of the weekly allocation rate, whichever is smaller.
Second Allocation: 10% of the requested DataCap total or 100% of the weekly allocation rate, whichever is smaller.
Third Allocation: 20% of the requested DataCap total or 200% of the weekly allocation rate, whichever is smaller.
Fourth Allocation: 40% of the requested DataCap total or 400% of the weekly allocation rate, whichever is smaller.
...
The maximum allocation does not exceed 2 PiB.

**31. Will you use programmatic or software based allocations?:**
No, manually calculated & determined

**32. What tooling will you use to construct messages and send allocations to clients?:**
https://filplus.fil.org/#/ and https://filplus-registry.netlify.app/

**33. Describe the process for granting additional DataCap to previously verified clients.:**
fillus-ssa-bot is a useful open source tool. We will continue to continue the current rules and use bot to monitor the remaining DataCap. When it falls below 25%, the next round of allocation requests will be triggered. When approving the next round of applications, we will check the customer's usage, including the number and distribution of SPs, retrieval, backup and cid conditions, etc.

**34. Describe in as much detail as possible the tools used for: • client discoverability & applications • due diligence & investigation • bookkeeping • on-chain message construction • client deal-making behavior • tracking overall allocator health • disput:**
Discovery of clients and management applications: We utilize our website and GitHub for discovery, and Discord is widely used for managing application workflows.
Investigation and due diligence: Background investigation tools (LexisNexis) for customer background and reputation checks; survey software (SurveyMonkey) for collecting customer feedback and opinions. For VPN detection, we rely on IPQualityScore (https://www.ipqualityscore.com/vpn-ip-address-check). For comprehensive checks, we also utilize the services of MaxMind (https://www.maxmind.com), and Namescan.io supports our compliance verification process.
Maintenance of financial records: Spreadsheet software (Microsoft Excel) for data analysis and record keeping.
Building on-chain messaging: Blockchain interaction tools (Ledger, GILF) for creating and sending on-chain messages.
Monitoring customer transactions: Filecoin Boost for tracking customer transaction behavior, along with tools like Glassnode for blockchain analysis, and data analysis tools (Tableau, Power BI) for analyzing and visualizing transaction data.
Overall health monitoring of distributors: Internally designed dedicated dashboards to help us track and supervise distribution activities.
Dispute resolution: Discord and GitHub are the main forums for dispute discussions and resolution.
Community engagement and updates: For community engagement and updates, we use Discord and GitHub, and provide additional channels through Substack for sending newsletters and updates.

### Tools and Bookkeeping
**35. Will you use open-source tooling from the Fil+ team?:**
Yes, we will use the open-source tools from the FIL+ team. We appreciate the hard work of the FIL+ team. filplus-registry: Manages LDN. filplus-ssa-bot: Monitors DC quotas and triggers limits. filplus-checker: Checks data related to LDN, such as CID status, backup status, SP distribution, etc. These tools are open-source and useful, and we are happy to use them.

**36. Where will you keep your records for bookkeeping? How will you maintain transparency in your allocation decisions?:**
Bookkeeping records, including client applications, client basic information, total DC quotas obtained, and significant decisions, are stored in GitHub. Furthermore, dispute resolutions will also take place on GitHub.

While private communications such as private emails, DMs on Slack, and phone conferences are considered private, significant decisions and the rationale behind them that result from private communications will be synchronized on GitHub.

In the event of a dispute, we will synchronize private information with the governance team.
### Risk Mitigation, Auditing, Compliance
**37. Describe your proposed compliance check mechanisms for your own clients.:**
Regular checks: Before the initial allocation of DataCap, we conduct comprehensive checks on customer qualifications. Only after conducting internal KYC and third-party KYB, do we allocate the first round of quotas to customers. Before allocating the second round of quotas, we rigorously examine the customer's allocation status. We proceed to the next round only if the allocations are compliant.
DataCap distribution metrics: We will monitor the distribution of DataCap to customers using the filplus-saa-bot system. This includes monitoring allocations, utilization rates, and any deviations from expected patterns.
Customer demographic analysis: We will use https://datacapstats.io to understand customer demographic data. We will conduct regular analysis to ensure decentralized distribution of DataCap.
Time-based indicators: Time-based indicators will be tracked to determine usage patterns and trends during different periods. This analysis will help optimize DataCap distribution strategies and ensure efficiency.
Trust evaluation: Whether they are new or existing customers, we will use a trust evaluation mechanism to assess the reliability and responsible use of DataCap by customers. We will prioritize working with customers who have a good community reputation.
Use of dedicated tools: Tools such as CID Checker and Retrievability Bot will be integrated into the monitoring system. The CID Checker will verify the integrity of Content IDs, and the Retrievability Bot will assess the retrievability of stored data.

Tolerance for new customers: Our trust in new customers will be based on a thorough onboarding process:

1. We will conduct thorough due diligence on new customers to verify their legitimacy and the reasonableness of their allocation plans.
2. We will implement a phased expansion approach for new customers, with relatively low DC quotas allocated in the first three rounds. This allows us to closely monitor and evaluate their compliance before increasing DataCap distribution.
3. We will provide continuous monitoring of all customers, with special attention to those in the initial stages of participation, to ensure smooth integration and compliance. We will also actively assist customers when needed.

**38. Describe your process for handling disputes. Highlight response times, transparency, and accountability mechanisms.:**
If a dispute arises, we have a unified bookkeeping system to record it, which is GitHub.
We will refer to the current handling process of the FIL+ governance team and establish a dedicated proposal where all communication regarding the dispute will be documented. This facilitates information recording and management.
Whether the dispute is internal or external, whether it is against a customer or against myself, I will actively participate in resolving the dispute.
If the dispute is significant, we will invite the governance team to join the process. I am willing to provide all private communications with the customer, such as contracts, identity verification documents, and chat record screenshots, to the FIL+ team.
Lastly, all decisions and the rationale behind them will be displayed and synchronized on GitHub.

**39. Detail how you will announce updates to tooling, pathway guidelines, parameters, and process alterations.:**
First, we will announce our major updates on our official website. Second, we will also keep updates on GitHub, Slack channels, or any other necessary channels and engage with the community. Third, in addition to public announcements, we will notify the FIL+ governance team of significant updates through email. Fourth, if necessary, we will hold Zoom meetings and conduct voting to gather community opinions.

**40. How long will you allow the community to provide feedback before implementing changes?:**
We are committed to respecting the diverse voices of the community, and for any updates, we want to see a healthy development and continuous participation from the community. Therefore, in general, we allow the community a period of three months to provide feedback. However, we understand that in most cases, it may not require such a long time. Nonetheless, there may be important updates that require extensive discussions. By setting a three-month timeframe, we aim to demonstrate our respect for the community's opinions. We will discuss through the following channels:

Public forums and discussion platforms: Utilizing platforms such as Slack, GitHub, and Zoom, we encourage open discussions. We provide detailed explanations regarding the changes and potential impact assessments to facilitate meaningful conversations.

Feedback collection and analysis: We establish dedicated channels such as GitHub proposals, online forms, etc., where community members can share their opinions and suggestions. This allows us to better analyze the feedback received.

Engaging the governance team in decision-making: For technical updates, we will pay close attention to the opinions of the governance team, particularly for significant decisions. We value the perspectives of the governance team and the PL

**41. Regarding security, how will you structure and secure the on-chain notary address? If you will utilize a multisig, how will it be structured? Who will have administrative & signatory rights?:**

I will use a hardware wallet (Ledger) to protect my custody address.
Management authority: a1991car (Filwallet founder)
Signing authority: a1991car (Filwallet founder)

**42. Will you deploy smart contracts for program or policy procedures? If so, how will you track and fund them?:**
We plan to continue using FIL+'s open-source tools, such as filplus-saa-bot, AC bot, CID Checker, and Retrievability Bot. We may consider integrating the signing system with our filwallet's multi-signature feature.
### Monetization
**43. Outline your monetization models for the services you provide as a notary allocator pathway.:**
We believe that the core goal of DataCap is to attract customers with genuine storage needs through network subsidies, and the economic model should focus on the value of data storage. Taking reference from the pricing on the BDX platform, which is endorsed by the PL , the approximate price for 1TB of DC is 1 FIL. However, due to the dynamic nature of FIL price, per-TB income, and gas fees, the price of 1TB of DC fluctuates. For now, we calculate it as 1 FIL/TB.

Here are the main costs: customer data, data processing fees, bandwidth costs, hard drive costs, hard drive shipping costs, and labor costs.

In general, when customers store their data on the Filecoin network, we need to provide incentives to them. As customers contact Service Providers (SPs) and the SPs acquire DC from customers, they can save on hardware and operational costs. Therefore, SPs provide incentives to customers, and our charging price is lower than the incentives provided by SPs. The remaining portion is the customer's data storage revenue.

Therefore, we have decided to adopt a discount model to provide greater network subsidies to genuine data providers:

Enterprise customers with genuine data storage needs: 30%
Public datasets: 10%
SPs with retrieval rates exceeding 80%: 10%
SPs distributed in specific regions: 10%
Data storage duration of no less than 540 days: 5%
As a result, the highest discount can reach 55%, which means the lowest charge can be 0.45 TB/FIL.

The price of 0.45 TB/FIL primarily covers developer costs, bandwidth costs, data processing costs, and the cost of hiring third-party companies for KYB processes.


**44. Describe your organization's structure, such as the legal entity and other business & market ventures.:**
With so many ecosystems of Filecoin, we choose to in the field of wallets.Because our team has experience in the development of blockchain wallets, our person in charge even once worked in imtoken. Therefore, to maximize the functions, UI and experience of FILWallet to serve Filecoin ecological users, this is the goal of our team. And we are confident we can make it happen.  In June 2021, FILWallet will launch V1.0.5, which integrates the following functions: Support FIL full account system (f0, f1, f2, f3) Support FIL multi-signature  In August 2021, FILWallet V1.1.1 launched, which integrate the following functions:     Support node management, can change Owner to multi-signature, node exit, observe node dynamics Support the function of re-signing after FIL multi-signature signature fails In 2022, FILWallet V1.1.5 will be launched, which integrates the following functions:     Support message push, content unified management     Support international languages​(English, Traditional Chinese, Korean, Japanese)     Support FIL multi-signature red envelope function, red envelopes are distributed through multi-signature addresses In 2023, FILWallet V2.0.0 will be launched. The version integrates the following functions: Access to ETH, BSC, Filecoin public chain The on-chain ecological DApp can be accessed through FILWallet  Asset security: Security is the most important thing to FILWallet and we always place at the top of the development. FILWallet completes a comprehensive security review by two security auditing companies (Certik and Artemis). At the same time,  the user's mnemonic and private key are only stored in the ciphertext on the mobile phone, and the stored ciphertext is generated by complex strategies and secure encryption algorithms to ensure security. The user needs to enter the password to decrypt the data before using the private key to sign the data. The platform will not access and store any user's mnemonic or private key, and will not transmit it through the network; and has also made more security protections to prevent illegal attacks.   FILWallet currently has a 3000+ user base, with a daily FIL transfer of nearly 100000+, and has won unanimous praise from ecological users. In the future, Filecoin will support smart contracts, and FILWallet will explore financial-based derivatives services and provide on-chain data analysis services. Ultimately, it will provide FIL users with access to the Filecoin ecosystem. FILWallet will also continue to pay attention to the voices of ecological participants and meet the needs of the community as much as possible; iteratively upgrade according to the needs of the community, and keep providing the most professional and safe digital asset services for participants in the Filecoin ecosystem.  FILWallet has grown rapidly, not only serving many users, but also taking third place in the Filecoin hackathon competition, and has become the most popular Filecoin wallet in China and Asia.  1. Provide the most professional and secure digital asset services for participants in the Filecoin ecosystem. At present, most of the mining methods of filecoin are cluster or joint mining. There will be some mistrust problems in how to store the produced coins. FILWallet launched the FIL multi-signature wallet to solve this problem. Several people manage this FIL multi-signature wallet at the same time. . Through the FIL multi-signature wallet, the Owner can be multi-signed, and the FIL red envelope can be issued through the FIL multi-signature wallet 2. In the v2.0.0. version of FILWallet, ETH&BSC is added. Through the FILWallet DApp browser, users can experience the current popular DApps based on the ETH&BSC ecology, which greatly reduces the threshold for digital asset users. 3. FILWallet has held a number of community ama, and DoraHacks allows participants of the Filecoin ecosystem to better understand the ecosystem.  https://hackerlink.io/zh/buidl/916?roundProj=711

**45. Where will accounting for fees be maintained?:**
Generally, customers make payments to the company's account, and the receiving address can be an f1 address or a TRC-20 USDT address. These addresses allow us to monitor the inflows and outflows, and we can track the transaction history of each payment. We will develop our own bookkeeping system to record detailed information of each income and expense. If the FIL+ team requires it, we can provide the contracts we have signed with customers and other sensitive data.
### Past Experience, Affiliations, Reputation
**46. If you've received DataCap allocation privileges before, please link to prior notary applications.:**
https://github.com/filecoin-project/notary-governance/issues/644

**47. How are you connected to the Filecoin ecosystem? Describe your (or your organization's) Filecoin relationships, investments, or ownership.:**
As a renowned Filecoin wallet, we have received rewards from hackathons and gained official support. We actively communicate and engage with Service Providers (SPs) to facilitate FIL storage. The multi-signature feature has been well-received by many customers.

**48. How are you estimating your client demand and pathway usage? Do you have existing clients and an onboarding funnel?:**
Yes, we have a GitHub application form where customers can submit their applications. We conduct due diligence on GitHub to review these applications.

**Comment by kevzak** [comment]
## Datacap Request for Allocator
#### Address
> f27j36upkm2mk3vrae25i7rhdtzmxjnntnvrxnasa
#### Datacap Allocated
> 5PiB

**Comment by galen-mcandrew** [comment]
## Datacap Request for Allocator
#### Address
> f27j36upkm2mk3vrae25i7rhdtzmxjnntnvrxnasa
#### Datacap Allocated
> 2.5PiB

**Comment by galen-mcandrew** [comment]
bafy2bzacecspo5j7xyjdyojbo22kjb356q32scczwinyg7vz6ozpmck2fq4ni
