### ISSUE TITLE
v5 Notary Allocator Application: DSPA

### ISSUE THREAD

**Issue by pandacrypto** [filecoin-project/notary-governance#1045]
# v5 Notary Allocator Application

To apply to be an allocator, organizations will submit one application for each proposed pathway to DataCap. If you will be designing multiple specific pathways, you will need to submit multiple applications. 

Please complete the following steps:
# 1. Fill out the information below and create a new GitHub Issue

1. Notary Allocator Pathway Name (This can be your name, or the name of your pathway/program. For example "E-Fil+"): DSPA Filecoin Pathway
3. Organization Name: Decentralised Storage Provider Accelerator (DSPA)
4. On-chain address for Allocator (Provide a NEW unique address. During ratification, you will need to initialize this address on-chain): f1xdpvmkm75sinulbz5j73wseupq4equmchxonvjy
5. Country of Operation (Where your organization is legally based): Singapore
6. Region of Operation (What region will you serve?): All Regions
7. Type of Allocator, diligence process: (Automated/programmatic, Market-based, or Manual (human-in-the-loop at some phase): Manual
9. DataCap requested for allocator for 12 months of activity (This should be an estimate of overall expected activity. Estimate the total amount of DataCap you will be distributing to clients in 12 months, in TiB or PiB): 500 PiB

# 2. Access allocator application (download to save answers)
Click link below to access a Google doc version of the allocator application that can be used to save your answers if you are not prepared to fully submit the application in Step 3. https://docs.google.com/document/d/1-Ze8bo7ZlIJe8qX0YSFNPTka4CMprqoNB1D6V7WJJjo/copy

# 3. Submit allocation application 
Clink link below to access full allocator questionnaire and officially submit your answers:
https://airtable.com/appvyE0VHcgpAkt4Z/shrQxaAIsD693e1ns

Note: Sections of your responses WILL BE posted back into the GitHub issue tracking your application. 
The final section (Additional Disclosures) will NOT be posted to GitHub, and will be maintained by the Filecoin Foundation. 
Application information for notaries not accepted and ratified in this round will be deleted.

**Comment by Kevin-FF-USA** [comment]
Hi @pandacrypto 
Wanted to let you know this application has been received. Once you complete and submit the include Airtable (form) information - the public answers will be posted in a thread below soon. If you have any questions - please let me know.

**Comment by Kevin-FF-USA** [comment]
Hi @pandacrypto,
Wanted to let you know this application has been received. Once you complete and submit the include Airtable (form) information - the public answers will be posted in a thread below soon. If you have any questions - please let me know.

**Comment by pandacrypto** [comment]
> Hi @pandacrypto, Wanted to let you know this application has been received. Once you complete and submit the include Airtable (form) information - the public answers will be posted in a thread below soon. If you have any questions - please let me know.

@Kevin-FF-USA It has been submitted through Airtable!

**Comment by Kevin-FF-USA** [comment]
Hi @pandacrypto,

Thanks for submitting to become and Allocator! Wanted to confirm this application has been received along with your completed Airtable form.

**Comment by pandacrypto** [comment]
> Hi @pandacrypto,
> 
> 
> 
> Thanks for submitting to become and Allocator! Wanted to confirm this application has been received along with your completed Airtable form. 

Thanks for the confirmation! Looking forward for public feedback

**Comment by Filplus-govteam** [comment]
### Basic Information
**1. Notary Allocator Pathway Name:**
DSPA Filecoin Pathway

**2. Organization:**
Decentralised Storage Provider Accelerator (DSPA)

**3. On Chain Address for Allocator:**
f1ypa6bsr6olb53kssbwgjyjcrzk4x3ijmpd5cmbq

**4. Country of Operation:**
Singapore

**5. Region(s) of operation:**
Africa , Asia minus GCR, Greater China, Europe, Oceania, Japan, North America, South America

**6. Type of Allocator:**
Manual

**7. DataCap requested for allocator for 12 months of activity:**
500 PiB

**8. Is your allocator providing a unique, new, or diverse pathway to DataCap? How does this allocator differentiate itself from other applicants, new or existing?:**
1. This will be a diverse pathway to DataCap. As DSPA has existing and upcoming potential new Storage Providers, DSPA helps accelerate both SP's business transformation.
2. There are systems currently available for node management, DataCap management, and tracking tools on the DataCap application by SP through DSPA portal.
3. DSPA allocators accept all types of datasets, for example, public datasets, enterprise datasets, privacy datasets, encrypted datasets and etc.

**9. As a member in the Filecoin Community, I acknowledge that I must adhere to the Community Code of Conduct, as well other End User License Agreements for accessing various tools and services, such as GitHub and Slack.:**
Acknowledge
### Client Diligence
**10. Who are your target clients?:**
Individuals learning about Filecoin, Small-scale developers or data owners, Enterprise Data Clients

**11. Describe in as much detail as possible how you will perform due diligence on clients.  If you are proposing an automated pathway, what diligence mechanism will you use to determine client eligibility?:**
Every application has to go through a thorough evaluation process, where the more Datacap sought, the more thorough the examination will be.
Manual due diligence involves:
1. Identity verification: KYC documents such as business licenses, business registration certificates, passport information files, etc. 
  a. Note: The business Manager will reach out to the applicant via email and set up 1-1 video/voice call for further check and review
2. Compliance check: Company's product types, business model, and news status through social media accounts, official websites, and other platforms.
3. Background check: Client's business history, reputation, and experience

**12. Please specify how many questions you’ll ask, and provide a brief overview of the questions.:**
https://dspa-asia.io/sp-certification

Additional questions (flexibly adapted based on the unique circumstances of the client):
1. Could you provide background information about your company or yourself, co-owner, or directors, including links to your website and any pertinent online accounts?
2. What is the source of the data, how much of it do you plan to preserve, and can you substantiate this claim?
3. How do you want to store data initially? Which appropriate storage providers are you now in contact with? Please tell me each person's name.
4. How would you go about submitting data to Filecoin?
5. To guarantee compliance with its use, could you provide the actual usage situation of your Datacap allocation?
6. What kind of data content do you save, and is it compliant with regional and federal laws?

**13. Will you use a 3rd-party Know your client (KYC) service?:**
Provide as much detail about the service, what questions and regions they cover, and how the data will be integrated with your pathway.

For the first phase, we will use specific questions for a preliminary KYC check on clients. For the second phase, once operational business processes are implemented, we'll recommend integrating a third-party KYC platform to standardize the business processes.

Third-party service providers: Jumio, Genpact, Trulioo, Onfido, Toggle, and so on.

Regions and questions covered: KYC services usually include CFT (Counter Financing of Terrorism) and FATF (Financial Action Task Force) checks and customer identification verification. To guarantee adherence to both local and international regulations, they might have a worldwide reach.

Service integration: The business can incorporate KYC service calls into its internal platforms, applications, or website if considering using third-party KYC services.

**14. Can any client apply to your pathway, or will you be closed to only your own internal clients? (eg: bizdev or self-referral):**
Applying to DSPA Filecoin Pathway is open to all clients. They must, however, adhere to the DSPA Filecoin Pathway's specifications. This could apply to companies, sole proprietors, or other entities. Typically, the goals of this strategy are to increase visibility, draw in a wider audience, and grow the FIL+.

**15. How do you plan to track the rate at which DataCap is being distributed to your clients?:**
Datacap allocations and consumption data will be manually compiled into a form in the beginning.   Currently, DSPA portal admin has Real-time data synchronisation via interaction with platform APIs from third parties, where the nodes and wallet management tracking is available.  https://admin.dspa-asia.io/login
### Data Diligence
**16. As an operating entity in the Filecoin Community, you are required to follow all local & regional regulations relating to any data, digital and otherwise. This may include PII and data deletion requirements, as well as the storing, transmit:**
Acknowledge

**17. What type(s) of data would be applicable for your pathway?:**
Public Open Dataset (Research/Non-Profit), Public Open Commercial/Enterprise, Private Commercial/Enterprise, Private Non-Profit/Social Impact

**18. How will you verify a client’s data ownership? Will you use 3rd-party KYB (know your business) service to verify enterprise clients?:**
DSPA will verify the client data through the KYB information provided/uploaded to the DSPA platform.
1. To confirm the data owner's data source and type, request the provision of primary information, such as identification documents, company licenses, government websites, etc. This will be the first level check through registration, will cross-check with CFT and FATF Blacklist (country and high-risk person)
2. Request the submission of data servers, data samples, and other proof of data capacity.
3. Require the data owner to sign a data ownership declaration based on the trust principle; if they don't, they bear full responsibility for any repercussions.
4. Confirm the client's standing and reputation in the business network by contacting the client's business associates or other supply chain participants. This will help you verify the client's business partners and supply chain.
5. Using Know Your Business (KYB) services provided by third parties will also be considered.

**19.  How will you ensure the data meets local & regional legal requirements?:**
 19.  How will you ensure the data meets local & regional legal requirements? * 1. DSPA has a team keeping up to date and monitoring the current local and regional legal requirements.  2. DSPA's compliance and legal team will review all the information to ensure the data meets local and regional legal requirements.

**20. What types of data preparation will you support or require?:**
The following types of data are supported by DSPA; 1. Video 2. Images 3. Text 4. And all types of data It is recommended to continue using official open-source tools for data preparation, such as Singularity.

**21. What tools or methodology will you use to sample and verify the data aligns with your pathway?:**
AC Bot that was developed by Filecoin governance team will be integrated and implemented to verify the data. This will also help with data matches confirmation of both in type and preparation through AC Bot.
### Data Distribution
**22. How many replicas will you require to meet programmatic requirements for distribution?:**
4+

**23. What geographic or regional distribution will you require?:**
All regions, with a minimum of three different geographical locations, and limited use of VPNs.

**24. How many Storage Provider owner/operators will you require to meet programmatic requirements for distribution?:**
4+

**25. Do you require equal percentage distribution for your clients to their chosen SPs? Will you require preliminary SP distribution plans from the client before allocating any DataCap?:**
1. There is no requirement to assign the chosen Service Providers (SPs) a fixed percentage; however, the maximum share is capped at 30%. 2. Customers must submit an initial SP allocation plan before allocating Datacap. Flexibility is permitted, though, since real collaboration with SPs during business may differ from the original concept. Giving a plausible explanation is adequate.

**26. What tooling will you use to verify client deal-making distribution?:**
It is advised to continue using official tools like the datacapstats.io tooling and the CID checker bot. As an example, the current datacapstats.io tooling and the CID checker bot

**27. How will clients meet SP distribution requirements?:**
It will be a manual distribution through the DSPA portal. However, there are certain rules and policies for the distribution requirement as below:  - - Rule Configuration: Allow clients to alter distribution and selection rules to suit their unique requirements. - Flexibility: Enable flexibility to accommodate various customers' unique needs and business procedures.

**28. As an allocator, do you support clients that engage in deal-making with SPs utilizing a VPN?:**
DSPA allows SPs to use a limited number of VPNs. To make sure that only authorised users may conduct transactions, individuals using VPNs are subject to enhanced identity verification methods including KYB checks.
### DataCap Allocation Strategy
**29. Will you use standardized DataCap allocations to clients?:**
Yes, standardized

**30. Allocation Tranche Schedule to clients::**
First Maximum for Each Client: To guarantee equitable distribution and avoid abuse, clients in the early phases may be limited to the total cap. The initial cap may be gradually increased in proportion to the client's growing network engagement and reputation.
Dynamic Modification of Total Cap: The total cap may be dynamically changed in response to gains made by a client in terms of reputation and performance within the Filecoin network. This incentivizes users to actively participate in the Filecoin ecosystem and provide valuable data.
Allocator Adopts a ""Limited Trust Over Time"" Strategy at All Times: Based on the time process, more Datacap is progressively issued; for example, the rate from the previous round is doubled.
As an illustration:
- First Round: 512 TiB
- Second Round: 1 PiB
- Third Round: 2 PiB
- Fourth Round: 2 PiB
- Overall Cap for Each Client: (2 PiB)


**31. Will you use programmatic or software based allocations?:**
No, manually calculated & determined

**32. What tooling will you use to construct messages and send allocations to clients?:**
Yes，using the existing notary registry tooling.

**33. Describe the process for granting additional DataCap to previously verified clients.:**
We will implement the following strategies: 1. Encourage clients to distribute Datacap among various Service Providers (SPs). Comprehensive and effective Know Your Customer (KYC) processes, due diligence, and clear rules explanations are essential during the initial phases. 2. Mandate clients to routinely provide transaction information. 3. Regularly examine Datacap transactions and allocations through the filplus.info website. We will document these transactions and cross-verify them with the information clients disclose. 4. If any client violations are identified, warnings will be issued. In cases of severe violations, the client's misconduct will be publicly disclosed in the Slack community.

**34. Describe in as much detail as possible the tools used for: • client discoverability & applications • due diligence & investigation • bookkeeping • on-chain message construction • client deal-making behavior • tracking overall allocator health • disput:**
• Client Discoverability & Applications:
- GitHub: Explore client applications and discoverability tools.
• Due Diligence & Investigation:
- GitHub: Utilize repositories for due diligence and investigation.
- Due Diligence Questionnaire: Employ a structured questionnaire for comprehensive assessments.
- KYC Platform: Leverage Know Your Customer platforms for thorough client verification.
• Bookkeeping:
- GitHub/Excel: Utilize GitHub repositories and Excel for efficient bookkeeping.
• On-chain Message Construction:
- Filplus: Utilize on-chain messaging tools for constructing messages.
• Client Deal-Making Behavior:
- GitHub CID Check Report: Refer to GitHub for deal-making behavior analysis.
- On-chain Messaging: Leverage on-chain messaging for additional insights.
• Tracking Overall Allocator Health:
- Datacapstats: Monitor and track overall allocator health using this platform.
• Dispute Discussion & Resolution:
- Google Dispute: Use Google platforms for dispute discussions and resolutions.
• Community Updates & Communication:
- GitHub & Slack: Stay connected with the community through GitHub and Slack for updates and communication.

### Tools and Bookkeeping
**35. Will you use open-source tooling from the Fil+ team?:**
Open-source tooling such as Boost, Lotus, Singularity and Github Repo will be the primary tools used by DSPA.

**36. Where will you keep your records for bookkeeping? How will you maintain transparency in your allocation decisions?:**
We understand the importance of transparency and adherence to FIL+ guidelines. To align with these principles, we will adopt a balanced approach regarding the public availability of diligence and client information. While recognizing the need for community transparency and ongoing auditing, we also acknowledge that specific details should remain accessible upon request by the Fil+ Governance team for dispute resolution or audits.
Our commitment involves publicly disclosing allocation decisions and review processes on GitHub, ensuring that the community remains informed about our activities while maintaining the confidentiality required for effective governance and dispute resolution.
### Risk Mitigation, Auditing, Compliance
**37. Describe your proposed compliance check mechanisms for your own clients.:**
This should include regular check-ins, tracking DataCap distribution metrics, understanding client demographics, time metrics, trust evaluations, and the use of tools such as CID Checker/Retrievability Bot.

Datacap allocations are primarily tracked through the DSPA portal, which retrieves the information from two leading platforms: Filplus and Datacapstats. Through DSPA portal, it has in-house build record-keeping of the DataCap allocations.

Regarding customer tolerance, DSPA is open to initially trusting the sincerity and reliability of customers. 

However, as part of due diligence, GH will seek supporting evidence, which may include business licenses, business types, data sources, and the scale of data. This approach ensures a balance between trust and verification in the customer relationship.

**38. Describe your process for handling disputes. Highlight response times, transparency, and accountability mechanisms.:**
A dispute within the context of DataCap allocation refers to any contention or disagreement arising between parties involved in the storage and retrieval of data on the Filecoin network. This could involve discrepancies over DataCap distribution, disagreements on data compliance with stated parameters, or conflicts over the execution of storage deals.
 
Disputes may be internal, involving yourself and your client, or external, where you will need to defend your decisions against another active notary or the Fil+ Governance Team.

When disputes arise, DSPA will implement proactive measures to address the issues:
1. Response Time:
  - Immediate suspension of additional DC allocations.
  - Clarification within three working days.
  - Resolution attempts within one week to expedite the DC allocation process.
2. Transparency:
  - All disputes and corresponding explanations will be publicly disclosed on GitHub.
  - Ensuring fairness and justice in handling every dispute.
3. Accountability Mechanism:
  - Fil-plus operates on established principles and rules.
  - All DC allocations must adhere to the predetermined execution standards, ensuring accountability in the process.

**39. Detail how you will announce updates to tooling, pathway guidelines, parameters, and process alterations.:**
We anticipate and endorse the iterative improvement of tactical tooling and strategic programmatic rules. Updates will occur as needed for security or compliance requirements, but we will be mindful not to introduce excessive change or scope creep. Some significant programmatic changes may be subject to Fil+ Governance Team evaluation, requiring a reapplication against the rubric. Effective communication of updates, including tool modifications, pathway guidelines, parameter changes, and process adjustments. The following methods can be employed: 1. Email Notifications:   - Send email notifications to key participants in the Filecoin Plus ecosystem, summarizing the changes and providing links to detailed information. 2. Publish Messages on the DSPA Website, Official Slack, and Social Media:   - Share announcements on the DSPA website, the official Slack, and the Social Media interactive platform to reach a wider audience. 3. Update Documents and Guides on GitHub:   - Keep community documentation and guides on GitHub updated to ensure transparency and accessibility. 4. Conduct Webinars, X-space, Podcast:   - Host webinars, X-space, or PodcastsPodcast if necessary to explain the details of the changes. Record the session for future reference. 5. Establish Transition Period:   - Implement a transition period to allow participants to adapt gradually to the new rules and processes.   - These communication methods will ensure the community is well-informed and can smoothly adapt to updates while maintaining transparency and clarity in the Filecoin Plus ecosystem.

**40. How long will you allow the community to provide feedback before implementing changes?:**
Ensuring open, transparent, and decentralized community structures is a key priority. While decentralization doesn't always imply equal ownership or power for every community member, engagement, moderation, and facilitation are critical aspects of community governance. Here's how we plan to engage the community, provide moderation and facilitation, and weigh feedback:
1. Community Feedback Period:
  - Allow a substantial three-month period for community feedback before implementing changes. This extended timeframe ensures that decisions are made with rationality and receive broad acceptance.
2. Open Community Forum:
  - Establish an open community forum, creating a space for extensive discussions and encouraging community members to express their opinions. This forum will serve as a platform for collaborative decision-making.
3. Online Feedback Form:
  - Provide an accessible online feedback form if necessary, offering a straightforward method for community members to submit their thoughts and suggestions.
4. Community Governance Emphasis:
  - Implement changes following community governance principles, emphasizing fairness and transparency in decision-making.
These measures aim to foster an inclusive and participatory environment, ensuring that community members have ample opportunity to contribute to discussions and decisions. The emphasis on fairness and transparency aligns with the commitment to open and decentralized community structures.

**41. Regarding security, how will you structure and secure the on-chain notary address? If you will utilize a multisig, how will it be structured? Who will have administrative & signatory rights?:**
1. Building and Securing On-Chain Notary Addresses:
  - Implementing a multi-signature (Multisig) approach, such as 2-of-3 or 3-of-5 schemes, bolsters security.
  - Requiring multiple private key signatures for critical operations, enhancing resilience against potential security breaches.
2. Allocation of Management and Signing Authority:
  - Distributing management and signing authority across multiple parties to decentralize control.
  - Mitigating the risk of single points of failure by involving multiple entities in critical decision-making processes.
3. Additional IT and OpSec Safeguards:
  - Incorporating supplementary IT and Operational Security (OpSec) safeguards for comprehensive protection.
  - Conducting regular security audits, including thorough assessments of notary address configurations, access controls, and multi-signature settings.
  - Ensuring ongoing reviews to adapt to evolving security threats and maintain a robust defense against potential vulnerabilities.
By implementing these measures, the system aims to achieve higher security, resilience, and transparency, aligning with best practices in safeguarding on-chain notary addresses and associated management processes.

**42. Will you deploy smart contracts for program or policy procedures? If so, how will you track and fund them?:**
Unfortunately, currently we are unable to provide direct repository tools or existing drafts.  However, we will be allocating resources to have this in our pipelines for improvement of our pathway.
### Monetization
**43. Outline your monetization models for the services you provide as a notary allocator pathway.:**
Monetization structures may include staking and slashing collateral for clients or SPs based on compliance, as well as fees for services: application review, data prep, data clearinghouse distribution, or auditing.
Provide as much detail as possible, including specific price points for end-to-end services.
 

The monetization model aims to establish transparent and compliant service fees and collateral requirements for both customers and storage providers. Although detailed plans are not currently available, considerations can be made in the following areas:
1. Collateral Pledges:
  - Customers may be required to pledge FIL or other assets to obtain DataCap.
  - Storage Providers: Might need to pledge FIL as a deposit for participating in notary services.
2. Service Fees:
  - Review Fees: Customers may incur fees when applying for DataCap, such as review fees.
  - Data Distribution Fees: Fees could be associated with data distribution to storage providers.
3. End-to-End Service Pricing:
  - Different service modules may have independent pricing, allowing for flexibility in pricing structures.
These considerations aim to balance the needs of customers and storage providers while ensuring the sustainability and transparency of the monetization model. The details of these fees and collateral requirements will be further developed and communicated as the monetization plan is finalized.

**44. Describe your organization's structure, such as the legal entity and other business & market ventures.:**
DSPA-Asia, a community organization jointly launched by Protocol Labs and GREATER HEAT, aims to assist Asian storage providers in overcoming transformation challenges and unlocking the growth potential of their data businesses.  DSPA-Asia offers professional services such as FIL+ courses, strategic consulting, and solution support. It provides storage providers with practical experience and expert guidance, helping them become leaders in FIL+ storage services and achieve sustainable business revenue.  Our teams and offices are located in Singapore, Kuala Lumpur, and Hangzhou, China.

**45. Where will accounting for fees be maintained?:**
Through DSPA portal, where the team member that has full access as admin will be able to view the fees that are generated.   Discuss staking, burning, or releasing mechanisms, and how the Fil+ Governance and other stakeholders will be able to audit monetization. Implementing staking, burning, or releasing mechanisms in the context of Fil+ monetization can introduce additional layers of security, transparency, and accountability. Here's how these mechanisms may work, and how the Fil+ Governance and stakeholders could audit the monetization process: 1. Staking Mechanism:   - Purpose: Staking involves users depositing FIL or other assets as a commitment to the network, demonstrating a level of trustworthiness or seriousness.   - Implementation: Customers seeking DataCap or storage providers participating in notary services may stake FIL as collateral. This collateral could be used to cover potential defaults or violations.   - Auditability: The Fil+ Governance and stakeholders can audit the staking process by reviewing on-chain transactions, smart contract logs, and associated documentation. Regular reports on the status of staked assets may be provided. 2. Burning Mechanism:   - Purpose: Burning entails permanently removing tokens from circulation, often controlling supply or as a penalty for certain actions.   - Implementation: For non-compliance or breach of terms, the platform might burn a portion of the staked FIL or impose penalties, reducing the total supply.   - Auditability: The Fil+ Governance and stakeholders can audit burning activities through on-chain records, transaction histories, and reports detailing the reasons and amounts burned. 3. Releasing Mechanism:   - Purpose: Releasing involves returning staked assets or tokens to the user after fulfilling specific conditions.   - Implementation: Upon successful compliance or the completion of certain actions, staked FIL could be released back to the users.   - Auditability: Fil+ Governance and stakeholders can audit the releasing mechanism by monitoring on-chain transactions and verifying compliance with predefined criteria. 4. Audit by Fil+ Governance:   - Transparency Reports: Fil+ Governance can regularly publish reports detailing the allocation, burning, and releasing of tokens, ensuring transparency.   - On-Chain Audits: Utilize blockchain explorers and smart contract analyses to verify token movements and adherence to monetization rules.   - Community Feedback: Encourage community participation and feedback, allowing stakeholders to raise concerns or questions related to the monetization process. 5. Stakeholder Involvement:   - Participatory Governance: Involve stakeholders in decision-making processes related to staking, burning, and releasing mechanisms through proposals and voting.   - Regular Updates: Provide regular updates to stakeholders on the status of the monetization model, including any changes to mechanisms or policies. By incorporating these mechanisms and ensuring transparent, auditable processes, Fil+ Governance and stakeholders can maintain oversight and accountability in the monetization of the platform. Open communication and community involvement will play crucial roles in building trust and ensuring the success of the governance and audit mechanisms.
### Past Experience, Affiliations, Reputation
**46. If you've received DataCap allocation privileges before, please link to prior notary applications.:**
No, DSPA doesn't have prior notary applications, however DSPA has LDN and received DataCAP  DSPA 100 PiB LDN: f1a6gqgju3wote6qui3v2gxh2gk3gpqlltw4ipq7y

**47. How are you connected to the Filecoin ecosystem? Describe your (or your organization's) Filecoin relationships, investments, or ownership.:**
DSPA-Asia, a community organization jointly launched by Protocol Labs and GREATER HEAT through a joint partnership with USD500K initial investment grant, aims to assist Asian storage providers in overcoming transformation challenges and unlocking the growth potential of their data businesses.  DSPA-Asia offers professional services such as FIL+ courses, strategic consulting, and solution support. It provides storage providers with practical experience and expert guidance, helping them become leaders in FIL+ storage services and achieve sustainable business revenue.  These may include Storage Providers, existing client applications, developer service providers, and more.  As of December 2023, DSPA has more than 100+ verified SP members with a total of more than 390+ Storage Power (QAP). There are few leading SP within DPSA, such as NWG, ND Labs, Aligned, and GLIF. The following is the few of Storage Providers onboarded through DSPA.  Chenzhuo, Node ID: f02131881 Xu Lingchao Node ID: f01046069 , f02259777 , f02093396 安徽飞舸信息技术有 Node ID: f01046069 , f02259777 , f02093396 MICHELLE Node ID: f02368987 , f02058333 DSPA project, concentrating on the transformation and upgrade of Asian storage providers. Please refer to the following websites for more information:  https://dspa-asia.io/#home  Since the launch of DSPA in March 2023, DSPA has been actively building the Storage Providers community, and Filecoin ecosystem. DSPA has been promoting and publishing Filecoin community related activities on Youtube, Twitter, Facebook, Medium and other platform channels, providing some of the links below.  https://dspa-asia.io  DSPA-Asia | Youtube DSPA-Asia BootCamp Singapore 2023 - Juan Benet interviewed DSPA Asia 2023 Singapore BootCamp Highlights Introducing DSPA-Asia DSPA-Asia Boot Camp 2023 Highlights  DSPA-Asia | LinkedIn https://www.linkedin.com/posts/dspa-asia_filecoin-decentralized-crypto-activity-7150378254401474561-pAiw?utm_source=share&utm_medium=member_desktop https://www.linkedin.com/posts/dspa-asia_filecoin-github-dspa-activity-7150377656897650688-Wh1j?utm_source=share&utm_medium=member_desktop https://www.linkedin.com/posts/dspa-asia_filecoins-robust-tokenomics-activity-7150739351285436416-GaFc?utm_source=share&utm_medium=member_desktop  DSPA-Asia | Medium https://medium.com/@DSPA-Asia/unraveling-the-role-of-providers-deals-and-sectors-in-mastering-filecoins-storage-model-48e9072eb2af https://medium.com/@DSPA-Asia/filecoins-allocator-pathways-empowering-a-diverse-and-decentralized-storage-network-b662a9a7c13e https://medium.com/@DSPA-Asia/5-compelling-reasons-to-join-the-decentralized-storage-provider-accelerator-asia-fe1df9779523  Github Issue: Asian Filecoin Storage Provider Convertor BootCamp - Large Amount Datacap application is on t  DSPA-Asia | Twitter https://x.com/DSPA_Asia/status/1646698730685607936?s=20 https://x.com/DSPA_Asia/status/1744613039033483679?s=20 https://x.com/DSPA_Asia/status/1739925844334923934?s=20 https://x.com/DSPA_Asia/status/1725402585732108353?s=20 https://x.com/DSPA_Asia/status/1724683125262033190?s=20 https://x.com/FilFoundation/status/1711441571982274749?s=20 https://x.com/DSPA_Asia/status/1706659888254812356?s=20 https://x.com/DSPA_Asia/status/1701550048994341021?s=20 https://x.com/DSPA_Asia/status/1701477932022333465?s=20 https://x.com/DSPA_Asia/status/1701070283468321258?s=20 https://x.com/DSPA_Asia/status/1687415946452049920?s=20

**48. How are you estimating your client demand and pathway usage? Do you have existing clients and an onboarding funnel?:**
In the first quarter, DSPA-Asia attracted 56 applications from storage providers interested in becoming residents through the Cohort#1boot camp, held in Hong Kong.  After the Cohort#2 boot camp scheduled in Singapore, 23 storage providers with 60 nodes have officially registered within DSPA-Asia's backend management system, making them official beneficiaries of DSPA-Asia.  Regarding the growth of RawBytePower, DSPA-Asia has already directly contributed to the Filecoin network by creating an increment of 9,410 TiB(approximately 94.10 PiB QAP) by the end of 2023. This data can be found on the homepage of https:////admin.dspa-asia.io/home/  Through the existing client and onboarding funnel, and the DataCap that has been distributed, we are confident we can further improve the DataCap usage by SP through the DSPA Filecoin Allocator Pathway

**Comment by pandacrypto** [comment]
Hi @Kevin-FF-USA @Filplus-govteam

<img width="804" alt="Screenshot 2024-03-07 at 4 25 41 PM" src="https://github.com/filecoin-project/notary-governance/assets/52273713/dd168fda-b9da-4c8e-acd6-78eb28846712">

Update the ledger address as required: f1xdpvmkm75sinulbz5j73wseupq4equmchxonvjy

**Comment by pandacrypto** [comment]
<img width="1438" alt="image" src="https://github.com/filecoin-project/notary-governance/assets/52273713/63a6f252-83e2-4986-9682-666c21567855">


The ledger address in the application  has been updated to match the address in the submitted airtable form, thank you!

**Comment by kevzak** [comment]
## Datacap Request for Allocator
#### Address
> f2a2ssk6ijg2nnjoewazyjxwqu77uahe5o6xrfvoy
#### Datacap Allocated
> 5PiB

**Comment by Kevin-FF-USA** [comment]
Hi @pandacrypto

On the next Fil+ Allocator meeting we will be going over each refill application. Wanted to ensure you were tracking the review discussion taking place in https://github.com/filecoin-project/Allocator-Governance/issues/21.

If your schedule allows, recommend coming to the May 28th meeting to answer/discuss the issues raised in the recent distributions. This will allow you to faster address - or, the issue in Allocator Governance for ongoing written discussion.

Warmly,
-Kevin
https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles

**Comment by galen-mcandrew** [comment]
## Datacap Request for Allocator
#### Address
> f2a2ssk6ijg2nnjoewazyjxwqu77uahe5o6xrfvoy
#### Datacap Allocated
> 10PiB

**Comment by galen-mcandrew** [comment]
https://github.com/filecoin-project/Allocator-Governance/issues/21

**Comment by galen-mcandrew** [comment]
https://filfox.info/en/message/bafy2bzaced6rmfjmvitcrubfwnot52efig6zg2akktlkdknuqzsz77fliv53q?t=4

**Comment by galen-mcandrew** [comment]
## Datacap Request for Allocator
#### Address
> f2a2ssk6ijg2nnjoewazyjxwqu77uahe5o6xrfvoy
#### Datacap Allocated
> 20PiB
