### ISSUE TITLE
v5 Notary Allocator Application: TOP POOL

### ISSUE THREAD

**Issue by TOPPOOL-LEE** [filecoin-project/notary-governance#1046]
# v5 Notary Allocator Application

To apply to be an allocator, organizations will submit one application for each proposed pathway to DataCap. If you will be designing multiple specific pathways, you will need to submit multiple applications. 

Please complete the following steps:
# 1. Fill out the information below and create a new GitHub Issue

1. Notary Allocator Pathway Name (This can be your name, or the name of your pathway/program. For example "E-Fil+"):TOP POOL
3. Organization Name:TOP POOL
4. On-chain address for Allocator (Provide a NEW unique address. During ratification, you will need to initialize this address on-chain): f1grjkkw3p5hw3vx5gonvppkkzpcgmu4xnwfm7sli
5. Country of Operation (Where your organization is legally based): Singapore
6. Region of Operation (What region will you serve?):   All Regions
7. Type of Allocator, diligence process: (Automated/programmatic, Market-based, or Manual (human-in-the-loop at some phase): Market-based and Manual
9. DataCap requested for allocator for 12 months of activity (This should be an estimate of overall expected activity. Estimate the total amount of DataCap you will be distributing to clients in 12 months, in TiB or PiB): 100PiB

# 2. Access allocator application (download to save answers)
Click link below to access a Google doc version of the allocator application that can be used to save your answers if you are not prepared to fully submit the application in Step 3. https://docs.google.com/document/d/1-Ze8bo7ZlIJe8qX0YSFNPTka4CMprqoNB1D6V7WJJjo/copy

# 3. Submit allocation application 
Clink link below to access full allocator questionnaire and officially submit your answers:
https://airtable.com/appvyE0VHcgpAkt4Z/shrQxaAIsD693e1ns

Note: Sections of your responses WILL BE posted back into the GitHub issue tracking your application. 
The final section (Additional Disclosures) will NOT be posted to GitHub, and will be maintained by the Filecoin Foundation. 
Application information for notaries not accepted and ratified in this round will be deleted.

**Comment by Kevin-FF-USA** [comment]
Hi @liou38469 
Wanted to let you know this application has been received. Also verifying you have submitted the Airtable form with your detailed Allocator plan - the public answers will be posted in a thread below soon. If you have any questions - please let me know.

**Comment by Filplus-govteam** [comment]
### Basic Information
**1. Notary Allocator Pathway Name:**
TOP POOL

**2. Organization:**
TOP POOL

**3. On Chain Address for Allocator:**
f1grjkkw3p5hw3vx5gonvppkkzpcgmu4xnwfm7sli

**4. Country of Operation:**
Singapore

**5. Region(s) of operation:**
Asia minus GCR, Greater China, Europe, North America, Japan

**6. Type of Allocator:**
Market-based

**7. DataCap requested for allocator for 12 months of activity:**
100PiB

**8. Is your allocator providing a unique, new, or diverse pathway to DataCap? How does this allocator differentiate itself from other applicants, new or existing?:**
TOPPOOL is a resource optimization platform dedicated to connecting the blockchain and metaverse industries. We joined the Filecoin network in 2019, 2022, we established a FIL+-based technical department with the goal of bringing green, valuable, and efficient data storage to the Filecoin network. We have developed our own data processing system, which has helped numerous SPs worldwide upgrade from CC to DC.

The DataCap allocator provided by TOPPOOL offers comprehensive, unique, diversified, and traceable paths:

Comprehensive due diligence: Our due diligence process includes customer submission of application forms, contract signing, collaboration with third-party KYB companies, and, if the customer is in the same country as us, on-site visits to the customer's company. Comprehensive due diligence is a prerequisite for customers to obtain DC.

Diversified DataCap options: We provide various DataCap options, allowing enterprise-level customers, customers with public datasets, and individuals with substantial data to submit applications to us.

Unique pricing mechanism: We have established a unique pricing mechanism based on the customer's data type, the number and geographical locations of SPs, retrieval capabilities, and pledge duration.

Transparency and traceability: We create a TOPPOOL GitHub project group where customers can submit their applications. Both we and the community can monitor customer usage at any time, ensuring high transparency and traceability.

**9. As a member in the Filecoin Community, I acknowledge that I must adhere to the Community Code of Conduct, as well other End User License Agreements for accessing various tools and services, such as GitHub and Slack.:**
Acknowledge
### Client Diligence
**10. Who are your target clients?:**
Small-scale developers or data owners, Enterprise Data Clients, Individuals learning about Filecoin

**11. Describe in as much detail as possible how you will perform due diligence on clients.  If you are proposing an automated pathway, what diligence mechanism will you use to determine client eligibility?:**
Generally, the more DC the customer applies for, the stricter about diligence mechanism. We verify customers from various perspectives, including their establishment time, main business operations, and assessment of their data volume.

Firstly, customers fill out the GitHub application form, through which we obtain a significant amount of information and details about the customer.

Secondly, we communicate with customers via email and Slack, requesting additional information such as:

1. Entity information: This includes registration certificates, company registration documents, or information about the entity; government-issued identification numbers for the entity.

2. Authorized signatory information: Evidence that the authorized signatory represents the applying entity.

3. Commitment letter: A commitment from the company to store data on the Filecoin network.

After conducting the initial steps and investigations, we use tools like WikiGloba and x315 to examine the customer's situation. We also verify the customer's data using third-party business databases such as Twitteraudit and Dun & Bradstreet.

Lastly, we may engage third-party KYB (Know Your Business) companies to conduct due diligence on the customer.

**12. Please specify how many questions you’ll ask, and provide a brief overview of the questions.:**
https://github.com/liou38469/TOPPOOL/issues/new/choose

Can you introduce yourself? Where can I find you online? 
If you represent an organization, what is the name, nature, registration country, time since inception?
What is your use case for the DataCap being requested?
Provide the F1 address accepting DataCap.
Request the total amount of DataCap.
How much DataCap is allocated per week?
Which region do you plan to use DataCap in?
List the cooperating SPs.
In which region do you intend to use the DataCap?
How long the data is expected to be stored？
Did you ask SP to provide the fast retrival to the network?
How will you handle the data?
List the data processing platforms.
Is there anything I could improve to serve you better in future allocations?
Can you confirm that you will follow the Fil+ guideline？

**13. Will you use a 3rd-party Know your client (KYC) service?:**
Yes, we may utilize third-party services for customer verification. KYC services are commonly used procedures to verify the identity of customers and conduct anti-money laundering and counter-terrorism financing checks to ensure compliance with relevant regulations and compliance requirements.

KYC services typically cover the following aspects and areas:

1. Identity verification: Verifying customer identity information such as name, address, nationality, etc.

2. Business verification: Validating the registered information, organizational structure, ownership structure, etc., of the business.

3. Anti-money laundering and counter-terrorism financing checks: Conducting risk assessments and background checks to ensure customers are not involved in money laundering, terrorist financing, or other illegal activities.

4. Regulatory compliance: Ensuring customers comply with applicable regulatory requirements and compliance standards.

Different countries have different information query websites and KYC service providers. We will select and collaborate with reputable KYC service providers to ensure the customer verification process is accurate, comprehensive, and compliant with regulatory requirements. When integrating data, we will ensure that data exchange and sharing with KYC service providers adhere to best practices for privacy and data protection.

**14. Can any client apply to your pathway, or will you be closed to only your own internal clients? (eg: bizdev or self-referral):**
Any customer can apply.We will make our application process and channels public so that everyone can submit applications to us

**15. How do you plan to track the rate at which DataCap is being distributed to your clients?:**
We plan to use filplus-checker and datacapstats.io as primary tools to track the rate of DataCap distribution to customers.  filplus-checker is a tool that helps monitor and track the distribution of DataCap. It provides real-time data analysis and statistics, allowing us to understand the rate of DataCap distribution and its allocation to customers.  datacapstats.io is another tool that provides detailed statistical data and charts about DataCap distribution. It includes information such as distribution rate, allocation volume, and remaining amount. These data can help us better track and manage the distribution process of DataCap.  Additionally, about https://www.bytebase.cn/#/searchDatacap, we can quickly check the balance of customers' F1 addresses. This tool provides real-time balance information about customers' F1 addresses, enabling us to stay updated on customers' DataCap usage.  With these tools and resources, we will be able to effectively track and monitor the rate at which DataCap is distributed to customers, ensuring its fair and efficient allocation and utilization.
### Data Diligence
**16. As an operating entity in the Filecoin Community, you are required to follow all local & regional regulations relating to any data, digital and otherwise. This may include PII and data deletion requirements, as well as the storing, transmit:**
Acknowledge

**17. What type(s) of data would be applicable for your pathway?:**
Public Open Dataset (Research/Non-Profit), Public Open Commercial/Enterprise, Private Commercial/Enterprise, Private Non-Profit/Social Impact

**18. How will you verify a client’s data ownership? Will you use 3rd-party KYB (know your business) service to verify enterprise clients?:**
In order to validate the ownership of customer data, we will implement a series of measures and consider utilizing third-party KYB services to verify the corporate clients.

The following are the general steps we take to verify customer data ownership:

Document Verification: We request customers to provide official documents such as company registration certificates, business licenses, and other relevant legal documents. These documents are used to confirm the customer's business entity and legal status.

Source of Data Confirmation: We ask customers to provide relevant information about the generation or acquisition of the data to demonstrate their legal access and ownership of the data. This may include contracts, licenses, authorization documents, or other legal files.

Data Comparison in Databases: We conduct checks and compare the data within our databases to ensure that the customer's data is not downloaded from the internet.

KYB Services: We may utilize third-party KYB services to further validate the authenticity and data ownership of corporate clients. KYB services provide comprehensive information about the company's background, ownership structure, operational licenses, and compliance, ensuring the legality and data ownership of the customers.

Internal Auditing: We conduct internal audits and investigations to ensure the consistency and authenticity of the information and documents provided by the customers. This may involve further communication and verification with the customers.

By following these steps and utilizing third-party KYB services, we are able to comprehensively verify the ownership of customer data. This helps ensure that the data we handle is legal, trustworthy, and compliant with relevant laws and regulations.

1. For global company information queries:
   - WikiGlobal: www.wikiglobal.com
   - x315: https://www.x315.cn/searchworld

2. For specific country information queries:
   - China: Qichacha: https://www.qcc.com/;  Tianyancha : https://www.tianyancha.com
   - United States: Wysk B2B Hub: http://www.wysk.com/index/
   - Singapore: ACRA website: https://www.acra.gov.sg/home/
   - United Kingdom: BVI Financial Services Commission: http://www.bvifsc.vg/en-gb/regulatedentities.aspx

**19.  How will you ensure the data meets local & regional legal requirements?:**
To ensure that customer data complies with regional and local legal standards, our process includes:  1. Legal Compliance Assessment: We establish a professional legal team with expertise in data protection and privacy laws relevant to each operating region. They assess local legal requirements and ensure that data processing and storage methods comply with regulations.  2. Data Classification and Labeling: Our technical engineers classify data based on sensitivity and legal requirements and apply appropriate labels. This helps determine suitable handling and protection measures and ensures compliance with legal standards in different jurisdictions.  3. User Commitment and Transparent Communication: We engage in communication with customers to understand if their data contains sensitive or special categories of information. We request customers to provide commitments that the data stored in the system is public, compliant, and adheres to applicable legal standards.  4. Contracts and Agreements: We enter into contracts or agreements with customers, clearly defining responsibilities and obligations, including provisions for data protection and privacy. This ensures both parties comply with local legal requirements and provides legal protection.  5. Security Measures and Technical Safeguards: We implement appropriate security measures, such as encryption, access controls, and data backups, to protect the confidentiality and integrity of data. We follow security best practices and industry standards to ensure data security.  It is important to note that ensuring compliance with regional and local legal standards is a complex process, and specific measures and procedures may vary depending on the circumstances. It is advisable to seek professional legal advice for specific legal issues and compliance requirements.

**20. What types of data preparation will you support or require?:**
We can provide customers with free technical support, including data preparation, boost optimization, and code packaging.   Regarding data processing, we offer services for physically transferring data to our devices, as well as data transfer through APIs. If the customer and service provider (SP) are in the same region, using hard drive transfer can be a good option.  Overall, we tailor our services to meet the specific needs of our customers.

**21. What tools or methodology will you use to sample and verify the data aligns with your pathway?:**
Generally, we assist customers with data preparation. However, if customers choose to handle data preparation themselves, we employ the following methods to verify the data:  1. Data retrieval and sampling tools: We use data retrieval tools (such as Lassie Fetch) to retrieve data from customers. We also employ common data sampling methods like random sampling or stratified sampling to obtain a subset of data for validation. We then compare it with the metadata and analyze for any signs of sector misuse.  2. Data comparison tools: We utilize open-source data comparison tools, such as data validation and hash algorithms, to determine if the data types and content match. These tools help ensure data integrity and accuracy.  3. Establish continuous monitoring: We retain each sampled dataset until the LDN (Life Data Normalization) process is completed. This enables us to establish a regular monitoring mechanism and risk assessment system, allowing us to promptly identify and address any misuse or anomalies. 
### Data Distribution
**22. How many replicas will you require to meet programmatic requirements for distribution?:**
5+

**23. What geographic or regional distribution will you require?:**
We have provided 30P DC for SPs, they located in various regions such as Hong Kong, Singapore, Japan, Vietnam, and the United States.  We require SP distribution across three different continents and five different countries, with no single SP exceeding a 25% share.  Regarding regions, all areas are considered equal. However, if some countries have restrictions on mining activities, we may not collaborate with SPs based in those countries.

**24. How many Storage Provider owner/operators will you require to meet programmatic requirements for distribution?:**
5+

**25. Do you require equal percentage distribution for your clients to their chosen SPs? Will you require preliminary SP distribution plans from the client before allocating any DataCap?:**
Before allocating DC to customers, we require them to provide an allocation plan.  From the perspective of data security and backup, SPs need to store the same data.  However, we will consider the number of cooperating SPs and require that at least 4 of the SPs have an equal distribution proportion.  For example, if a customer collaborates with 6 SPs, and 4 of them have the same storage capacity, the data stored will be the same. In this case, data security can be ensured. We pay close attention to the customer's SP allocation plan.  Yes, we will utilize the template provided at https://github.com/liou38469/TOPPOOL/issues/new/choose to track the customer's allocation plan.

**26. What tooling will you use to verify client deal-making distribution?:**
Datacapstats.io and bot

**27. How will clients meet SP distribution requirements?:**
1. Determine the number of collaborating SPs: First, the customer needs to determine how many SPs they plan to collaborate with. We require a minimum of 4 SPs, ensuring that these 4 SPs have the same storage capacity.  2. SP selection and negotiation: The customer needs to evaluate different SPs and choose partners that meet their requirements. This includes considering factors such as the SP's geographical location, reliability, data center facilities, and security. The customer can negotiate with potential SPs to discuss collaboration details and allocation plans.  3. Develop an allocation plan: The customer needs to create a detailed allocation plan to meet the requirements for SP distribution. This includes determining the storage capacity of each SP, data distribution methods, as well as data backup and recovery strategies.  4. Provide the allocation plan to us: Once the customer has developed the allocation plan, they can provide it to us for review and follow-up. The application form submitted by the customer on GitHub can be used as a tool for submitting, allocating, and tracking the plan.

**28. As an allocator, do you support clients that engage in deal-making with SPs utilizing a VPN?:**
We do not support SPs using VPNs, and we utilize an external platform to determine if SPs using VPN services. One key tool in this process is the VPN/IP Address Check provided by IPQualityScore, which can be accessed at https://www.ipqualityscore.com/vpn-ip-address-check. Additionally, we also utilize tools like MaxMind (https://www.maxmind.com) to enhance the verification process.
### DataCap Allocation Strategy
**29. Will you use standardized DataCap allocations to clients?:**
No, client specific

**30. Allocation Tranche Schedule to clients::**
The policies by FIL+ and the bot's settings are reasonable.
 
According to the bot's rules, the maximum allocation for the first round is 512T, the second round is 1P, and the third round is 2P, with a maximum limit of 2P.
 
We may consider setting the allocation as follows: 256T for the first round, 512T for the second round, 1P for the third round, and 2P for the fourth round, with a maximum limit of 2P.
 
The total allocation a customer can receive should not exceed 15PiB, and the allocation for a single request should not exceed 2PiB.

**31. Will you use programmatic or software based allocations?:**
Yes, standardized and software based

**32. What tooling will you use to construct messages and send allocations to clients?:**
The https://filplus.fil.org/#/ is a suitable tool. we can also manually construct messages if needed.

**33. Describe the process for granting additional DataCap to previously verified clients.:**
We will use the Filplus SSA Bot (https://github.com/filecoin-project/filplus-ssa-bot) to monitor the remaining DataCap and trigger subsequent allocation requests. The Filplus SSA Bot is part of the Filplus program and is designed to enhance the efficiency and effectiveness of the LDN program. It features automated scanning, where it scans all active DataCap requests every 12 hours. For requests that have consumed over 75% of the allocated DataCap in the previous allocation, the bot triggers a new allocation process.  We will use Bytebase and GLIF to verify the DC balance of customer addresses. If the Filplus SSA Bot is not functioning, but the customer's remaining balance is less than 15%, we will manually grant DC to the customer.

**34. Describe in as much detail as possible the tools used for: • client discoverability & applications • due diligence & investigation • bookkeeping • on-chain message construction • client deal-making behavior • tracking overall allocator health • disput:**

1. Customer Discoverability and Engagement:
  - Company Website: Customers can learn about the company's products and services through the company website (http://poolhub.top/). The website provides contact information, and customers can reach out to the company via email.
  - Social Media Platforms: The company can utilize social media platforms such as Twitter, LinkedIn, Facebook, etc., to enhance customer discoverability.

2. Due Diligence and Survey:
  - Survey Forms and Questionnaires: We regularly reach out to customers, including phone calls and one-on-one communication on Slack, to collect customer feedback and opinions.
  - Data Analytics Tools: By using data analytics tools like Google Analytics, the company can analyze customer behavior and preferences to better understand customer needs.

3. Bookkeeping:
  - Accounting Software: The company utilizes accounting software QuickBooks to help record and manage financial data, including income, expenses, invoices, etc.
  - Spreadsheets: Microsoft Excel is used for simple financial recording and tracking.

4. On-chain Message Construction:
  - Blockchain Platform: Use Lotus for on-chain messaging.

5. Customer Transaction Behavior and Overall Allocator Health Tracking:
  - Transaction Recording System: GitHub serves as our most important recording system, reflecting communication with customers, tracking customer allocations.

6. Dispute Discussion and Resolution:
  - Communication and Collaboration Tools: GitHub and Slack are the primary communication and collaboration tools, which also have bookkeeping functionalities.

7. Community Updates and Communication:
  - Email Communication: Community updates and communication are conducted through channels such as GitHub, Slack, Telegram, and email.
### Tools and Bookkeeping
**35. Will you use open-source tooling from the Fil+ team?:**
Yes, we will use the open-source tools provided by FIL+ team:  Technical processing: We use Singularity. Message construction: We use https://filplus.fil.org/#/. Checking customer allocations: We use SSABot.

**36. Where will you keep your records for bookkeeping? How will you maintain transparency in your allocation decisions?:**
We will use GitHub as the primary platform for storing bookkeeping records, which include customer applications, basic information, total DC allocations received, and important decisions. This ensures transparency and auditability of the records.

For sensitive due diligence and customer information, we will follow appropriate privacy and security measures. These pieces of information may not be fully disclosed, but we will provide partial information to achieve community transparency and ongoing auditing. We will also provide information as requested by the Fil+ governance team to address disputes or conduct audits.

Private communication channels such as email, direct messages on Slack, and phone conferences may involve some confidential discussions and exchanges. However, important decisions and relevant justifications will be recorded and shared on GitHub.

In the event of a dispute, we will provide necessary private information to the governance team and engage in communication and resolution with them. This ensures that disputes are handled properly and maintains transparency and accountability.
### Risk Mitigation, Auditing, Compliance
**37. Describe your proposed compliance check mechanisms for your own clients.:**
The compliance check mechanism we provide for our clients is designed to responsibly allocate and utilize DataCap in order to maintain the integrity of the storage market.

1. Initial due diligence and trust assessment: For new clients, we conduct comprehensive due diligence to evaluate their credibility and the legitimacy of their data storage needs. This includes verifying business registration, financial status, and data processing practices. High-risk clients are identified and required to undergo additional due diligence.

2. DataCap distribution tracking: We utilize tools such as datacapstats.io/CID check robots to monitor the distribution of DataCap. This tool helps track which CIDs (Content Identifiers) are stored in order to ensure consistency between storage and allocated DataCap. We closely monitor, report, and discuss metrics such as allocation frequency, size of DataCap allocated per distribution, and client request frequency on a weekly basis.

3. Downstream usage monitoring: We track clients' downstream usage using tools like the Retrievability Bot. This tool helps ensure that stored data is retrievable and aligns with the intended use of DataCap.

4. Customer demographics and time-based analysis: We collect and analyze data regarding client industries, scale, and storage behavior. During the same time period, we monitor and report metrics such as the duration of DataCap usage and data retention periods on a weekly basis to identify any abnormal patterns.

5. Transparency and community involvement: We maintain transparency in our operations and decision-making related to DataCap allocation. We regularly share updates and summaries of our activities with the community through channels like GitHub. We have a low tolerance for non-compliance as we are committed to upholding honesty and fairness in the storage market.

We do have a relatively low tolerance for errors made by new clients. However, we will still carefully listen to their explanations and consider all circumstances before deciding whether to continue working with them. We prioritize client integrity and compliance, so if a client can provide a reasonable explanation and demonstrate a willingness to rectify the error, we may consider giving them a second chance. However, we also weigh the risks and the sustainability of the partnership to ensure the effective implementation of our compliance check mechanism. The final decision will be based on a comprehensive assessment of factors such as the client's behavior, attitude, and willingness to cooperate.

**38. Describe your process for handling disputes. Highlight response times, transparency, and accountability mechanisms.:**
Our DataCap allocation dispute resolution process focuses on timely response, transparency, and establishing effective accountability mechanisms. This ensures that disputes are resolved fairly, objectively, and effectively, while maintaining trust and cooperative relationships.

1. Response Time: We prioritize timely handling of disputes. Once notified of a DataCap allocation dispute, we will initiate the resolution process as soon as possible. We aim to follow up and address the dispute within 24 hours. We will gather all relevant information and documents related to the DataCap allocation dispute, including DataCap allocation records, communication logs, agreements, contracts, evidence, etc. We will carefully analyze this information and conduct an objective and comprehensive assessment to understand all aspects and underlying causes of the dispute.

2. Transparency: We are committed to maintaining a high level of transparency. When handling DataCap allocation disputes, we actively engage with all parties involved and provide detailed explanations and information. We encourage the use of channels such as GitHub, Slack public channels, and Zoom meetings as central platforms for resolving disputes. This ensures that all decisions, discussions, and outcomes are documented.

3. Accountability Mechanisms: We have established clear accountability mechanisms to ensure proper handling of DataCap allocation disputes. If any party is found to have been at fault, their DC quota will be reduced.

We always maintain an open and transparent approach and welcome guidance from the governance team.

**39. Detail how you will announce updates to tooling, pathway guidelines, parameters, and process alterations.:**
To announce updates regarding tool, pathway guidelines, parameters, and process changes, we will take the following measures:  1. Announcement Notifications: We will post announcement notifications on relevant public channels in Slack to inform all stakeholders about the changes to tools, pathway guidelines, parameters, and processes. This will also include posting announcements on our official website, social media platforms, email newsletters, and forums.  2. Detailed Explanations: We will provide detailed explanations on GitHub to clarify the reasons, purposes, and impacts of the changes to tools, pathway guidelines, parameters, and processes.  3. Training and Support: If necessary, we will offer training and support to help users adapt to the changes. This may include online training courses, video tutorials, and online Q&A sessions. I will primarily use Zoom as the tool for these activities.  4. Involvement of the Fil+ Governance Team: For significant procedural changes or updates, we will engage in communication and consultation with the Fil+ Governance Team. They will participate in assessing the scope and impact of the changes and evaluate them based on predefined criteria.  We will strive to ensure that the announcements regarding updates to tools, pathway guidelines, parameters, and processes are comprehensive, accurate, and easy to understand.

**40. How long will you allow the community to provide feedback before implementing changes?:**
Before implementing changes, we will actively engage with community members and provide them with opportunities to provide feedback. Here are the steps we will take:

Sufficient Time: We will allow community members ample time to understand the details of the changes and provide feedback. The duration of this feedback period will depend on the significance of the updates, ranging from approximately one month to longer durations. Not all updates will be implemented without the agreement of the community and the governance team.

Multiple Feedback Channels: We will provide various channels for receiving feedback to accommodate different preferences of community members. This may include online feedback forms, email feedback, GitHub proposal feedback, and Slack discussions.

Consideration and Evaluation of Feedback: We will carefully consider the feedback and suggestions provided by community members. We will assess the reasonableness, relevance, and feasibility of the feedback while balancing various factors. We may schedule Zoom meetings or organize offline events to facilitate further discussions and gather additional input.

**41. Regarding security, how will you structure and secure the on-chain notary address? If you will utilize a multisig, how will it be structured? Who will have administrative & signatory rights?:**
Using Ledger to build and protect my notarization address.
I have sole responsibility for management and signing authority. I am the founder and technical lead of TOPPOOL, Anil Kumar.

**42. Will you deploy smart contracts for program or policy procedures? If so, how will you track and fund them?:**
We plan to utilize FIL+'s open-source tools such as filplus-saa-bot, AC bot, CID verification bot, and retrieval bot.
### Monetization
**43. Outline your monetization models for the services you provide as a notary allocator pathway.:**
The price of DC is influenced by various factors, such as the price of FIL, e24h Average Mining Reward, gas fees and more.

Based on my understanding, the current market price ranges from approximately 4000 to 5000 U/PiB.

The core of DC is to subsidize customers with valuable data. To attract customers to store their valuable data on the Filecoin network, we provide subsidies based on the quality of their data, which is approximately 1000-1500 U/PiB.

Therefore, the pricing is set at 3000-3500 U/PiB.

These fees primarily cover hardware costs, data center expenses, bandwidth costs, and labor costs.

Additionally, each year we will select an outstanding customer and service provider (SP) and reward them with 2000 U each, totaling 4000 U.


**44. Describe your organization's structure, such as the legal entity and other business & market ventures.:**
 TOP POOL is a leading Filecoin storage service provider that also specializes in BTC and ETC mining. It is comprised of three founders: Anil Kumar, Michael Wang, and Sophia Lee. We have extensive experience and expertise in the field of data storage and are committed to providing efficient, secure, and reliable storage solutions for our clients.  Over the past few years, TOP POOL has achieved significant milestones:  - 2018: TOP POOL was established and became an important participant in the Filecoin ecosystem. - 2019-2020: We continuously engaged in technological innovation and optimization to enhance storage efficiency and data security, providing our clients with more reliable and high-performance storage solutions. During these years, we actively participated in major IPFS and Filecoin forums, delivering speeches, engaging in client negotiations, and more. - 2023: We developed our own DC processing and development system, successfully loading 40P of DC into the Filecoin network. Additionally, we possess over 150PiB of computational power. This not only positions us as a technical service provider in the Filecoin field but also establishes us as a significant storage provider.  Name: Anil Kumar Position: Co-founder, Chief Technology Officer Resume: Anil Kumar is one of the co-founders of TOP POOL and brings extensive experience in technology and management. He has deep research and practical experience in the fields of data storage and distributed systems. Prior to joining TOP POOL, he held senior technical positions in renowned technology companies and led the development and implementation of multiple large-scale projects. He possesses remarkable abilities in developing Filecoin storage solutions, including the development of DC processing systems and distribution systems.  Name: Sophia Lee Position: Co-founder, Chief Marketing Officer Resume: Sophia Lee is one of the co-founders of TOP POOL and specializes in marketing and business development. She is well-versed in the Filecoin ecosystem and understands customer needs and market trends. Leading the team, she spearheads marketing strategies to enhance TOP POOL's brand influence and drive business growth.  Name: Michael Wang Position: Co-founder, Technical Engineer Resume: Michael Wang is one of the co-founders of TOP POOL and serves as the primary technical engineer. With excellent development capabilities and a strong synergy with Anil Kumar, he is responsible for developing features such as DC renewal, expired order reclamation, and optimizing the boost algorithm.  Through innovation and the collective efforts of our team, TOP POOL will continue to drive the development of blockchain storage technology, providing exceptional storage solutions to our clients and playing a crucial role in the industry.

**45. Where will accounting for fees be maintained?:**
We usually use a USDT receiving address and can provide public records of our transactions. Our communication with clients regarding payments is documented and stored on platforms such as Slack, Telegram (tg), and email. If the governance team requires access to these records, we are willing to communicate and share them.
### Past Experience, Affiliations, Reputation
**46. If you've received DataCap allocation privileges before, please link to prior notary applications.:**
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2152 https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2213 https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2108

**47. How are you connected to the Filecoin ecosystem? Describe your (or your organization's) Filecoin relationships, investments, or ownership.:**
We not only focus on providing technical services but also invest in Filecoin mining . As a SP, we have assisted many other SPs in transitioning from CC to decentralized DC storage solutions. Moreover, we have played a role in promoting enterprise clients to store their data on the Filecoin network.  In 2019-2020, we made investments and organized numerous Filecoin conferences. These events provided a platform for knowledge sharing, networking, and fostering collaboration within the Filecoin community. Additionally, in 2022-2023, we actively participated in several Filecoin conferences organized by PL.

**48. How are you estimating your client demand and pathway usage? Do you have existing clients and an onboarding funnel?:**
 We have contributed 400P of storage to the Filecoin network and served over 30 SPs. We have extensive experience in serving clients within the network. Currently, our onboarding channel is through emails on our official website. We review and evaluate each client during the onboarding process.  After the transition to v5, clients will be required to submit their information through https://github.com/liou38469/TOPPOOL/issues/new/choose. GitHub will become the primary onboarding channel for clients.

**Comment by kevzak** [comment]
## Datacap Request for Allocator
#### Address
> f2xhj666jsewrgjd53hqlijhc5edrezrkortncjpa
#### Datacap Allocated
> 5PiB

**Comment by Kevin-FF-USA** [comment]
Hi @TOPPOOL-LEE

On the next Fil+ Allocator meeting we will be going over each refill application. Wanted to ensure you were tracking the review discussion taking place in https://github.com/filecoin-project/Allocator-Governance/issues/16.

If your schedule allows, recommend coming to the May 28th meeting to answer/discuss the issues raised in the recent distributions. This will allow you to faster address - or, the issue in Allocator Governance for ongoing written discussion.

Warmly,
-Kevin
https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles

**Comment by TOPPOOL-LEE** [comment]
Hello, @Kevin-FF-USA we have participated in the meeting on May 28 and spoke at the meeting, thank you.Some SPs use the Venus system, resulting in SP retrieval being unavailable in Spark. We will not cooperate with these SPs in the future.

**Comment by galen-mcandrew** [comment]
## Datacap Request for Allocator
#### Address
> f2xhj666jsewrgjd53hqlijhc5edrezrkortncjpa
#### Datacap Allocated
> 10PiB

**Comment by galen-mcandrew** [comment]
https://filfox.info/en/message/bafy2bzacebkbhj3s7g4k34x4qkwj5kcyud6fuu6yc6nu7vsknxnaj5p6tzyl4

**Comment by galen-mcandrew** [comment]
## Datacap Request for Allocator
#### Address
> f2xhj666jsewrgjd53hqlijhc5edrezrkortncjpa
#### Datacap Allocated
> 10PiB

**Comment by galen-mcandrew** [comment]
## Datacap Request for Allocator
#### Address
> f2xhj666jsewrgjd53hqlijhc5edrezrkortncjpa
#### Datacap Allocated
> 5PiB

**Comment by galen-mcandrew** [comment]
Approval: bafy2bzaceasrv544tr22ibjngcjxdwigde3l3l5o673i46ze4meufkpxzw3u2
