### ISSUE TITLE
Formation of a tribunal of Filecoin-Plus stakeholders for dispute resolution.

### ISSUE THREAD

**Issue by NSC-FIL** [filecoin-project/notary-governance#105]
## Issue Description
Clear guidelines to the rules regarding Filecoin-Plus should been established for example whether self-dealing should be allowed (see filecoin-project/notary-governance#98) and other issues that affect the health of the Filecoin ecosystem.

Once Filecoin-Plus rules have been agreed upon and published (preferably in a summary format), the proposal is to form a rotating or elected tribunal (i.e. a Notary, a rep from Protocol Labs, a Miner or other Filecoin community member(s)) to determine the validity of any complaints about infractions of these rules by another ecosystem participant. The tribunal would act as judge in these disputes and determine whether there is an infraction and whether there should be a penalty. Who is responsible and how to enforce the penalty should be discussed here as well.

**Comment by dkkapur** [comment]
Hi @NSC-FIL - thanks for publishing the issue here. I generally agree that we are in need for a faster / more effective decision making system. The tribunal idea seems interesting, a few points: 
- IMO tribunal and similar scoped decision making parties are most effective when (1) the general community is very aligned and decisions need to be efficient, or (2) the community is not super aligned and decision making needs to be fair and representative of the opinions pervasive in the community. Given how young Filecoin, and Filecoin Plus is, it might be worth trying to aggregate opinions from more parties than just 3 in the decision making progress. What if we consider some combination of https://filpoll.io/ (looking at #s of miners rather than power) + timed and planned discussion in 1-2 notary governance calls for open issues before deciding based on majority? 
- The key voices that should be heard / incorporated into decision making: notaries, clients with legitimate use cases, and miners; Instead of PL - might be better to have a steward from the Filecoin Foundation leaning in to push fair governance practices. 
- If we have do a rotating decision mechanism, what determines who represents a set of stakeholders in a particular decision? Would it be a predetermined order or issue dependent based on who feels strongly?

**Comment by NSC-FIL** [comment]
On your first point, I agree that using https://filpoll.io/ with number of miners rather than power would be more fair in determining governance guidelines and ramifications of violations.  To prevent Sybil attack on the poll, maybe we should only allow miners with active accounts older than a period of time (say 90 days or equivalent epochs)?
On your second point, in the interest of fairness, all participants in the Filecoin community should have a voice in the governance of Filecoin and Filecoin Plus.  You're right that the Filecoin Foundation should have representation as well.
On your final point, maybe it can be handled similarly to electing a Board of Directors.  Setup an open mechanism to give stakeholders who are interested in having governance responsibility and put there qualifications and affiliation up for review by the Filecoin community, to be elected to the BOD on an annual or set term basis.  This is one idea ... but in any event, I believe Protocol Labs and/or the Filecoin Foundation would need to push for and organize things to establish the governance framework, as the community still seems to look to PL and FF for guidance and structure IMO.

**Comment by NSC-FIL** [comment]
After the discussion in the Filecoin+ meeting today, I just want to confirm that @dkkapur and @philippbanhardt at the Filecoin Foundation find that it might be worthwhile to fork the https://filpoll.io app and modify it for future governance polls to determine community sentiment on governance and dispute resolution issues.  Finding a qualified developer would be a possible action item to move this proposal forward.

**Comment by dkkapur** [comment]
@NSC-FIL - thanks for sharing the updates from the call! I think that probably just using filpoll.io in the meanwhile (even without the potential fork to optimize it for Fil+) is probably a good first step as well, just so we can start somewhere and continue to iterate/improve. Thoughts on this? Might be interesting to give this a shot for one of the currently open issues in the coming weeks.

**Comment by NSC-FIL** [comment]
I agree using filpoll.io would be a good temporary solution to gauge the sentiment on issues concerning the community regarding Fil+.  According to the filpoll.io website "Filpoll.io is a project designed and sponsored by Protocol Labs and built by Digital Mob, a Filecoin ecosystem collaborator."  Do you know who to contact regarding their tool and how to get permission or access to create a survey for Fil+?

**Comment by dkkapur** [comment]
https://github.com/filecoin-project/notary-governance/issues/112

**Comment by dkkapur** [comment]
@NSC-FIL - given the agreement on the initial direction with using filpoll (with exploring forking in the future), can we close this issue out for now and agree to re-open / consider alternatives based on the near future?

**Comment by NSC-FIL** [comment]
Agreed.
