### ISSUE TITLE
v5 Notary Allocator Application: Hash Big Data

### ISSUE THREAD

**Issue by hash889900** [filecoin-project/notary-governance#1050]
# v5 Notary Allocator Application

To apply to be an allocator, organizations will submit one application for each proposed pathway to DataCap. If you will be designing multiple specific pathways, you will need to submit multiple applications. 

Please complete the following steps:
# 1. Fill out the information below and create a new GitHub Issue

1. Notary Allocator Pathway Name (This can be your name, or the name of your pathway/program. For example "E-Fil+"):Hash Big Data
3. Organization Name: Hash Team
4. On-chain address for Allocator (Provide a NEW unique address. During ratification, you will need to initialize this address on-chain): f1lldgcje747faqelcksrwgwcml4s5u3h7afhltey
5. Country of Operation (Where your organization is legally based): china
6. Region of Operation (What region will you serve?): All Regions
7. Type of Allocator, diligence process: (Automated/programmatic, Market-based, or Manual (human-in-the-loop at some phase): Market-based and Manual
9. DataCap requested for allocator for 12 months of activity (This should be an estimate of overall expected activity. Estimate the total amount of DataCap you will be distributing to clients in 12 months, in TiB or PiB):100PiB

# 2. Access allocator application (download to save answers)
Click link below to access a Google doc version of the allocator application that can be used to save your answers if you are not prepared to fully submit the application in Step 3. https://docs.google.com/document/d/1-Ze8bo7ZlIJe8qX0YSFNPTka4CMprqoNB1D6V7WJJjo/copy

# 3. Submit allocation application 
Clink link below to access full allocator questionnaire and officially submit your answers:
https://airtable.com/appvyE0VHcgpAkt4Z/shrQxaAIsD693e1ns

Note: Sections of your responses WILL BE posted back into the GitHub issue tracking your application. 
The final section (Additional Disclosures) will NOT be posted to GitHub, and will be maintained by the Filecoin Foundation. 
Application information for notaries not accepted and ratified in this round will be deleted.

**Comment by Kevin-FF-USA** [comment]
Hi @hash889900 
Wanted to let you know this application has been received. Also verifying you have submitted the Airtable form with your detailed Allocator plan - the public answers will be posted in a thread below soon. If you have any questions - please let me know.

**Comment by Filplus-govteam** [comment]
### Basic Information
**1. Notary Allocator Pathway Name:**
Hash Big Data 

**2. Organization:**
Hash Team

**3. On Chain Address for Allocator:**
f1lldgcje747faqelcksrwgwcml4s5u3h7afhltey

**4. Country of Operation:**
china

**5. Region(s) of operation:**
Africa , Asia minus GCR, Greater China, Europe, Oceania, Japan, North America, South America, Other

**6. Type of Allocator:**
Manual

**7. DataCap requested for allocator for 12 months of activity:**
100PiB

**8. Is your allocator providing a unique, new, or diverse pathway to DataCap? How does this allocator differentiate itself from other applicants, new or existing?:**
DataCap may use different distribution strategies to meet different needs. It can formulate allocation policies based on the type, size, and importance of data to ensure proper distribution and efficient utilization of data in the system.

**9. As a member in the Filecoin Community, I acknowledge that I must adhere to the Community Code of Conduct, as well other End User License Agreements for accessing various tools and services, such as GitHub and Slack.:**
Acknowledge
### Client Diligence
**10. Who are your target clients?:**
Individuals learning about Filecoin, Small-scale developers or data owners, Enterprise Data Clients

**11. Describe in as much detail as possible how you will perform due diligence on clients.  If you are proposing an automated pathway, what diligence mechanism will you use to determine client eligibility?:**
Our due diligence process is designed to comprehensively assess the integrity and compliance of our clients. We use a standardized questionnaire that covers company information, financial viability, regulatory compliance, compliance documentation, data ownership and privacy. This extensive survey ensures that we collect detailed information about our clients, their data and proposed transactions. The information collected not only supports quantitative compliance checks, but also ensures that our partnerships meet the highest integrity, security and regulatory standards.


**12. Please specify how many questions you’ll ask, and provide a brief overview of the questions.:**
https://form.jotform.com/233531471737457
1.Introduction of yourself/ your organization (with links);
2.Use case examples and scope;
3.Geographic location of the client;
4.DataCap Allocation Requests Amount;
5.Filecoin On-Chain Address;
6.Declaration of Copy rights and Legal Compliance Requirements;
7.Specific requirement of miners and storage service
Nature Of Business (Government, Public, Private, NGO)

**13. Will you use a 3rd-party Know your client (KYC) service?:**
Yes, we use as third party KYC service to ensure thorough customer verification.
China Enterprise Search Tianyecha 
Offshore Google Company Profile U.S. Secretary of State Companies and Business Entities Taiwan Business and Industry Network Singapore Accounting and Corporate Regulatory Authority, etc.

**14. Can any client apply to your pathway, or will you be closed to only your own internal clients? (eg: bizdev or self-referral):**
Our channel is completely open and inclusive. Any client is welcome to apply, whether it is an external entity, a business development partner or a self-referral. Our open application process and robust systems support reflect a commitment to complete openness and inclusiveness.

**15. How do you plan to track the rate at which DataCap is being distributed to your clients?:**
Our strategy for tracking DataCap distribution is characterized by a commitment to real-time monitoring and integration with multiple open source tools   https://filplus.d.interplanetary.one/clients
### Data Diligence
**16. As an operating entity in the Filecoin Community, you are required to follow all local & regional regulations relating to any data, digital and otherwise. This may include PII and data deletion requirements, as well as the storing, transmit:**
Acknowledge

**17. What type(s) of data would be applicable for your pathway?:**
Public Open Dataset (Research/Non-Profit), Public Open Commercial/Enterprise

**18. How will you verify a client’s data ownership? Will you use 3rd-party KYB (know your business) service to verify enterprise clients?:**
We use a variety of methods to validate data ownership for different customer types. For public data, we use decentralized identifiers and verifiable credentials and leverage blockchain as a cryptographically verified immutable ledger. For private data, we perform secure authentication, using cryptographic techniques such as encrypted access keys and digital signatures to verify ownership. For corporate data, we integrate reputable third-party KYB services to rigorously validate corporate identities, ownership structures and registrations.


**19.  How will you ensure the data meets local & regional legal requirements?:**
Legal Team Consultation: We will engage a team of specialized legal advisors who will be responsible for researching and understanding the legal requirements of the local region. They will work with our data management team to ensure that our data management activities comply with local laws and regulations. Data Classification and Labeling: We will classify and label our data according to the legal requirements of the local region. This will help us to better manage and control the flow of data and ensure data security and compliance. Data Protection Measures: We will take necessary data protection measures, including but not limited to encryption, access control, backup and recovery. These measures will help to secure data and prevent data leakage and misuse. Data Auditing and Monitoring: We will conduct regular data auditing and monitoring to ensure data compliance. We will record and track activities such as the collection, storage, use and transmission of data for auditing and investigation as and when required. Compliance Reviews: We will conduct regular compliance reviews to ensure that our data management activities remain compliant with the legal requirements of the local region. If any non-compliance with legal requirements is identified, we will take immediate steps to rectify the situation.

**20. What types of data preparation will you support or require?:**
Supports any type of data preparation, does not provide specific preparation services, supports data sharding

**21. What tools or methodology will you use to sample and verify the data aligns with your pathway?:**
This process involves comparing the data to its metadata size to ensure that what is stored in the sector matches what it declares.  Data Distribution
### Data Distribution
**22. How many replicas will you require to meet programmatic requirements for distribution?:**
4+

**23. What geographic or regional distribution will you require?:**
Not less than 3 physical locations. Not less than 2 separate geopolitical regions. Not less than 4 or more SP entities Reduced VPN usage

**24. How many Storage Provider owner/operators will you require to meet programmatic requirements for distribution?:**
4+

**25. Do you require equal percentage distribution for your clients to their chosen SPs? Will you require preliminary SP distribution plans from the client before allocating any DataCap?:**
Prior to initial allocation, clients must provide a detailed allocation plan using a standardized template. This ensures the transparency and accuracy of the allocation process, and through such a standardized process, we can effectively manage the data and ensure compliance with relevant laws and regulations. Secondly sp cannot exceed 30% of the total quota for that LDN

**26. What tooling will you use to verify client deal-making distribution?:**
Open source tools used by the community. Examples include AC Bot and CID checker datacapstats.io tools, etc.

**27. How will clients meet SP distribution requirements?:**
In order to fulfill my client's need for data distribution, I will fully understand their situation. If the client lacks suitable service providers (SP) in certain areas , I will actively provide a list of some well-performing SPs to facilitate cooperation. In order to ensure the reliability and quality of SPs, I will maintain an SP table. The data in it comes from SP that have already cooperated or those that have performed well in historical audits. By doing so, we can provide better choices for our clients and ensure smooth data distribution. 

**28. As an allocator, do you support clients that engage in deal-making with SPs utilizing a VPN?:**
Before I start, I will ask the customer if they are using a VPN, and if they are using a VPN, the customer will need to provide proof that the physical devices are not in the same region, as well as supporting documentation.
### DataCap Allocation Strategy
**29. Will you use standardized DataCap allocations to clients?:**
Yes, standardized

**30. Allocation Tranche Schedule to clients::**
Allocation according to existing rules
- First allocation: 5% of the total amount of DataCap requested, or 50% of the weekly allocation rate, whichever is less
- Second allocation: 10% of the total DataCap requested or 100% of the weekly allocation rate, whichever is less
- Second allocation: 10% of the total amount of DataCap requested or 100% of the weekly allocation rate, whichever is less Third allocation: 20% of the total amount of DataCap requested or 200% of the weekly allocation rate, whichever is less
- Fourth allocation: 40% of the total DataCap requested or 400% of the weekly allocation rate, whichever is less
Overall limit of 5P for a single customer for a single application

**31. Will you use programmatic or software based allocations?:**
Yes, standardized and software based

**32. What tooling will you use to construct messages and send allocations to clients?:**
filplus.storage request. lotus binary publish datacap. lassie to validate data content 

**33. Describe the process for granting additional DataCap to previously verified clients.:**
Using the Subsequent Assignment (SA) robot, manually view the 

**34. Describe in as much detail as possible the tools used for: • client discoverability & applications • due diligence & investigation • bookkeeping • on-chain message construction • client deal-making behavior • tracking overall allocator health • disput:**
I'll be utilizing Google online documents to categorize records that
Including due diligence, bookkeeping, on-chain message construction, customer transactions, and other behaviors.
And tracking information like overall distributor health.
For dispute discussion resolution, this is done on GitHub. Community updates, GitHub, and Slack and Discord tools.
### Tools and Bookkeeping
**35. Will you use open-source tooling from the Fil+ team?:**
 GitHub repositories, Google spreadsheets, MongoDB filplus inspector app bot, large datacap request bot https://filecoin.tools/ singularity 

**36. Where will you keep your records for bookkeeping? How will you maintain transparency in your allocation decisions?:**
By using Google Docs, you can present the results of your audit to your customers in a clear, easy-to-understand manner. This not only lets the client know if their information was accepted or rejected, but also explains the reason for the rejection so that the client can take the appropriate steps to fulfill the request. If a dispute arises, I'll provide more details in the google docs and github!

### Risk Mitigation, Auditing, Compliance
**37. Describe your proposed compliance check mechanisms for your own clients.:**
Go through the current bot report and first exclude CID shares, copies, duplicates, and other necessities
Conduct periodic audits to check that each customer's storage usage matches the allocated DataCap. During the audit, compare actual usage to allocated volume to ensure that customers are not exceeding or misusing the

**38. Describe your process for handling disputes. Highlight response times, transparency, and accountability mechanisms.:**
For disputed situations, allocation decision discussions should first be initiated publicly on Slack or GitHub We will resolve within 72 hours


**39. Detail how you will announce updates to tooling, pathway guidelines, parameters, and process alterations.:**
Since the FIL+ apps are handled on github, I'll maintain a public folder under my github account to make the tools publicly available

**40. How long will you allow the community to provide feedback before implementing changes?:**
7 days

**41. Regarding security, how will you structure and secure the on-chain notary address? If you will utilize a multisig, how will it be structured? Who will have administrative & signatory rights?:**
I would use a hardware wallet (Ledger) to manage it instead of multiple signatures. The hardware wallet is kept by the team and the signing is done by the administrator who reviews the client's application.

**42. Will you deploy smart contracts for program or policy procedures? If so, how will you track and fund them?:**
If necessary, I will develop simple smart contracts. But there are no plans to do so at the moment.
### Monetization
**43. Outline your monetization models for the services you provide as a notary allocator pathway.:**
There are no plans for monetization at this time.


**44. Describe your organization's structure, such as the legal entity and other business & market ventures.:**
We are Hash Team, providing infrastructure and Filecoin services.

**45. Where will accounting for fees be maintained?:**
N/A
### Past Experience, Affiliations, Reputation
**46. If you've received DataCap allocation privileges before, please link to prior notary applications.:**
N/A

**47. How are you connected to the Filecoin ecosystem? Describe your (or your organization's) Filecoin relationships, investments, or ownership.:**
We are a technical team, early adopters and ecosystem builders of Filecoin. Founded in 2022 to understand and participate in Filecoin. Providing technical support for Filecoin to numerous clients. Collaborating with our clients to become qualified storage providers We are also working on building an eco-project Provide free and open source tools for community developers

**48. How are you estimating your client demand and pathway usage? Do you have existing clients and an onboarding funnel?:**
I will initially assess the client's actual needs based on their industry, business type and data type.

**Comment by kevzak** [comment]
## Datacap Request for Allocator
#### Address
> f2djzdtcymz55csoxj4ounmdvurqif6kv6cjuzsey
#### Datacap Allocated
> 5PiB

**Comment by galen-mcandrew** [comment]
## DataCap Request for Allocator
#### Address
> f2djzdtcymz55csoxj4ounmdvurqif6kv6cjuzsey
#### Datacap Allocated
> 5PiB

**Comment by galen-mcandrew** [comment]
https://filfox.info/en/message/bafy2bzaceaalkljutbshmdgxkfnthlgtcoxvklgkncbv2iqprosioorre526y

**Comment by hash889900** [comment]
> 30. Allocation Tranche Schedule to clients::
> Allocation according to existing rules
> 
> - Overall limit of 5P for a single customer for a single application

Request to amend question 30 from 5P to 15P
as below
 - Overall limit of 15P for a single customer for a single application

**Comment by galen-mcandrew** [comment]
## Datacap Request for Allocator
#### Address
> f2djzdtcymz55csoxj4ounmdvurqif6kv6cjuzsey
#### Datacap Allocated
> 10PiB
