### ISSUE TITLE
v5 Notary Allocator Application: Antalpha

### ISSUE THREAD

**Issue by nj-steve** [filecoin-project/notary-governance#1052]
# v5 Notary Allocator Application

To apply to be an allocator, organizations will submit one application for each proposed pathway to DataCap. If you will be designing multiple specific pathways, you will need to submit multiple applications. 

Please complete the following steps:
# 1. Fill out the information below and create a new GitHub Issue

1. Notary Allocator Pathway Name (This can be your name, or the name of your pathway/program. For example "E-Fil+"):Ant Steve
3. Organization Name: Antalpha
4. On-chain address for Allocator (Provide a NEW unique address. During ratification, you will need to initialize this address on-chain): f1xx6555qijma7igpnjspyvdunc4vfxkawnpqy5ii
5. Country of Operation (Where your organization is legally based): Singapore
6. Region of Operation (What region will you serve?):  Greater China Region (GCR), North America, Asia minus GCR, Japan
7. Type of Allocator, diligence process: (Automated/programmatic, Market-based, or Manual (human-in-the-loop at some phase): Manual
8. DataCap requested for allocator for 12 months of activity (This should be an estimate of overall expected activity. Estimate the total amount of DataCap you will be distributing to clients in 12 months, in TiB or PiB): 100 PiB

# 2. Access allocator application (download to save answers)
Click link below to access a Google doc version of the allocator application that can be used to save your answers if you are not prepared to fully submit the application in Step 3. https://docs.google.com/document/d/1-Ze8bo7ZlIJe8qX0YSFNPTka4CMprqoNB1D6V7WJJjo/copy

# 3. Submit allocation application 
Clink link below to access full allocator questionnaire and officially submit your answers:
https://airtable.com/appvyE0VHcgpAkt4Z/shrQxaAIsD693e1ns

Note: Sections of your responses WILL BE posted back into the GitHub issue tracking your application. 
The final section (Additional Disclosures) will NOT be posted to GitHub, and will be maintained by the Filecoin Foundation. 
Application information for notaries not accepted and ratified in this round will be deleted.

**Comment by Filplus-govteam** [comment]
### Basic Information
**1. Notary Allocator Pathway Name:**
Ant Steve

**2. Organization:**
Antalpha

**3. On Chain Address for Allocator:**
f1wptpz63azsjoxu7z46zo34d2rjb3nssdrvn75iq

**4. Country of Operation:**
Singapore

**5. Region(s) of operation:**
Asia minus GCR, Greater China, North America, Japan

**6. Type of Allocator:**
Manual

**7. DataCap requested for allocator for 12 months of activity:**
100PiB

**8. Is your allocator providing a unique, new, or diverse pathway to DataCap? How does this allocator differentiate itself from other applicants, new or existing?:**
1. Publicity: Let more people know that we can help people to store data on the Filecoin chain. We will promote it on Twitter or WeChat group.
2. Personal data sets: In the past, our big data sets were almost targeted at corporate customers. But in reality, although the individual's data is small, the number of people is large. We allow individuals to apply for some of their quotas to store personal data sets. Includes some public videos they record, pictures and some other interesting data recorded by individuals. Let them view their data anytime and anywhere in the future.
3. Institutions that have data: Let more useful data be stored on the Filecoin network. For example, video and picture rendering companies, artificial intelligence companies, or education companies and so on.
4. Data classification: We will classify the data into content categories.When others need this data, they will easily find the shared data.In the future, we can also recommend data according to user needs.
5. Training services: We are responsible for providing training and contacting SP services. Let more and more users use the Filecoin network to store their data. The goal is that Filecoin will store everyone’s data.
6. Supervise compliance: For those who are non-compliant and do not abide by fil+ rules, we will ask them to give a reasonable explanation. If the explanation is unreasonable, we will terminate the allocation and initiate the deletion of the corresponding unused DataCap.
7. Legal risks: We will randomly check the data stored by customers and prevent some illegal data from entering the Filecoin network to create a healthy ecosystem.

**9. As a member in the Filecoin Community, I acknowledge that I must adhere to the Community Code of Conduct, as well other End User License Agreements for accessing various tools and services, such as GitHub and Slack.:**
Acknowledge
### Client Diligence
**10. Who are your target clients?:**
Individuals learning about Filecoin, Small-scale developers or data owners, Enterprise Data Clients

**11. Describe in as much detail as possible how you will perform due diligence on clients.  If you are proposing an automated pathway, what diligence mechanism will you use to determine client eligibility?:**
1.We will research the background of the client organization.Including conducting KYC processes, company size, company creation time, company location and main business.
2.We will research the sample data,We'll look at the sample data carefully, and will check if the data has relationship between the client.We will also check whether the data conforms to legal norms and health data
3.We will research the client organization authenticity and size, if the client has ability to hold the so much data.
4.We will allocate DataCap to client in four stages.If the client do it well,we will expand the DataCap to the client in next stage.

**12. Please specify how many questions you’ll ask, and provide a brief overview of the questions.:**
Below will be what we want to ask:
1.Do you know the rules that we store data in filecoin? Please describe it briefly.
2.Could you tell me briefly about your organization background? I will check if the data type is generated or owned by the client.
3.Could you know the SPs you want to send deal?
4.How do you find the SPs you want to send deal?
5.How do you send data to SP？
6.Could you send me picture of the business license or certificate information of the organization?
7.Could you tell me how much data do you have now,and where do you store the data in?

**13. Will you use a 3rd-party Know your client (KYC) service?:**
We use third-party tools to verify KYC for our customers. We will ask them to provide relevant information about the company or the person. The company shall verify the company email and business license, and the individual shall verify the academic certificate, wechat, twitter, Facebook or mobile phone number.
Prevent some people with ulterior motives from using the decentralized blockchain to do bad things.

**14. Can any client apply to your pathway, or will you be closed to only your own internal clients? (eg: bizdev or self-referral):**
Yes,any client can apply in our pathway.Our goal is to make Filecoin accessible to everyone.

**15. How do you plan to track the rate at which DataCap is being distributed to your clients?:**
The speed of DataCap usage from different users is different.We will build a platform to manage the frequency of use of these users,every day we will update, we can clearly see: how much the datacap of customer has left, whether it needs to be re-allocated, whether the customer use meets the rules. When the customer uses normally, we can see clearly when there is no margin, and the customer can also take the initiative to contact us.
### Data Diligence
**16. As an operating entity in the Filecoin Community, you are required to follow all local & regional regulations relating to any data, digital and otherwise. This may include PII and data deletion requirements, as well as the storing, transmit:**
Acknowledge

**17. What type(s) of data would be applicable for your pathway?:**
Public Open Dataset (Research/Non-Profit), Public Open Commercial/Enterprise, Private Commercial/Enterprise, Private Non-Profit/Social Impact, Other (specified elsewhere)

**18. How will you verify a client’s data ownership? Will you use 3rd-party KYB (know your business) service to verify enterprise clients?:**
We verify ownership of customer data by following these steps:
First, we will sample the content of the client's data. Then investigate the history of the company and the main business, and whether there is a relationship between these data and the company. We will ask the client to reply the following questions with official email: Please confirm that these data belong to your company, please confirm that these data are legitimate data, and please confirm that these data are legitimate use.
Also we will use third-party verification platforms to check whether these companies are healthy and have a history of dishonesty, illegal business operations, tax evasion or other problems.
For individual users, we sample the content of their data and ask questions about data ownership.

**19.  How will you ensure the data meets local & regional legal requirements?:**
First of all, we need to determine where the client is, confirm the data classification by sampling samples, and inquire whether the client meets the legal norms according to the local data law. Our company has colleagues scattered around the world, understand the local laws, we also have legal colleagues, we can consult.

**20. What types of data preparation will you support or require?:**
If the client knows the relevant technology, we will provide training on data preparation or order sending or data transfer. If the client knows nothing and just wants to save data, we will provide equipment and technical solutions, as well as data transmission or other things to serve the client.

**21. What tools or methodology will you use to sample and verify the data aligns with your pathway?:**
We will use retrieval tools to search the client's data content frequently and conduct random inspections to see if the data complies with the content in the application. High frequency will improve accuracy and reduce the risk of customers taking advantage of loopholes. Later, we will find ways to introduce AI tools for sample data analysis to improve efficiency.
### Data Distribution
**22. How many replicas will you require to meet programmatic requirements for distribution?:**
4+

**23. What geographic or regional distribution will you require?:**
3 geographic or regional distribution

**24. How many Storage Provider owner/operators will you require to meet programmatic requirements for distribution?:**
5+

**25. Do you require equal percentage distribution for your clients to their chosen SPs? Will you require preliminary SP distribution plans from the client before allocating any DataCap?:**
Yes, we will require the client to disclose the percentage of their chosen SPs allocated.The maximum allocation of one SP cannot exceed 25% of the total. In their application,we will let clients to provide a general SP distribution plan. If they want change the plan,they should disclose the new plan as soon as possible. Information about the application and SPs and Plans we will record it on our platform.

**26. What tooling will you use to verify client deal-making distribution?:**
We will use CID checker bot and datacapstats.io to assist us in verification. 

**27. How will clients meet SP distribution requirements?:**
We will check through CID checker tool and check the geographic location of the SP.If we find problems, we will inform them in time, so that their subsequent operations will meet the SP distribution requirements.

**28. As an allocator, do you support clients that engage in deal-making with SPs utilizing a VPN?:**
If a SP uses VPN for the purpose of false location, we firmly resist and do not support it. If you use VPN for security, we normally support it, but customers need to provide evidence of the specific location of the node. We will regularly conduct inspections on SP node VPNs. When a VPN is used, we will detect the true source of the VPN and whether it is fake. We use a third-party service to verify if the SP is using VPN. Such as https://www.ipqualityscore.com/vpn-ip-address-check.
### DataCap Allocation Strategy
**29. Will you use standardized DataCap allocations to clients?:**
Yes, standardized

**30. Allocation Tranche Schedule to clients::**
• First: 10% , in the first round we only allcate 10% of the total application.
• Second: 20% , if the first round runs nice, or othe little problem with reasonable explanation.The second round will be allocated.
• Third: 30%, if the second round runs nice with little problem with reasonable explanation, the thid round will be allocated.
• Fourth: 40%, if the third round runs nice with no problem, the fourth round will be allocated.
• Max per client overall:100T for individuals, 10PiB for enterprises

**31. Will you use programmatic or software based allocations?:**
Yes, standardized and software based

**32. What tooling will you use to construct messages and send allocations to clients?:**
Notary Registration Tool: https://filplus.fil.org/#/

**33. Describe the process for granting additional DataCap to previously verified clients.:**
First, check whether this client is in the first round. In the first round, we only need to allocate one week or 10% of the application amount, and instruct the customer to follow the application form. Later, we will use open source tools such as SA bot to detect whether its use is compliant, whether the data distribution is more than 4, whether it is distributed in more than 3 regions, and research and spot check whether the sample content complies with the rules. 20% of the total amount will be allocated in the second round, 30% in the third round, and 40% in the fourth round.

**34. Describe in as much detail as possible the tools used for: • client discoverability & applications • due diligence & investigation • bookkeeping • on-chain message construction • client deal-making behavior • tracking overall allocator health • disput:**
• client discoverability & applications 
We will publish news on Salck, WeChat group, and github. Clients can fill in the application online or send the application email to me.
• due diligence & investigation
We will investigate the client’s company background, Twitter, official website and company’s business license.
• bookkeeping
We will record the client's allocation and application records through Google Docs and Tencent Docs and our platform.
• on-chain message construction
We will use the following tools:
datacapstats.io
filecoin.tools/clients
explorer.glif.io
filplus.info
filfox.info
• client deal-making behavior
datacapstats.io
filecoin.tools/clients
explorer.glif.io
filplus.info
filfox.info
• tracking overall allocator health
CID checker bot and datacapstats.io
• dispute discussion & resolution
When encountering abuse of datacap or other violations, submit it to GitHub and let the community to review it. If everyone thinks it violates the rules, the quota will be cleared and added to the blacklist.
We will submit disputes to T&T Dispute Tracker: https://filecoin.notion.site/0586b40bc68e48d787587a5d6ebc1477?v=fdb6413e83fa499db3a2c1a41e2bbcb0
• community updates & comms 
Github、Email、Slack、Or wechat
### Tools and Bookkeeping
**35. Will you use open-source tooling from the Fil+ team?:**
Yes,we will use open-source tooling from the Fil+ team. Such as CID checker bot and datacapstats.io. Also github we will use to record some infromation about the application.

**36. Where will you keep your records for bookkeeping? How will you maintain transparency in your allocation decisions?:**
Application records will be completed via github or email. All allocation records we will synchronize all information to the fil+ team. And disclose some non-private information to github. Each records allocation will be documented in Google Docs and Tencent Docs and our platform. The records of allocation will be disclosed on github. When there is a dispute, we will submit it to the governance team for approval.When it is verified a abuse of datacap, we will remove them. Private information is about email , slack or phone number.
### Risk Mitigation, Auditing, Compliance
**37. Describe your proposed compliance check mechanisms for your own clients.:**
• Regular Check-ins: We regularly communicate with our clients online to understand their DC usage. Check their data reports regularly. Understand their compliance status regularly, communicate with them in time for non-compliance, and urge them to correct it in time.
• Tracking DataCap Distribution Metrics: We will develop scripts to monitor the client's address in real time. They may not be used intentionally, non-compliant use we will find in time, and tell the client, they will promptly correct in the subsequent use.
• Understanding Client Demographics: Communicate with customers about their SP partners. Periodically check the SP information sent by customers, as well as the geographical distribution.
• Monitoring Time Metrics: Monitoring Time Metrics：We manage our customers' DC usage efficiently. Time will be assessed based on weekly usage at the time of application. For those that have not been used for a long time (such as more than 2 months), we will timely communicate with customers about the specific situation and disclose it in a timely manner. For unwanted DC, we will delete the announcement in time, and do not allow zombie DC to occupy resources.
• Trust Assessment: We will evaluate a credit score based on the level of participation and contribution of companies and individuals on the Filecoin network, as well as their history of using DC. Their DC limit has a lot to do with this credit score.Adjust of DataCap allocation for new clients based on trust assessment results to control risks.
• Using Tools Like CID Checker/Retrievability Bot: We will use bots to accurately analyze customers' DC usage and SP distribution, find problems in time, withdraw unreasonable allcation in time, and give training to clients who do not understand the rules to follow FIL+ rules in time.

**38. Describe your process for handling disputes. Highlight response times, transparency, and accountability mechanisms.:**
When our clients use violations or have serious abuses, we respond within 48 hours.
First, we will submit a dispute, and we will notify the community not to continue to allocate datacap to this organization or individual.
Second, we will collect disputed data content or reports and disclose them to the community in a timely manner.
Then we will ask fil+ team and neutral parties in the community to check and give reasonable opinions.
If I did not investigate clearly and was deceived by a client, I will make a review. And will promptly recover the allocated DC. This organization or individual will be reported to the blacklist of the community, and will not be allocated DC in the future. 

**39. Detail how you will announce updates to tooling, pathway guidelines, parameters, and process alterations.:**
When we will updates tooling, pathway guidelines, parameters, and process alterations, we will announce our clients, community and fil+ team by slack ,github and email.We will let all concerned know when our information is updated.We will not change this information at will, and all changes will be for better governance and more efficient allocation of DataCap.

**40. How long will you allow the community to provide feedback before implementing changes?:**
When we have planned changes, we will write the change plan as soon as possible and submit it to github, slack or send an email to the relevant people. Discuss it within a week. We will disclose the results of everyone's discussions in a timely manner. Formulate reasonable change opinions based on the community and fil+ team, weigh the opinions of all parties, and notify relevant personnel of the change date.

**41. Regarding security, how will you structure and secure the on-chain notary address? If you will utilize a multisig, how will it be structured? Who will have administrative & signatory rights?:**
We will build multi-signature addresses to protect notary addresses. Multiple signatures only need to determine the signature address can be created, the signature address of the choice, we will choose some long-term participation in community affairs responsible notary. They need to understand the fil+ project and be willing to contribute to the community.
To protect the notary's address, we will ask them to create a signed address on the hardware wallet. For the use of the environment, we will recommend that the notary install security anti-virus software on the computer, do not randomly click links, do not log in to some insecure websites, do not install some unknown software.
In order to ensure that the notary's hardware wallet is always fine, we will ask the hardware wallet to send a heartbeat or signature at intervals.

**42. Will you deploy smart contracts for program or policy procedures? If so, how will you track and fund them?:**
No，we will not deploy smart contracts for program or policy procedures.
### Monetization
**43. Outline your monetization models for the services you provide as a notary allocator pathway.:**
We may charge a part of the service fee, mainly because we may do some work due to overtime. But this number may be relatively small. The main thing is to contribute to the community and make our community better.
Application review will be free.Our service fee will include data audit or data preparation or data distribution: application review may be 30 FIL each time. data audit may be 20 FIL each time. For data preparation, we will provide free training. If the data provider is willing to outsource this part of the business to us, we will charge a reasonable service fee based on the amount of data, about 0.5FIL/T.For data distribution, we will also provide free training. If the data party is willing to outsource this part of the business to us, we will charge 0.2FIL/T.

**44. Describe your organization's structure, such as the legal entity and other business & market ventures.:**
1.Antalpha Technologies Ltd is a key player in enabling institutional investors from both traditional finance and the blockchain space to transition towards the global adoption of the emerging megatrend of digital assets. 2.We were established in 2021 in Singapore, Antalpha have 300+ employees,and Antalpha manages over $800mm crypto asset and provides our customer with inistitutional grade financial services.We have lent USDT to some miners at low interest rates to help them run their companies. 3.We invest in the world's future infrastructure for Web 3.0, blockchain and digital asset technology.We have launched the Filecoin Fund,and that will help more institutions to participate in Filecoin network. 4.There will be active investment in the disaster data field or data insurance, and the plan will be integrated with Filecoin and IPFS.

**45. Where will accounting for fees be maintained?:**
Regarding the service fee, we will have a Filecoin payment address, and the payment at this address will be publicized on the chain. We will help clients to calculate the staking, burning or release mechanism, and let them notify the cooperating SPs to prepare so that the project can continue to operate. Regarding audit monetization, we will disclose the reasons for each income and expenditure to the community when necessary.
### Past Experience, Affiliations, Reputation
**46. If you've received DataCap allocation privileges before, please link to prior notary applications.:**
https://github.com/filecoin-project/notary-governance/issues/683

**47. How are you connected to the Filecoin ecosystem? Describe your (or your organization's) Filecoin relationships, investments, or ownership.:**
1.Antalpha Technologies Ltd is a key player in enabling institutional investors from both traditional finance and the blockchain space to transition towards the global adoption of the emerging megatrend of digital assets. 2.We have lent USDT to some miners at low interest rates to help them run their companies. 3.We invest in the world's future infrastructure for Web 3.0, blockchain and digital asset technology.We have launched the Filecoin Fund,a small group of institutional friends are already investing.And that will help more institutions to participate in Filecoin network. 4.There will be active investment in the disaster data field or data insurance, and the plan will be integrated with Filecoin and IPFS. 5.We have also developed some Filecoin financial tools for institutional friends.

**48. How are you estimating your client demand and pathway usage? Do you have existing clients and an onboarding funnel?:**
We have a certain customer base, like some data companies, 3D companies. We also have marketing people who can promote new users on Twitter, Facebook or Wechat to use Filecoin to store data. For customer needs, we will send some market research to collect client needs. For path usage, we record the usage of our allocated data and make reasonable planning in time.

**Comment by nj-steve** [comment]
<img width="1127" alt="image" src="https://github.com/filecoin-project/notary-governance/assets/15796059/e7e94edd-c1ea-465b-a13d-da6f3ad89b4e">
Hello, @Kevin-FF-USA @Filplus-govteam we have confirmed the email.Hope for your next support.

**Comment by nj-steve** [comment]
@Kevin-FF-USA @Filplus-govteam Hi Kevin 、filplus-gov , I want to change my On-chain address for Allocator with 
 **f1xx6555qijma7igpnjspyvdunc4vfxkawnpqy5ii**    . 

![image](https://github.com/filecoin-project/notary-governance/assets/15796059/c0bde5f2-6d73-4bc6-aeba-5a8e97195d07)

Because the previously disclosed address, the protocol is different, and the glif platform is not linked. 
Please help me.
Thanks!

**Comment by galen-mcandrew** [comment]
## Datacap Request for Allocator
#### Address
> f2easi46ap54rihqik5cck2wr55hwm4rmmi2c2wxy
#### Datacap Allocated
> 5PiB

**Comment by galen-mcandrew** [comment]
## DataCap Request for Allocator
#### Address
> f2easi46ap54rihqik5cck2wr55hwm4rmmi2c2wxy
#### Datacap Allocated
> 2.5PiB

**Comment by galen-mcandrew** [comment]
https://filfox.info/en/message/bafy2bzacedvnbb6b3rhbfkv4cba7wuoz5lchmw27jc3id2z3mg4c2gzsrti6c
