### ISSUE TITLE
v5 Notary Allocator Application Dcent 

### ISSUE THREAD

**Issue by cryptowhizzard** [filecoin-project/notary-governance#1053]
# v5 Notary Allocator Application

To apply to be an allocator, organizations will submit one application for each proposed pathway to DataCap. If you will be designing multiple specific pathways, you will need to submit multiple applications. 

Please complete the following steps:
# 1. Fill out the information below and create a new GitHub Issue

1. Notary Allocator Pathway Name (This can be your name, or the name of your pathway/program. For example "E-Fil+"): DCENT
3. Organization Name: DCENT BV
4. On-chain address for Allocator (Provide a NEW unique address. During ratification, you will need to initialize this address on-chain): f1xk4bsgn3hjobod4hoovtt4iuivgocwhduzwabxa
5. Country of Operation (Where your organization is legally based): The Netherlands
6. Region of Operation (What region will you serve?): Worldwide
7. Type of Allocator, diligence process: (Automated/programmatic, Market-based, or Manual (human-in-the-loop at some phase): Manual + market based.
9. DataCap requested for allocator for 12 months of activity (This should be an estimate of overall expected activity. Estimate the total amount of DataCap you will be distributing to clients in 12 months, in TiB or PiB): 1000 PiB

**Comment by Kevin-FF-USA** [comment]
Hi @cryptowhizzard 
Wanted to let you know this application has been received. Also verifying you have submitted the Airtable form with your detailed Allocator plan - the public answers will be posted in a thread below soon. If you have any questions - please let me know.

**Comment by Filplus-govteam** [comment]
### Basic Information
**1. Notary Allocator Pathway Name:**
DCENT Fil+

**2. Organization:**
DCENT BV.

**3. On Chain Address for Allocator:**
f1eiw5gn24wpa44azzxhbyj545vzm7jqjdrcdv2fy

**4. Country of Operation:**
The Netherlands

**5. Region(s) of operation:**
Africa , Asia minus GCR, Greater China, Europe, Oceania, Japan, North America, South America

**6. Type of Allocator:**
Manual

**7. DataCap requested for allocator for 12 months of activity:**
1000 PiB

**8. Is your allocator providing a unique, new, or diverse pathway to DataCap? How does this allocator differentiate itself from other applicants, new or existing?:**
Our allocator stands out and provides a new way to datacap with a clear focus on commercial clients. We prioritize serving paid storage, currently a niece within the Filecoin+ ecosystem, which currently focusses mostly on open datasets.

Unlike conventional approaches, we concentrate on helping commercial clients achieve Fil+ compliance with minimum resource utilization in a E-Fil+ path style. When compared to storage giants like AWS, Google, or Impossible Cloud, Filecoin faces cost challenges related to data sealing using GPUs. While Filecoin gains an advantage through unique CID creation, it also puts Filecoin at a competitive disadvantage when it comes to raw storage costs. Our pathway is tailored to empower clients to strike the perfect balance between cost and storage efficiency, offering them an unparalleled cost-to-storage equation in the market. 

Our focus is Small-scale businesses or data owners and Enterprise Data Clients as long as there is a commercial incentive and they want to pay the SP’s for storing their data. We intend to use an escrow servicemodel where the client stakes money that the SP receives after successfully completing the storage deal with monthly payments. For example when a Client wants to store a deal for 36 Euro with a duration of 36 months, the SP receives 1 Euro per month for a duration of 36 months.

**9. As a member in the Filecoin Community, I acknowledge that I must adhere to the Community Code of Conduct, as well other End User License Agreements for accessing various tools and services, such as GitHub and Slack.:**
Acknowledge
### Client Diligence
**10. Who are your target clients?:**
Small-scale developers or data owners, Enterprise Data Clients, Other (specified above), Individuals learning about Filecoin

**11. Describe in as much detail as possible how you will perform due diligence on clients.  If you are proposing an automated pathway, what diligence mechanism will you use to determine client eligibility?:**
Minimum of one video call with visuals.
KYC through Veriff where we compare the identity document to the person we are speaking with in the videocall
Chamber of commerce check and VAT check ( Mandatory for business transactions in the EU )


**12. Please specify how many questions you’ll ask, and provide a brief overview of the questions.:**
Business Verification Questions:
Can you provide your Chamber of Commerce registration details?
Do you have a valid VAT (Value Added Tax) number?
Can you provide proof of business identity, such as incorporation documents or business licenses?
Data Verification Questions:
What type of data do you intend to store on Filecoin?
How large is your data set?
Do you have any specific storage or retrieval requirements?
Is your data compliant with local and international data protection regulations (e.g., GDPR in Europe)?
Financial and Contractual Questions:
What is your budget for data storage?
Are you looking for short-term or long-term storage solutions?
Can you commit to a minimum storage period?
Do you have any specific Service Level Agreements (SLAs) or Key Performance Indicators (KPIs) that you expect from Service Providers?
Security and Compliance Questions:
How do you ensure the security and integrity of your data?
Do you require encrypted storage?
Are there any industry-specific compliance standards you need to meet (e.g., HIPAA for healthcare data, PCI DSS for financial data)?
Use Case and Purpose Questions:
What is the primary purpose of storing this data?
Do you anticipate frequent access to this data or is it primarily for archival purposes?
Is the data intended for public access or private use?
Service Provider (SP) Preference Questions:
Do you have any preference for specific Service Providers?
What criteria do you use to select a Service Provider?
Have you previously worked with Filecoin Service Providers?
Backup and Recovery Questions:
What are your expectations for data backup and recovery?
Do you have a disaster recovery plan in place?
Audit and Reporting Requirements:
Are you subject to any audit requirements for your data?
Do you need regular reporting on your data storage?
Apart from this we also discuss with the client if they need support finding Sp’s with a good standing reputation and guide them / help them with this.


**13. Will you use a 3rd-party Know your client (KYC) service?:**
Yes, Veriff. We worked with them before. We will use them on the client as well as on the SP’s prior allocation.

**14. Can any client apply to your pathway, or will you be closed to only your own internal clients? (eg: bizdev or self-referral):**
Any client can apply as long as they are willing to pay to store commercial data.

**15. How do you plan to track the rate at which DataCap is being distributed to your clients?:**
We have our own software system built in retool and will monitor this per tranche / application to make sure it is compliant with the conditions we set. We will use the limited thrust principle ( Start with small tranches ). We also monitor the total use of datacap and put daily alerts on it. We already have PHP scripts looking at certain wallets in the network providing alerts who are suitable for this.
### Data Diligence
**16. As an operating entity in the Filecoin Community, you are required to follow all local & regional regulations relating to any data, digital and otherwise. This may include PII and data deletion requirements, as well as the storing, transmit:**
Acknowledge

**17. What type(s) of data would be applicable for your pathway?:**
Public Open Dataset (Research/Non-Profit), Public Open Commercial/Enterprise, Private Commercial/Enterprise, Private Non-Profit/Social Impact, Other (specified elsewhere)

**18. How will you verify a client’s data ownership? Will you use 3rd-party KYB (know your business) service to verify enterprise clients?:**
We will check the license of the dataset involved. If it is an open license we don’t have to check as it is free to distribute. In case of commercial licenses we will ask for a document that show’s permission from the dataset owner. Apart from this we will advise a NOTD ( Notice and takedown ) procedure. As we are experienced as former Usenet provider and the legal aspect of storing data on European ground we will provide advice to client’s / SP’s if deemed necessary.

**19.  How will you ensure the data meets local & regional legal requirements?:**
We will do automatic retrieval tests of samples and manually inspect the data before each (new) tranche is granted. We already have this operational in the current Fil+ environment. As we are experienced as former Usenet provider and the legal aspect of storing data on European ground we will provide advice to client’s / SP’s if deemed necessary.

**20. What types of data preparation will you support or require?:**
We will provide an onboarding service for commercial data for clients who are interested. We are already doing this for customers where we use parts of Singularity to build a dataset ( The compilation of cars and content provider part ) and use our own software for distribution that supports sharding. Apart from this we have our own API.  When a customer provides us with the data credentials of their S3 bucket and system takes care of the rest. Clients can use our API to get the CID’s and file lists and status of the onboarding set’s ( Like project motion ). We already have this up and running with some of our customers.  Please note that we are open to use / integrate other existing tools like Spade per clients request.

**21. What tools or methodology will you use to sample and verify the data aligns with your pathway?:**
How will you confirm the data matches what a client claims, both in type and preparation requirements? How will you prevent sector-size abuse, such as sector padding? We will do visual semi-automatic random sample checks on the data before each tranche of new datacap.
### Data Distribution
**22. How many replicas will you require to meet programmatic requirements for distribution?:**
5+

**23. What geographic or regional distribution will you require?:**
As we are seeking commercial storage solutions it is impossible for a general client to pay to store 5 replicas at minimum. In a perfect world we can imagine that clients have one copy on AWS or Google and they want to store one or two copy’s on Filecoin ( Without Fil + ). If we enable clients to store with Fil+ then the price of storing the data should be less but that also means it has to be paid with block rewards on SP side and that is a diminishing “thing” and risky.  We propose that some commercial set’s ( aka paid storage ) can go with just one replica but we will seek consensus with notary’s per application on the minimum requirements on each client / dataset.  Please note that in all examples below we seek SLA documents from SP’s with penalty fees and we solely discuss unforeseen disasters.  Our suggested guideline: Dataset for commercial use, non-critical and not recoverable when SP go offline in case of bankruptcy etc: 1 replica’s, used for testing Dataset for commercial use, non-critical and not recoverable when one SP goes offline: 2 replica’s, used for verifiability of data. Dataset for commercial use, critical and recoverable when 2 SP’s go offline: 3 replica’s, used for verifiability of data and backup. Dataset for commercial use, critical and recoverable for disaster recovery when 3 SP’s get offline: 5 replica’s, used for verifiability of data and disaster backup. Can be used in healthcare and other environments fe.  23. What geographic or regional distribution will you require? * That depends on the client's needs per above but we intend to only work with regions / SP’s where we are confident that there will be no blocking by unexpected governmental limitations or firewalls. Secondly for applications that require 3 or more replica’s we require 3 or more regions including unique geopolitical/language coverage, each replica at different physical location, no or minimal VPN and different SP owner operators. 24. How many Storage Provider owner/operators will you require to meet programmatic requirements for distribution? * That depends on the client's needs but we have build software tools that use statistics like IP quality scoring to track and trace Service providers whereabouts. Secondly we look on chain for IP addresses where the SP’s have originated. Thirdly we are using the tools from Protocol labs ( Check bot ). For applications that require 3 or more replica’s we require 3 or more regions including unique geopolitical/language coverage, each replica at different physical location, no or minimal VPN and different SP owner operators. Lastly we have a comprehensive log of last months which service provide belongs to who.

**24. How many Storage Provider owner/operators will you require to meet programmatic requirements for distribution?:**
5+

**25. Do you require equal percentage distribution for your clients to their chosen SPs? Will you require preliminary SP distribution plans from the client before allocating any DataCap?:**
Yes, we will require preliminary SP distribution plans and equal distribution if the term’s are set to store with multiple SP’s.

**26. What tooling will you use to verify client deal-making distribution?:**
We are using the CID checker bot, but also use the Fil+ API together with our own software tools built in Retool to check what is stored and where. The governance team is familiar with those we believe. If needed we are open to discuss making them open source.

**27. How will clients meet SP distribution requirements?:**
We use Singularity and our own distribution software where sharding is enabled to make sure that distribution is equal. We monitor this according to point 26 with the CID check bot and our own software.

**28. As an allocator, do you support clients that engage in deal-making with SPs utilizing a VPN?:**
No. We solely believe that storing commercial dataset’s should not be done on VPN’s. See point 23: we intend to only work with regions / SP’s where we are confident that there will be no blocking by unexpected governmental limitations or firewalls.
### DataCap Allocation Strategy
**29. Will you use standardized DataCap allocations to clients?:**
Yes, standardized

**30. Allocation Tranche Schedule to clients::**
• First: 10%
• Second: 20%
• Third: 35%
• Fourth: 35%
• Max per client overall: 100%.

The amount of PiB depends on the scale of the commercial data that is stored. We can imagine that the internet archive for example would need more datacap than a simple ICT company for a one time offline backup. See point 29.



**31. Will you use programmatic or software based allocations?:**
Yes, standardized and software based

**32. What tooling will you use to construct messages and send allocations to clients?:**
We will either use something available ( preferred ) or write something ourselves that keeps track of the messages sent etc. Available tools are the CLI of lotus daemon itself to send datacap, but also the Fil+  registry software panel. It is not clear to us if there are still notary’s in the loop together with the allocators. Notary’s will still use something like the Fil+ registry to grant datacap.

**33. Describe the process for granting additional DataCap to previously verified clients.:**
We will use the SA bot to alert when there is less then 25% of datacap available or write similar software in case it is unavailable for use.

**34. Describe in as much detail as possible the tools used for: • client discoverability & applications • due diligence & investigation • bookkeeping • on-chain message construction • client deal-making behavior • tracking overall allocator health • disput:**
• client discoverability & applications
We will create a public Github repository where we will keep track of the clients applications and where clients can submit their applications.
• due diligence & investigation
We will do this with Github to have it open towards the community.
• bookkeeping

We will do this with Github to have this open towards the community.
• on-chain message construction

See question 32. We will either use something available ( preferred ) or write something ourselves that keeps track of the messages sent etc. Available tools are the CLI of lotus daemon itself to send datacap, but also the Fil+ software panel. It is not clear to us if there are still notary’s in the loop together with the allocators. Notary’s will still use something like the Fil+ software to grant datacap.
• client deal-making behavior

We intend to use both our custom software that we will open source or make accessible on request, together with the current tooling of PL ( The CID checker bot ). We also build a API on the retrieval bot statistics that we will use to make decisions.
• tracking overall allocator health
We intend to use both our custom software that we will open source or make accessible on request, together with the current tooling of PL ( The CID checker bot ).
• dispute discussion & resolution
We intend to use a software tool like https://civicrm.org/ 
CiviCRM is a powerful, web-based CRM software that is particularly popular among non-profits, civic sector organizations, and advocacy groups. Its flexibility makes it suitable for managing various community interactions, including dispute resolution.
- Key Features:
    - Case Management: It offers robust case management features that can be used to track and handle disputes. Each case can encompass all relevant information, activities, and communications.
    - Customizable Workflows: You can create custom workflows to reflect the specific steps and stages of your dispute resolution process.
    - Communication Tracking: CiviCRM allows for the logging and tracking of all communications related to a case, ensuring transparency and accountability.
    - User Access Control: Different levels of access can be set for different users, ensuring that sensitive information is only accessible to authorized personnel.
- Benefits for Community Dispute Resolution:
    - Versatility: It can be used for a wide range of community management tasks beyond dispute resolution, including contact management and event organization.
    - Integration Capabilities: CiviCRM can be integrated with other platforms and websites, enhancing its functionality and ease of use.
    - Community Support: Being a popular open-source tool, it has a strong community support base, which can be invaluable for troubleshooting and enhancements.
- Open Source Advantage:
    - As an open-source platform, CiviCRM offers the flexibility to modify and extend its features to suit the specific needs of your dispute resolution process.
- Considerations:
    - CiviCRM is quite comprehensive and may require some technical know-how to set up and customize effectively for dispute resolution purposes.
    - You'll need to ensure that your implementation of CiviCRM adheres to data security and privacy standards, especially when handling sensitive dispute-related information.
Using CiviCRM for dispute resolution in a community like Filecoin's involves leveraging its case management and communication tracking features to ensure disputes are handled transparently, efficiently, and fairly.

Note: This software is a suggestion. If the governance team has alternatives we are open to conside those.
• community updates & comms *

We will create a webpage for this that visualizes all tools available and reports on outage of maintenance.
### Tools and Bookkeeping
**35. Will you use open-source tooling from the Fil+ team?:**
Yes. We intend to use all resources available.   CID checker bot CID retrieval bot. Sa bot. Vercel.app ( Retrieval bot statistics ) Fil+ notary panel datacapstats.io ( and it’s API ). And others if available.

**36. Where will you keep your records for bookkeeping? How will you maintain transparency in your allocation decisions?:**
Github for the public accessible information:

- Application info, diligence info that is public ( Size / type of dataset etc ) and statistics about the datacap and distribution ( What / where / to who and when )  + retrievability statistics etc go on Github.
- Veriff for the KYC / KYB information. This information stays private but is available to the governance team on request.
- Warnings about non compliance go on github together with the reason / cause.
- Termination of cooperation after warnings go on github together with the reason / cause.
- CRM software for dispute resolution like Civicrm ( See above ).
### Risk Mitigation, Auditing, Compliance
**37. Describe your proposed compliance check mechanisms for your own clients.:**
Client Onboarding Verification:
Implement strict verification processes during client onboarding. This includes validating business registration documents, VAT numbers, and any relevant certifications + KYC / KYB.
Conduct background checks to ensure clients have a legitimate business presence and no history of fraudulent activities.
Data Usage and Storage Policy Agreement:
Require clients to sign a policy agreement that outlines acceptable use of DataCap, data storage protocols, and compliance with legal regulations.
Clearly define the consequences of policy violations.
Automated Monitoring System:
Utilize automated tools described above to monitor client data usage and storage patterns. This can help in identifying any unusual activities or deviations from agreed-upon terms.
Set up alerts for when clients approach their DataCap limits or exhibit potential non-compliant behavior.
Regular Compliance Audits:
Schedule regular audits of client data storage practices, ensuring adherence to Filecoin’s standards and your own compliance rules.
Include checks for data security, encryption standards, and data integrity.
Documentation and Reporting:
Keep detailed records of all client interactions, DataCap allocations, and compliance checks on Github for review by the community.
Implement a standardized reporting system for clients to submit their data usage and storage reports periodically.
Client Training and Resources:
Provide educational resources and training sessions to clients about best practices in data storage, security, and compliance within the Filecoin network. ( A client should attend at least 2 ).
Encourage open communication for clients to ask questions or report issues.
Response Plan for Non-Compliance:
Develop a clear response plan for instances of non-compliance. This may include warnings, reduction or removal of DataCap, and in severe cases, termination of services.
Ensure that the response plan is transparent and understood by all clients.
Feedback and Improvement Mechanism:
Create a feedback loop with clients to continuously improve compliance mechanisms based on real-world usage and challenges.
Stay updated with Filecoin network updates and global compliance standards to refine your strategies.

How will you track and audit your own DataCap distribution, and the downstream usage by your clients? How much tolerance will you have for new clients? *

DataCap Distribution Tracking System:
We will Establish a robust tracking system that records every allocation of DataCap to clients. This system includes client details, amount of DataCap allocated and dates of allocation.
Client Usage Monitoring:
We will develop or integrate a monitoring tool that tracks how clients are utilizing their allocated DataCap. This includes tracking the volume of data stored where and when.
We will set up alerts for unusual patterns or behaviors that might indicate misuse or deviation from agreed terms.
Risk Assessment for New Clients:
We will implement a risk assessment protocol for new clients. This involves a tiered approach where new clients start with a smaller DataCap allocation and earn more as they demonstrate compliant usage.
We will conduct more frequent audits and reviews for new clients until they establish a history of compliant behavior.
Regular Audits and Compliance Checks:
We will schedule regular audits of both DataCap distribution and client usage. These audits should assess compliance with our policies and Filecoin's regulations.
Include both automated checks and manual reviews in the audit process.
Zero Tolerance for Illegal Activities:
We maintain a zero-tolerance policy for illegal activities. Any client found using DataCap for unlawful purposes should face immediate action.
For other types of non-compliance, we consider a graduated response depending on the severity and frequency of the violation.
Documentation and Reporting:
We keep detailed documentation of all DataCap distributions and the results of usage audits on Github. This will be crucial for internal reviews and responding to any disputes or inquiries.
Regularly report these findings internally and, if required, to the Filecoin community or relevant authorities.
Client Feedback and Intervention Mechanism:
Allow clients to report their usage and provide feedback on their needs and challenges. This can help in adjusting policies for better compliance and client satisfaction.
Set up a clear mechanism for intervening when clients are close to exceeding their allocated DataCap or are showing signs of non-compliance.
Tolerance Levels for New Clients:
We will define clear tolerance levels for new clients, balancing the need for compliance with the opportunity for them to prove their reliability. This could include a probationary period with more frequent checks and lower DataCap allocations.
Gradually increase tolerance as clients demonstrate compliance and trustworthiness over time.


**38. Describe your process for handling disputes. Highlight response times, transparency, and accountability mechanisms.:**
To handle disputes effectively within the context of DataCap allocation on the Filecoin network, it is crucial to establish a clear, transparent, and accountable process. We suggest the following:
Dispute Intake and Initial Assessment:
We set up a dedicated channel (e.g., email, portal on Civicrm) for clients or involved parties to raise disputes.
Upon receiving a dispute, conduct an initial assessment to categorize the issue (e.g., DataCap allocation, compliance issues, storage deal conflicts or NOTD).
Acknowledge receipt of the dispute within 24 hours to ensure the parties involved know their concerns are being addressed.
Transparent Documentation and Tracking:
Maintain a log of all disputes, including details of the parties involved, the nature of the dispute, and any initial evidence or claims.
Use a case management system in CiviCRM to track the progress of each dispute, ensuring no case is overlooked or delayed.
Investigation and Information Gathering:
Assign a dedicated team or individual to investigate the dispute. This might involve gathering data logs, contract details, communication records, and any other relevant information.
Ensure that the investigation is thorough and unbiased, seeking to understand all aspects of the dispute.
Response Time and Communication:
Aim to provide an initial response or update within a set timeframe (e.g., 48-72 hours) after the dispute is logged.
Keep all parties informed throughout the investigation process, maintaining transparency about the steps being taken.
Resolution and Mediation:
Once sufficient information is gathered, propose a resolution based on the findings. In cases where a simple resolution is not possible, consider mediation between parties.
Ensure that the resolution is fair, aligns with Filecoin’s guidelines, and respects the terms agreed upon by the parties involved.
Accountability and Enforcement:
Implement the agreed-upon resolution, ensuring that all parties adhere to the decision.
Hold parties accountable for any breach of agreement or misconduct identified during the dispute resolution process.
Review and Feedback:
After resolution, review the handling of the dispute to identify any areas for improvement in the process.
Seek feedback from the parties involved to understand their experience of the dispute resolution process and to make necessary adjustments.
Reporting and Learning:
Document key learnings from each dispute to refine your processes and prevent similar issues in the future.
Regularly review dispute trends to identify systemic issues or areas requiring policy changes.
Public Reporting and Transparency:
Where appropriate, and respecting confidentiality, share summaries of dispute resolutions with the community to enhance transparency and trust.
Regularly update your dispute resolution policy and make it publicly available for clients and other stakeholders to review.
This process ensures that disputes are handled efficiently, transparently, and fairly, fostering trust among all parties involved in the Filecoin network. It also demonstrates a commitment to maintaining a high standard of service and accountability in our role as a notary allocator.


**39. Detail how you will announce updates to tooling, pathway guidelines, parameters, and process alterations.:**
We intend to do this by email and slack + on a dedicated website where and overview of all systems is given.

**40. How long will you allow the community to provide feedback before implementing changes?:**
For effective community engagement and feedback implementation in the context of a decentralized environment like the Filecoin network, it's important to strike a balance between openness and practical governance. Here's a structured approach to this process:
Setting a Standard Feedback Period:
Establish a standard period for community feedback on proposed changes. This period should be long enough to allow ample participation, typically ranging from 2 to 4 weeks, depending on the complexity and impact of the proposed changes.
Announcing Changes and Soliciting Feedback:
Clearly communicate any proposed changes to the community through multiple channels (Slack / Website / Mail etc). This ensures broad awareness and encourages participation.
Provide detailed information about the changes, including the rationale, expected impact, and any potential concerns.
Facilitating and Moderating Discussions:
Host moderated discussions, Q&A sessions, or webinars where community members can ask questions, seek clarifications, and voice opinions.
Ensure that moderation is fair and unbiased, allowing diverse viewpoints to be expressed while maintaining respectful and constructive discourse.
Diverse Channels for Feedback Collection:
Offer various channels for feedback, including surveys, online forums, direct emails, and possibly even offline meetings, to accommodate different preferences and ensure inclusivity.
Active Listening and Engagement:
Actively engage with the community during the feedback period. This includes responding to queries, participating in discussions, and acknowledging the receipt of feedback.
Weighing and Integrating Feedback:
After the feedback period, we review all input carefully. We consider the feasibility, impact, and alignment of the feedback with the overall goals and policies.
Weight feedback based on its relevance, the number of times a particular point is raised, and the overall benefit to the community and network.
Transparent Decision-Making:
Make decisions transparently, explaining how feedback was integrated into the final implementation.
In cases where certain feedback cannot be accommodated, provide clear explanations to the community.
Implementing and Reviewing Changes:
Implement changes in a phased manner, if possible, to monitor effects and make adjustments as needed.
Continuously review the impact of changes and remain open to further feedback and iterations.
Reporting Back to the Community:
After implementation, providing reports back to the community summarizing the feedback received, decisions made, and the rationale behind them.
This ensures accountability and maintains trust in the process.
By following this approach, we ensure that the community is actively involved in the decision-making process, their feedback is valued and considered, and that changes are implemented in a way that is transparent and aligned with the community's needs and expectations.


**41. Regarding security, how will you structure and secure the on-chain notary address? If you will utilize a multisig, how will it be structured? Who will have administrative & signatory rights?:**
We will create a multisig wallet that requires signatures from both Wijnand Schouten and Hidde Hoogland to authorize transactions. This enhances security by ensuring that no single party can unilaterally make changes or transactions.
Setting Up Signatory Rights:
We will ensure that both (Wijnand Schouten and Hidde Hoogland) have equal signatory rights. This means that both signatures are required for any transaction to take place.
Security Protocols:
We will implement robust security protocols for the multisig wallet. This includes secure storage of private keys, regular updating of wallet software, and the use of two-factor authentication (2FA) for access.
Backup and Recovery Plan:
We will create a backup and recovery plan in case of loss of access to the multisig wallet. This involves secure backups of private keys and having a predefined process for restoring access.
Audit and Compliance:
Regularly audit the wallet for any unusual activities or security threats.


**42. Will you deploy smart contracts for program or policy procedures? If so, how will you track and fund them?:**
No, no yet.
### Monetization
**43. Outline your monetization models for the services you provide as a notary allocator pathway.:**
Monetization structures may include staking and slashing collateral for clients or SPs based on compliance, as well as fees for services: application review, data prep, data clearinghouse distribution, or auditing.

Monetization is structured in 2 parts:

1:) Costs involving the initial application

For the application cost itself we suggest the following fee structure:

- First application and diligence : 
* Veriff costs ( +/- 100 USD for KYB or KYC )
* Labor costs ( +/- 250 USD for all comms and diligence / audit on the first allocation )
These are costs based on time.
Two training sessions ( labor costs +/- 200 USD ) are mandatory for first clients to make sure that they understand the rules and guidelines and agreements we make with them.
Cost involved per subsequent allocation:
Labor costs ( +/- 125 USD for all comms and diligence )
2:) Escrow service:
5% fee Receiving funds from paying clients and holding them in escrow during the transaction, then automatically disbursing them to the storage providers on a scheduled basis ( 36 months ). Because we offer a commercial service for commercial data this is a mandatory part to make sure that we only store valuable data on the network that’s payed for.

Discounts are negotiable based on client reputation.

**44. Describe your organization's structure, such as the legal entity and other business & market ventures.:**
DCENT BV is an innovative company in the Netherlands focusing on decentralized green storage solutions. They are specialized in eco-friendly practices, utilizing solar power for their operations. The company features cutting-edge technology, including 3rd Gen AMD CPUs and Nvidia GPUs, and ensures high-speed connectivity. As a legal entity, DCENT BV complies with European and Dutch data regulations, emphasizing data privacy and security. They are a significant European Storage Provider for the Filecoin/IPFS network, contributing to the decentralized web and secure data storage. For more detailed insights into their structure and business ventures, visit their website at www.dcent.nl.

**45. Where will accounting for fees be maintained?:**
We will use an escrow service that has a good reputation and is existing in the ecosystem as the primary choice. We are open for advice from the governance team. This service should have transparency and a high reputation. If nothing is available we aim to design a service ourselves in cooperation with Protocol labs. The other fees will be commercial invoices and not be available for the public.
### Past Experience, Affiliations, Reputation
**46. If you've received DataCap allocation privileges before, please link to prior notary applications.:**
https://github.com/filecoin-project/notary-governance/issues/678 https://github.com/filecoin-project/notary-governance/issues/414

**47. How are you connected to the Filecoin ecosystem? Describe your (or your organization's) Filecoin relationships, investments, or ownership.:**
As an individual, I bring over six years of experience in crypto mining and programming to the Filecoin community, being active since the 2020 spacerace. I co-founded Speedium and DCENT with Hidde. DCENT, as a leading European service provider, specializes in high-quality data onboarding to the Filecoin network, working extensively within the ecosystem. We are a major decentralized Filecoin node in Europe, offering global, reliable storage solutions. Our advanced networking capabilities, private IP backbone, and 100Gbit/s throughput place us at the forefront of this emerging technology. We maintain several Service Provider IDs: f01720359, f01771403, f01786387, f02095132, f02033496, and f02366527.

**48. How are you estimating your client demand and pathway usage? Do you have existing clients and an onboarding funnel?:**
We are already providing service to commercial customers. Our estimate is 365 days * 3 PiB of datacap daily that will be requested. We are aware that this estimation is based on the other applicants who might provide similar pathways but if there are none, we expect something like this.

**Comment by cryptowhizzard** [comment]
Hello,

Please note that I had to change Ledger. The new address is f1xk4bsgn3hjobod4hoovtt4iuivgocwhduzwabxa as updated above.

**Comment by kevzak** [comment]
## Datacap Request for Allocator
#### Address
> f2om4d4e33huuiphsjjvs7mkeafeoastu2gzfjsey
#### Datacap Allocated
> 5PiB
