### ISSUE TITLE
v5 Notary Allocator Application:RFfil

### ISSUE THREAD

**Issue by MikeH1999** [filecoin-project/notary-governance#1054]
# v5 Notary Allocator Application

To apply to be an allocator, organizations will submit one application for each proposed pathway to DataCap. If you will be designing multiple specific pathways, you will need to submit multiple applications. 

Please complete the following steps:
# 1. Fill out the information below and create a new GitHub Issue

1. Notary Allocator Pathway Name (This can be your name, or the name of your pathway/program. For example "E-Fil+"):RFfil
3. Organization Name:RFfil
4. On-chain address for Allocator (Provide a NEW unique address. During ratification, you will need to initialize this address on-chain): f1uci7zkbdvscvu5mklxwwafkqqn7qo7rwc6rfoxi
5. Country of Operation (Where your organization is legally based): HongKong
6. Region of Operation (What region will you serve?): All region
7. Type of Allocator, diligence process: (Automated/programmatic, Market-based, or Manual (human-in-the-loop at some phase): Market-based and Manual 
9. DataCap requested for allocator for 12 months of activity (This should be an estimate of overall expected activity. Estimate the total amount of DataCap you will be distributing to clients in 12 months, in TiB or PiB):150PiB

# 2. Access allocator application (download to save answers)
Click link below to access a Google doc version of the allocator application that can be used to save your answers if you are not prepared to fully submit the application in Step 3. https://docs.google.com/document/d/1-Ze8bo7ZlIJe8qX0YSFNPTka4CMprqoNB1D6V7WJJjo/copy

# 3. Submit allocation application 
Clink link below to access full allocator questionnaire and officially submit your answers:
https://airtable.com/appvyE0VHcgpAkt4Z/shrQxaAIsD693e1ns

Note: Sections of your responses WILL BE posted back into the GitHub issue tracking your application. 
The final section (Additional Disclosures) will NOT be posted to GitHub, and will be maintained by the Filecoin Foundation. 
Application information for notaries not accepted and ratified in this round will be deleted.

**Comment by Kevin-FF-USA** [comment]
Hi @MikeH1999 

Wanted to let you know this application has been received. Once you complete and submit the include Airtable (form) information - the public answers will be posted in a thread below soon. If you have any questions - please let me know.

**Comment by MikeH1999** [comment]
Submitted the include Airtable (form)

**Comment by Kevin-FF-USA** [comment]
Hi @MikeH1999,

Thanks for submitting to become and Allocator! Wanted to confirm this application has been received along with your completed Airtable form.

**Comment by Filplus-govteam** [comment]
### Basic Information
**1. Notary Allocator Pathway Name:**
RFfil

**2. Organization:**
RFfil

**3. On Chain Address for Allocator:**
f1uci7zkbdvscvu5mklxwwafkqqn7qo7rwc6rfoxi

**4. Country of Operation:**
HongKong

**5. Region(s) of operation:**
South America, North America, Japan, Oceania, Europe, Greater China, Asia minus GCR, Africa , Other

**6. Type of Allocator:**
Manual

**7. DataCap requested for allocator for 12 months of activity:**
150PiB

**8. Is your allocator providing a unique, new, or diverse pathway to DataCap? How does this allocator differentiate itself from other applicants, new or existing?:**
no

**9. As a member in the Filecoin Community, I acknowledge that I must adhere to the Community Code of Conduct, as well other End User License Agreements for accessing various tools and services, such as GitHub and Slack.:**
Acknowledge
### Client Diligence
**10. Who are your target clients?:**
Individuals learning about Filecoin, Small-scale developers or data owners, Enterprise Data Clients

**11. Describe in as much detail as possible how you will perform due diligence on clients.  If you are proposing an automated pathway, what diligence mechanism will you use to determine client eligibility?:**
1. Manually verify whether the customer's KYB and KYC information is consistent, such as using enterprise query tools from different countries, etc
2. Check if the data sample submitted by the customer is consistent with the situation reported by the company or individual
3. Whether the total amount of data replicas is consistent with the application, and whether the backend screenshot or S3 bucket display is available
4. Does the data have copyright and comply with local laws
5. Does the data have storage value, such as its contribution to humanity, society, and so on

**12. Please specify how many questions you’ll ask, and provide a brief overview of the questions.:**
https://github.com/nicelove666/ipfstt/issues/new/choose
Roughly confirm each question on the existing application form one by one
Here are some examples
First of all, we will check the applicant's company qualifications, such as company information, official website, and scale, and verify their identity by checking the official domain email with the business license attached.
Secondly, we will check whether their data samples have value and copyright relationships.
Thirdly, we will review the detailed information of the SP provided, such as geographical distribution.
etc

**13. Will you use a 3rd-party Know your client (KYC) service?:**
The following are some company information query websites in some countries
 China - Qichacha (https://www.qcc.com/)
 - Qichacha is a commonly used online platform in China for querying company information. It provides company registration details, shareholder information, business scope, credit ratings, and more.
 
 United States - U.S. Business Registry (https://www.usa.gov/business-search)
 - U.S. Business Registry is a website used for accessing company information in the United States. It provides access to federal and state-level company registration databases.

 United Kingdom - Companies House (https://www.gov.uk/government/organisations/companies-house)
 - Companies House is the official website for accessing company information in the United Kingdom. It provides access to registration and financial information of UK companies.

 Japan - Japan Corporate Number (https://www.houjin-bangou.nta.go.jp/)
 - Japan Corporate Number is a website used for accessing company registration information in Japan. It provides company registration numbers and basic information.

There are still many, I believe they can be found on the internet

**14. Can any client apply to your pathway, or will you be closed to only your own internal clients? (eg: bizdev or self-referral):**
any client

**15. How do you plan to track the rate at which DataCap is being distributed to your clients?:**
every day
### Data Diligence
**16. As an operating entity in the Filecoin Community, you are required to follow all local & regional regulations relating to any data, digital and otherwise. This may include PII and data deletion requirements, as well as the storing, transmit:**
Acknowledge

**17. What type(s) of data would be applicable for your pathway?:**
Public Open Dataset (Research/Non-Profit), Public Open Commercial/Enterprise

**18. How will you verify a client’s data ownership? Will you use 3rd-party KYB (know your business) service to verify enterprise clients?:**
Please refer to the answers to the 12th and 13th questions

**19.  How will you ensure the data meets local & regional legal requirements?:**
Compliance with privacy regulations: Ensure compliance with applicable privacy regulations when processing personal data, and ensure appropriate permission or explicit consent is obtained for the processing of sensitive personal data. Respect intellectual property rights, abide by intellectual property laws, and do not infringe on the copyrights, trademarks, or patents of others. When providing company information, ensure the legal source of the information and avoid infringing on the trade secrets of others. Comply with local company regulations: When searching for company information, understand and comply with local company laws and regulations. Do not abuse query results, and do not use them for illegal purposes or infringe on the rights and interests of others. Understanding data protection requirements: If you collect and process user personal data, ensure compliance with local and regional data protection requirements, including regulations on data collection, storage, processing, and security. Seeking legal professional advice: If you have specific legal issues or questions about specific regulations, it is best to consult local legal professionals to ensure that your activities comply with applicable legal requirements.

**20. What types of data preparation will you support or require?:**
Support any type of data preparation, offer paid data preparation services, support specific data shards, such as video data, logs, etc

**21. What tools or methodology will you use to sample and verify the data aligns with your pathway?:**
In the first round, regardless of the amount of datacap quota applied for, I will only allocate 50T. After being sealed, I will immediately use a retrieval tool to retrieve the complete data and verify whether it matches the sample, to prevent sector size abuse, sector filling, and other situations
### Data Distribution
**22. How many replicas will you require to meet programmatic requirements for distribution?:**
3+

**23. What geographic or regional distribution will you require?:**
Meeting distributed requirements in at least 3 different cities is sufficient

**24. How many Storage Provider owner/operators will you require to meet programmatic requirements for distribution?:**
3+

**25. Do you require equal percentage distribution for your clients to their chosen SPs? Will you require preliminary SP distribution plans from the client before allocating any DataCap?:**
I will not require proportional allocation because the situation of this SP is variable, as long as the existing rules are met, I will regularly use existing tools for inspection

**26. What tooling will you use to verify client deal-making distribution?:**
Existing datacaptstats.io tools, CID inspection robots, and various browser data, etc

**27. How will clients meet SP distribution requirements?:**
If possible, I will try to request them to use official software to distribute the data, or they have better methods

**28. As an allocator, do you support clients that engage in deal-making with SPs utilizing a VPN?:**
Supporting VPN for security reasons will require them to provide a proof of geographical location
### DataCap Allocation Strategy
**29. Will you use standardized DataCap allocations to clients?:**
Yes, standardized

**30. Allocation Tranche Schedule to clients::**
Some changes have been made based on existing rules
Firstly, allocate 50T to verify whether the data is consistent with the declaration
Secondly, allocate 10% of the total DataCap requested or 100% of the weekly allocation rate, whichever is smaller, up to a maximum of 1P
Thirdly, allocate 20% of the total DataCap requests or 100% of the weekly allocation rate, whichever is smaller, up to 1P
Fourth: Allocate 30% of the total DataCap requests or 200% of the weekly allocation rate, whichever is smaller, up to 1P
Up to 1P per time, until the overall upper limit is fully allocated
The overall upper limit for each customer is 10P

**31. Will you use programmatic or software based allocations?:**
Yes, standardized and software based

**32. What tooling will you use to construct messages and send allocations to clients?:**
Existing official tools

**33. Describe the process for granting additional DataCap to previously verified clients.:**
Using official open-source tools for processing

**34. Describe in as much detail as possible the tools used for: • client discoverability & applications • due diligence & investigation • bookkeeping • on-chain message construction • client deal-making behavior • tracking overall allocator health • disput:**
Those who can use official tools should use official tools, while others are as follows
Due diligence&investment, manual review is conducted here to ensure the validity of the data
Dispute discussion&resolution such as GitHub repo, Google spreadsheet
Community updates&comments slip, wechat, github
### Tools and Bookkeeping
**35. Will you use open-source tooling from the Fil+ team?:**
All use open-source tools from the Fil+team

**36. Where will you keep your records for bookkeeping? How will you maintain transparency in your allocation decisions?:**
Private information will be stored in one's own notebook, and those that need to be disclosed will be made into a Google spreadsheet, etc
### Risk Mitigation, Auditing, Compliance
**37. Describe your proposed compliance check mechanisms for your own clients.:**
I think using official tools can track these situations very well. As long as new customers pass the review, I think there is no problem, and then conduct data review according to question 21

**38. Describe your process for handling disputes. Highlight response times, transparency, and accountability mechanisms.:**
The response time will not exceed 72 hours, as we work here every day. It seems that there are two controversial aspects at present. The first is the situation of inconsistent data. If the data does not match the content of the application, I will ask the customer to explain it. If there is no objection from both parties after explanation, the dispute will be terminated. Otherwise, the remaining datacap will be removed, and LDN will be closed. If the data content does not meet the specifications, the remaining datacap will be immediately removed, LDN cannot be reapplied for even if it is closed due to this. The second issue is with the SP, which is inconsistent with the pre approved ones. LDN will be temporarily closed and the customer will be asked to explain and provide the latest SP information

**39. Detail how you will announce updates to tooling, pathway guidelines, parameters, and process alterations.:**
I will use all official tools as well as GitHub, Slack, WeChat, or other channels to make reminders

**40. How long will you allow the community to provide feedback before implementing changes?:**
5 working days

**41. Regarding security, how will you structure and secure the on-chain notary address? If you will utilize a multisig, how will it be structured? Who will have administrative & signatory rights?:**
LEDGER hardware wallet to protect my notarized address, only the technical leader of our team has this password

**42. Will you deploy smart contracts for program or policy procedures? If so, how will you track and fund them?:**
no
### Monetization
**43. Outline your monetization models for the services you provide as a notary allocator pathway.:**
Technical services are required and will be charged at a rate of 10 fil per occurrence

**44. Describe your organization's structure, such as the legal entity and other business & market ventures.:**
Due to our location in China, it is currently not convenient to disclose. We are a technical team dedicated to FIL

**45. Where will accounting for fees be maintained?:**
Chat records on social media or on the chain
### Past Experience, Affiliations, Reputation
**46. If you've received DataCap allocation privileges before, please link to prior notary applications.:**
no

**47. How are you connected to the Filecoin ecosystem? Describe your (or your organization's) Filecoin relationships, investments, or ownership.:**
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2137

**48. How are you estimating your client demand and pathway usage? Do you have existing clients and an onboarding funnel?:**
After reviewing the information on Slack and the applied LDN, it was found that this section is still quite popular

**Comment by kevzak** [comment]
## Datacap Request for Allocator
#### Address
> f2qlt2ancrjsiqvp72evgm5ifcplk5twdrol7mxgi
#### Datacap Allocated
> 5PiB

**Comment by Kevin-FF-USA** [comment]
Hi @MikeH1999

On the next Fil+ Allocator meeting we will be going over each refill application. Wanted to ensure you were tracking the review discussion taking place in https://github.com/filecoin-project/Allocator-Governance/issues/11

If your schedule allows, recommend coming to the May 28th meeting to answer/discuss the issues raised in the recent distributions. This will allow you to faster address - or, the issue in Allocator Governance for ongoing written discussion.

Warmly,
-Kevin
https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles
![image](https://github.com/filecoin-project/notary-governance/assets/94004586/fae7a048-f67a-4b5d-9884-187f9f0de261)

**Comment by galen-mcandrew** [comment]
## Datacap Request for Allocator
#### Address
> f2qlt2ancrjsiqvp72evgm5ifcplk5twdrol7mxgi
#### Datacap Allocated
> 2.5PiB

**Comment by galen-mcandrew** [comment]
https://filfox.info/en/message/bafy2bzacebyxgn6hvkojbysa66rvba4g4o2ov53tr2h27ijdkxqb6ognecpsk?t=1

**Comment by galen-mcandrew** [comment]
## DataCap Request for Allocator
#### Address
> f2qlt2ancrjsiqvp72evgm5ifcplk5twdrol7mxgi
#### Datacap Allocated
> 5PiB

**Comment by galen-mcandrew** [comment]
https://filfox.info/en/message/bafy2bzacecnsaipyqks46cj3souo7neg7q4k6lbsmnizndmkddxo3mhme7tb4

**Comment by galen-mcandrew** [comment]
## Datacap Request for Allocator
#### Address
> f2qlt2ancrjsiqvp72evgm5ifcplk5twdrol7mxgi
#### Datacap Allocated
> 10PiB

**Comment by galen-mcandrew** [comment]
bafy2bzaceaehfukte35dxuakba4ubpejr3wx5urm4ohyildkbxml2jlyxetl2
