### ISSUE TITLE
v5 Notary Allocator Application: EF

### ISSUE THREAD

**Issue by Lind111** [filecoin-project/notary-governance#1056]
# v5 Notary Allocator Application

To apply to be an allocator, organizations will submit one application for each proposed pathway to DataCap. If you will be designing multiple specific pathways, you will need to submit multiple applications. 

Please complete the following steps:
# 1. Fill out the information below and create a new GitHub Issue

1. Notary Allocator Pathway Name (This can be your name, or the name of your pathway/program. For example "E-Fil+"):EF
3. Organization Name: EF
4. On-chain address for Allocator (Provide a NEW unique address. During ratification, you will need to initialize this address on-chain): f13ujyzruulb6isvjlto2snyj5weptr4shqbh4bvq
5. Country of Operation (Where your organization is legally based): China
6. Region of Operation (What region will you serve?):  Entire world
7. Type of Allocator, diligence process: (Automated/programmatic, Market-based, or Manual (human-in-the-loop at some phase): Market-based & Manual
9. DataCap requested for allocator for 12 months of activity (This should be an estimate of overall expected activity. Estimate the total amount of DataCap you will be distributing to clients in 12 months, in TiB or PiB):200PiB

# 2. Access allocator application (download to save answers)
Click link below to access a Google doc version of the allocator application that can be used to save your answers if you are not prepared to fully submit the application in Step 3. https://docs.google.com/document/d/1-Ze8bo7ZlIJe8qX0YSFNPTka4CMprqoNB1D6V7WJJjo/copy

# 3. Submit allocation application 
Clink link below to access full allocator questionnaire and officially submit your answers:
https://airtable.com/appvyE0VHcgpAkt4Z/shrQxaAIsD693e1ns

Note: Sections of your responses WILL BE posted back into the GitHub issue tracking your application. 
The final section (Additional Disclosures) will NOT be posted to GitHub, and will be maintained by the Filecoin Foundation. 
Application information for notaries not accepted and ratified in this round will be deleted.

**Comment by Kevin-FF-USA** [comment]
Hi @Lind111,

Thanks for submitting to become and Allocator! Wanted to confirm this application has been received along with your completed Airtable form.

**Comment by Filplus-govteam** [comment]
### Basic Information
**1. Notary Allocator Pathway Name:**
EF

**2. Organization:**
EF

**3. On Chain Address for Allocator:**
f13ujyzruulb6isvjlto2snyj5weptr4shqbh4bvq

**4. Country of Operation:**
China

**5. Region(s) of operation:**
Africa , Asia minus GCR, Greater China, Europe, Oceania, Japan, North America, South America

**6. Type of Allocator:**
Manual

**7. DataCap requested for allocator for 12 months of activity:**
200PiB

**8. Is your allocator providing a unique, new, or diverse pathway to DataCap? How does this allocator differentiate itself from other applicants, new or existing?:**
By manually distributing and labeling the data manually, you can differentiate the available data. This approach helps you better manage and organize your data, making it easier to understand and use.
During the data distribution process, labels are used to mark the characteristics or attributes of each data set. These labels can be descriptive words, numbers, or other identifiers, depending on your needs and preferences. For example, you can use tags to indicate the source, type, time frame, geographic location, etc. of the data.


**9. As a member in the Filecoin Community, I acknowledge that I must adhere to the Community Code of Conduct, as well other End User License Agreements for accessing various tools and services, such as GitHub and Slack.:**
Acknowledge
### Client Diligence
**10. Who are your target clients?:**
Individuals learning about Filecoin, Small-scale developers or data owners, Enterprise Data Clients

**11. Describe in as much detail as possible how you will perform due diligence on clients.  If you are proposing an automated pathway, what diligence mechanism will you use to determine client eligibility?:**
We will ask the customer to provide supporting documents, and may also require the customer to provide proof of business registration, tax registration certificates and other relevant documents.
In order to verify the identity of the customer, we will verify the identity verification documents provided by the customer by comparing them with information from public databases or other reliable sources.
In addition, we will also conduct a background check on the customer to find out his/her past credit history, criminal records, legal disputes, etc. This can be done by checking credit reporting agencies, court records, and other relevant databases.
Finally, we will assess the client's risk level, including factors such as his or her financial condition, business history, and industry background. This will help us determine the potential risk and creditworthiness of the client.

**12. Please specify how many questions you’ll ask, and provide a brief overview of the questions.:**
Introduce yourself/your organization (with links);
Example use cases and scope;
Geographic location of customers;
Number of DataCap allocation requests;
Filecoin on-chain address;
Copyright notice and legal compliance requirements;
Specific requirements for miners and warehousing services
Nature of business (government, public, private, NGO)

**13. Will you use a 3rd-party Know your client (KYC) service?:**
Yes, we use KYC as a third party service.
Verify business entity information by going to relevant information websites based on customer information
Search the name of the business on social media platforms (e.g. LinkedIn) to view its page and related information.
In addition, use inquiries ,(e.g. Yelp, Google My Business, etc.) to find information such as a business's address, phone number, and hours of operation.

**14. Can any client apply to your pathway, or will you be closed to only your own internal clients? (eg: bizdev or self-referral):**
We welcome any customer to apply for our services, whether internal or external, and we aim to provide high quality service and support to all our customers. Whether you are an individual user or a corporate user, we are ready to help you whenever you need it.

**15. How do you plan to track the rate at which DataCap is being distributed to your clients?:**
We will use an advanced monitoring system to monitor DataCap's distribution rate in real time. The system will collect and analyze relevant data and generate detailed reports so that we can understand the actual distribution situation. We will maintain close contact with our customers and collect their feedback and comments on a regular basis. This will help us understand their experience with DataCap and any potential problems or limitations.
### Data Diligence
**16. As an operating entity in the Filecoin Community, you are required to follow all local & regional regulations relating to any data, digital and otherwise. This may include PII and data deletion requirements, as well as the storing, transmit:**
Acknowledge

**17. What type(s) of data would be applicable for your pathway?:**
Public Open Dataset (Research/Non-Profit), Public Open Commercial/Enterprise

**18. How will you verify a client’s data ownership? Will you use 3rd-party KYB (know your business) service to verify enterprise clients?:**
For data, we verify the ownership of the data, whether there is a watermark, and query according to the sample provided by the label customer, and strictly verify the data compliance according to the third-party KYB service.



**19.  How will you ensure the data meets local & regional legal requirements?:**
We consult with local laws and regulations to ensure that data management activities comply with local laws and regulations, and conduct regular compliance reviews.

**20. What types of data preparation will you support or require?:**
 We support various types of data preparation and data slicing.

**21. What tools or methodology will you use to sample and verify the data aligns with your pathway?:**
We can use methods such as random sampling or stratified sampling to select a portion of the sample from the client's data for validation. This will help us ensure that the sample is representative and accurately reflects the characteristics of the entire dataset. We will also conduct a manual review. Professional data analysts will scrutinize the data and compare it with the information provided by the client to ensure consistency and accuracy. We will clearly agree sector size requirements with the client and ensure that both parties are in agreement on this. This will help prevent sector size abuse.
### Data Distribution
**22. How many replicas will you require to meet programmatic requirements for distribution?:**
4+

**23. What geographic or regional distribution will you require?:**
 3 physical locations At least 2 separate geopolitical regions Not less than 4 or more SP entities

**24. How many Storage Provider owner/operators will you require to meet programmatic requirements for distribution?:**
4+

**25. Do you require equal percentage distribution for your clients to their chosen SPs? Will you require preliminary SP distribution plans from the client before allocating any DataCap?:**
Each batch of data is distributed over more than 4 sp's with no more than 30% stored on each sp. Public program description on Github

**26. What tooling will you use to verify client deal-making distribution?:**
Existing datacapstats.io tools and CID check bots

**27. How will clients meet SP distribution requirements?:**
Explicitly require customers to SP plans and specific distributions in advance on Github Manual selection and distribution of data: customers can use their own tools or systems to manually select the data to be distributed and send it to SPs

**28. As an allocator, do you support clients that engage in deal-making with SPs utilizing a VPN?:**
We don't support VPN, we ask customers to provide the real address of sp and related materials.
### DataCap Allocation Strategy
**29. Will you use standardized DataCap allocations to clients?:**
Yes, standardized

**30. Allocation Tranche Schedule to clients::**
Distribution according to existing rules
5% of the first DataCap total, or 50% of the weekly allocation rate, whichever is lower
Second 10% of total DataCap or 100% of weekly allocation rate, whichever is less
Third 20% of total DataCap or 200% of the weekly allocation rate, whichever is less
Fourth 40% of total DataCap or 400% of the weekly allocation rate, whichever is less
Overall cap of 8P for a single client for a single application


**31. Will you use programmatic or software based allocations?:**
Yes, standardized and software based

**32. What tooling will you use to construct messages and send allocations to clients?:**
filplus.fil.org website I really like with proficiency

**33. Describe the process for granting additional DataCap to previously verified clients.:**
I love how easy and quick the follow up distribution bot is now!

**34. Describe in as much detail as possible the tools used for: • client discoverability & applications • due diligence & investigation • bookkeeping • on-chain message construction • client deal-making behavior • tracking overall allocator health • disput:**
To ensure the reliability and security of the application, use platforms such as the website, GitHub, and Discord to track and manage application processes, as well as custom programmed Excel sheets to handle bookkeeping. 
For users in the Filecoin Boost community, Discord and GitHub, Slack, and other platforms can be used to track and monitor their transactions to ensure compliance and security.
In order to monitor the health of your allocator in real-time, you can use a customized dashboard for tracking and monitoring. This will help you identify and resolve potential issues in a timely manner.
When dealing with disputes, you can utilize platforms such as Discord, Slack, and GitHub to discuss and communicate in order to reach consensus and resolve issues.
Community Updates & Newsletters*,Slack github Discord,Linkdin, Twitter, Facebook, Medium, etc.- Websites, etc.

### Tools and Bookkeeping
**35. Will you use open-source tooling from the Fil+ team?:**
GitHub repository to create a repository to which the files of the dataset will be uploaded  You can use Google Spreadsheets to record and manage information about a dataset, such as the dataset's name, description, file size, and so on. You can create different worksheets to track information about different datasets MongoDB is an open source NoSQL database that can store and retrieve large amounts of unstructured data. You can use MongoDB to store metadata and other relevant information about a dataset. IPFS IPFS is a distributed file system that stores files on multiple nodes and provides persistence and availability. You can use IPFS to host your datasets and link them to the Filecoin network. Inspector App Bot etc.

**36. Where will you keep your records for bookkeeping? How will you maintain transparency in your allocation decisions?:**
GitHub Repository: publicly store summaries, links to documents, etc. of due diligence and customer information in a GitHub repository.
Issue Tracker: Use GitHub's Issue Tracker to log and resolve any issues or disputes related to the dataset.
Private Methods,Email Communications,Engage in private email communications with relevant parties to discuss and share details of due diligence and customer information,Encrypted Files,Store sensitive due diligence and customer information in encrypted files and share the decryption key with relevant parties.

Public information:Store some due diligence and customer information publicly on a public platform so that it can be viewed and audited by members of the community. This information should include basic information about the dataset, its source, terms of use, etc.
Dispute Resolution Mechanism: Establish a clear dispute resolution mechanism so that community members can raise objections or disputes as needed. Provide the necessary information to resolve disputes or conduct audits as requested by the Fil+ governance team.
Transparent communication: Maintain open and transparent communication with community members and respond to their queries and concerns in a timely manner. This can be done through comments on public platforms (e.g. GitHub), issue trackers, or dedicated community forums.

### Risk Mitigation, Auditing, Compliance
**37. Describe your proposed compliance check mechanisms for your own clients.:**
Establish regular communication channels with customers, such as monthly or quarterly meetings, to understand their business operations and data usage. Online chat tools are available for this.
Track DataCap distribution metrics: set up a system to track and manage your customers' DataCap distribution. This can include recording information such as distribution volume, frequency and target audience for each client. This can be done using spreadsheets or specialized data management tools.
Conduct a trust assessment of new customers to ensure they meet your compliance standards. This can include verifying their identity, checking their business background and reputation, etc. You might consider partnering with a third-party organization for reports on customer credit and compliance
Monitor customer data usage with tools such as CID checkers and retrievable bots, which can help detect potential breaches, such as unauthorized data copying or sharing.

**38. Describe your process for handling disputes. Highlight response times, transparency, and accountability mechanisms.:**
When a dispute request is received, within 72 hours and document the request. Ensure that all relevant details and evidence are recorded for follow-up.
Conduct an investigation and analysis to understand the background and cause of the dispute. This may involve communicating with relevant parties, collecting evidence and data, and conducting necessary due diligence.
Develop a fair and reasonable decision based on the results of your investigation and analysis. Ensure that your decision is in line with relevant compliance requirements and policies.
Maintain transparency and proactive communication with relevant parties throughout the processing. Explain the basis and process of your decision-making and provide the necessary information and support.
If the dispute involves other notaries or the Fil+ Governance Team, and provide the necessary support and cooperation. Follow the Fil+ Governance Team's guidelines and procedures for resolving disputes.




**39. Detail how you will announce updates to tooling, pathway guidelines, parameters, and process alterations.:**
Maintain a public folder under your github account and use the tool's update email notifications publicly.

**40. How long will you allow the community to provide feedback before implementing changes?:**
7 days 

**41. Regarding security, how will you structure and secure the on-chain notary address? If you will utilize a multisig, how will it be structured? Who will have administrative & signatory rights?:**
I would use a hardware wallet (Ledger) to manage it and the signing would be done by the administrator reviewing the client's application.

**42. Will you deploy smart contracts for program or policy procedures? If so, how will you track and fund them?:**
There are no plans to do so at this time.
### Monetization
**43. Outline your monetization models for the services you provide as a notary allocator pathway.:**
There are no plans to monetize

**44. Describe your organization's structure, such as the legal entity and other business & market ventures.:**
At EF, we believe the world is a better place when people from different countries and cultures understand each other. Since its founding years ago, EF has helped millions of people see new landscapes, experience new cultures, and gain new insights into the world and themselves.

**45. Where will accounting for fees be maintained?:**
N/A
### Past Experience, Affiliations, Reputation
**46. If you've received DataCap allocation privileges before, please link to prior notary applications.:**
no

**47. How are you connected to the Filecoin ecosystem? Describe your (or your organization's) Filecoin relationships, investments, or ownership.:**
 https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2290 https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2094

**48. How are you estimating your client demand and pathway usage? Do you have existing clients and an onboarding funnel?:**
Existing customers

**Comment by Kevin-FF-USA** [comment]
Hi @Lind111

On the next Fil+ Allocator meeting we will be going over each refill application. Wanted to ensure you were tracking the review discussion taking place in https://github.com/filecoin-project/Allocator-Governance/issues/12.

If your schedule allows, recommend coming to the May 28th meeting to answer/discuss the issues raised in the recent distributions. This will allow you to faster address - or, the issue in Allocator Governance for ongoing written discussion.

Warmly,
-Kevin
https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles
![image](https://github.com/filecoin-project/notary-governance/assets/94004586/121d8426-fbfe-46e9-991d-48733771e0a7)

**Comment by galen-mcandrew** [comment]
## Datacap Request for Allocator
#### Address
> f27ltg7qozyhtei2otrpxouilznihitzhvt52l22a
#### Datacap Allocated
> 2.5PiB

**Comment by galen-mcandrew** [comment]
https://filfox.info/en/message/bafy2bzacedl4tztyb26tlju3qdgougssei5jdryuuk4xy5ul6xyggtzbisb66?t=4

**Comment by galen-mcandrew** [comment]
## DataCap Request for Allocator
#### Address
> f27ltg7qozyhtei2otrpxouilznihitzhvt52l22a
#### Datacap Allocated
> 5PiB

**Comment by galen-mcandrew** [comment]
https://filfox.info/en/message/bafy2bzacec26ropzdmmxohqaqll3s4znxuw6xfsvjp3tga7cobaxso5mfczz2

**Comment by galen-mcandrew** [comment]
## Datacap Request for Allocator
#### Address
> f27ltg7qozyhtei2otrpxouilznihitzhvt52l22a
#### Datacap Allocated
> 10PiB

**Comment by galen-mcandrew** [comment]
bafy2bzacecfu4vva6y2tyjdwx2r2ql3vehcdrk3hsnojhwyg5cj3gf6xjiqzu
