### ISSUE TITLE
v5 Notary Allocator Application:Bitmain USA

### ISSUE THREAD

**Issue by taft-chen** [filecoin-project/notary-governance#1076]
# v5 Notary Allocator Application

To apply to be an allocator, organizations will submit one application for each proposed pathway to DataCap. If you will be designing multiple specific pathways, you will need to submit multiple applications. 

Please complete the following steps:
# 1. Fill out the information below and create a new GitHub Issue

1. Notary Allocator Pathway Name (This can be your name, or the name of your pathway/program. For example "E-Fil+"):Bitmain USA
3. Organization Name:Bitmain USA
4. On-chain address for Allocator (Provide a NEW unique address. During ratification, you will need to initialize this address on-chain): f1n7bbtyuxpudbjiomiob4c7rhwofxlhv5dbi33uy
5. Country of Operation (Where your organization is legally based): America
6. Region of Operation (What region will you serve?): Asia (excluding Greater China), Greater China, Europe, North America, Japan
7. Type of Allocator, diligence process: (Automated/programmatic, Market-based, or Manual (human-in-the-loop at some phase): Manual
9. DataCap requested for allocator for 12 months of activity (This should be an estimate of overall expected activity. Estimate the total amount of DataCap you will be distributing to clients in 12 months, in TiB or PiB):150PiB

# 2. Access allocator application (download to save answers)
Click link below to access a Google doc version of the allocator application that can be used to save your answers if you are not prepared to fully submit the application in Step 3. https://docs.google.com/document/d/1-Ze8bo7ZlIJe8qX0YSFNPTka4CMprqoNB1D6V7WJJjo/copy

# 3. Submit allocation application 
Clink link below to access full allocator questionnaire and officially submit your answers:
https://airtable.com/appvyE0VHcgpAkt4Z/shrQxaAIsD693e1ns

Note: Sections of your responses WILL BE posted back into the GitHub issue tracking your application. 
The final section (Additional Disclosures) will NOT be posted to GitHub, and will be maintained by the Filecoin Foundation. 
Application information for notaries not accepted and ratified in this round will be deleted.

**Comment by Filplus-govteam** [comment]
### Basic Information
**1. Notary Allocator Pathway Name:**
Bitmain USA

**2. Organization:**
Bitmain USA

**3. On Chain Address for Allocator:**
f1n7bbtyuxpudbjiomiob4c7rhwofxlhv5dbi33uy

**4. Country of Operation:**
America

**5. Region(s) of operation:**
Greater China, Asia minus GCR, Europe, North America, South America

**6. Type of Allocator:**
Manual

**7. DataCap requested for allocator for 12 months of activity:**
150PiB

**8. Is your allocator providing a unique, new, or diverse pathway to DataCap? How does this allocator differentiate itself from other applicants, new or existing?:**
1.Diverse pathway: We will encourage individuals to apply store personal data for free storage and retrieval, expanding the impact of Filecoin. We will attract our partners to Filecoin to store data, including some university static datasets, enterprise datasets and more.
2.Responsible due diligence: We will conduct kyc verification on applicants, investigate their background, and avoid storing fake data and junk data to occupy Filecoin's storage space.
3.Training guidance service: Because Filecoin's data storage requires some professional knowledge and data processing capabilities, we will provide free training for application clients who do not have it.
4.Legal risk: We will combine data from different regions and the laws of different regions to determine whether the data is at legal risk. We firmly reject unproven data


**9. As a member in the Filecoin Community, I acknowledge that I must adhere to the Community Code of Conduct, as well other End User License Agreements for accessing various tools and services, such as GitHub and Slack.:**
Acknowledge
### Client Diligence
**10. Who are your target clients?:**
Individuals learning about Filecoin, Small-scale developers or data owners, Enterprise Data Clients

**11. Describe in as much detail as possible how you will perform due diligence on clients.  If you are proposing an automated pathway, what diligence mechanism will you use to determine client eligibility?:**
1. We conduct different levels of review based on the amount of DC the client is applying for, which includes when the client's company was founded, its main business, and its community involvement.
2. We ask the client to fill out an application form to obtain detailed information about the client and review it to ensure its authenticity.
3. Check the update cycle of the client through the client’s Twitter account and the client's official website to determine whether the client is active or not.
4. We request the client to provide a business license and related certificates
5. we will strictly review the data provided by the client to ensure that the data is legal and compliant.
6. We will also communicate with the client via email and Slack to get more detailed information to determine the client's eligibility


**12. Please specify how many questions you’ll ask, and provide a brief overview of the questions.:**
1. Please briefly introduce your information, how long has your company been established, and where is the registered address
2. Why do you want to apply for DataCap and what do you want to use it for?
3. Have you applied for DataCap before?
4. How much DataCap are you applying for this time?
5. What areas do you plan to use the DataCap in?
6. Do you confirm that you will strictly follow the Fil+ guidelines?

**13. Will you use a 3rd-party Know your client (KYC) service?:**
Yes. The KYC service requires us to review the actual account holder when we provide services to our clients to confirm whether the account holder or the actual beneficiary's clients are at risk of the existence of anti-money laundering laws, anti-terrorist financing, and other risks, to ensure compliance with the corresponding laws and regulations. We will select a KYC partner with a good reputation in the region according to the region where the client is located.

**14. Can any client apply to your pathway, or will you be closed to only your own internal clients? (eg: bizdev or self-referral):**
Any client can apply, in our opinion, Filecoin is diverse and inclusive!

**15. How do you plan to track the rate at which DataCap is being distributed to your clients?:**
We conduct real-time tracking daily and use open-source tools to assist in tracking and detecting the distribution of DataCap to ensure that DataCap is utilized fairly and efficiently.
### Data Diligence
**16. As an operating entity in the Filecoin Community, you are required to follow all local & regional regulations relating to any data, digital and otherwise. This may include PII and data deletion requirements, as well as the storing, transmit:**
Acknowledge

**17. What type(s) of data would be applicable for your pathway?:**
Public Open Dataset (Research/Non-Profit), Public Open Commercial/Enterprise, Private Commercial/Enterprise, Private Non-Profit/Social Impact

**18. How will you verify a client’s data ownership? Will you use 3rd-party KYB (know your business) service to verify enterprise clients?:**
We will verify the ownership of the client's data in 3 ways, which include document verification, data ownership attribution verification, and KYB service. Document verification is to ask client to provide business licenses and other legal documents. Data ownership attribution requires client to provide the source of data to ensure that the data is legally compliant, and we will also determine whether the data is valid through data matching. Finally, we will further verify the authenticity and validity of  client's data through the KYB service.

**19.  How will you ensure the data meets local & regional legal requirements?:**
1. Evaluate the data and storage methods according to the laws of the client's region to ensure legal compliance, and directly reject the data if it does not meet the local legal requirements.2. Detect any sensitive words in the data through big data recognition algorithms and take appropriate measures.

**20. What types of data preparation will you support or require?:**
Supports any type of data preparation

**21. What tools or methodology will you use to sample and verify the data aligns with your pathway?:**
We will make a search request and sample the data
### Data Distribution
**22. How many replicas will you require to meet programmatic requirements for distribution?:**
5+

**23. What geographic or regional distribution will you require?:**
We're requiring to be spread across 3 continents, 5 different countries.

**24. How many Storage Provider owner/operators will you require to meet programmatic requirements for distribution?:**
5+

**25. Do you require equal percentage distribution for your clients to their chosen SPs? Will you require preliminary SP distribution plans from the client before allocating any DataCap?:**
We wouldn't ask for equal proportions to be distributed, but we would ask for no more than 25% each, and ask the SP to provide a distribution plan and strictly adhere to it, and we'd do occasional checking to see if it's being followed.

**26. What tooling will you use to verify client deal-making distribution?:**
Datacapstats.io, bot, CID Checker

**27. How will clients meet SP distribution requirements?:**
1. The client first determines how many SPs he/she intends to work with 2. Selection of SP's geographical location and security factors 3. There is a clear distribution plan

**28. As an allocator, do you support clients that engage in deal-making with SPs utilizing a VPN?:**
If the SP is for security purposes and can provide proof of their real location, I have no problem about using a VPN. If the SP use VPN in order to cover up the real location, and there is no reasonable explanation, I think this is a kind of cheating behavior. We will inform the client in time, ask the client do not send data to the SP.
### DataCap Allocation Strategy
**29. Will you use standardized DataCap allocations to clients?:**
Yes, standardized

**30. Allocation Tranche Schedule to clients::**
First: Maximum 256T allocated in the first round
Second: Up to 512T in the second round
Third: Maximum 1P in the third round
Fourth: Max per client overall:2p
Max per client overall:2p
 

**31. Will you use programmatic or software based allocations?:**
Yes, standardized and software based

**32. What tooling will you use to construct messages and send allocations to clients?:**
I use https://filplus.fil.org/#/ 

**33. Describe the process for granting additional DataCap to previously verified clients.:**
1. The client needs to distribute the DC data to at least 4 or more miners. 2. SP retrieval rate must be greater than 20% and at least 5 copies must be kept. 3. Utilize tools for processing and checking, including but not limited to CID checker, etc.

**34. Describe in as much detail as possible the tools used for: • client discoverability & applications • due diligence & investigation • bookkeeping • on-chain message construction • client deal-making behavior • tracking overall allocator health • disput:**
client discoverability & applications : 
Client can learn about the company's products and services through Twitter and the official company website. They can also contact us via Twitter and email.
due diligence & investigation: 
We will communicate with customers through various means such as email, Slack, and phone to collect feedback and conduct detailed investigations.
bookkeeping：
Our company has deployed Lotus on our servers, which can be used for on-chain data and information transmission.
on-chain message construction：
Our company has deployed Lotus on our servers, which can be used for on-chain data and information transmission.
client deal-making behavior：
We use GitHub to track and record client transaction behavior.
dispute discussion & resolution：
We use GitHub, Slack, and Telegram to resolve disputes.
community updates & comms *：
We utilize various channels such as GitHub, Slack, Telegram, and email for community communication and updates. Additionally, we also post synchronously on our official Twitter and various social media platforms.

### Tools and Bookkeeping
**35. Will you use open-source tooling from the Fil+ team?:**
Yes, we will be using the open-source tools provided by the FIL+ team, including https://filplus.fil.org/#/ Github and Fil+.

**36. Where will you keep your records for bookkeeping? How will you maintain transparency in your allocation decisions?:**
We keep our allocation strategies updated in real-time on GitHub, and we are open and transparent. We also use appropriate privacy and security programs for client information, we do not disclose all client information but do provide some information to keep the community safe and transparent. All interactions are public and queries related to allocation decisions can be discussed openly.
### Risk Mitigation, Auditing, Compliance
**37. Describe your proposed compliance check mechanisms for your own clients.:**
1. First we provide an initial survey and assessment of our client. For every new client, we conduct a comprehensive survey to determine the legitimacy of their data storage needs, and some special customers are asked to undergo additional surveys.
2. We utilize tools such as datacapstats.io/CID checking bots to monitor the distribution of DataCap to ensure consistency of storage and allocation.
3. We are proactive in ensuring that all of our decisions are made publicly and transparently, we regularly showcase our activities on GitHub, and we are committed to maintaining the honesty and transparency of our community.
4. If a client is found to violate the law, we will first advise them and guide them to modify their violations, and if they continue to violate the law, we will blacklist them as a client and will not pass their application again. 

**38. Describe your process for handling disputes. Highlight response times, transparency, and accountability mechanisms.:**
For response time: when faced with a dispute, we will handle the dispute promptly and resolve it as soon as possible. We will endeavor to resolve disputes within 24 hours
For Transparency: When faced with a dispute, we will actively communicate with the parties involved in the dispute and provide appropriate explanations. In addition, we will use public channels including, but not limited to, GitHub, Telegram, zoom meetings, and so on.
Accountability: We will scrutinize and handle disputes appropriately, and any disputes will be handled fairly, openly, and transparently.


**39. Detail how you will announce updates to tooling, pathway guidelines, parameters, and process alterations.:**
1. We will tweet and post on GitHub to inform everyone of the changes to our tools, pathfinders, parameters, and processes, as well as on our official Twitter and social media platforms, and we will email our client to remind them of the changes in turn. 2. we'll explain why we're doing this update in emails and on GitHub and Twitter. 3. we have plans to create a separate channel for all customers to be alerted, so they don't miss out on my messages. Certain material programmatic changes or updates may be deemed out of scope by the Fil+ Governance Team and may require a reapplication to be scored against the rubric. For example, an 'update' from a single automated diligence process to include a new manual process may require a new notary allocator application.

**40. How long will you allow the community to provide feedback before implementing changes?:**
1. For small changes, we think 1 week would be sufficient
2. For large changes, we think we need about a month to discuss them in the community

**41. Regarding security, how will you structure and secure the on-chain notary address? If you will utilize a multisig, how will it be structured? Who will have administrative & signatory rights?:**
We use multiple signatures to protect notary addresses. For the choice of signers, we will choose from our employees and reputable people in the community.  in case of accidents , we will choose 4 people to be our signers, and the threshold is 2. We will train them on the security of multiple signatures and how to protect their signature addresses.

**42. Will you deploy smart contracts for program or policy procedures? If so, how will you track and fund them?:**
We don't have this idea at the moment, but we will consider it afterwards and list the options
### Monetization
**43. Outline your monetization models for the services you provide as a notary allocator pathway.:**
1.For client's technical consultation, we will be free.
2.For data inspection and statement audit, we will charge 10-100FIL depending on the client volume.
3.Find the right SP for the client, we will also be free.
4.If the client needs our help in processing and transferring data, we will charge 0.5FIL/T.

**44. Describe your organization's structure, such as the legal entity and other business & market ventures.:**
Established in 2013, BITMAIN is the world's leading manufacturer of cryptocurrency mining servers. The company's ANTMINER product has long maintained a leading position within the industry in terms of technical strength and market status. With cutting-edge technology in energy efficiency, the company offers advanced computational infrastructure and solutions to the global blockchain network.  Our company joined the Filecoin research in 2018. In 2021, we will start to invest in the construction of the mine, investing million +FIL to support the Filecoin project. We have established partnerships with many clients and Filecoin software vendors. We have also recommended Filecoin to btc partners. In the future, we will continue to promote the Filecoin network and attract more people to participate in Filecoin decentralized data storage.

**45. Where will accounting for fees be maintained?:**
We will have a fixed receiving address and be able to provide the community with a record of transactions that we can make public, we will keep a record of all communications and transactions on platforms such as Telegram and email, retaining these records for review by the community, and we will also develop a specialized transaction bookkeeping system for this purpose.
### Past Experience, Affiliations, Reputation
**46. If you've received DataCap allocation privileges before, please link to prior notary applications.:**
https://github.com/filecoin-project/notary-governance/issues/642

**47. How are you connected to the Filecoin ecosystem? Describe your (or your organization's) Filecoin relationships, investments, or ownership.:**
Bitmain is committed to supporting the Filecoin ecosystem in various ways. We created Filecoin miners, worked with the community's clients, and stored a lot of real data. We actively promote the Filecoin network and products to our partners. Always establish effective communication with the Filecoin community. In the future, we will invest more money and people to support the development of Filecoin.

**48. How are you estimating your client demand and pathway usage? Do you have existing clients and an onboarding funnel?:**
Client demand can be predicted by the amount of past allocations.  Our company is currently selling FIL miners on our official website, with positive feedback from our client, and several client have had in-depth conversations with us in this regard and want to participate with us. Our channel is through our official website email and various social channels to encourage client to join and promote the positive development of the whole community.

**Comment by taft-chen** [comment]
I need to change the chain address to a dedicated address.
the new address is: f1foffaxmwijkw7hlhoqd5weighivmhkcr5xfeqsy

**Comment by galen-mcandrew** [comment]
## Datacap Request for Allocator
#### Address
> f2trnpa3qxldhtpxaf4u5pu75kzvus3pqbnl6ttiq
#### Datacap Allocated
> 5PiB
