### ISSUE TITLE
v5 Notary Allocator Application:New Web Group

### ISSUE THREAD

**Issue by newwebgroup** [filecoin-project/notary-governance#1080]
# v5 Notary Allocator Application

To apply to be an allocator, organizations will submit one application for each proposed pathway to DataCap. If you will be designing multiple specific pathways, you will need to submit multiple applications. 

Please complete the following steps:
# 1. Fill out the information below and create a new GitHub Issue

1. Notary Allocator Pathway Name (This can be your name, or the name of your pathway/program. For example "E-Fil+"):New Web Group
3. Organization Name:New Web Group
4. On-chain address for Allocator (Provide a NEW unique address. During ratification, you will need to initialize this address on-chain): f1knqrv2si4d4piqlw7deq4p3t5cejtn7e6nq4jxq
5. Country of Operation (Where your organization is legally based): Greater China Region (GCR)
6. Region of Operation (What region will you serve?): All Regions
7. Type of Allocator, diligence process: (Automated/programmatic, Market-based, or Manual (human-in-the-loop at some phase): Manual
9. DataCap requested for allocator for 12 months of activity (This should be an estimate of overall expected activity. Estimate the total amount of DataCap you will be distributing to clients in 12 months, in TiB or PiB):200PiB

# 2. Access allocator application (download to save answers)
Click link below to access a Google doc version of the allocator application that can be used to save your answers if you are not prepared to fully submit the application in Step 3. https://docs.google.com/document/d/1-Ze8bo7ZlIJe8qX0YSFNPTka4CMprqoNB1D6V7WJJjo/copy

# 3. Submit allocation application 
Clink link below to access full allocator questionnaire and officially submit your answers:
https://airtable.com/appvyE0VHcgpAkt4Z/shrQxaAIsD693e1ns

Note: Sections of your responses WILL BE posted back into the GitHub issue tracking your application. 
The final section (Additional Disclosures) will NOT be posted to GitHub, and will be maintained by the Filecoin Foundation. 
Application information for notaries not accepted and ratified in this round will be deleted.

**Comment by Filplus-govteam** [comment]
### Basic Information
**1. Notary Allocator Pathway Name:**
New Web Group (E-Fil+)

**2. Organization:**
New Web Group

**3. On Chain Address for Allocator:**
f1knqrv2si4d4piqlw7deq4p3t5cejtn7e6nq4jxq

**4. Country of Operation:**
GCR

**5. Region(s) of operation:**
Africa , Asia minus GCR, Greater China, Europe, Oceania, Japan, North America, South America, Other

**6. Type of Allocator:**
Manual

**7. DataCap requested for allocator for 12 months of activity:**
200PIB

**8. Is your allocator providing a unique, new, or diverse pathway to DataCap? How does this allocator differentiate itself from other applicants, new or existing?:**
NWG's reputation and experience as an allocator in the Filecoin ecosystem provides a unique, novel and diverse approach to DataCap allocations. Our key features include:
1. Reputation and experience: NWG has been deeply involved in the Filecoin ecosystem for more than three years, and enjoys a good reputation with deep relationships with many Clients and Storage Providers (SPs).
2. Dataset Diversity: We accept multiple types of datasets, including but not limited to encrypted datasets, enterprise datasets, public datasets, etc., to meet the needs of different customers.
3. Specialized operation: Our team is very familiar with the operation process and technical tools of Filecoin Plus, especially for BOOST and LOTUS, etc. We have in-depth understanding and application experience.
4. Monitoring and Approval: NWG's allocator mainly operates in manual mode and relies on an automated monitoring system, which is able to monitor the usage of SPs and conduct timely approval to ensure the efficiency and compliance of the allocation process.
5. Compliance Monitoring: We track user behavior through our monitoring system to ensure that all operations comply with the regulations and standards of the Filecoin ecosystem.
6. Data Preparation and Support: NWG is highly proficient in the use of data processing tools such as go-graphsplit, singularity, etc. and is equipped with abundant hardware resources. We are able to efficiently convert data to car file format when the client (Client) uploads the data. This process not only provides data preparation services for the Client, but also includes sending the data to the Storage Provider (SP), which greatly reduces the difficulty of storage operations for the Client. With this service, we aim to improve the convenience and efficiency of the entire storage process, ensuring that our customers' storage experience in the Filecoin ecosystem is both smooth and efficient.


**9. As a member in the Filecoin Community, I acknowledge that I must adhere to the Community Code of Conduct, as well other End User License Agreements for accessing various tools and services, such as GitHub and Slack.:**
Acknowledge
### Client Diligence
**10. Who are your target clients?:**
Individuals learning about Filecoin, Small-scale developers or data owners, Enterprise Data Clients, Other (specified above)

**11. Describe in as much detail as possible how you will perform due diligence on clients.  If you are proposing an automated pathway, what diligence mechanism will you use to determine client eligibility?:**
In order to achieve efficient and comprehensive due diligence, NWG will adopt the following comprehensive strategy:

1. Identity verification and background checks:
For individual customers, we will analyze account age and activity history and may use third-party tools to assist in verifying online identities to rule out bots or fake accounts.
For institutional customers, we will conduct an initial review based on the appearance of the application and conduct an in-depth investigation of applications in the development stage to ensure their legitimacy and validity.
Comprehensive background checks are conducted, including social media and official website audits, as well as evaluating a client's credibility through credit rating agencies and internal industry recommendations.
2. Exhaustive due diligence process:
Review a number of key pieces of information, including entity information, authorized signatory information and beneficial owner information, based on the client's DataCap needs.
For authorized signatories and beneficial owners, verify their legal identity and authorized actions to ensure the authenticity and legality of all information.
3. Data security and privacy protection:
Adopt high standards of data protection measures during the due diligence process and use encryption technology to guarantee the secure transmission and storage of data.
4. Transparency and customer interaction:
Clearly explain the due diligence process and standards to clients, and regularly communicate with clients via video conference or telephone to deepen our understanding of their needs and background.
5. Ongoing monitoring and evaluation:
Consider due diligence as an ongoing process and periodically reassess customer eligibility to adapt to changes and new standards in the Filecoin ecosystem.
6. team training and customer education:
Regularly train teams on compliance, due diligence techniques and data protection regulations.
Provide training or guidance to clients on the Filecoin ecosystem and DataCap requirements.
Through these strategies, NWG strives to enhance customer trust and satisfaction while protecting customer data, ensuring fair and transparent distribution of DataCap, and strengthening its position in the Filecoin ecosystem.

**12. Please specify how many questions you’ll ask, and provide a brief overview of the questions.:**
We will go through a comprehensive due diligent process to make sure the client spending DataCap responsibly.
Firstly, we need to confirm their identification.
For individual customers, the verification of their identity will be verified through:
1.Identification number
2.Name
3.Data of birth
4.Copy of Passport
5.Address
6.Social media account (Facebook/LinkedIn/Twitter)
7.Local Offices Contact Details
8.Social reputation (Prize, Achievement)
For corporate clients, the verification of their identity will be verified through:
1.Company Registration Certificate/Operating Licence
2.Address
3.Website
4.Social media account (Facebook/Linkedin/Twitter)
5.Record of law suits and legal reputation
6.Company equity structure and key stakeholders
7.Scanned copy of letter from company with stamps and signature of director/stakeholder from the company
Stakeholder due diligence process for company shares/equity over 20%. (Stakeholder due diligence process will be similar to the above process, until the final beneficiary/the-actual-stakeholder is found.)

We will ask the following questions:
We will ask customers the following questions:
1.Can you identify yourself as organization or individual?  Your name/Your organization name?
2.What is your/ your organization social media/website link?
3.how much data you want to store? Can you specify the data you want to store according to use case type, source and by how much in each category?
4.Are you receiving DataCap from other notaries? If yes, can you list their names?
5.What cloud service/platform do you use, can you describe to me your usage frequency, volume, price/rates and purpose?
6.How many miners do you want to allocate your data to? How much data for each miner?
7.Can you provide transparency on your DataCap allocation/decision/ execution respectively?
8.What are the advance FileCoin features do you use to apply your DataCap allocation?
9.What content you’re going to store, does this content comply with local law and FileCoin community standards and regulation?
is there any potential client will paid for the content you store?
10.Where do you store these data, how much in total, and how much do you pay respectively per year?


**13. Will you use a 3rd-party Know your client (KYC) service?:**
Yes, e.g. QCC (https://www.qcc.com/), Tianyancha (www.tianyancha.com), these software provide different functions and services that can fulfill the needs for auditing business information queries.

**14. Can any client apply to your pathway, or will you be closed to only your own internal clients? (eg: bizdev or self-referral):**
At NWG, our DataCap distribution path is open to all customers and is designed to support the growth of the Filecoin network: 1. Fully open: for all types of customers, including companies and self-employed individuals. 2. Transparent process: Publish a clear application process to facilitate customer participation. 3. Technical support: Provide a professional team to solve technical problems during the application process. 4. Customer guidance: help customers understand and complete the application process. 5. Promoting network growth: Committed to expanding the Filecoin ecosystem and attracting a wider audience.  Our goal is to provide a convenient and efficient application path for all clients who wish to participate in Filecoin.

**15. How do you plan to track the rate at which DataCap is being distributed to your clients?:**
In order to track the rate at which DataCap is allocated to customers, we have adopted an efficient monitoring strategy: 1. Real-time monitoring system: At this stage, relying on the monitoring system we developed, we are able to obtain real-time DataCap usage information through Lotus' API interface. 2. Threshold Alert Mechanism: The system sets thresholds, and once the preset conditions are reached, our monitoring robot (BOT) will send out alerts on social media platforms commonly used by the team, including Wechat, SMS and phone alerts. This ensures that we can replenish DataCap credits in a timely manner and maintain continuity of allocation. 3. Future plans: In the long term, we plan to shift part of the distribution work to smart contracts, combined with the data provided by the ""CID checker tool"". When certain conditions are met, the contract will automatically execute the allocation of DataCap.  In this way, we can not only effectively monitor the rate of DataCap distribution, but also ensure the efficiency and automation of the distribution process, which will further improve the quality and responsiveness of our services.
### Data Diligence
**16. As an operating entity in the Filecoin Community, you are required to follow all local & regional regulations relating to any data, digital and otherwise. This may include PII and data deletion requirements, as well as the storing, transmit:**
Acknowledge

**17. What type(s) of data would be applicable for your pathway?:**
Public Open Dataset (Research/Non-Profit), Public Open Commercial/Enterprise, Private Commercial/Enterprise, Private Non-Profit/Social Impact, Other (specified elsewhere)

**18. How will you verify a client’s data ownership? Will you use 3rd-party KYB (know your business) service to verify enterprise clients?:**
For different types of datasets, NWG will use the following specific validation measures to ensure the authenticity and legitimacy of customer data ownership:
**Publicly available datasets**:
1. Source Information Requirement: We will ask customers to provide detailed source information about the dataset, including the name of the dataset, a link to the website where the dataset is hosted, and information about the team or organization to which the data belongs. This helps us verify the public availability and accessibility of the dataset.
**Enterprise datasets, encrypted & private datasets, etc.**:
1. Legal Documentation Audit: Require clients to provide copyright notices, ownership certificates or other relevant legal documents. Use e-signature and document verification tools commonly used in the China region, such as eSignature or Fada, to verify the authenticity and validity of these documents.
2. Enterprise third-party KYB services: For enterprise customers, use well-known KYB service providers such as Enterprise Check or Tianyecha to conduct enterprise background checks and identity verification.
3. Disclaimer undertaking: Customers are required to sign a disclaimer undertaking stating the legitimacy of the data provided and the assumption of responsibility for any data issues.
4. Face-to-face communication: Through video conferencing tools such as Tencent Conference or Nail, we communicate directly with customers to gain an in-depth understanding of data ownership and usage.
5. Data consistency check: Compare the content of the data provided by the client with the data it declares it owns to verify the consistency and completeness of the data and ensure data authenticity and ownership.

Through these meticulous verification measures, NWG will be able to more accurately identify and verify the ownership of various types of datasets, ensuring that our services comply with legal requirements and ethical standards.


**19.  How will you ensure the data meets local & regional legal requirements?:**
To ensure compliance with the laws and regional regulations of the client's region, NWG will implement the following measures: 1. Legal Compliance Review: Examine the data samples provided by the client against the laws of the client's location to ensure that the data complies with local regulations. 2. Data Sample Analysis: Evaluate whether the data samples involve any infringing or illegal content. 3. Legal Information Updates: NWG has a professional legal team and will regularly update the legal requirements on data protection through the legal team. 4. Comprehensive Compliance Check: Ensure that all data complies with local and regional laws and regulations.

**20. What types of data preparation will you support or require?:**
NWG has a technical team that specializes in providing Car data packaging services to our clients, which include: 1. technical expertise: our team is skilled in using advanced tools such as go-graphsplit, singularity, etc. to ensure efficient and accurate data packaging. 2. Data Processing Flow: We use self-developed programs to cut, package, and compress the data provided by our clients into 28-32GB zip files to meet the storage requirements of the Filecoin network. Through these services, we are able to effectively help our clients process and prepare data for storage and use on the Filecoin network.

**21. What tools or methodology will you use to sample and verify the data aligns with your pathway?:**
1. AC Bot Integration: Utilizes the AC Bot developed by Filecoin's Governance team to automatically validate the type and readiness of the data to ensure that it matches our standards. 2. Manual Sample Validation: Require customers to provide data samples to initially validate the authenticity and consistency of the samples through manual checks. 3. Bulk Random Sampling and Retrieval: A large random sample of data is taken from the storage provider for checking to ensure that the data occupancy is at least 50% of the sector capacity to prevent sector size abuse.
### Data Distribution
**22. How many replicas will you require to meet programmatic requirements for distribution?:**
4+

**23. What geographic or regional distribution will you require?:**
1. Politically Independent Regional Distribution: It is recommended that customers' data be distributed in at least two or more politically independent regions to minimize political or legal risks that may arise in a single region. 2. Multi-city storage: It is further recommended to store data in more than three cities, and users are encouraged to store more than five copies of data, which helps to improve the reliability of data backup and disaster recovery. 3. Worldwide Support: We support our customers in decentralizing data storage globally, aiming to provide wider accessibility and data security.

**24. How many Storage Provider owner/operators will you require to meet programmatic requirements for distribution?:**
4+

**25. Do you require equal percentage distribution for your clients to their chosen SPs? Will you require preliminary SP distribution plans from the client before allocating any DataCap?:**
NWG will utilize the following simplified and effective strategies during the DataCap allocation process: 1. Allocation Plan Submission: Customers will be required to submit a detailed allocation plan containing the allocation percentages of the different Service Providers (SPs) and the KYB information of the SPs prior to the first DataCap allocation. 2. Allocation Percentage Flexibility: While we have not set a fixed allocation percentage requirement, the maximum allocation share for a single SP is capped at 35% to promote diversity in allocations. 3. Adaptability to change: We understand the unpredictable factors that may arise in practice, and therefore allow our clients to adjust the original allocation plan and accept new SPs to join if necessary.

**26. What tooling will you use to verify client deal-making distribution?:**
We will use existing open source tools AC Bot, CID Checker and DataCapstats.io to check the distribution of customer transactions.

**27. How will clients meet SP distribution requirements?:**
First, we will fully understand our client's needs for data distribution. Within the scope of FIL+ compliance, we will help our clients distribute according to their needs. If there is a lack of SPs in certain regions, we also help our clients find more SPs globally with the help of multiple channels such as Slack, Wechat, DSPA, and more.

**28. As an allocator, do you support clients that engage in deal-making with SPs utilizing a VPN?:**
We are willing to support customers who work with SPs that use VPNs. In certain countries with sensitive policies, the use of VPNs can be further effective in safeguarding the security and privacy of SPs. However, at the same time, for compliance reasons, for SPs using VPNs, we will strengthen KYB checks to ensure compliance.
### DataCap Allocation Strategy
**29. Will you use standardized DataCap allocations to clients?:**
Yes, standardized

**30. Allocation Tranche Schedule to clients::**
 First: Clients receive lesser of 5% of total DataCap requested or 50% of weekly allocation rate
• Second: After used at least 80% of the first round, clients can receive lesser of 10% of total DataCap requested or 100% of weekly allocation rate
• Third: After used at least 80% of the second round, clients can receive lesser of 20% of total DataCap request or 200% of weekly allocation rate
• Fourth: After used at least 80% of the third round, clients can receive lesser of 40% of total DataCap requested or 400% of weekly allocation rate
• Max per client overall:  No more than 5 PiB

**31. Will you use programmatic or software based allocations?:**
No, manually calculated & determined

**32. What tooling will you use to construct messages and send allocations to clients?:**
For example, the existing notary registry tooling at https://filplus.fil.org/#/ https://filplus.fil.org/#/

**33. Describe the process for granting additional DataCap to previously verified clients.:**
To ensure the validity of additional DataCap allocation, NWG will implement the following process: 1. Demand Confirmation: When a customer applies for additional DataCap, first verify its demand. 2. Monitoring and checking: In combination with the use of the Subsequent Allocation (SA) bot, the filplus.info website, and our self-developed monitoring system, we will conduct regular monitoring and reviewing of the customer's DataCap usage. 3. Violation Handling: If a customer is found to be in violation of the law, we will issue a warning in the public community channels. If the customer fails to improve, we will consider stopping issuing DataCap to them. This process is designed to maintain transparency and fairness in the allocation of DataCap while ensuring customer compliance.

**34. Describe in as much detail as possible the tools used for: • client discoverability & applications • due diligence & investigation • bookkeeping • on-chain message construction • client deal-making behavior • tracking overall allocator health • disput:**
• client discoverability & applications ：GitHub&spreadsheet tracking
• due diligence & investigation：publicly available information& meetings&KYB
• bookkeeping：GitHub,Google Docs, 
• on-chain message construction： https://filplus.fil.org/#/
• client deal-making behavior ：AC Bot, CID Checker, DataCapstats.io
• tracking overall allocator health：DataCapstats.io, Filfox
• dispute discussion & resolution :Slack, GitHub, Email
• community updates & comms *Slack&GitHub&TG
### Tools and Bookkeeping
**35. Will you use open-source tooling from the Fil+ team?:**
Yes, we will be using open source tools like boost, lotus, singularity, go-graphsplit, CID Checker, AC Bot and DataCapstats.io.

**36. Where will you keep your records for bookkeeping? How will you maintain transparency in your allocation decisions?:**
To promote transparency and effectively manage confidential information, NWG will implement the following measures:
1. GitHub Disclosure: We will publicly post all DataCap allocation records, allocation decisions, and review processes on GitHub. The purpose of this is to provide the community with real-time access to our activities while ensuring the confidentiality required for effective governance and dispute resolution processes.
2. Confidential Information Management: Client-provided identifying information and other allocation information that needs to be kept confidential will be securely stored in our company's private database. If the FIL+ team needs to conduct an audit
We will provide the necessary support and information via our corporate email address with the @newwebgroup.com suffix.

### Risk Mitigation, Auditing, Compliance
**37. Describe your proposed compliance check mechanisms for your own clients.:**
To ensure customer compliance, NWG will implement the following simplified checking mechanism:
1. Trust assessment: A trust assessment will be conducted between the inception phase and the DataCap allocation phase. For new customers, if there is a violation, we will give one chance to correct it at the first allocation and ask for appropriate proof.
2. Regular communication and checking: We track DataCap allocation metrics through regular communication to understand customer needs and usage.
3. Monitoring with tools: Use CID Checker, AC Bot and DataCapstats.io to track and monitor DataCap usage.
4. Customer Relationship Management: Be open to the sincerity and reliability of our customers while seeking evidence in due diligence to ensure a balance of trust and validation.


**38. Describe your process for handling disputes. Highlight response times, transparency, and accountability mechanisms.:**
When dealing with disputes related to DataCap allocations, NWG will utilize the following process to ensure a rapid, transparent and accountable response:
1. rapid response: in the event of any dispute, whether internal (involving us and our clients) or external (requiring a defense against another active notary or the Fil+ governance team), we are committed to providing an initial response within 72 hours.
2. detailed investigation: we will promptly conduct a full investigation to clarify the specifics of the dispute and related information.
3. Public communication: Upon completion of the investigation, we will provide a detailed explanation and response to the challenging party within 72 hours through a public channel such as Github or Slack.
4. Transparency and accountability mechanisms: In handling all disputes, we will adhere to the principle of transparency and accountability mechanisms to ensure that all decisions and actions are in line with the rules and guidelines of the Filecoin Network.
Through this process, NWG is committed to resolving any disputes in the DataCap allocation process in a positive and fair manner to ensure that the rights and interests of all stakeholders are properly addressed.


**39. Detail how you will announce updates to tooling, pathway guidelines, parameters, and process alterations.:**
To ensure effective communication of tooling, pathway guidance, parameter and process changes, NWG will adopt the following streamlined and efficient communication strategy: 1. announcement channels: publicly post updates, including specific change sections and their functionality, via GitHub, the official website, and Slack channels. 2. Communication with the Fil+ Governance Team: Confirm the feasibility of an update with the Fil+ Governance Team via email prior to implementation. Major changes may require reapplication and reassessment. 3. email notification: send a summary of the update and a link to detailed information to participants in the Filecoin Plus ecosystem. 4. Documentation updates: Community documentation and guidelines are continuously updated on GitHub to ensure transparency and easy access to information. 5. webinars or podcasts: if necessary, explain the details of the changes via a webinar or podcast and record the session. In this way, NWG is committed to maintaining a high level of transparency and clarity during the update process to ensure that the community can smoothly adapt to any changes.

**40. How long will you allow the community to provide feedback before implementing changes?:**
Prior to implementing changes, NWG will use the following methods to actively incorporate community feedback and ensure a transparent and fair process:
1. feedback period: we will provide the community with at least **two weeks** to provide feedback to ensure that community members have adequate opportunities to express their opinions and suggestions.
2. Community Engagement: Through channels such as GitHub, Slack channels, and the official website, community members are encouraged to participate in discussions and provide their feedback on upcoming changes.
3. Moderate moderation and facilitation: During community discussions, we will provide moderate moderation and facilitation to ensure that discussions are orderly and constructive. We will note the expression of different points of view and guide the discussion appropriately.
4. Weighing Feedback: We will take community feedback into account, especially with regard to the possible impacts of changes and the concerns of community members. We are committed to maintaining the rationality and fairness of our decisions while respecting community input.
5. Transparency in Decision Making: When final decisions are made, we will publicly state how community feedback was considered and explain the rationale behind the final decision.
Through this approach, NWG strives to achieve effective community engagement and feedback incorporation within an open and transparent community structure, while ensuring a rational and balanced decision-making process.


**41. Regarding security, how will you structure and secure the on-chain notary address? If you will utilize a multisig, how will it be structured? Who will have administrative & signatory rights?:**
In terms of ensuring the security of the on-chain notarized address, NWG will adopt the following structure and protection measures:
1. Address creation using Ledger S Plus: We will use the Ledger S Plus hardware wallet to create on-chain notarized addresses. This method ensures the security of the private key, as the private key never leaves the hardware device.
2. Private key management: The private key for the notarized address will be held by the company's legal person/legal representative, ensuring that the private key is managed and used in accordance with the highest security standards.
3. Internal Approval Process: Our internal approval process will be realized by relying on the process approval tool of office software to ensure that all DataCap distribution operations are subject to strict internal audits.


**42. Will you deploy smart contracts for program or policy procedures? If so, how will you track and fund them?:**
For the time being, NWG does not plan to deploy smart contracts to handle procedures or policy processes in our current strategy and procedures. Our focus is on ensuring that DataCap distribution and monitoring is effectively managed through existing tools and processes. This includes the use of the already mentioned Ledger S Plus hardware wallet, internal approval processes, and other security measures to ensure operational security and transparency. However, we are always open to new technologies and will closely monitor the development of smart contracts within the Filecoin ecosystem. If in the future we decide to adopt smart contracts to optimize or enhance our procedures and policy processes, we will ensure: 1. transparent tracking and management: after deploying smart contracts, we will track and manage their execution through publicly available code repositories and tools. 2. Funds Management: Funds management for Smart Contracts will follow strict financial procedures and security protocols to ensure transparent and compliant use of funds. 3. Open resources: We will make available relevant code repositories, tools used, and any existing drafts to ensure that the community is able to participate and review our process. Currently, all relevant information and resources will be made public through our GitHub page, official website, and Slack channel to maintain communication and transparency with the community.
### Monetization
**43. Outline your monetization models for the services you provide as a notary allocator pathway.:**
In order to ensure the sustainability and transparency of the Notary Distribution Service, NWG plans to implement a reasonable monetization model as follows:
1. collateralization requirements: customers and storage providers (SPs) may be required to collateralize FIL or other assets based on compliance to ensure reasonable use of DataCap.
2. service fees:
   - Review Fee: In order to process DataCap applications, Customer may be required to pay a review fee.
   - Data Distribution Fee: fees associated with the distribution of data to SPs.
3. Flexible Pricing: Separate pricing will be provided for different service modules to provide flexibility in pricing structure.
NWG will make the detailed fees and collateral requirements publicly available once the monetization plan is finalized. We are committed to balancing the needs of our customers and SPs while ensuring transparency of our services.


**44. Describe your organization's structure, such as the legal entity and other business & market ventures.:**
NEW WEB GROUP is a technology-based enterprise focusing on distributed storage and AI computing, integrating hardware and software research and development, equipment sales, IDC server room hosting, cloud storage operation and maintenance, etc., and is committed to becoming the world's first-class decentralized storage and AI computing service brand. The Group is headquartered in Shenzhen and Hong Kong. In March 2021, the Shenzhen subsidiary, Westworld Technology Co., Ltd. was invested by the guidance funds of the Shenzhen Municipal Government and the Futian District Government. In March 2021, the Shenzhen entity, ""Westworld Technology Co.  https://newwebgroup.com/about

**45. Where will accounting for fees be maintained?:**
At NWG, the following comprehensive strategy has been implemented to ensure the highest level of transparency and auditability: 1. Asset management and logging: Comprehensive tracking of assets pledged by users or storage providers, including the process of asset destruction and release, to maintain operational transparency and traceability. 2. Fil+ Governance Expense Tracking: Accurately record all expenses incurred under the Fil+ governance framework and conduct regular audits to provide the community with comprehensive and transparent reports on governance expenses. 3. Internal Audit Team: Our internal audit team will conduct regular in-depth reviews of transactions and fund flows to ensure compliance and correctness of all operations. 4. Regular Communication and Transparency Reporting: Maintaining a strong relationship with the Fil+ governance team and stakeholders through regular financial reporting and ongoing communication with the community. These measures are designed to ensure that NWG is not only compliant but also maintains openness and transparency to the community in terms of expense handling and cost management, thereby enhancing community trust and facilitating the efficient execution of our services.
### Past Experience, Affiliations, Reputation
**46. If you've received DataCap allocation privileges before, please link to prior notary applications.:**
NWG is the notary for the V3 V4 round. https://github.com/filecoin-project/notary-governance/issues/713 https://github.com/filecoin-project/notary-governance/issues/422

**47. How are you connected to the Filecoin ecosystem? Describe your (or your organization's) Filecoin relationships, investments, or ownership.:**
These may include Storage Providers, existing client applications, developer service providers, and more. In 2017, the founding team of New Web Group was involved in IPFS and formed a technical team. In August 2020, we participated in the FIL Space Race. In 2019, NWG established a deep long-term partnership with GCR local IDC operators.  December 2020, New Web Group Technology was established and now has 100+ employees and has gained a very good reputation in China. In August 2021, New Web Group's international office was established and is building an international computing platform, hoping that more people internationally will come to focus on FileCoin. In January 2022, we cooperated with the FileCoin retrieval market and submitted a development proposal for a distributed shared CDN to help FileCoin improve the reward mechanism for retrieval service providers and enhance the experience of the Filecoin retrieval market and the ecological construction of FileCoin. In March 2022, we officially became a member of the orbit community, and as a founding member, we are ready to work with the community to do a good job of educating the world and making more people aware of and enjoy FileCoin. In February 2023, hosted the FVM Open Hack Day and won the second prize in the global competition for the selected project. July 2023, became the regional coordinator of Filecoin Orbit in Greater China. January 2024, co-hosted the China Orbit event with the Filecoin Foundation. On top of that, our company has a great group of employees who each promote Filecoin on social media and in total have gained a following of over 50,000 people and influenced 5 million crypto digital currency investors.

**48. How are you estimating your client demand and pathway usage? Do you have existing clients and an onboarding funnel?:**
When it comes to estimating customer demand and path usage, NWG relies on the following key factors for accurate assessment: 1. Partner network: Through our excellent relationships with cloud service giants such as Aliyun, Huawei Cloud, and AWS, we are able to gain valuable customer referrals and market insights that help us estimate potential customer demand. 2. Advantage of self-developed technology: Our self-developed distributed storage solutions based on Ceph and MinIO are better than other solutions in the market in terms of price/performance ratio, which makes us the preferred choice of many customers, thus better predicting market acceptance. 3. Investment and government support: With a strong investment background and government support, we have established strong credibility and attracted widespread customer attention. 4. Existing Customer Base and Expansion Channels: We have established relationships with customers in a variety of fields, covering a wide range of industries, including education, film and media, AI, and genetics. We continue to expand new customers through face-to-face meetings, emails, and regular online and offline events, forming an efficient customer guidance channel.  Based on these strategies, NWG is able to accurately estimate customer needs and ensure the effectiveness of path usage to meet growing and changing market demands.

**Comment by kevzak** [comment]
## Datacap Request for Allocator
#### Address
> f2dl7rnxidgmzdqfzjkjtn2mjixgr5qi7gq6np3li
#### Datacap Allocated
> 5PiB

**Comment by Kevin-FF-USA** [comment]
Hi @newwebgroup 

Wanted to send a friendly check in.  
As of this comment date, haven't seen any client applications or DataCap disbursements for the organization.   Inactive organizations are in the process of being [reviewed to see if still wanting to remain in program](https://github.com/filecoin-project/Allocator-Governance/issues/6).    If you would like this pathway to remain active as an Allocator, kindly asking that you reply to [the proposal ](https://github.com/filecoin-project/Allocator-Governance/issues/6) with your timeline for onboarding pathway or plan for action to clients.

[1080](https://github.com/filecoin-project/Allocator-Registry/blob/main/Allocators/1080.json) | New Web Group, New Web Group (E-Fil+) | Manual | [Bookkeeping](https://github.com/newwebgroup/Allocator-Pathway-New-Web-Group) | China | https://github.com/filecoin-project/notary-governance/issues/1080 | [f03015081](https://filecoinpulse.pages.dev/allocator/f03015081/#pageparamsallocator_id)
