### ISSUE TITLE
Lighthouse.Storage Notary application

### ISSUE THREAD

**Issue by nandit123** [filecoin-project/notary-governance#1084]
# v5 Notary Allocator Application

1. Notary Allocator Pathway Name (This can be your name, or the name of your pathway/program. For example "E-Fil+"): Nandit Mehra
3. Organization Name: Lighthouse.Storage
4. On-chain address for Allocator (Provide a NEW unique address. During ratification, you will need to initialize this address on-chain):  f1x66qujypjp5miucjypizfdwruef6sbv33nxxpza
5. Country of Operation (Where your organization is legally based): Singapore
6. Region of Operation (What region will you serve?): All
7. Type of Allocator, diligence process: (Automated/programmatic, Market-based, or Manual (human-in-the-loop at some phase): Manual
9. DataCap requested for allocator for 12 months of activity (This should be an estimate of overall expected activity. Estimate the total amount of DataCap you will be distributing to clients in 12 months, in TiB or PiB): 5PiB

**Comment by Filplus-govteam** [comment]
### Basic Information
**1. Notary Allocator Pathway Name:**
Nandit Mehra

**2. Organization:**
Lighthouse.Storage

**3. On Chain Address for Allocator:**
f1x66qujypjp5miucjypizfdwruef6sbv33nxxpza

**4. Country of Operation:**
Singapore

**5. Region(s) of operation:**
Asia minus GCR, Europe, North America

**6. Type of Allocator:**
Manual

**7. DataCap requested for allocator for 12 months of activity:**
5 PiB

**8. Is your allocator providing a unique, new, or diverse pathway to DataCap? How does this allocator differentiate itself from other applicants, new or existing?:**
We bring our experience of building essential tooling in Filecoin and the FVM ecosystem at Lighthouse.Storage where we work with various clients and know what data can be valuable for the filecoin network. 
Lighthouse has a big focus on bringing many kinds of web3 applications to store on filecoin with use cases ranging from NFTs, Web3 social, Data availability, and much more. 



**9. As a member in the Filecoin Community, I acknowledge that I must adhere to the Community Code of Conduct, as well other End User License Agreements for accessing various tools and services, such as GitHub and Slack.:**
Acknowledge
### Client Diligence
**10. Who are your target clients?:**
Small-scale developers or data owners, Enterprise Data Clients

**11. Describe in as much detail as possible how you will perform due diligence on clients.  If you are proposing an automated pathway, what diligence mechanism will you use to determine client eligibility?:**
- Currently the process will be manual, review all materials and verify details about the client
- One person on our team will be reviewing the application and checking if the information provided is legit
- To check all materials provided, do a background check
- Ask any follow up questions in doubt



**12. Please specify how many questions you’ll ask, and provide a brief overview of the questions.:**
Here are the 11 initial questions we will ask our clients:

1. Please provide information such as the company's registered name, legal representative, and registered address.
2. Is the company legally registered and operating in the region? If so, please provide relevant business registration information or business license.
3. Please describe the data that you want to store through Lighthouse?
4. What is the Filecoin address you would like me to allocate the DataCap to?
5. Can you share a sample of the data? A link to a file, an image, a table, etc. 
6. What is the expected retrieval frequency for your data?
7. For how long do you plan to keep this dataset stored through Lighthouse?
8. What are your security and privacy requirements? Do they need encryption or access control?
9. Do you have any preferences for where your data is stored geographically?
10. What payment methods are preferred?
11. Are you willing to sign a Non Disclosure Agreement?


**13. Will you use a 3rd-party Know your client (KYC) service?:**
We can use a 3rd-party ""Know your client"" (KYC) service if needed


**14. Can any client apply to your pathway, or will you be closed to only your own internal clients? (eg: bizdev or self-referral):**
Our channel will be open for any customer to apply and obtain the corresponding DataCap which means both our own internal clients and external clients can apply

**15. How do you plan to track the rate at which DataCap is being distributed to your clients?:**
It will be done Manually by our team on google sheets
### Data Diligence
**16. As an operating entity in the Filecoin Community, you are required to follow all local & regional regulations relating to any data, digital and otherwise. This may include PII and data deletion requirements, as well as the storing, transmit:**
Acknowledge

**17. What type(s) of data would be applicable for your pathway?:**
Public Open Dataset (Research/Non-Profit), Public Open Commercial/Enterprise, Private Commercial/Enterprise, Private Non-Profit/Social Impact

**18. How will you verify a client’s data ownership? Will you use 3rd-party KYB (know your business) service to verify enterprise clients?:**
We will do an initial manual checks which will include some verification information like:
- Organization name, nationality, country of incorporation, date of incorporation, names of executives and relevant websites.
- Business license 
- Business authorization letter (CEO signature + stamp)
- Sample data submission 
- Social media (official website, LinkedIn, GitHub, Twitter) 

If required we will take up some KYB Services for further verification  


**19.  How will you ensure the data meets local & regional legal requirements?:**
1. After onboarding Client: Secure legal documentation related to location and data privacy from clients. Obtain commitments from clients to comply with relevant regulations. 2. Legal Compliance Assessment: Conduct a thorough review of local data privacy laws. Consult with legal professionals for expert insights. Make informed judgments on legal compliance based on relevant laws. 3. Dynamic Legal Adaptation: Actively monitor changes in data privacy laws globally. Continuously update compliance strategies to reflect the evolving legal landscape.

**20. What types of data preparation will you support or require?:**
If required we can provide specific data preparation or integrations as and when needed

**21. What tools or methodology will you use to sample and verify the data aligns with your pathway?:**
1. Data Integrity Checks: We routinely download customer data to confirm its accuracy and adherence to agreed-upon specifications. This process ensures data preparation matches declared data types. 2. Random Verification Audits: To continuously monitor data quality, our team will randomly selects a small portion (e.g., 5%) of the data for in-depth download and verification in the background. This ongoing audit catches any potential issues. 3. Consequences for Abuse: If we detect misuse of resources or data, we will immediately halt the allocation of further quotas. Additionally, any unused data credits associated with the abuse will be automatically reduced.
### Data Distribution
**22. How many replicas will you require to meet programmatic requirements for distribution?:**
2+

**23. What geographic or regional distribution will you require?:**
It’s quite flexible and we can expand to geographic locations as per the client’s request. 

**24. How many Storage Provider owner/operators will you require to meet programmatic requirements for distribution?:**
5+

**25. Do you require equal percentage distribution for your clients to their chosen SPs? Will you require preliminary SP distribution plans from the client before allocating any DataCap?:**
1. Transparency and Consistency: To promote open allocation processes, we'll request public allocation plans on Github from clients. Subsequent applications will be assessed for plan consistency.  2. Public Scrutiny and Verification: Clients will outline their data allocation plans publicly on Github for transparency. During future applications, we'll ensure their plans remain consistent with their published versions. 3. Collaborative Commitment and Monitoring: We encourage public planning through Github for customer data allocation. Later applications will verify if plans remain aligned, fostering ongoing commitment and transparency.

**26. What tooling will you use to verify client deal-making distribution?:**
It will be done by our team but we are open to explore open source tooling like AC Bot and CID checker datacapstats.io

**27. How will clients meet SP distribution requirements?:**
Working with the client, we'll analyze their KYC and distribution plan for compliance and provide relevant information about the SP's reputation to enhance their due diligence.

**28. As an allocator, do you support clients that engage in deal-making with SPs utilizing a VPN?:**
No we don't encourage this because as the SP can be from a sanctioned country.
### DataCap Allocation Strategy
**29. Will you use standardized DataCap allocations to clients?:**
Yes, standardized

**30. Allocation Tranche Schedule to clients::**
We I will refer to the current FIL+ allocation rules
- First allocation: lesser of 5% of total DataCap requested or 50% of weekly allocation rate
- Second allocation: lesser of 10% of total DataCap requested or 100% of weekly allocation rate
- Third allocation: lesser of 20% of total DataCap request or 200% of weekly allocation rate
- Fourth allocation: lesser of 40% of total DataCap requested or 400% of weekly allocation rate
- Max per client overall: lesser of 80% of total DataCap request or 800% of weekly allocation rate
Max per client overall: 500 Tib



**31. Will you use programmatic or software based allocations?:**
Yes, standardized and software based

**32. What tooling will you use to construct messages and send allocations to clients?:**
Open source tools such as the current Filecoin Plus Registry

**33. Describe the process for granting additional DataCap to previously verified clients.:**
Currently we will be doing it manually by Verifying the previous data cap. If it falls below 10%, the next round of allocation requests will be approved, but we are open to explore open-source tooling or other automated tooling.

**34. Describe in as much detail as possible the tools used for: • client discoverability & applications • due diligence & investigation • bookkeeping • on-chain message construction • client deal-making behavior • tracking overall allocator health • disput:**
- For client discoverability & applications - Airtable, Googlesheets
- For due diligence & investigation - manually 
- For bookkeeping - Google Sheets
- For on-chain message construction - Glif wallet
-  For client deal-making behavior - CID checker bot
- For tracking overall allocator health - Telegram , Gmail
- For dispute discussion & resolution - Manually, GitHub.
- For community updates & comms - Discord , Telegram , Gmail 
### Tools and Bookkeeping
**35. Will you use open-source tooling from the Fil+ team?:**
We Will be using GitHub repositories and Google Sheets.

**36. Where will you keep your records for bookkeeping? How will you maintain transparency in your allocation decisions?:**
We will place the publicly available data in the public repository of our Github account apart from that there will be a public (View only) Google sheet maintained by our team.

### Risk Mitigation, Auditing, Compliance
**37. Describe your proposed compliance check mechanisms for your own clients.:**
Regular inspection and tracking is a key step in ensuring data compliance and security. Here are the specific plans we will implement:
a. We will communicate with the client on a monthly basis and the client should provide an update on their progress
b. Tracking DataCap allocation and client usage with CID Checker, AC Bot and DataCapstats.io
We welcome new clients, but new clients are also required to follow Fil+'s rules and participate in line with the laws and regulations of their country of location.


**38. Describe your process for handling disputes. Highlight response times, transparency, and accountability mechanisms.:**
To establish trust and confidence in Filecoin's dispute resolution process, we prioritize building a transparent, efficient, and fair mechanism for data storage and retrieval that empowers all relevant parties. Here's how:
Internal Dispute 
- Multi-Stage Process: A tiered process starting with informal mediation, escalating to formal arbitration if necessary.
- Clear Timelines: Timely response within 7 days of a dispute being filed. Resolution within 10-15 business days, depending on complexity.
- Transparent Communication: Regular updates provided to both parties throughout the process.

External Disputes:
- Collaboration and Engagement: Actively engage with other notaries and Fil+ Governance Team to gather information and reach equitable solutions.
- Data-Driven Defense: Thorough review of evidence and data logs to support our decisions and actions.
- Public Transparency: Publicized summaries of resolved disputes (with anonymized details) to promote community learning and prevent similar issues.


**39. Detail how you will announce updates to tooling, pathway guidelines, parameters, and process alterations.:**
Any changes will be posted in the fil-plus channel in Slack with advance notice. Relevant update announcements will also be posted in GitHub.

**40. How long will you allow the community to provide feedback before implementing changes?:**
We'll leverage diverse feedback mechanisms to ensure inclusive decision-making:

We value your input! We're committed to collaborating with the community through the notary governance GitHub repo. If your feedback makes logical sense and aligns with our team's vision, we'll implement changes together.

Ongoing Engagement:
- Maintain open communication channels for post-implementation feedback and suggestions.
- Proactively involve the community in future discussions and decisions.
- Encourage ongoing participation and knowledge-sharing within the Filecoin community.


**41. Regarding security, how will you structure and secure the on-chain notary address? If you will utilize a multisig, how will it be structured? Who will have administrative & signatory rights?:**
It will be controlled by our team with a access on the cold wallet

**42. Will you deploy smart contracts for program or policy procedures? If so, how will you track and fund them?:**
n/a
### Monetization
**43. Outline your monetization models for the services you provide as a notary allocator pathway.:**
This strategy focuses on selling storage deals to miners through two primary methods: auctions and commissions.
Selling Storage Deals:

Auctions:
Platform: Leverage a platform like BDE (Big Data Exchange) to host transparent and efficient auctions for storage deals.
Deal types: Offer various deal types with different durations, storage capacities, and pricing tiers to cater to diverse miner needs.

 Commissions:
Partner with miners: Establish partnerships with large, established miners who have a network of smaller miners seeking storage solutions.
Commission Structure: we would be the sales team for these miners. Every time we get them enough customers to fill a sector, they pay you a commission


**44. Describe your organization's structure, such as the legal entity and other business & market ventures.:**
Web3 tech labs pte. Ltd is a Singapore registered entity  

**45. Where will accounting for fees be maintained?:**
None
### Past Experience, Affiliations, Reputation
**46. If you've received DataCap allocation privileges before, please link to prior notary applications.:**
N/A

**47. How are you connected to the Filecoin ecosystem? Describe your (or your organization's) Filecoin relationships, investments, or ownership.:**
Active builder in the ecosystem. Protocol Labs is an investor.

**48. How are you estimating your client demand and pathway usage? Do you have existing clients and an onboarding funnel?:**
Yes we have existing clients using Lighthouse CLI, SDK, Files dapp to onboard to filecoin.

**Comment by galen-mcandrew** [comment]
## Datacap Request for Allocator
#### Address
> f2acflimlivomkevkhc63mhvppk465b26tszfb7ii
#### Datacap Allocated
> 5PiB

**Comment by Kevin-FF-USA** [comment]
Hi @nandit123 

Wanted to send a friendly check in.  
As of this comment date, haven't seen any client applications or DataCap disbursements for the organization.   Inactive organizations are in the process of being [reviewed to see if still wanting to remain in program](https://github.com/filecoin-project/Allocator-Governance/issues/6).    If you would like this pathway to remain active as an Allocator, kindly asking that you reply to [the proposal ](https://github.com/filecoin-project/Allocator-Governance/issues/6) with your timeline for onboarding pathway or plan for action to clients.

[1084](https://github.com/filecoin-project/Allocator-Registry/blob/main/Allocators/1084.json) | Lighthouse.Storage, Nandit Mehra | Manual | [Bookkeeping](https://github.com/filplus-bookkeeping/Nandit-Mehra-Lighthouse.Storage) | Singapore | https://github.com/filecoin-project/notary-governance/issues/1084 | [f03019939](https://filecoinpulse.pages.dev/allocator/f03019939/#pageparamsallocator_id)

**Comment by nandit123** [comment]
Hi,We will have applications soon in one months time

Yahoo Mail: Search, organise, conquer 
 
  On Tue, 11 Jun 2024 at 5:09, ***@***.***> wrote:   


Hi @nandit123

Wanted to send a friendly check in.
As of this comment date, haven't seen any client applications or DataCap disbursements for the organization. Inactive organizations are in the process of being reviewed to see if still wanting to remain in program. If you would like this pathway to remain active as an Allocator, kindly asking that you reply to the proposal  with your timeline for onboarding pathway or plan for action to clients.

1084 | Lighthouse.Storage, Nandit Mehra | Manual | Bookkeeping | Singapore | #1084 | f03019939
