### ISSUE TITLE
v5 Notary Allocator Application:ANTPOOL

### ISSUE THREAD

**Issue by Davisson2025** [filecoin-project/notary-governance#1088]
# v5 Notary Allocator Application

To apply to be an allocator, organizations will submit one application for each proposed pathway to DataCap. If you will be designing multiple specific pathways, you will need to submit multiple applications. 

Please complete the following steps:
# 1. Fill out the information below and create a new GitHub Issue

1. Notary Allocator Pathway Name (This can be your name, or the name of your pathway/program. For example "E-Fil+"):ANTPOOL Pathway
3. Organization Name:ANTPOOL
4. On-chain address for Allocator (Provide a NEW unique address. During ratification, you will need to initialize this address on-chain): f1acun2mgluaau5nx4ixbzwyo422k3i2ghkptqaoy
5. Country of Operation (Where your organization is legally based): SINGAPORE
6. Region of Operation (What region will you serve?): Asia (excluding Greater China), Europe, North America
7. Type of Allocator, diligence process: (Automated/programmatic, Market-based, or Manual (human-in-the-loop at some phase):Manual
9. DataCap requested for allocator for 12 months of activity (This should be an estimate of overall expected activity. Estimate the total amount of DataCap you will be distributing to clients in 12 months, in TiB or PiB):100PiB

# 2. Access allocator application (download to save answers)
Click link below to access a Google doc version of the allocator application that can be used to save your answers if you are not prepared to fully submit the application in Step 3. https://docs.google.com/document/d/1-Ze8bo7ZlIJe8qX0YSFNPTka4CMprqoNB1D6V7WJJjo/copy

# 3. Submit allocation application 
Clink link below to access full allocator questionnaire and officially submit your answers:
https://airtable.com/appvyE0VHcgpAkt4Z/shrQxaAIsD693e1ns

Note: Sections of your responses WILL BE posted back into the GitHub issue tracking your application. 
The final section (Additional Disclosures) will NOT be posted to GitHub, and will be maintained by the Filecoin Foundation. 
Application information for notaries not accepted and ratified in this round will be deleted.

**Comment by Filplus-govteam** [comment]
### Basic Information
**1. Notary Allocator Pathway Name:**
ANTPOOL Pathway

**2. Organization:**
ANTPOOL

**3. On Chain Address for Allocator:**
f1acun2mgluaau5nx4ixbzwyo422k3i2ghkptqaoy

**4. Country of Operation:**
SINGAPORE

**5. Region(s) of operation:**
Europe, North America, Asia minus GCR

**6. Type of Allocator:**
Manual

**7. DataCap requested for allocator for 12 months of activity:**
100PiB

**8. Is your allocator providing a unique, new, or diverse pathway to DataCap? How does this allocator differentiate itself from other applicants, new or existing?:**
Feature: We will invite more active community members to participate in the vote to enhance the fairness of our distribution. We will conduct voice meetings for each client, voice plus text to clarify their needs. We will classify different companies and different data for easy checking later.
Pathway: We will package decentralized storage applications for clients in need of storage and retrieval, thereby expanding the influence of Filecoin. We aim to draw our partners to Filecoin for data storage, including datasets from web3 projects and more.
Due diligence And Risk: The ANTPOOL platform has launched KYC functionality, and we will require applicants to pass KYC verification. We have purchased services from Refinitiv to investigate their backgrounds and mitigate business risks. We will assess data policies and related risks in different regions to decide whether to conduct business there.

**9. As a member in the Filecoin Community, I acknowledge that I must adhere to the Community Code of Conduct, as well other End User License Agreements for accessing various tools and services, such as GitHub and Slack.:**
Acknowledge
### Client Diligence
**10. Who are your target clients?:**
Small-scale developers or data owners, Enterprise Data Clients, Individuals learning about Filecoin, Other (specified above)

**11. Describe in as much detail as possible how you will perform due diligence on clients.  If you are proposing an automated pathway, what diligence mechanism will you use to determine client eligibility?:**
We conduct different levels of document review based on the type of client and the amount of DC they are applying for. For corporate clients, we require clients to provide the company name, place of registration, registration certificates, company statutes, shareholder structure, identification of ultimate beneficial owners, authorized company representatives, and proof of actual business premises. For individual clients, we ask for an electronic ID, nationality, proof of residence, and a facial recognition photo. The document review will be integrated with the services of LexisNexis for verification. Clients from countries with business restrictions, those listed on various global sanctions lists, or those who fail facial recognition will not pass the review and will be unable to use services. We also conduct an annual review of documents and may require clients to update their information to reassess their status.
We will ask clients to provide sample data for assessment before going live, after going live, we will strictly review the users' data to ensure its legality and compliance.
Additionally, we have a dedicated business development team that communicates with major clients, including offline visits, to gather more detailed information to determine client eligibility.


**12. Please specify how many questions you’ll ask, and provide a brief overview of the questions.:**
1.Please briefly introduce yourself. Are you able to provide sufficient documentation to meet the KYC requirements of our platform?
2.Are you aware of the data-related legal provisions or regulatory requirements in your region? Does your use comply with these provisions or requirements?
3.Why do you wish to apply for DataCap, and what do you intend to use it for?
4.How do you plan to use the DataCap?
5.Do you confirm that you will strictly adhere to the Fil+ guidelines?
What measures do you have in place to ensure that the use complies with the Fil+ guidelines?
6.Are you aware of the potential consequences of violating the Fil+ guidelines?
7.Have you applied for DataCap before?
8.How much DataCap are you applying for this time?


**13. Will you use a 3rd-party Know your client (KYC) service?:**
Yes, ANTPOOL has established a partnership with Refinitiv, a company within the London Stock Exchange Group (LSEG), which is one of the world's largest providers of financial market data and infrastructure. We have utilized Refinitiv's KYC, AML, and other services to ensure that our users' KYC complies with our business requirements.

**14. Can any client apply to your pathway, or will you be closed to only your own internal clients? (eg: bizdev or self-referral):**
Any client can apply, in our opinion, Filecoin is diverse and inclusive!

**15. How do you plan to track the rate at which DataCap is being distributed to your clients?:**
We will have dedicated engineers for data monitoring and will use open-source tools or develop proprietary tools to assist in tracking and detecting the distribution of DataCap, with regular reports on the results to the company.
### Data Diligence
**16. As an operating entity in the Filecoin Community, you are required to follow all local & regional regulations relating to any data, digital and otherwise. This may include PII and data deletion requirements, as well as the storing, transmit:**
Acknowledge

**17. What type(s) of data would be applicable for your pathway?:**
Public Open Dataset (Research/Non-Profit), Public Open Commercial/Enterprise, Private Commercial/Enterprise, Private Non-Profit/Social Impact, Other (specified elsewhere)

**18. How will you verify a client’s data ownership? Will you use 3rd-party KYB (know your business) service to verify enterprise clients?:**
We will verify the ownership of the client's data in ways, which include client document verification, data ownership attribution verification, and 3rd-party KYB service. We will ask clients to provide documents to verify the data ownership.
Yes, we will use third-party KYB services. Specifically, we will require clients to provide sufficient corporate and business-related documentation, and we will integrate with Refinitiv services to review the relevant information, ensuring that the client's business meets our requirements.

**19.  How will you ensure the data meets local & regional legal requirements?:**
Firstly, we will require clients to declare that their data complies with local legal requirements, and they will bear the consequences for any violations of local laws. Secondly, we will integrate certain APIs to automatically screen text, images, and video data for compliance with local legal standards, such as political content, pornography, etc. Finally, we will conduct manual sampling reviews of the data. Any data that does not meet the requirements will be outright rejected.

**20. What types of data preparation will you support or require?:**
Supports any type of data preparation. Priority will be given to Web3-related data.

**21. What tools or methodology will you use to sample and verify the data aligns with your pathway?:**
We are looking for some open-source tools, and we will develop our own if necessary.
### Data Distribution
**22. How many replicas will you require to meet programmatic requirements for distribution?:**
4+

**23. What geographic or regional distribution will you require?:**
We're requiring to be spread across 3 continents, 3 different countries.

**24. How many Storage Provider owner/operators will you require to meet programmatic requirements for distribution?:**
5+

**25. Do you require equal percentage distribution for your clients to their chosen SPs? Will you require preliminary SP distribution plans from the client before allocating any DataCap?:**
We won't require equal proportion distribution, but we will require that no single SP's distribution exceeds 20%, and we will ask for a distribution plan from the SP, which we will review as necessary.

**26. What tooling will you use to verify client deal-making distribution?:**
Datacapstats.io, bot, CID Checker

**27. How will clients meet SP distribution requirements?:**
1. The client first determines how many SPs he/she intends to work with 2. Selection of SP's geographical location and security factors 3. There is a clear distribution plan

**28. As an allocator, do you support clients that engage in deal-making with SPs utilizing a VPN?:**
We will impose restrictions on the use of VPNs to prevent some controls from being circumvented, such as the use of VPNs in restricted areas to violate regulations.  In legal cases, we will support SP if it is for security purposes. If the location information is falsified, we will reject it and ask the client not to cooperate with it. We will investigate the details carefully.
### DataCap Allocation Strategy
**29. Will you use standardized DataCap allocations to clients?:**
Yes, standardized

**30. Allocation Tranche Schedule to clients::**
- First: Maximum 128T allocated in the first round
- Second: Up to 512T in the second round
- Third: Maximum 1P in the third round
- Fourth: Max per client overall:5p
- Max per client overall:5p

**31. Will you use programmatic or software based allocations?:**
Yes, standardized and software based

**32. What tooling will you use to construct messages and send allocations to clients?:**
 I use https://filplus.fil.org/#/ 

**33. Describe the process for granting additional DataCap to previously verified clients.:**
1. The client needs to distribute the DC data to at least 4 or more miners. 2. SP retrieval rate must be greater than 20% and at least 3 copies must be kept. 3. Utilize tools for processing and checking, including but not limited to CID checker, etc.

**34. Describe in as much detail as possible the tools used for: • client discoverability & applications • due diligence & investigation • bookkeeping • on-chain message construction • client deal-making behavior • tracking overall allocator health • disput:**
• client discoverability & applications :
Clients can learn about our related products and services through our website at www.antpool.com. They can also contact us via Telegram, X platform, email, and perhaps even find us at some conferences.
• due diligence & investigation:
We will communicate with clients through various means such as email, phone and visit to collect feedback and conduct detailed investigations. And we will set up a public email to receive tip-offs.
• bookkeeping
On one hand, we will utilize Excel for data recording and analysis; on the other hand, we will develop a specialized software dedicated to recording and managing data.
• on-chain message construction
Our company has deployed Lotus on our servers, which can be used for on-chain data and information transmission.
• client deal-making behavior
We use GitHub to track and record client transaction behavior.
• dispute discussion & resolution
We use GitHub, Telegram to resolve disputes.
• community updates & comms *
We utilize various channels such as GitHub, Slack, Telegram, and email for community communication and updates. Additionally, we also post synchronously on our official Twitter and various social media platforms.
### Tools and Bookkeeping
**35. Will you use open-source tooling from the Fil+ team?:**
Yes, we will be using the open-source tools provided by the FIL+ team, including https://filplus.fil.org/#/ Github and Fil+.

**36. Where will you keep your records for bookkeeping? How will you maintain transparency in your allocation decisions?:**
We keep our allocation strategies updated in real-time on Git Hub, and we are open and transparent.
### Risk Mitigation, Auditing, Compliance
**37. Describe your proposed compliance check mechanisms for your own clients.:**
We require clients to provide sufficient documentation to pass KYC/KYB/AML-related checks, and clients need to sign compliance declarations. For every new client, we conduct a data review using API services to scan for sensitive data to ensure the legality of their data storage needs; clients who are flagged are asked to undergo additional investigations.
We utilize tools such as datacapstats.io/CID checking bots to monitor the allocation of DataCap, ensuring consistency in storage and allocation.

**38. Describe your process for handling disputes. Highlight response times, transparency, and accountability mechanisms.:**
A dispute within the context of DataCap allocation refers to any contention or disagreement arising between parties involved in the storage and retrieval of data on the Filecoin network. This could involve discrepancies over DataCap distribution, disagreements on data compliance with stated parameters, or conflicts over the execution of storage deals.
For response time: when faced with a dispute, we will handle the dispute promptly and resolve it as soon as possible. We will endeavor to resolve disputes within 3 days.
For Transparency: When faced with a dispute, we will actively communicate with the parties involved in the dispute and provide appropriate explanations. In addition, we will use public channels including, but not limited to, GitHub, Telegram, zoom meetings, and so on.
Accountability: We will scrutinize and handle disputes appropriately, and any disputes will be handled fairly, openly, and transparently.

**39. Detail how you will announce updates to tooling, pathway guidelines, parameters, and process alterations.:**
1. We will tweet and post on GitHub to inform everyone of the changes to our tools, pathfinders, parameters, and processes, as well as on our official Twitter and social media platforms, and we will email our clients to remind them of the changes in turn. 2. we'll explain why we're doing this update in emails and on GitHub and Twitter. 3. we have plans to create a separate channel for all clients to be alerted, so they don't miss out on my messages. Certain material programmatic changes or updates may be deemed out of scope by the Fil+ Governance Team and may require a reapplication to be scored against the rubric. For example, an 'update' from a single automated diligence process to include a new manual process may require a new notary allocator application.

**40. How long will you allow the community to provide feedback before implementing changes?:**
We strive for open, transparent, and decentralized community structures. However, decentralization does not always mean equal ownership or power granted to any and every community member. 
1. For small changes, we think 1 week would be sufficient.
2. For large changes, we think we need about a month to discuss them in the community.

**41. Regarding security, how will you structure and secure the on-chain notary address? If you will utilize a multisig, how will it be structured? Who will have administrative & signatory rights?:**
ANTPOOL will use a five-signature, three-key multisignature scheme to protect the notary addresses. We will select signatories from our reliable and trusted employees who are familiar with the signing process, and they will be chosen on a back-to-back basis.

**42. Will you deploy smart contracts for program or policy procedures? If so, how will you track and fund them?:**
Not yet.
### Monetization
**43. Outline your monetization models for the services you provide as a notary allocator pathway.:**
Because the project is just starting and still in the exploratory stage, we won't charge too much. We will provide clients with free technical support and training services. 
For data audit and investigation, because it takes a lot of time, we will charge 20-200FIL each time. If the client is willing to hand over the data to us for processing, we will charge 1FIL/T.

**44. Describe your organization's structure, such as the legal entity and other business & market ventures.:**
AntPOOL is a leading global digital currency mining platform that has garnered substantial support from users since its launch in August 2014. It supports nearly 20 kinds of POW coins, with its Bitcoin mining power consistently ranking at the forefront worldwide. Since 2021, we have been actively exploring opportunities in the Filecoin space and have participated in several Filecoin projects. We actively recommend Filecoin projects to our clients.

**45. Where will accounting for fees be maintained?:**
We will have a fixed receiving address and be able to provide the community with a record of transactions that we can make public.
### Past Experience, Affiliations, Reputation
**46. If you've received DataCap allocation privileges before, please link to prior notary applications.:**
None.

**47. How are you connected to the Filecoin ecosystem? Describe your (or your organization's) Filecoin relationships, investments, or ownership.:**
ANTPOOL is committed to the application of Filecoin, aiming to facilitate the widespread use of Filecoin in Web3 projects. Based on business needs, we will purchase Filecoin tokens.

**48. How are you estimating your client demand and pathway usage? Do you have existing clients and an onboarding funnel?:**
Client demand can be predicted by current data trends and business growth. We plan to add an entry point for Filecoin clients on our website, and of course, potential clients can also join through email, Telegram, or our business development contacts.

**Comment by galen-mcandrew** [comment]
## Datacap Request for Allocator
#### Address
> f2yz73r5qvr257jpifsdxyinpfnkhnyzl6p2qot2q
#### Datacap Allocated
> 5PiB

**Comment by Kevin-FF-USA** [comment]
Hi @Davisson2025 

Wanted to send a friendly check in.  
As of this comment date, haven't seen any client applications or DataCap disbursements for the organization.   Inactive organizations are in the process of being [reviewed to see if still wanting to remain in program](https://github.com/filecoin-project/Allocator-Governance/issues/6).    If you would like this pathway to remain active as an Allocator, kindly asking that you reply to [the proposal ](https://github.com/filecoin-project/Allocator-Governance/issues/6) with your timeline for onboarding pathway or plan for action to clients.

[1088](https://github.com/filecoin-project/Allocator-Registry/blob/main/Allocators/1088.json) | ANTPOOL, ANTPOOL Pathway | Manual | [Bookkeeping](https://github.com/filplus-bookkeeping/ANTPOOL-Pathway) | Singapore | https://github.com/filecoin-project/notary-governance/issues/1088 | [f03019944](https://filecoinpulse.pages.dev/allocator/f03019944/#pageparamsallocator_id)

**Comment by Davisson2025** [comment]
Hi Kevin

Thank you for your reminder in your recent email. We have been actively
promoting Filecoin within our community due to our investments in this
cryptocurrency. Our involvement includes participating in Bitmain's
Filecoin mining machine sales and delegated storage services. Furthermore,
we are continuously refining and optimizing this aspect to attract more
clients.


In addition, we have been engaging with potential Filecoin clients offline
through our BD team. We are pleased to share that we are expecting clients
to apply for datacap soon. Upon receiving applications, we will conduct
thorough due diligence before allocation.


Thank you for your attention to these developments. We are committed to
expanding our Filecoin initiatives and serving our clients effectively.


Warm regards,


Davisson


ANTPOOL

**Comment by Kevin-FF-USA** [comment]
Hi @Davisson2025 
Thanks - appreciate you providing the update.
