### ISSUE TITLE
v5 Notary Allocator Application:

### ISSUE THREAD

**Issue by maramc8** [filecoin-project/notary-governance#1089]
# v5 Notary Allocator Application

To apply to be an allocator, organizations will submit one application for each proposed pathway to DataCap. If you will be designing multiple specific pathways, you will need to submit multiple applications. 

Please complete the following steps:
# 1. Fill out the information below and create a new GitHub Issue

1. Notary Allocator Pathway Name (This can be your name, or the name of your pathway/program. For example "E-Fil+"): DeStor
3. Organization Name: DeStor
4. On-chain address for Allocator (Provide a NEW unique address. During ratification, you will need to initialize this address on-chain): TBH
5. Country of Operation (Where your organization is legally based): USA
6. Region of Operation (What region will you serve?): Worldwide
7. Type of Allocator, diligence process: (Automated/programmatic, Market-based, or Manual (human-in-the-loop at some phase): Manual to start but working with Xinan for automation
9. DataCap requested for allocator for 12 months of activity (This should be an estimate of overall expected activity. Estimate the total amount of DataCap you will be distributing to clients in 12 months, in TiB or PiB): 20

# 2. Access allocator application (download to save answers)
Click link below to access a Google doc version of the allocator application that can be used to save your answers if you are not prepared to fully submit the application in Step 3. https://docs.google.com/document/d/1-Ze8bo7ZlIJe8qX0YSFNPTka4CMprqoNB1D6V7WJJjo/copy

# 3. Submit allocation application 
Clink link below to access full allocator questionnaire and officially submit your answers:
https://airtable.com/appvyE0VHcgpAkt4Z/shrQxaAIsD693e1ns

Note: Sections of your responses WILL BE posted back into the GitHub issue tracking your application. 
The final section (Additional Disclosures) will NOT be posted to GitHub, and will be maintained by the Filecoin Foundation. 
Application information for notaries not accepted and ratified in this round will be deleted.

**Comment by Filplus-govteam** [comment]
### Basic Information
**1. Notary Allocator Pathway Name:**
DeStor

**2. Organization:**
DeStor

**3. On Chain Address for Allocator:**
TBD

**4. Country of Operation:**
United States

**5. Region(s) of operation:**
Africa , Asia minus GCR, Greater China, Europe, Oceania, Japan, North America, South America

**6. Type of Allocator:**
Manual

**7. DataCap requested for allocator for 12 months of activity:**
20

**8. Is your allocator providing a unique, new, or diverse pathway to DataCap? How does this allocator differentiate itself from other applicants, new or existing?:**
Background context - This is a unique and new use of DataCap to quote the DN vision statement “To make web3 tenable to enterprises and make enterprises tenable to web3” based on bringing paid deals to the ecosystem. This has been referred to as Web2.5 - and that is the bridge we are building founded on the principle of meeting network participants (customer side and fulfillment side) where they are and growing with them, as opposed to making people on either side have to adopt business process that is specific to Filecoin and at this early stage of maturity is not adding value to their experience.  In creating this allocator application, DeStor Network revisited Filecoin Plus’ mission as restated here:
Filecoin Plus’ mission is to build a decentralized network of useful storage. Filecoin Plus is a pragmatic solution to the technically challenging problem of verifying that a particular set of data is useful in a permissionless, incentive-compatible, and pseudonymous network. By adding a layer of social trust and providing leverage to storage clients, Filecoin Plus makes the network more decentralized and accelerates the proliferation of high-quality services on the network. Offering additional reward incentives for storing a Filecoin Plus Client’s deals also ensures reward subsidies go where they are needed most – encouraging legitimate use of the network.
With these founding principles in mind, DN is creating an entirely new use case for Data Cap allocation. It is specifically targeting enterprise data owners who are declaring perhaps the highest degree of the useful nature of their data by paying a monthly fee for it to be stored on FIlecoin. This data from enterprises is resoundingly Private, with perhaps some tolerance and need for it to be Shared.  The graph below illustrates private, shared and public data categories.  

Data as an asset class is different than the other assets a company has because it is “anti-rivalous” where “Many people can access them at the same time, and they can be consumed over and over again without impacting their quality or running the risk that supply will be depleted” (Investopedia). For enterprises this creates friction and a need for protection of their data which can be used to improve their own operations, profitability, evolution and more. As a result, enterprises take special measures to protect their proprietary and useful data from being exposed to competitors.  
As we have seen in the web2 space for a few decades, this means paying for services (storage, security, compute, network and more) to ensure data protection. The DeStor Network is building bridges between the web2 organizations that require the privacy of their useful data and the storage and service providers of web3.  
From the Filecoin Docs that are focused on Filecoin Plus we have the following: “Clients can use DataCap to incentivize storage providers to serve their needs. This can include providing additional features and levels of services that meet their specific requirements. In doing so, storage-related goods and services on Filecoin are made more valuable and competitive over time.”
DeStor Network is doing just this in our bridge building. SPs within the DeStor Network will go through a required qualification assessment that results in providing data owners with a pool of certified storage fulfillment organizations that meet their needs. The requirements of the SPs may include but are not limited to SOC2 and/or ISO 27001 data center certification, ability to participate in smart contracts for billing and receiving fiat payments, KYSP examination, and architectural standards to ensure availability and design for durability. These assessments will be made available for auditing purposes under NDA with redacted name identification. A visual of the relationships within the DeStor Network is as follows.


In support of decentralized principles of Filecoin Plus, the DeStor NetWork will offer a closed marketplace for verified data owners and SPs to connect and complete deals.  This provides the data owner the ability to choose the level of decentralization they require in protecting and storing their data. As erasure coding technology becomes available, the DeStor Network will incorporate those SPs with the capability into the marketplace and further advance the data owners ability to inherently decentralize their data even if they have a single copy stored on Filecoin.  
The participants in the DeStor include the following:
Customer side of the network includes:
Aggregators - DN vetted partners that are ISVs and/or MSPs who are incorporating Filecoin storage into the services they deliver to paying, predominantly web2 clientele.  The clients of the aggregators may or may not be aware that Filecoin is one of the technologies being used to deliver the solution they have purchased.  
Direct Clients - web2 and web3 enterprises (generally mid to large size) that own data and are interested in paying for Filecoin storage services.
The Fulfillment side of the network includes:
SP - Filecoin storage providers who have qualified into the network with functional and or certified characteristics - ISO, SOC, billing, etc.
Partners, ISVs, MSPs - all delivering additional services and value to the paying customers to fulfill the solution requirements.   
The DN pathway is designed for clients/aggregators interested in paying for storage on Filecoin. Each client/aggregator will go through a KYB process, must share their Filecoin use case, and must pay for storing data on Filecoin (limited free trials may be offered as well). Clients/aggregators will store their data with Filecoin SPs who meet a minimum threshold for enterprise compliance, for example SOC2 and/or ISO27001-certified data centers, and availability and retrieval SLAs.  


**9. As a member in the Filecoin Community, I acknowledge that I must adhere to the Community Code of Conduct, as well other End User License Agreements for accessing various tools and services, such as GitHub and Slack.:**
Acknowledge
### Client Diligence
**10. Who are your target clients?:**
Enterprise Data Clients, Small-scale developers or data owners

**11. Describe in as much detail as possible how you will perform due diligence on clients.  If you are proposing an automated pathway, what diligence mechanism will you use to determine client eligibility?:**
We are in discussion with Togggle.io for them to do the KYB.  It is anticipated that this will work out and that the process will align with verification of the following factors for each of the following customer/fulfillment partners.  


**12. Please specify how many questions you’ll ask, and provide a brief overview of the questions.:**
Aggregators
KYB process by providing the following:
Registered company name.
Address.
Type/status.
Nature of business.
Company reference number/VAT number/GST number.
Company directors/partners/owners (and contact details/personal information for the aforementioned).
Name of bank.
Branch address.
Account number/Swift code/IBAN.
Supporting documents.
Certificate of incorporation/incumbency/memorandum/articles of association.
Audited annual reports/financial accounts/statements.
Share Register / Ownership Structure Chart.
Confirmation of company address.
Confirmation of the identity of directors

Aggregators will also have to illustrate an auditable KYC of their direct customers that follows that same or more detailed collection and review of data points as outlined above.  

Direct Clients
KYC process by providing the following:
Registered company name.
Address.
Type/status.
Nature of business.
Company reference number/VAT number/GST number.
Company directors/partners/owners (and contact details/personal information for the aforementioned).
Name of bank.
Branch address.
Account number/Swift code/IBAN.
Supporting documents.
Certificate of incorporation/incumbency/memorandum/articles of association.
Audited annual reports/financial accounts/statements.
Share Register / Ownership Structure Chart.
Confirmation of company address.
Confirmation of the identity of directors

Storage Providers
KYB process by providing the following:
Registered company name.
Address.
Type/status.
Nature of business.
Company reference number/VAT number/GST number.
Company directors/partners/owners (and contact details/personal information for the aforementioned).
Name of bank.
Branch address.
Account number/Swift code/IBAN.
Supporting documents.
Certificate of incorporation/incumbency/memorandum/articles of association.
Audited annual reports/financial accounts/statements.
Share Register / Ownership Structure Chart.
Confirmation of company address.
Confirmation of the identity of directors

Storage providers will also have to provide certifications, the minimum being in a SOC2 and/or ISO27001 certified data center. Physical presence in data will have to be proven through sharing space, power, pipe contract with specified data center provider.  
An approved/official aggregator or SP will work directly with each client to understand the client/data owner requirements (e.g. certifications, geolocation, capacity, sealing rate, retrieval capabilities, and pricing) and will help the clients/data owners connect with the appropriate Filecoin SPs that meet their requirements. This process will initially be manual but to be replaced with a marketplace where bidding and matching making occur without manual intervention.


**13. Will you use a 3rd-party Know your client (KYC) service?:**
We are working with Togggle.io to cover the questions and verification as outlined above.  From Togggle.io - 
Our KYB solution taps into a wealth of global databases, employing advanced analytics for comprehensive business checks. Whether verifying a business's registration, conducting a thorough due diligence check on directors and UBOs, or assessing financial risk
Liveness Check
Our technology detects fake pictures, identifies a face’s unique features, generating a biometric descriptor. This ensures you’re dealing with a real person at onboarding.

Face Match
Verify genuine presence and ownership of identification documents with technology designed to ensure the Liveness Check matches the photo identification.

ID Document Verification
Our algorithm uses Machine Readable Zone (MRZ) technology to extract the relevant encoded information, match them with the government databases and verify the validity and ownership of the document to avoid fraud risk.

AML Check
Prevent interactions with high-risk entities at onboarding and avoid potential financial crimes with our Anti-Money Laundering solution.

IP Check
Verify your customers are authorised users of their IP address with technology designed to detect unauthorised fraudsters and prevent bots.

These checks comprise of ID verification, source of funds checks, customer due diligence, and watchlist screening. In addition, advanced KYC providers such as Togggle provide decentralized, re-useable credentials empowering both the customer or account holder and the enterprise or entity trying to confirm identities with frictionless onboarding.

**14. Can any client apply to your pathway, or will you be closed to only your own internal clients? (eg: bizdev or self-referral):**
The pathway will be reserved for DN designated/approved partners/aggregators (MSP and ISVs) and DN direct clients created through our demand generation efforts.  To create the expected client experience, DN will conduct the client diligence and apply to the allocator pathway on behalf of direct clients.

**15. How do you plan to track the rate at which DataCap is being distributed to your clients?:**
The DN allocator will be a manual allocator so it will have records of all client applications, client addresses, DataCap allocations, and DataCap usage.   There will be a designated person to oversee the tracking and recording of the allocation and usage.  The tool(s) to be used are still being defined.  But we are in talks with Xinan regarding using tools he has a service.
### Data Diligence
**16. As an operating entity in the Filecoin Community, you are required to follow all local & regional regulations relating to any data, digital and otherwise. This may include PII and data deletion requirements, as well as the storing, transmit:**
Acknowledge

**17. What type(s) of data would be applicable for your pathway?:**
Private Commercial/Enterprise, Private Non-Profit/Social Impact

**18. How will you verify a client’s data ownership? Will you use 3rd-party KYB (know your business) service to verify enterprise clients?:**
All direct clients must sign a legal agreement with DN attesting that they have the rights to the data they are storing.  All indirect clients (through aggregators) will sign a legal agreement with the respective aggregator attesting that they have the rights to the data being managed/stored. 

**19.  How will you ensure the data meets local & regional legal requirements?:**
All direct clients must sign a legal agreement with DN attesting that they comply with all local laws.  All indirect clients (through aggregators) will sign a legal agreement with the respective aggregator attesting that they comply with all local laws. 

**20. What types of data preparation will you support or require?:**
DN will provide common connector interfaces (SMB, NFS, iSCSI, S3, HTTPS) aggregators/data owners and to the Filecoin fulfillment SPs.  The data movement experience for the aggregator/data owner is to align with what they are familiar with.  The data will then be passed through the SP who will prep, seal and store the data. 

**21. What tools or methodology will you use to sample and verify the data aligns with your pathway?:**
DN will partner with Steeldome using their Stratistor and Infinivault software which provides telemetry regarding the data stored, including sector packing and SP selection, to ensure clients align with the DN pathway.
### Data Distribution
**22. How many replicas will you require to meet programmatic requirements for distribution?:**
2+

**23. What geographic or regional distribution will you require?:**
The number of copies reflect the requirements of the data owner regarding, RPO, RTO, durability, retrieval time, and others as specified.  At the same time, our default solutioning will include two copies of data in two different locations by two different providers.   We are also working with Togggle.io on payment verification.  This is important to our approach as stated earlier the highest expression of useful data being onboarded to is the data owner paying for services.  With Togggle.io, we plan to illustrate this as part of the verification and audit trail of datacap allocation.  This truly brings a unique and new use case of filecoin plus to the network supporting the original purpose “encouraging legitimate use of the filecoin network.”

**24. How many Storage Provider owner/operators will you require to meet programmatic requirements for distribution?:**
2+

**25. Do you require equal percentage distribution for your clients to their chosen SPs? Will you require preliminary SP distribution plans from the client before allocating any DataCap?:**
No. Aggregators/data owners may choose to distribute their data to SPs (prefer to say - based on the solution that best accomplishes their desired outcomes) in their chosen list. DN aggregators/data owners may choose SPs for a given data set based on the data center locations and certifications, retrieval performance, cost, and other factors.   It is also possible that DN will identify the SP(s) for the aggregator/data owner.  The SP chosen will first be based on capability alignment with data owner requirements; after which a round robin allocation methodology will be employed.  

**26. What tooling will you use to verify client deal-making distribution?:**
Because all deals will pass through the DN marketplace, DN will know each client’s deal-making address and will be able to track and monitor all deals made from that wallet.

**27. How will clients meet SP distribution requirements?:**
Aggregators/data owners will use common connector interfaces to move data to DN for distribution to SPs.  SPs will have a choice of using those same common interfaces or using the DN interface provided by Steeldome.  

**28. As an allocator, do you support clients that engage in deal-making with SPs utilizing a VPN?:**
It is possible that an SP may use a VPN, however, it must be clearly stated by the SP in the contract with DN.   DN will know where the data center is and it will be explicitly defined within the contractual arrangement between the delivery partners.  We will physically confirm data center existence and SP deployment within the data center.  In other words, if a VPN is used it must direct traffic to a known and approved data center.  
### DataCap Allocation Strategy
**29. Will you use standardized DataCap allocations to clients?:**
No, client specific

**30. Allocation Tranche Schedule to clients::**
• 50% of max requested amount with a min of 1 TiB and max of 100 TiB (every allocation of data cap to every customer requires an application for audit trails)
• Max per client overall: None based on successful prior usage of datacap.

**31. Will you use programmatic or software based allocations?:**
No, manually calculated & determined

**32. What tooling will you use to construct messages and send allocations to clients?:**
The existing notary registry tooling at https://filplus.fil.org/#/

**33. Describe the process for granting additional DataCap to previously verified clients.:**
The existing notary registry tooling at https://filplus.fil.org/#/DN will look at: DataCap remaining DataCap used in the past 3, 7, 30, 90, 180 days Data distribution over the last 3, 7, 30, 90, 180 days Self-reported changes to the client’s forecasted DataCap requirements DN will use the Fil+ Subsequent Allocation (SA) bot to allocate subsequent allocations.

**34. Describe in as much detail as possible the tools used for: • client discoverability & applications • due diligence & investigation • bookkeeping • on-chain message construction • client deal-making behavior • tracking overall allocator health • disput:**
• client discoverability & applications: fileplus.storage
• due diligence & investigation
• bookkeeping: hubspot, github
• on-chain message construction
• client deal-making behavior: datacap stats
• tracking overall allocator health: datacap stats
• dispute discussion & resolution: Hubspot ticketing, zoom and slack
• community updates & comms : notary governance call and slack
### Tools and Bookkeeping
**35. Will you use open-source tooling from the Fil+ team?:**
GitHub repo, Google spreadsheet, MongoDB

**36. Where will you keep your records for bookkeeping? How will you maintain transparency in your allocation decisions?:**
Since the DN target market is enterprise data, it is anticipated that DN will not be able to publicly announce the name of aggregators/data owners.  DN will provide transparency of deals on GitHub with redacted information.  The deal tracking will be no less than two weeks in arrears at any point.  
If further audit or insights are required, NDAs would have to be signed.  

### Risk Mitigation, Auditing, Compliance
**37. Describe your proposed compliance check mechanisms for your own clients.:**
Use the AC BOT for tracking and auditing of usage.  The reporting initially will be weekly to ensure smooth operations and will move to monthly for the long-term.  CID Checker and Retrievability Bot will also be used for tracking and for ensuring the upholding of the SLAs being offered to clients.  

**38. Describe your process for handling disputes. Highlight response times, transparency, and accountability mechanisms.:**
We will have a “contact us here” on the DN website - where inquiries can be made.  As needed we will provide audit trail documentation to respond to inquiry.  



**39. Detail how you will announce updates to tooling, pathway guidelines, parameters, and process alterations.:**
With any material changes to the process, tooling and/or programmatic rules, DN will contact the Fil+ Governance Team by GitHub and/or Slack outlining changes to be made.  We will then outline those changes to be community at large on GitHub.  

**40. How long will you allow the community to provide feedback before implementing changes?:**
We will provide a minimum of 2 weeks notice to the community.


**41. Regarding security, how will you structure and secure the on-chain notary address? If you will utilize a multisig, how will it be structured? Who will have administrative & signatory rights?:**
We will have a 2 step authorization process to secure the on-chain notary address.  We will have a multisig wallet where 2 of a pool of at least 3 wallets have to authorize.  



**42. Will you deploy smart contracts for program or policy procedures? If so, how will you track and fund them?:**
No
### Monetization
**43. Outline your monetization models for the services you provide as a notary allocator pathway.:**
no

**44. Describe your organization's structure, such as the legal entity and other business & market ventures.:**
DN will be a standalone corporate entity - nucleated from PLGO

**45. Where will accounting for fees be maintained?:**
No fees
### Past Experience, Affiliations, Reputation
**46. If you've received DataCap allocation privileges before, please link to prior notary applications.:**
none

**47. How are you connected to the Filecoin ecosystem? Describe your (or your organization's) Filecoin relationships, investments, or ownership.:**
We are a nucleation from PL to deliver a decentralized storage marketplace connecting web2 enterprises and web3 businesses to providers of filecoin storage.  

**48. How are you estimating your client demand and pathway usage? Do you have existing clients and an onboarding funnel?:**
DN has a current funnel of 320 PiBs of sales qualified leads and we have delivered 110 PiBs of inbound pipeline through organic traffic.  All of these leads and pipeline are kept in HubSpot.

**Comment by galen-mcandrew** [comment]
## Datacap Request for Allocator
#### Address
> f2nugegi5abln6wn6vcfhsqq7xssop6q7f2tbupyq
#### Datacap Allocated
> 5PiB
