### ISSUE TITLE
v5 Notary Allocator Application: ZetaCubeAllen

### ISSUE THREAD

**Issue by ipfsAllen** [filecoin-project/notary-governance#1092]
# v5 Notary Allocator Application

To apply to be an allocator, organizations will submit one application for each proposed pathway to DataCap. If you will be designing multiple specific pathways, you will need to submit multiple applications. 

Please complete the following steps:
# 1. Fill out the information below and create a new GitHub Issue

1. Notary Allocator Pathway Name (This can be your name, or the name of your pathway/program. For example "E-Fil+"): ZetaCubeAllen
3. Organization Name:ZetaCube Inc
4. On-chain address for Allocator (Provide a NEW unique address. During ratification, you will need to initialize this address on-chain): f1kth524kqjwd5r6pfkw23y5ef73c5e33edurjroa
5. Country of Operation (Where your organization is legally based): Korea Republic (South Korea)
6. Region of Operation (What region will you serve?): Greater China, Asia minus GCR, Africa , Europe, Oceania, Japan, North America, South America, Other
7. Type of Allocator, diligence process: (Automated/programmatic, Market-based, or Manual (human-in-the-loop at some phase): Manual
9. DataCap requested for allocator for 12 months of activity (This should be an estimate of overall expected activity. Estimate the total amount of DataCap you will be distributing to clients in 12 months, in TiB or PiB): 3,000PiB

# 2. Access allocator application (download to save answers)
Click link below to access a Google doc version of the allocator application that can be used to save your answers if you are not prepared to fully submit the application in Step 3. https://docs.google.com/document/d/1-Ze8bo7ZlIJe8qX0YSFNPTka4CMprqoNB1D6V7WJJjo/copy

# 3. Submit allocation application 
Clink link below to access full allocator questionnaire and officially submit your answers:
https://airtable.com/appvyE0VHcgpAkt4Z/shrQxaAIsD693e1ns

Note: Sections of your responses WILL BE posted back into the GitHub issue tracking your application. 
The final section (Additional Disclosures) will NOT be posted to GitHub, and will be maintained by the Filecoin Foundation. 
Application information for notaries not accepted and ratified in this round will be deleted.

**Comment by Filplus-govteam** [comment]
### Basic Information
**1. Notary Allocator Pathway Name:**
ZetaCubeAllen

**2. Organization:**
ZetaCube Inc

**3. On Chain Address for Allocator:**
f1kth524kqjwd5r6pfkw23y5ef73c5e33edurjroa

**4. Country of Operation:**
Korea Republic (South Korea)

**5. Region(s) of operation:**
Africa , Asia minus GCR, Greater China, Europe, Oceania, Japan, North America, South America, Other

**6. Type of Allocator:**
Manual

**7. DataCap requested for allocator for 12 months of activity:**
3,000PiB

**8. Is your allocator providing a unique, new, or diverse pathway to DataCap? How does this allocator differentiate itself from other applicants, new or existing?:**
ZetaCube is a representative SP that has built and operated a total of 5 Filecoin-only data centers in Korea since the end of 2020, and is a manufacturer and supplier of a Filecoin-only ultra-small data center solution called NANODC, and supports the Filecoin community through Fil So~Good.io and Filmountain.io. We are focusing on revitalization and technical education and are doing our best to create and expand new SPs in Korea and neighboring countries.

Since the end of 2020, the year when the Filecoin ecosystem began in earnest in Korea, we have established Korea's first ultra-large data center exclusively for Filecoin with 220 racks in Bupyeong, and have handled all construction, system supply, and node operation and management. Afterwards, starting in 2021, a new Filecoin-specific data center was built in Gwangju, Jeonju, and Gyeonggi-do, and in 2022, a Filecoin data center and an SP support center to educate and support SPs were simultaneously established in Gangnam, Seoul.

We decided to participate in the Filecoin Seoul Meetup held in Korea for the first time in August 2022 and exchange with executives from Protocol Labs and the Filecoin Foundation, and then participate in the Filecoin Meetup held in Singapore in 2022 and hold Filecoin Networkday in Korea in December. After reaching an agreement, 'Filecoin Network Day Seoul' was successfully held for 3 days at the Seoul data center established by our company on December 15, 2022, and the video was posted on YouTube.

Since then, we have actively participated in meetup events hosted by Protocol Labs and the Filecoin Foundation and technical training such as ESPA and DSPA, striving to deliver the technologies of the rapidly changing Filecoin ecosystem to Korea and neighboring countries, and holding forums to promote the SP community. We have been working to expand it.

Below are the Filecoin-related events and training completion/activity details in which we participated.

Filecoin Data Center opens in Bupyeong, Korea in May 2021
Filecoin data center opens in Gwangju, Korea in October 2021
Filecoin data center opens in Jeonju, Korea in February 2022
Filecoin Datacenter opens in Gyeonggi-do, Korea in June 2022
Filecoin Datacenter opens in Gangnam, Seoul, Korea in October 2022
.Participation in Seoul Meetup in August 2022
.Participation in Singapore Meetup in November 2022
Hosted by Filecoin Network Day Seoul on December 15, 2022
                          ZetaCube Founder Allen Cho 2 presentations (YouTube)
.Completion of Lasvegas ESPA Cohort 5 training in January 2023
                           ZetaCube Founder Allen Cho 1 presentation (YouTube)
.Participation in Hong Kong Web3 Forum in April 2023
.Hong Kong DSPA training completed in June 2023
.Participation in Fil Dev Singapore in September 2023
                   ZetaCube Founder Allen Cho NANODC Presentation (YouTube)
.NANODC #1 installed in Gwangju, Korea in September 2023
NANODC #2 established in Seoul, Korea in October 2023
.Participation in FilVegas23/ESPA Cohort 7 in October 2023
                ZetaCube Founder Allen Cho 2 presentations (YouTube)
.NANODC #3 installed in Bupyeong, Korea in January 2024
.NANODC SP POOL scheduled to launch in February 2024
.FilMountain.io Defi Project scheduled to open in April 2024

**9. As a member in the Filecoin Community, I acknowledge that I must adhere to the Community Code of Conduct, as well other End User License Agreements for accessing various tools and services, such as GitHub and Slack.:**
Acknowledge
### Client Diligence
**10. Who are your target clients?:**
Individuals learning about Filecoin, Small-scale developers or data owners, Enterprise Data Clients, Other (specified above)

**11. Describe in as much detail as possible how you will perform due diligence on clients.  If you are proposing an automated pathway, what diligence mechanism will you use to determine client eligibility?:**
Since our company is currently participating in the official virtual asset business license project implemented by the Korean government, we can use the corresponding KYC program. Through this, a secure KYC system with enhanced security and identity verification through video chat can be applied.

**12. Please specify how many questions you’ll ask, and provide a brief overview of the questions.:**
*Business Confirmation Questions:
1. Please provide your official company name, location, address and contact information.
2. Can you provide your business registration number?
3. Can you give me a copy of your business registration certificate?
4. Please tell us the size and composition of your organization.
* Dataset verification questions:
1. What data do you want to store in Filecoin?
2. What is the total amount of data you want to store?
3. How is the data licensed?
* Questions about storage space:
1. How many SPs do you want to store in?
2. Where is each SP located?
3. What node address does each SP have?
4. How much storage space is available for each SP?
5. What is the line speed of each SP?
* Security questions:
1. What measures are in place for data security?
2. Is there any way to check its integrity?
3. How do I back up and recover data?
* Search related questions:
1. How long do you want to keep the data?
2. How often does data access occur?
3. How do you index to retrieve data?

**13. Will you use a 3rd-party Know your client (KYC) service?:**
Yes, we are in the process of government approval as a virtual asset business, so it is possible to provide a government-approved KYC system. It is more secure and convenient.

**14. Can any client apply to your pathway, or will you be closed to only your own internal clients? (eg: bizdev or self-referral):**
Yes we can apply to the every SP

**15. How do you plan to track the rate at which DataCap is being distributed to your clients?:**
We have already developed our own tool to monitor the operating status of multiple nodes and servers located in various data centers and applied it to NANODC. Through this, the operating status of each node is transmitted and reported to our monitoring server in real time as Json and XML through the Node exporter. Tracking and monitoring are possible through this, and functions and efficiency are continuously upgraded.
### Data Diligence
**16. As an operating entity in the Filecoin Community, you are required to follow all local & regional regulations relating to any data, digital and otherwise. This may include PII and data deletion requirements, as well as the storing, transmit:**
Acknowledge

**17. What type(s) of data would be applicable for your pathway?:**
Public Open Dataset (Research/Non-Profit), Public Open Commercial/Enterprise, Private Commercial/Enterprise, Private Non-Profit/Social Impact, Other (specified elsewhere)

**18. How will you verify a client’s data ownership? Will you use 3rd-party KYB (know your business) service to verify enterprise clients?:**
Basically, we first find out whether the data is an open dataset by searching the Internet and check whether it is licensed. However, if necessary, there are plans to use the KYB system to check in detail.

**19.  How will you ensure the data meets local & regional legal requirements?:**
Korea is one of the countries in the world that is very sensitive to copyright protection. For this purpose, a very large copyright association has been formed, and search engines and systems are very actively operated and managed. If this is actively utilized, it is expected that at least many copyright-related issues within Korea will be covered.

**20. What types of data preparation will you support or require?:**
We are carrying out the process of creating and uploading the CAR File through our own script. Through this, it is already possible to process large amounts of data more safely and efficiently than existing processes.

**21. What tools or methodology will you use to sample and verify the data aligns with your pathway?:**
As already explained, the process and operation of randomly selecting and sampling the file through its own script is possible.
### Data Distribution
**22. How many replicas will you require to meet programmatic requirements for distribution?:**
5+

**23. What geographic or regional distribution will you require?:**
Our NANODC systems (micro data centers) are distributed and installed in various cities in Korea. For example, NANODC #1 is installed in Seoul, #2 is installed in Incheon, and #3 is installed in Gwangju, thus geographically satisfying three cities in Korea. Configuration of the other two additional SPs is relatively easy and is currently connected to the United States, Hong Kong, or Europe. Another advantage of our NANODC system is that it is advantageous to configure SPs in five distributed regions in this way.

**24. How many Storage Provider owner/operators will you require to meet programmatic requirements for distribution?:**
5+

**25. Do you require equal percentage distribution for your clients to their chosen SPs? Will you require preliminary SP distribution plans from the client before allocating any DataCap?:**
Before allocating Datacap, We must receive an explanation of the data cap SP distribution plan and ratio in advance and confirm it afterwards.

**26. What tooling will you use to verify client deal-making distribution?:**
Check the saved contents through the Fil+ API and use the CID bot at the same time. Additionally, we check the information of the relevant business operator again through Slack, etc.

**27. How will clients meet SP distribution requirements?:**
As already explained, we monitor and guide through APIs, bots, and Slack information. In most cases, initial SPs who do not know much need to be guided at the beginning so that our monitoring can be helpful.

**28. As an allocator, do you support clients that engage in deal-making with SPs utilizing a VPN?:**
No we don’t support it
### DataCap Allocation Strategy
**29. Will you use standardized DataCap allocations to clients?:**
Yes, standardized

**30. Allocation Tranche Schedule to clients::**
 • First: 10%
• Second: 25%
• Third: 25%
• Fourth: 35%
• Max per client overall: 100%

**31. Will you use programmatic or software based allocations?:**
Yes, standardized and software based

**32. What tooling will you use to construct messages and send allocations to clients?:**
We are planning to track messages by improving the monitoring tool we have previously written and used. Through this, we want to support our clients and make assignment tasks easy for them.

**33. Describe the process for granting additional DataCap to previously verified clients.:**
Using our own code by SA bot, we will operate a program that automatically warns and provides guidance when the remaining data cap reaches 20%.

**34. Describe in as much detail as possible the tools used for: • client discoverability & applications • due diligence & investigation • bookkeeping • on-chain message construction • client deal-making behavior • tracking overall allocator health • disput:**
• client discoverability & applications 
We will open public Github repository to follow up client applications
• bookkeeping
We will be doing a bookkeeping job  through Github.
• on-chain message construction
We will support you using a program that tracks and writes messages sent through our own code.
• client deal-making behavior
We will create a program that automatically monitors customer situations using a CID inspection bot. Additionally, we plan to conduct detailed monitoring by making full use of the standard software tools provided by Protocol Labs.
• tracking overall allocator health
We will using a CID inspection bot and we plan to conduct detailed monitoring by making full use of the standard software tools provided by Protocol Labs. Also human resources.
• dispute discussion & resolution
• community updates & comms 
*We are in the process of becoming certified as a virtual asset business operator by the government of the Republic of Korea and can utilize the government-affiliated dispute arbitration system.
### Tools and Bookkeeping
**35. Will you use open-source tooling from the Fil+ team?:**
yes. We plan to actively apply open source tools while utilizing our own tools. In particular, continuous integration of the provided API and existing tools. I'm trying to do it. Our solution is based on Maria DB based Java code unit with node exporter. And operated on the Android system.

**36. Where will you keep your records for bookkeeping? How will you maintain transparency in your allocation decisions?:**
We will using Github for the handling public information.
Almost of informations for the bookkeeping is in the Github (Application dataset types, size, file volume etc and datacap distribution informations.)
### Risk Mitigation, Auditing, Compliance
**37. Describe your proposed compliance check mechanisms for your own clients.:**
1. Customer verification procedure
To verify the client, we proceed with a verification process such as verifying the customer's detailed information and business license such as business registration number, verification by video conference, verification of application of government-supported KYC system, and internet search.
2. Customer dataset verification
Through procedures such as sampling verification of the customer's dataset, CID check, and original file confirmation, we use self-written scripts and codes to check whether the data is suitable for onboarding.
3. Agree to data cap use and storage regulations
We notify the customer of the allowable data cap defined by the verified results of the data set held by the customer and obtain consent for compliance with regulations such as the process for storing it and maintaining balance between independent SP groups.
4. Monitor onboarding datacap usage
We monitor in real time whether storage between SPs is progressing as specified using self-produced monitoring tools and public tools, and provide warnings and guidance when the data cap reaches less than 20% of the target usage to ensure balanced storage and on-site storage. We support customers with boarding.
5. Supports data security and integrity checking
Standardized standards for the security level and integrity of stored data are regularly checked and reports are provided.
6. Conduct post-audit
We maintain sustainable provision of stable data by applying a post-audit process to ensure stable storage of the dataset according to the provided data cap allocation.
7. Modification request report
According to the results of the post-audit, a defect report on problems and defects discovered will be provided to the customer and corrected. We help you do it.

**38. Describe your process for handling disputes. Highlight response times, transparency, and accountability mechanisms.:**
To effectively handle disputes within the context of DataCap allocation on the Filecoin network, it is important to establish a clear, transparent, and accountable process. We suggest:
Our plan for handling disputes related to Datacap allocation and dataset validation is as follows:

1. Receiving customer feedback
Customers raise . We support an open channel where various dispute issues can be reported. (Slack, e-mail, web site)
2. Analysis, classification and feedback of received opinions
We analyze filed disputes, classify them based on the history of existing disputes, compare and review them, and create a report.
3. Dispute response by the dispute response team
A person in charge of dispute response delivers the analyzed data on the dispute issue to the customer and explains it in an easy-to-understand manner to mediate the dispute.
4. Create database for processing results
By storing and indexing the results of dispute coordination and feedback analysis data in our self-configured database system, we manage to easily resolve similar cases in the future and coordinate disputes clearly and quickly.
5. Launch and share with the community
We help promote fair and rapid dispute resolution by transparently sharing resolved disputes with the community.

**39. Detail how you will announce updates to tooling, pathway guidelines, parameters, and process alterations.:**
We will manage and report through our website and share it through email and Slack.

**40. How long will you allow the community to provide feedback before implementing changes?:**
You can usually provide feedback through the community. The delivery period is expected to be within 4 weeks.
There should be sufficient time for feedback to ensure any changes are fully reviewed and to encourage as much participation as possible.
To this end, a standard period is set and announced to encourage diverse and rapid exchange of feedback within the period.
In particular, there is a strong tendency to be limited when exchanging opinions through only one channel such as Slack, so it is advisable to encourage broad participation by collecting opinions through various channels as possible (email, website, SNS, etc.). Sufficient time should be given for this purpose. I think it does.

**41. Regarding security, how will you structure and secure the on-chain notary address? If you will utilize a multisig, how will it be structured? Who will have administrative & signatory rights?:**
We can use Multi-Sig Wallet to secure that on-chain notary address.
Our company will be managed by Allen Cho, Founder and CTO, and Hoon Choi, RnD Head, with joint authority.
In addition, for safe wallet management, we will conduct regular backups and have a separate Wallet Room in the office to strictly manage it separately from the existing network so that only the relevant signers can access it. This is a management method established in Korea's virtual asset business regulations.

**42. Will you deploy smart contracts for program or policy procedures? If so, how will you track and fund them?:**
Our company is currently developing new SP Pool and managing it using smart contracts. Therefore, I plan to Contribute and invest.
### Monetization
**43. Outline your monetization models for the services you provide as a notary allocator pathway.:**
*Our expected revenue generation is as follows:

Onboarding dataset verification cost (30FIL) + reporting cost (20FIL)

**44. Describe your organization's structure, such as the legal entity and other business & market ventures.:**
Zeta Cube Inc is a spin-off of CobaltRay Co., Ltd, a hardware manufacturer and software solutions provider based in Korea and Hong Kong. Mr. has past experience in manufacturing payment terminals and building and supplying cryptocurrency payment services, as well as leading the Korea Linux Association. From the end of 2020, Allen Cho opened five Filecoin-dedicated data centers in Seoul, Gwangju, Jeonju, Gyeonggi, and Incheon, separating them from the headquarters in 2022 and launching a groundbreaking ultra-small data center solution called NANODC. By building a 10PiB data center through a single server rack system, we are leading the spread and dissemination of SPs in Korea. At the same time, we are leading the spread and dissemination of SPs in Korea, and at the same time, we are supporting KESPA, an education support project for SPs, Filmountain, a Filecoin Defi Project, and Fil So~Good!, a Filecoin community. We are actively promoting the community. Our website is zetacube.net!

**45. Where will accounting for fees be maintained?:**
Our main business and revenue is data center system supply, operation, and maintenance. With the profits earned through this, we continue to invest in the Filecoin community, education business, SP support community, and new product development.
### Past Experience, Affiliations, Reputation
**46. If you've received DataCap allocation privileges before, please link to prior notary applications.:**
This is first time

**47. How are you connected to the Filecoin ecosystem? Describe your (or your organization's) Filecoin relationships, investments, or ownership.:**
As an individual, I, Allen Cho, have been involved in IT hardware and software development for over 30 years and am a member of CobaltRay Co., Ltd. He leads several manufacturing and solutions entities, including AbeTree Inc and Zeta Cube Inc. He used to exclusively supply payment equipment and solutions to KakaoPay in Korea, but about six years ago, he began providing cryptocurrency payment-related services and conducted two cryptocurrency ICOs in Singapore. Then, at the end of 2020, I was introduced to Filecoin and received a request to build a data center dedicated to Filecoin. I ended up building five data centers in Seoul, Incheon, Gwangju, Jeonju, and Gyeonggi for IPFS Korea Datacenter. However, due to the decentralized nature of Filecoin and the With the idea that independent regional characteristics, etc. should be reflected, and that a method to dramatically reduce data center construction and management costs should be developed, five patents were issued and an ultra-small data center solution called NANODC was manufactured and launched, and Seoul and We are installing it in Gwangju, Bucheon, etc. and are developing FilMountain, a Filecoin Defi POOL based on this. He manages 8 nodes, including f01227505, and is preparing for DC ceiling by creating a number of new nodes based on NANODC. After meeting Protocol Labs and Filecoin Foundation people for the first time through the Seoul Meetup in August 2022, we directly planned an event called Filecoin Network Day Seoul on December 15, 2022, and invited Protocol Labs executives and Filecoin Foundation people to our Seoul data center. After the successful completion, we continued to participate in and lecture at meetups in Hong Kong, Singapore, and Las Vegas, and many of the videos were posted on Youtub.

**48. How are you estimating your client demand and pathway usage? Do you have existing clients and an onboarding funnel?:**
As already explained, there are five data centers and nodes, and new nodes are being created and data centers are being opened as a way to spread NANODC. Our goal is to open 10 NANODCs by April 2024, and since storage from 2PiB to 10PiB is installed and sealed in each NANODC, about 500PiB will already be secured based on QAP. Therefore, we plan to supply a data cap of 3,000 PiB per year.

**Comment by kevzak** [comment]
## Datacap Request for Allocator
#### Address
> f25h7rohl3giczsv67rbrjm55y3mwd25tlk3cxkmq
#### Datacap Allocated
> 5PiB

**Comment by Kevin-FF-USA** [comment]
Hi @ipfsAllen 

Wanted to send a friendly check in.  
As of this comment date, haven't seen any client applications or DataCap disbursements for the organization.   Inactive organizations are in the process of being [reviewed to see if still wanting to remain in program](https://github.com/filecoin-project/Allocator-Governance/issues/6).    If you would like this pathway to remain active as an Allocator, kindly asking that you reply to [the proposal ](https://github.com/filecoin-project/Allocator-Governance/issues/6) with your timeline for onboarding pathway or plan for action to clients.

[1092](https://github.com/filecoin-project/Allocator-Registry/blob/main/Allocators/1092.json) | ZetaCube Inc" | Manual | [Bookkeeping](https://github.com/ipfsAllen/Fil-DC-Allocator-Allen) | Korea | https://github.com/filecoin-project/notary-governance/issues/1092 | [f03018530](https://filecoinpulse.pages.dev/allocator/f03018530/#pageparamsallocator_id)

**Comment by ipfsAllen** [comment]
Kevin, I just working for the onboarding issue with project in Korea.
Today or rommorrow will start that.
I will working on notary work and allocation job immediately.

Thank you.

Allen

2024년 6월 11일 (화) 오전 8:49, Kevin ***@***.***>님이 작성:
