### ISSUE TITLE
v5 Notary Allocator Application: CIDgravity decentralized onboarding to the mix

### ISSUE THREAD

**Issue by s0nik42** [filecoin-project/notary-governance#1093]
# v5 Notary Allocator Application

To apply to be an allocator, organizations will submit one application for each proposed pathway to DataCap. If you will be designing multiple specific pathways, you will need to submit multiple applications. 

Please complete the following steps:
# 1. Fill out the information below and create a new GitHub Issue

1. Notary Allocator Pathway Name (This can be your name, or the name of your pathway/program. For example "E-Fil+"): CIDgravity decentralized onboarding to the mix
3. Organization Name: Twinquasar - CIDgravity
5. On-chain address for Allocator (Provide a NEW unique address. During ratification, you will need to initialize this address on-chain): f16l3walhmmr3rreaurzmznjq3xypjg3p27t2ht2i
7. Country of Operation (Where your organization is legally based): France
8. Region of Operation (What region will you serve?): World Wide
9. Type of Allocator, diligence process: (Automated/programmatic, Market-based, or Manual (human-in-the-loop at some phase): Automated/programmatic
10. DataCap requested for allocator for 12 months of activity (This should be an estimate of overall expected activity. Estimate the total amount of DataCap you will be distributing to clients in 12 months, in TiB or PiB): 200PiB

# 2. Access allocator application (download to save answers)
Click link below to access a Google doc version of the allocator application that can be used to save your answers if you are not prepared to fully submit the application in Step 3. https://docs.google.com/document/d/1-Ze8bo7ZlIJe8qX0YSFNPTka4CMprqoNB1D6V7WJJjo/copy

# 3. Submit allocation application 
Clink link below to access full allocator questionnaire and officially submit your answers:
https://airtable.com/appvyE0VHcgpAkt4Z/shrQxaAIsD693e1ns

Note: Sections of your responses WILL BE posted back into the GitHub issue tracking your application. 
The final section (Additional Disclosures) will NOT be posted to GitHub, and will be maintained by the Filecoin Foundation. 
Application information for notaries not accepted and ratified in this round will be deleted.

**Comment by Filplus-govteam** [comment]
### Basic Information
**1. Notary Allocator Pathway Name:**
CIDgravity decentralized onboarding to the mix

**2. Organization:**
Twinquasar - CIDgravity

**3. On Chain Address for Allocator:**
f16l3walhmmr3rreaurzmznjq3xypjg3p27t2ht2i

**4. Country of Operation:**
France

**5. Region(s) of operation:**
Africa , Asia minus GCR, Greater China, Europe, Oceania, Japan, North America, South America, Other

**6. Type of Allocator:**
Automatic

**7. DataCap requested for allocator for 12 months of activity:**
200PiB

**8. Is your allocator providing a unique, new, or diverse pathway to DataCap? How does this allocator differentiate itself from other applicants, new or existing?:**
This pathway operates as a fully automated system, prioritizing key benefits:
- Trustless (No KYC/KYB)
- Large data distribution
- User-friendly
	- Fast first-byte onboarding
	- Right first time: CIDgravity selects the miner based on direct miner availability
	- Client and SP dashboards accessible through a user interface (UI)
	- Easy REST API
- Service-free
- Low-risk data allocation (small tranche of datacap, quickly and automatically audited and renewed)
- Deal making is decentralized directly between the client and the SP
- Scalable

Allocation Process Overview:
1. Registration:
   - The client connects to CIDgravity with its GitHub account and claims a Filecoin address in CIDgravity (signs a challenge).
   - The client requests datacap, and a 1 TiB allocation is automatically attached to this address.
  
2. Onboarding:
- For each deal:
	- The client calls the CIDgravity API to get the target miner for the next deal.
	- The client processes the deal using a tool of its choice (Singularity / Boost / etc.).
- When the datacap is as low as 1 TiB, an audit report is created, verifying that client send the deals in accordance to CIDgravity guidance, and the next tranche is automatically allocated.

Reporting / Monitoring:
- Clients can monitor their onboarding through CIDgravity.
- A datacap consumption dashboard will be provided.
- A public page is accessible with all the logs associated with this address.
- Standard Fil+ tools like filplus-checker-app will be compatible.

**9. As a member in the Filecoin Community, I acknowledge that I must adhere to the Community Code of Conduct, as well other End User License Agreements for accessing various tools and services, such as GitHub and Slack.:**
Acknowledge
### Client Diligence
**10. Who are your target clients?:**
Individuals learning about Filecoin, Small-scale developers or data owners, Enterprise Data Clients, Other (specified above)

**11. Describe in as much detail as possible how you will perform due diligence on clients.  If you are proposing an automated pathway, what diligence mechanism will you use to determine client eligibility?:**
No due diligence is necessary. 
This offer is restricted to one Filecoin address per GitHub account. 
The client will be allocated a small tranche at a time. 
To receive a new tranche, clients must submit deals in accordance with the CIDgravity matching engine. Since clients cannot choose the Service Provider (SP) to which deals are sent, this measure effectively prevents fraudulent activities.
In the event that a client fails to adhere to CIDgravity guidance, the next tranche will not be allocated. Any fraudulent activity will be confined to the current allocated tranche.

**12. Please specify how many questions you’ll ask, and provide a brief overview of the questions.:**
N/A

**13. Will you use a 3rd-party Know your client (KYC) service?:**
N/A

**14. Can any client apply to your pathway, or will you be closed to only your own internal clients? (eg: bizdev or self-referral):**
Any clients

**15. How do you plan to track the rate at which DataCap is being distributed to your clients?:**
Each datacap allocation is recorded in the ledger. CIDgravity has direct access to the chain and the preceding datacap allocation epoch before assigning the new one.
### Data Diligence
**16. As an operating entity in the Filecoin Community, you are required to follow all local & regional regulations relating to any data, digital and otherwise. This may include PII and data deletion requirements, as well as the storing, transmit:**
Acknowledge

**17. What type(s) of data would be applicable for your pathway?:**
Public Open Dataset (Research/Non-Profit), Public Open Commercial/Enterprise, Private Commercial/Enterprise, Private Non-Profit/Social Impact, Other (specified elsewhere)

**18. How will you verify a client’s data ownership? Will you use 3rd-party KYB (know your business) service to verify enterprise clients?:**
No KYB nor data ownership will be performed as this offer is specifically crafted to prevent collaboration between clients and Service Providers (SPs) in attempting to cheat the system and the block reward mechanism. More below 19.

**19.  How will you ensure the data meets local & regional legal requirements?:**
The data doesn't flow through our platform but is exchanged in a decentralized manner between the client and the SPs. Proactive data checking is not possible.  In the event of notification (court order,etc…) regarding illegal data, we will suspend the account and promptly inform the SPs responsible for storing the content.

**20. What types of data preparation will you support or require?:**
We do not provide data preparation on this pathway; clients are responsible for self-onboarding the data. We offer user-friendly APIs and integration samples to assist clients in seamlessly integrating their onboarding pipeline with CIDgravity.

**21. What tools or methodology will you use to sample and verify the data aligns with your pathway?:**
N/A
### Data Distribution
**22. How many replicas will you require to meet programmatic requirements for distribution?:**
2+

**23. What geographic or regional distribution will you require?:**
The client has no role in selecting the data location.  The data will be distributed across all regions, allowing for up to 10 copies as per the client's preference. Our track record includes successfully onboarding datasets to 25 different miners, as documented here: [GitHub Link](https://github.com/data-preservation-programs/filplus-checker-assets/blob/main/filecoin-project/filecoin-plus-large-datasets/issues/2217/1703844157484.md).

**24. How many Storage Provider owner/operators will you require to meet programmatic requirements for distribution?:**
2+

**25. Do you require equal percentage distribution for your clients to their chosen SPs? Will you require preliminary SP distribution plans from the client before allocating any DataCap?:**
CIDgravity's algorithm is designed to leverage the best reputation for the selected client.  The algorithm ensures the distribution of data across as many Service Providers (SPs) as possible.  Our estimation indicates that easily reaching 20 SPs is achievable through this approach, optimizing the distribution for enhanced reliability and availability. We ask the client to follow CIDgravity distribution plan before allocating the next tranche.

**26. What tooling will you use to verify client deal-making distribution?:**
By Reconciling the on-chain deals with the miner selection provided to the client by CIDgravity.

**27. How will clients meet SP distribution requirements?:**
The client call the CIDgravity APIs before each deal to obtain information on the next Service Provider to use.

**28. As an allocator, do you support clients that engage in deal-making with SPs utilizing a VPN?:**
Yes, we do
### DataCap Allocation Strategy
**29. Will you use standardized DataCap allocations to clients?:**
Yes, standardized

**30. Allocation Tranche Schedule to clients::**
• First: 1TiB
• Second:2TiB
• Third:5TiB
• Fourth:10TiB
• Max per client overall: No limit

**31. Will you use programmatic or software based allocations?:**
Yes, standardized and software based

**32. What tooling will you use to construct messages and send allocations to clients?:**
CIDgravity is already plugged to the filecoin chain. It will support to send the message natively

**33. Describe the process for granting additional DataCap to previously verified clients.:**
Datacap Exhaustion Check: -	When the Datacap reaches zero, the API ceases to provide information on the next Service Provider (SP) and instead returns an error message: ""No more datacap available. Waiting for next tranche validation."" Concurrent Datacap Renewal Process: -	Simultaneously, the datacap renewal process is initiated. -	If the datacap has been consumed as per CIDgravity's request, the next tranche is automatically allocated by sending a message on-chain.

**34. Describe in as much detail as possible the tools used for: • client discoverability & applications • due diligence & investigation • bookkeeping • on-chain message construction • client deal-making behavior • tracking overall allocator health • disput:**
• client discoverability & applications
ð Current CIDGravity onboarding process , with a new section for selecting datacap pathway
• due diligence & investigation
N/A
• bookkeeping
All actions will be recorded in the CIDgravity database, and a public WebUI will provide access to these logs.
• on-chain message construction
Message send direction by CIDgravity
• client deal-making behavior
We already track any deals since proposed by CIDgravity to onchain status.
• tracking overall allocator health
Stats will be available.
• dispute discussion & resolution
Dispute will be done via slack for private and github for public
• community updates & comms *
We will utilize our Slack channel: #fil-cid-gravity for announcements. These announcements will also be crossposted to all Service Provider (SP) workgroups , #fil-plus and #fil-hobby.
### Tools and Bookkeeping
**35. Will you use open-source tooling from the Fil+ team?:**
To maintain transparency, we will keep our stack’s compliance with the filplus-checker-app.

**36. Where will you keep your records for bookkeeping? How will you maintain transparency in your allocation decisions?:**
We are committed to full transparency by publicly disclosing the following information through our portal:
- Client details
- Filecoin-related addresses
- Comprehensive logs of all actions related to data allocation and new tranche allocation audits, stored in a Datawarehouse
- The capability for clients to run the filplus-checker-app within our platform.

### Risk Mitigation, Auditing, Compliance
**37. Describe your proposed compliance check mechanisms for your own clients.:**
As previously outlined, adherence to our datacap consumption guidances is mandatory. 
Any deviation from these guidelines will result in the automatic suspension of the account. 
Clients seeking a deeper analysis and account reactivation will be subject to a fee.


**38. Describe your process for handling disputes. Highlight response times, transparency, and accountability mechanisms.:**
Disputes between clients and CIDgravity are handled through the outlined process via Slack. 
Disputes involving Allocators and CIDgravity will be managed through the community-defined process on Slack and GitHub.


**39. Detail how you will announce updates to tooling, pathway guidelines, parameters, and process alterations.:**
Part of the CIDgravity annoucement already in place and as descibed above.

**40. How long will you allow the community to provide feedback before implementing changes?:**
- Rules of allocation-related changes: 1 month notice
- Critical issues (security flaws in the process/abuse/adding more constraints): 5 days’ notice
- UX/API changes: No notifications


**41. Regarding security, how will you structure and secure the on-chain notary address? If you will utilize a multisig, how will it be structured? Who will have administrative & signatory rights?:**
The entire process will be fully automated. Instead of utilizing a multisig, the signatory key will be encrypted with a passphrase known exclusively to Julien NOEL.

**42. Will you deploy smart contracts for program or policy procedures? If so, how will you track and fund them?:**
Not planned yet.
### Monetization
**43. Outline your monetization models for the services you provide as a notary allocator pathway.:**
No monetization will be applied to this pathway. 
""This is a complimentary service crafted to streamline and accelerate data onboarding to Filecoin, aiming to minimize friction in client-SP relationships by preventing the artificial increase of miner power to earn more block rewards.


**44. Describe your organization's structure, such as the legal entity and other business & market ventures.:**
CIDgravity is a solution developed by Twin Quasar. A French company leader in the Filecoin ecosystem / PLN. Since 2021

**45. Where will accounting for fees be maintained?:**
N/A
### Past Experience, Affiliations, Reputation
**46. If you've received DataCap allocation privileges before, please link to prior notary applications.:**
We’ve been notary since 2021 round 1. Notary Round 1 : https://github.com/filecoin-project/notary-governance/issues/5 Notary Round 2 : https://github.com/filecoin-project/notary-governance/issues/136 Notary Round 3 : https://github.com/filecoin-project/notary-governance/issues/468 Notary Round 4 : https://github.com/filecoin-project/notary-governance/issues/739

**47. How are you connected to the Filecoin ecosystem? Describe your (or your organization's) Filecoin relationships, investments, or ownership.:**
Twin Quasar provides top-tier solutions, delivering infrastructure and open-source tooling designed for storage providers and Filecoin ecosystem partners as well as seamless data onboarding and Filecoin+ services. Strategically located in Paris, our facilities are directly connected to our 12,000km fiber backbone network. Explore our Tier 3 colocation services, managed services, IaaS, and Filecoin expertise, all marked by a first-class 100% client satisfaction rate, and run on 100% renewable energy.

**48. How are you estimating your client demand and pathway usage? Do you have existing clients and an onboarding funnel?:**
We expect this to be massive as it’s the easiest, the most simple and straightforward pathway for real clients.

**Comment by galen-mcandrew** [comment]
## Datacap Request for Allocator
#### Address
> f16l3walhmmr3rreaurzmznjq3xypjg3p27t2ht2i
#### Datacap Allocated
> 5PiB
