### ISSUE TITLE
FF Social Impact Notary Allocator Application

### ISSUE THREAD

**Issue by ianconsolata** [filecoin-project/notary-governance#1096]
# v5 Notary Allocator Application

1. Notary Allocator Pathway Name (This can be your name, or the name of your pathway/program. For example "E-Fil+"):

**FF Social Impact**

2. Organization Name:

**Filecoin Foundation (FF)**

3. On-chain address for Allocator (Provide a NEW unique address. During ratification, you will need to initialize this address on-chain): 

**Created new multisig:  `f02943486` `f2lrh4szv7ymlmit7qprpk6re2cpksgjgcdth5f3a`**

4. Country of Operation (Where your organization is legally based): 

**United States**

5. Region of Operation (What region will you serve?): 

**Global**

6. Type of Allocator, diligence process: (Automated/programmatic, Market-based, or Manual (human-in-the-loop at some phase):

**Manual**

7. DataCap requested for allocator for 12 months of activity (This should be an estimate of overall expected activity. Estimate the total amount of DataCap you will be distributing to clients in 12 months, in TiB or PiB):

**5 PiB**

**Comment by Filplus-govteam** [comment]
### Basic Information
**1. Notary Allocator Pathway Name:**
FF Social Impact

**2. Organization:**
Filecoin Foundation (FF)

**3. On Chain Address for Allocator:**
Created new multisig:  f02943486 f2lrh4szv7ymlmit7qprpk6re2cpksgjgcdth5f3a

**4. Country of Operation:**
United States

**5. Region(s) of operation:**
Africa , Asia minus GCR, Greater China, Europe, Oceania, Japan, North America, South America, Other

**6. Type of Allocator:**
Manual

**7. DataCap requested for allocator for 12 months of activity:**
5 PiB

**8. Is your allocator providing a unique, new, or diverse pathway to DataCap? How does this allocator differentiate itself from other applicants, new or existing?:**
Yes. The Filecoin Foundation (FF) Social Impact team works with a variety of high profile, deeply impactful projects looking to onboard useful data to the Filecoin network, including Starling Lab, the Internet Archive, the Prelinger Archive, The University of Maryland EASIER Data Initiative, MIT Open Learning, Harvard Library Innovation Lab, and many more.

The FF Social Impact team is applying to become a Fil+ Allocator so we can provide hands-on support to FF/FFDW Social Impact award recipients (“social impact awardees”) in acquiring and refilling the DataCap needed to achieve the goals of the projects we collaborate with them on. Because of our close professional relationship with these orgs and the funding support we provide we are uniquely qualified to run the allocator that serves them. Since we will only be working with social impact awardees  we will have a significantly different process from other applicants.

**9. As a member in the Filecoin Community, I acknowledge that I must adhere to the Community Code of Conduct, as well other End User License Agreements for accessing various tools and services, such as GitHub and Slack.:**
Acknowledge
### Client Diligence
**10. Who are your target clients?:**
Other (specified above)

**11. Describe in as much detail as possible how you will perform due diligence on clients.  If you are proposing an automated pathway, what diligence mechanism will you use to determine client eligibility?:**
In order to receive an FF or FFDW award from the Social Impact team, organizations must go through an extensive due diligence process including multiple meetings both online and in person. This diligence process includes vetting each social impact awardee organization through a robust KYC system (outlined in the KYC question below).

Our diligence process culminates in a signed legal agreement with a specific individual, institution, or organization. Since we will be exclusively working with social impact awardees who have already been through this diligence process, the only additional diligence we will likely perform before disbursing DataCap is ensuring they have taken adequate security measures to protect the wallet to which we will be allocating DataCap.

**12. Please specify how many questions you’ll ask, and provide a brief overview of the questions.:**
FF Social Impact has a standard list of more than a dozen questions we seek to answer for each potential awardee before the relationship is formalized with a signed agreement.  These questions focus on the project’s charitable or social benefits, how it aligns with the Foundation’s priorities, the resources required to make the project a success, and how we will measure that success.  

**13. Will you use a 3rd-party Know your client (KYC) service?:**
We will use an internal robust KYC process, including:
- Retrieving prior year’s 990 forms and IRS letter of determination from nonprofit organizations
- Reviewing individual contributors, including an OFAC search performed on signer, board (if available), external program manager, and key individuals working on the project itself

Additionally, in order to provide an additional layer of security and trust, we operate under the principles of Separation of Duty once the candidate has passed an initial screening performed by the Social Impact team. This means we do not rely on the program managers and funding decision makers on the FF Social Impact team to conduct OFAC sanctions checks and pre-payment diligence, but rely on other separate teams.

**14. Can any client apply to your pathway, or will you be closed to only your own internal clients? (eg: bizdev or self-referral):**
No, only our social impact awardees would be eligible to receive DataCap from our allocator.

**15. How do you plan to track the rate at which DataCap is being distributed to your clients?:**
We will keep an Airtable spreadsheet tracking the disbursements to our social impact awardees and the date the DataCap was transferred. At first, we will maintain this list manually, but if that proves cumbersome we will add automated tracking of disbursements from chain state.
### Data Diligence
**16. As an operating entity in the Filecoin Community, you are required to follow all local & regional regulations relating to any data, digital and otherwise. This may include PII and data deletion requirements, as well as the storing, transmit:**
Acknowledge

**17. What type(s) of data would be applicable for your pathway?:**
Other (specified elsewhere), Private Non-Profit/Social Impact, Public Open Commercial/Enterprise, Public Open Dataset (Research/Non-Profit)

**18. How will you verify a client’s data ownership? Will you use 3rd-party KYB (know your business) service to verify enterprise clients?:**
FF Social Impact engages closely with all potential awardees, including a robust KYC / KYB process on all individuals involved in the project as outlined above.  This engagement process includes multiple meetings, formal vetting, and the signing of an official agreement. Over the course of this engagement we also verify the client’s data ownership.

**19.  How will you ensure the data meets local & regional legal requirements?:**
We review each proposed project in detail, and have dedicated program managers for each project to ensure ongoing compliance.

**20. What types of data preparation will you support or require?:**
We provide active support to our social impact awardees in uploading via engineers on the Social Impact team, and work on a case by case basis with our social impact awardees to determine the best data preparation and data onboarding tools for their use case. We have no requirements that they use specific tools or preparation pipelines.

**21. What tools or methodology will you use to sample and verify the data aligns with your pathway?:**
As part of our existing due diligence with our social impact awardees, we will manually sample the uploaded CIDs to ensure they are retrievable according to the agreed upon retrieval pathway for that project. Over time, we hope to replace our manual random verification with a more automated and robust process, potentially using the retrieval bot or similar tooling.
### Data Distribution
**22. How many replicas will you require to meet programmatic requirements for distribution?:**
2+

**23. What geographic or regional distribution will you require?:**
We will require at least 4 geographically diverse replicas (including copies stored using non-Filecoin systems). We will require at least 2 replicas stored on 2 separate Filecoin SPs which are not affiliated with the social impact awardee who owns the dataset. For example, if the Internet Archive becomes a Storage Provider, they would be required to store their data with 2 Storage Providers in addition to storing it on their own nodes, for a total of 3 replicas. A maximum of 1 replica will be self-stored with a node affiliated with the social impact awardee who is uploading the data, though that awardee may store data affiliated with other awardees as long as the two projects are not run by the same organization. We will require at least two separate geopolitical regions. While we will not exclude any geopolitical regions as part of program requirements (aside from restrictions imposed under U.S. sanctions), individual projects may also request exclusion from specific geopolitical areas on a project-by-project basis, and we will incorporate this into our criteria. 

**24. How many Storage Provider owner/operators will you require to meet programmatic requirements for distribution?:**
2+

**25. Do you require equal percentage distribution for your clients to their chosen SPs? Will you require preliminary SP distribution plans from the client before allocating any DataCap?:**
We will not require equal percentage distribution among chosen SPs. Given the size of many of the datasets our social impact awardees are uploading, the bottleneck has historically been finding enough reliable SPs with capacity and willingness to take the data. Many SPs will only upload a small portion of the data before running out of capacity or deciding to stop onboarding for other reasons. Some SPs have proven unreliable by corrupting or losing data. Balancing these dynamic concerns is a challenge, and sometimes requires prioritizing some SPs over others. While we cannot promise equal distribution, we will encourage our social impact awardees to be equitable and fair in distributing data between all willing SPs who meet their reliability and capacity requirements.

**26. What tooling will you use to verify client deal-making distribution?:**
We will manually verify using datacapstats.io.

**27. How will clients meet SP distribution requirements?:**
This will be left up to individual social impact awardees to decide. Some of our larger data onboarding projects currently use Spade, while others work with a lead SP who is responsible for redistributing data to secondary SPs.

**28. As an allocator, do you support clients that engage in deal-making with SPs utilizing a VPN?:**
We do not anticipate this scenario, but could consider working with clients and SPs who engage in deal-making utilizing VPNs on a case by case basis. If this is the case, we will not track and report VPN usage ourselves, but will closely investigate VPN usage publicly and privately reported to us and take appropriate action when necessary.
### DataCap Allocation Strategy
**29. Will you use standardized DataCap allocations to clients?:**
No, client specific

**30. Allocation Tranche Schedule to clients::**
We will structure allocations on a case by case basis depending on the total size of the dataset our partners are uploading, and their expected data onboarding rate. Our allocations will aim to provide enough DataCap for our social impact awardees to continue uploading data at their intended rate for at least a month before requesting a new allocation.

We have no set schedule for allocations or max allocations per project. Our projects vary wildly in size, and so the amount of DataCap allocated to each project will be determined on a case by case basis. After a smaller initial allocation for testing and validation of their data onboarding pipeline, subsequent allocations will be based on their previously demonstrated data onboarding rate and will cover at least 1 month of continued data onboarding at their current rate.

**31. Will you use programmatic or software based allocations?:**
No, manually calculated & determined

**32. What tooling will you use to construct messages and send allocations to clients?:**
We will use lotus CLI commands + Ledger wallets to manually send new allocations to clients.

**33. Describe the process for granting additional DataCap to previously verified clients.:**
A social impact awardees will contact a member of the FF Social Impact team requesting a new allocation via email when they anticipate they will run out soon, or they have already run out. The FF Social Impact team will then verify how much DataCap they have remaining and what their data onboarding rate has been during the previous allocation period. We will then issue them a new DataCap allocation covering at least 1 month’s worth of data onboarding at their historical rate.

**34. Describe in as much detail as possible the tools used for: • client discoverability & applications • due diligence & investigation • bookkeeping • on-chain message construction • client deal-making behavior • tracking overall allocator health • disput:**
Social impact awardees will request new allocations and apply for the program via Email, including specifying which wallet address to use. They will then be added to the public Airtable spreadsheet mentioned below.
For due diligence we will use the processes outlined in our other responses.

Disbursements will be tracked using the public Airtable spreadsheet, and on-chain messages will be executed via Ledger wallets / Lotus. Additional automation will be built or integrated on an as needed basis.
Client deal making behavior will be tracked via datacapstats.io, and through regular in-person conversations and oversight with our social impact awardees who are making the deals.
We will attempt to resolve disputes, as well as provide community updates and comms, through our existing communication channels with partners and the wider community, which includes Slack, Signal, Email, Google Meet, and Zoom.
### Tools and Bookkeeping
**35. Will you use open-source tooling from the Fil+ team?:**
Only datacapstats.io. The rest of our process will rely on our own open source tooling and private tracking via tools like Airtable, Google Drive, and Email .

**36. Where will you keep your records for bookkeeping? How will you maintain transparency in your allocation decisions?:**
Initially, we plan to track and audit DataCap distribution using a shared Airtable spreadsheet that is publicly auditable: https://airtable.com/appeVumC6EBSC785l/shrHPdb3Ye41BD8Ev/tblLCJWKHkeQAdmKt/viwTEixU8PmhPTZkz

This Airtable sheet will have two sheets. The first will track allocations, including information about when DataCap was allocated, who approved the allocation, and which wallet it was allocated to. The second sheet will track which projects are part of the FF Social Impact Allocator program, including the following info about the project:
- Name of your organization
- Organizational website (if applicable)
- Title of project
- Short summary of project (max 300 words) 
- Project website (if applicable)
- Wallet Address
- Estimated Dataset Size
- Date joined

Over time, we plan to build more extensive monitoring infrastructure that allows us to track which CIDs our social impact awardees are storing, the retrievability of that data, and the terms of the associated deals (including if DataCap was used, and if it was which Allocator that DataCap came from). To build this infrastructure, we will rely on existing tools as much as possible, and have a public dashboard with information about social impact datasets supported by our team.
### Risk Mitigation, Auditing, Compliance
**37. Describe your proposed compliance check mechanisms for your own clients.:**
Initially, we plan to track and audit DataCap distribution using a shared Airtable spreadsheet. Over time, we plan to build more extensive monitoring infrastructure that allows us to track which CIDs our social impact awardees are storing, the retrievability of that data, and the terms of the associated deals (including if DataCap was used, and if it was which Allocator that DataCap came from). To build this infrastructure, we will rely on existing tools as much as possible, and have a public dashboard where information about social impact datasets supported by our team can be viewed.

New projects will be given an initial allocation of DataCap to allow them to experiment and build out their pipeline. Once they have an established throughput, we will work with them to decide on a cadence for regular allocations that makes sense for their project.

**38. Describe your process for handling disputes. Highlight response times, transparency, and accountability mechanisms.:**
Social Impact Allocator disputes should be communicated to impact@fil.org. We will provide best effort response times to any disputes or calls for accountability by the broader community and will respond on a case by case basis to the complaints raised.

**39. Detail how you will announce updates to tooling, pathway guidelines, parameters, and process alterations.:**
All social impact awardees send 1-2 representatives to quarterly calls hosted by the FF Social Impact team. We will announce any significant changes to our Allocator process on these quarterly calls, and will include notifications of any upcoming changes in our regular email correspondence with awardees. Additionally, since our list of awardees is small and we meet regularly, we will directly follow up with any affected awardees to coordinate changes with them.

**40. How long will you allow the community to provide feedback before implementing changes?:**
We engage with our social impact awardees on a regular basis, often having multiple meetings with each awardee every month. We anticipate a tight feedback loop between our awardees and Allocator operations to ensure the process is as smooth as possible for them. Any issues with the Allocator process raised by our awardees will be addressed as swiftly as possible.

**41. Regarding security, how will you structure and secure the on-chain notary address? If you will utilize a multisig, how will it be structured? Who will have administrative & signatory rights?:**
We will use a multi-sig wallet with a threshold of 1 so that multiple members of the social impact team can approve new requests as they come in. The signers on that wallet will be Danny O’Brien, Hunter Treseder, Ian Davis, and Jefferson Sankara, who will each have Ledger hardware wallets that will be used to make allocations.

**42. Will you deploy smart contracts for program or policy procedures? If so, how will you track and fund them?:**
We do not anticipate needing smart contracts at this time. If they are needed, they will be developed by the FF Social Impact team and funded through our normal budgetary process.
### Monetization
**43. Outline your monetization models for the services you provide as a notary allocator pathway.:**
Our service will not be monetized, and will be freely available for all of our social impact awardees.

**44. Describe your organization's structure, such as the legal entity and other business & market ventures.:**
The Filecoin Foundation is an independent organization that facilitates governance of the Filecoin network, funds critical development projects, supports the growth of the Filecoin ecosystem, and advocates for Filecoin and the decentralized web.

**45. Where will accounting for fees be maintained?:**
Not Applicable
### Past Experience, Affiliations, Reputation
**46. If you've received DataCap allocation privileges before, please link to prior notary applications.:**
Danny O’Brien is a member of our team and has been extremely active in the notary process in the past: https://github.com/filecoin-project/notary-governance/issues/469, https://github.com/filecoin-project/notary-governance/issues/750

**47. How are you connected to the Filecoin ecosystem? Describe your (or your organization's) Filecoin relationships, investments, or ownership.:**
The Filecoin Foundation is an independent organization that facilitates governance of the Filecoin network, funds critical development projects, supports the growth of the Filecoin ecosystem, and advocates for Filecoin and the decentralized web.

**48. How are you estimating your client demand and pathway usage? Do you have existing clients and an onboarding funnel?:**
We have existing awardees who are part of the LDN notary process. We are estimating our pathway usage based on past allocations to those awardees

**Comment by galen-mcandrew** [comment]
## Datacap Request for Allocator
#### Address
> f2lrh4szv7ymlmit7qprpk6re2cpksgjgcdth5f3a
#### Datacap Allocated
> 5PiB
