### ISSUE TITLE
v5 Notary Allocator Application:Titan Network

### ISSUE THREAD

**Issue by TitanNet** [filecoin-project/notary-governance#1097]
# v5 Notary Allocator Application

To apply to be an allocator, organizations will submit one application for each proposed pathway to DataCap. If you will be designing multiple specific pathways, you will need to submit multiple applications. 

Please complete the following steps:
# 1. Fill out the information below and create a new GitHub Issue

1. Notary Allocator Pathway Name (This can be your name, or the name of your pathway/program. For example "E-Fil+"):Titan Network
3. Organization Name:Titan Network
4. On-chain address for Allocator (Provide a NEW unique address. During ratification, you will need to initialize this address on-chain): f1nns66tt2vmcfxu74n5glbf4dclf62pod5ecdnay
5. Country of Operation (Where your organization is legally based): SINGAPORE
6. Region of Operation (What region will you serve?): All Regions
7. Type of Allocator, diligence process: (Automated/programmatic, Market-based, or Manual (human-in-the-loop at some phase): Manual
9. DataCap requested for allocator for 12 months of activity (This should be an estimate of overall expected activity. Estimate the total amount of DataCap you will be distributing to clients in 12 months, in TiB or PiB):50PiB

# 2. Access allocator application (download to save answers)
Click link below to access a Google doc version of the allocator application that can be used to save your answers if you are not prepared to fully submit the application in Step 3. https://docs.google.com/document/d/1-Ze8bo7ZlIJe8qX0YSFNPTka4CMprqoNB1D6V7WJJjo/copy

# 3. Submit allocation application 
Clink link below to access full allocator questionnaire and officially submit your answers:
https://airtable.com/appvyE0VHcgpAkt4Z/shrQxaAIsD693e1ns

Note: Sections of your responses WILL BE posted back into the GitHub issue tracking your application. 
The final section (Additional Disclosures) will NOT be posted to GitHub, and will be maintained by the Filecoin Foundation. 
Application information for notaries not accepted and ratified in this round will be deleted.

**Comment by Filplus-govteam** [comment]
### Basic Information
**1. Notary Allocator Pathway Name:**
Titan Network

**2. Organization:**
Titan Network

**3. On Chain Address for Allocator:**
f1nns66tt2vmcfxu74n5glbf4dclf62pod5ecdnay

**4. Country of Operation:**
Singapore

**5. Region(s) of operation:**
Africa , Asia minus GCR, Greater China, Europe, Oceania, Japan, North America, South America, Other

**6. Type of Allocator:**
Manual

**7. DataCap requested for allocator for 12 months of activity:**
50PiB

**8. Is your allocator providing a unique, new, or diverse pathway to DataCap? How does this allocator differentiate itself from other applicants, new or existing?:**
Titan Network as a DePin resource platform, has significant advantages in the Filecoin network, which are reflected not only in its abundant bandwidth and storage resources, but also in its capabilities and understanding of customer needs. Below is an optimized description of Titan Network's core advantages:
1. Resource Advantage: Titan Network not only provides extensive bandwidth resources, but also has a large amount of storage space. This enables it to serve a large and diverse group of users, meeting their needs for high-quality storage and data transfer.
2. Data Processing Diversity: Titan Network is able to process many types of data sets, including but not limited to encrypted data, enterprise data, and public data sets. This diversity enables it to provide customized DataCap to different customers, helping them integrate into the Filecoin network more easily.
3. Strict Monitoring and Approval Process: Through a combination of manual allocation and automated monitoring systems, Titan Network is able to monitor storage provider utilization in real-time and make quick approval decisions. This process is designed to ensure an efficient and compliant allocation process.
4. Ongoing Compliance Monitoring: Titan Network utilizes its monitoring system to track user behavior and ensure that all activities are in compliance with Filecoin Network regulations and standards.
5. Data Preparation and Technical Support: With a technical team that is well versed in data processing tools such as go-graphsplit and singularity, as well as abundant hardware resources, Titan Network is able to efficiently convert data uploaded by clients into car file format and send it to storage providers. This service reduces the difficulty of storage operations for clients, while improving the convenience and efficiency of the storage process, ensuring a smooth and efficient storage experience for clients in the Filecoin ecosystem.
Overall, Titan Network provides efficient, compliant and easy-to-use storage solutions for enterprises and individuals in the Filecoin network through its resource advantages, data processing capabilities, strict monitoring processes, continuous compliance monitoring and technical support.

**9. As a member in the Filecoin Community, I acknowledge that I must adhere to the Community Code of Conduct, as well other End User License Agreements for accessing various tools and services, such as GitHub and Slack.:**
Acknowledge
### Client Diligence
**10. Who are your target clients?:**
Individuals learning about Filecoin, Small-scale developers or data owners, Enterprise Data Clients, Other (specified above)

**11. Describe in as much detail as possible how you will perform due diligence on clients.  If you are proposing an automated pathway, what diligence mechanism will you use to determine client eligibility?:**
To ensure efficient and comprehensive due diligence, Titan Network has adopted a comprehensive set of strategies to improve the quality of its services and customer satisfaction in the Filecoin ecosystem. The following is a streamlined and optimized version of these strategies:
1. Identity verification and background checks:
a.For individual clients, verify online identities by analyzing account age and activity history, supplemented by third-party tools (e.g., twitteraudit) to identify and troubleshoot non-authentic users.
b.For institutional clients, initially review the appearance of their applications and conduct in-depth investigations of applications under development to confirm legitimacy and validity.
c.Execute a comprehensive background check covering social media and official website review, as well as assessing customer credibility through credit rating agencies and industry recommendations.
2.Due diligence process:
a.Review key customer information, including entity information, authorized signer and beneficial owner information.
b.Verify the legal identity and authorized behavior of authorized signers and beneficial owners to ensure that the information is true and valid.
3. Data security and privacy protection:
a.Adopt high standards of data protection measures throughout the due diligence process, including the use of encryption to ensure secure transmission and storage of data.
4. Transparency and customer interaction:
a.Clearly explain the due diligence process and standards to clients, and gain insight into client needs and background through regular video conferences or telephone communications.
5. Ongoing monitoring and evaluation:
a.Consider due diligence as an ongoing process, with periodic reassessment of customer eligibility to adapt to the evolution of the Filecoin ecosystem and new standards.
6. Team training and customer education:
a.Regularly train the team on compliance, due diligence methods and data protection regulations.
b.Provide training or guidance to customers on the Filecoin ecosystem and DataCap requirements.
By implementing these strategies, Titan Network aims to simultaneously protect customer data and enhance customer trust, ensure fair and transparent distribution of DataCap, and strengthen its position in the Filecoin ecosystem. These measures also include online authentication of individual customers and review of public datasets hosted by institutional customers. In addition, for organizational customers with large private encrypted datasets (e.g., law firms), a more rigorous due diligence process will be implemented

**12. Please specify how many questions you’ll ask, and provide a brief overview of the questions.:**
To ensure that our customers use DataCap responsibly, we implement an exhaustive due diligence process. This process is designed to fully validate customer identifying information for both individual and business customers.
Individual customer identity verification:
Identity Card Number
Name
Date of Birth
Passport copy
Residential address
Social media accounts (Facebook, LinkedIn, Twitter, etc.)
Local office contact information
Social reputation (including awards and achievements)
Corporate customer identification:
Certificate of Incorporation or Business License
Company address
Company website
Company social media accounts (Facebook, LinkedIn, Twitter, etc.)
Record of lawsuits and legal reputation
Company shareholding structure and key shareholders
Copies of company correspondence with company seal and director/shareholder signatures
Detailed due diligence for shareholders with more than 20% shareholding until the ultimate beneficiary or beneficial shareholder is identified
Client questionnaire:
Identity Confirmation: Please confirm whether you are applying as an individual or an organization by providing your name or the name of your organization.
Links to online platforms: provide links to your or your organization's social media and websites.
Stored Data Details: specify the amount of data you wish to store, detailing the amount of data by use case type, source and category.
DataCap sources: if you have obtained DataCap from other notaries, provide a list of them.
Cloud Service/Platform Usage: Describe the cloud service or platform you use, including frequency of use, amount of data, price/rate, and purpose of use.
Data Allocation Plan: Describe how many miners you plan to allocate your data to and the amount of data allocated per miner.
Allocation Transparency: Provides transparency into your DataCap allocations, decisions and execution.
FileCoin Advanced Features Application: lists the FileCoin advanced features you use.
Stored Content Compliance: Ensure that the content you store is compliant with local laws and FileCoin community standards, indicating whether any potential customers are paying for it.
Data Storage Locations and Fees: Detail where your data is stored, the total amount, and the annual fees.

**13. Will you use a 3rd-party Know your client (KYC) service?:**
Yes, for example, Enterprise Search (https://www.qcc.com/) and Eyeball Search (www.tianyancha.com), which provide different functions and services that can fulfill the needs of auditing business information search.

**14. Can any client apply to your pathway, or will you be closed to only your own internal clients? (eg: bizdev or self-referral):**
At Titan Network, we are committed to supporting the growth of the Filecoin network by providing an open and transparent DataCap allocation path for all customers. Our goal is to provide a convenient and efficient application path for all customers who wish to join the Filecoin ecosystem. Below are the features and promises of our service: Full openness: We welcome applications from all types of clients, whether they are companies or self-employed, and all have equal access to our services. Transparent process: We will publicize a clear application process to ensure that every applicant can easily participate and understand the application steps. Professional Technical Support: Our professional team will provide technical assistance to help solve any technical problems that may arise during the application process. Client Coaching: We not only help our clients understand the application process, but we also provide guidance throughout the process to ensure that every applicant completes the application successfully. Promoting network growth: Our services are designed to expand and enrich the Filecoin ecosystem, attracting more participants from different backgrounds and working together to promote the growth and development of the network.

**15. How do you plan to track the rate at which DataCap is being distributed to your clients?:**
We at Titan Network have currently implemented a highly effective DataCap monitoring strategy to ensure real-time visibility and management of customer distribution activities. This strategy includes the following core components: 1. Real-time monitoring system: Through our self-developed monitoring system, we utilize the Lotus API interface to obtain DataCap usage in real-time. 2. Threshold Alert Mechanism: We set specific thresholds, and once DataCap usage reaches these preset conditions, our monitoring bot (BOT) will send alerts on social media platforms commonly used by the team (e.g., Wechat) and via SMS and phone calls for timely response. Future plans: In the long run, we plan to migrate part of the distribution work to smart contracts and combine it with the data provided by the ""CID checker tool"" to realize that the contract will automatically perform DataCap distribution when certain conditions are met!
### Data Diligence
**16. As an operating entity in the Filecoin Community, you are required to follow all local & regional regulations relating to any data, digital and otherwise. This may include PII and data deletion requirements, as well as the storing, transmit:**
Acknowledge

**17. What type(s) of data would be applicable for your pathway?:**
Public Open Dataset (Research/Non-Profit), Public Open Commercial/Enterprise, Private Commercial/Enterprise, Private Non-Profit/Social Impact, Other (specified elsewhere)

**18. How will you verify a client’s data ownership? Will you use 3rd-party KYB (know your business) service to verify enterprise clients?:**
At Titan Network, we conduct rigorous validation of the different types of datasets provided by our customers when applying for DataCap to ensure data ownership authenticity and legitimacy. Our validation process is detailed for both public datasets and private datasets, including enterprise data:
Public dataset validation:
1. Source Information Requirements: Clients are required to provide detailed information about the dataset, including the name of the dataset, a link to the website where it resides, and information about the team or organization to which the data belongs. This helps us to confirm the public nature and accessibility of the dataset.
Enterprise dataset, encrypted & private dataset validation:
1. Legal Documentation Review: Customers must provide copyright notices, ownership certificates, or other relevant legal documents. We will verify the authenticity and validity of these documents using electronic signature and document verification tools such as eSignature or Fada.
2. Enterprise third-party KYB service: For enterprise customers, we will conduct enterprise background investigation and identity verification through KYB service providers such as Enterprise Search or Tianyecha.
3. Liability waiver commitment: Customers are required to sign a liability waiver commitment, stating the legitimacy of the data provided and the assumption of responsibility for any data issues.
4. Face-to-face communication: Direct communication with the customer through video conferencing tools (e.g. Tencent Conference or Nail) to gain an in-depth understanding of data ownership and usage.
5. Data consistency check: Verify the data content provided by the client against its stated ownership to verify the consistency and integrity of the data.
Through these meticulous and multi-layered verification measures, we aim to ensure that we accurately determine the ownership of our clients' datasets while complying with legal requirements and ethical standards, further enhancing the reliability and compliance of our services.

**19.  How will you ensure the data meets local & regional legal requirements?:**
Titan Network has a number of strict legal compliance measures in place to ensure the legitimacy and security of our customers' data, aiming to be fully compliant with the laws and regional regulations of the regions in which our customers are located. Our key measures include: 1. Legal Compliance Review: Sample data provided by our clients is reviewed in detail against the legal requirements of the client's location to ensure that the data complies with local regulations. 2. Data sample analysis: Meticulous evaluation of provided data samples to identify whether they contain infringing or illegal content. 3. Secure Storage and Transmission: We require our clients to use secure storage and transmission methods. 4. Legal information update: Our professional legal team is responsible for regularly updating the latest legal requirements related to data protection to ensure that our services develop in tandem with the law. 5. Ongoing Compliance Assurance: Ensure that all operations comply with the data protection legal requirements of different regions.

**20. What types of data preparation will you support or require?:**
Our technical team specializes in providing our clients with professional Car data packaging services to ensure that data is processed efficiently and accurately. Service features include: 1.Technical expertise: our team is proficient in go-graphsplit, singularity and other advanced tools to ensure efficient and accurate data packaging. 2.Data processing process: Using self-developed programs, we cut and pack customer data, then compress it into 28-32GB zip files to meet the storage standards of Filecoin network. 3. File conversion and cooperation: Use code base programs such as go-car to convert zip files to car file format.

**21. What tools or methodology will you use to sample and verify the data aligns with your pathway?:**
To ensure data authenticity and compliance, Titan Network implemented the following key steps: 1. Automated Tool Use: Automated tools are provided to clients for random sampling and analysis of client data. These tools automatically check the format of the data and evaluate it against predetermined data sample types to ensure data consistency. 2. Preventing Sector Size Abuse: Supports DP (Data Preparation) service to help clients with data packing. The required packing size is 28-32GiB to prevent sector size abuse. 3. Data Retrieval and Analysis: If the customer needs data packing service, we will retrieve the relevant files and check the actual size through GraphSync, Http, etc. to determine whether there is sector size abuse. 4. AC Bot Integration: Utilizing the AC Bot developed by Filecoin's governance team, we automatically verify the type and readiness of the data to ensure that it matches our standards.
### Data Distribution
**22. How many replicas will you require to meet programmatic requirements for distribution?:**
3+

**23. What geographic or regional distribution will you require?:**
1. Politically independent regional distribution: It is recommended that customers distribute their data in at least two or more politically independent regions to minimize the risks associated with political or legal changes in a single region. 2. Multi-city storage strategy: In order to enhance the reliability of data backup and disaster recovery capability, it is recommended that customers store data in three or more cities, and encouraged to store more than five copies of data. 3. Worldwide decentralized data storage: Customers are supported and encouraged to decentralize data storage globally to provide wider accessibility and further enhance data security. 4. Compliance with Laws and Regulations and International Sanctions: While recommending data storage on a global scale, we also comply with relevant laws and regulations and advise customers to avoid storing data in areas that may be controversial or subject to international sanctions.

**24. How many Storage Provider owner/operators will you require to meet programmatic requirements for distribution?:**
5+

**25. Do you require equal percentage distribution for your clients to their chosen SPs? Will you require preliminary SP distribution plans from the client before allocating any DataCap?:**
1. Allocation Plan Submission: Customers are required to submit a detailed allocation plan before the first allocation of DataCap. This plan should contain the percentages allocated to different Service Providers (SPs) and their KYB (Know Your Business) information. 2. Allocation percentage flexibility: We have not set a fixed allocation percentage to provide greater flexibility. However, in order to promote diversity, the maximum allocation share for a single SP is set at no more than 35%. 3. Ability to adapt to changes: Considering the unpredictable factors that may arise in practice, we allow clients to make adjustments to the original allocation plan and accept the addition of new SPs when necessary. 4. Adherence to the allocation plan: Customers are required to follow the submitted allocation plan. Before the first round of DataCap allocation, the client must fill in and submit the form provided by us, which specifies the allocation ratio of different SPs and their KYB information.

**26. What tooling will you use to verify client deal-making distribution?:**
We will use existing open source tools AC Bot, CID Checker and DataCapstats.io to check the distribution of customer transactions.

**27. How will clients meet SP distribution requirements?:**
In terms of DataCap distribution, Titan Network adopts the following strategies and measures to fulfill customers' data distribution needs and ensure process compliance and efficiency: 1. Fully Understanding Customer Needs: First and foremost, we take a deep dive into our customers' specific needs for data distribution. This step ensures that we are able to accurately tailor DataCap distribution to client needs within the FIL+ compliance framework. 2. Worldwide SP search: If the number of SPs (Service Providers) is insufficient in certain regions, we help our clients search for more SPs globally by utilizing multiple channels such as Slack, Wechat, and DSPA. 3. Uniform allocation based on history: During the allocation process, our platform makes uniform allocation based on the client's history. This not only ensures the compliance of allocation, but also improves the efficiency of allocation.

**28. As an allocator, do you support clients that engage in deal-making with SPs utilizing a VPN?:**
We are willing to support customers who work with SPs that use VPNs, first and foremost, we understand that SPs use VPNs to enhance their cybersecurity and privacy protections in countries or regions where specific policies are sensitive. Also to ensure compliance and security, Titan Network implements a more rigorous Know Your Business (KYB) process for those SPs using VPNs when supporting customers working with Service Providers (SPs) that use VPNs. This aims to gain insight into the specific reasons why SPs are using VPNs and to ensure that their activities comply with relevant laws and regulations. Through enhanced KYB checks, we are able to ensure that all operations related to the use of VPNs are carried out within a compliant framework, while also safeguarding customer data.
### DataCap Allocation Strategy
**29. Will you use standardized DataCap allocations to clients?:**
Yes, standardized

**30. Allocation Tranche Schedule to clients::**






**31. Will you use programmatic or software based allocations?:**
No, manually calculated & determined

**32. What tooling will you use to construct messages and send allocations to clients?:**
We communicate with our Clients mainly through Slack, TG. We also send DataCap distribution information to our Clients via Email.

**33. Describe the process for granting additional DataCap to previously verified clients.:**
We will use a variety of statistical tools, such as https://filplus.d.interplanetary.one/ and filfox.info, to conduct regular and ongoing monitoring to ensure that the allocated DataCap is not being abused or misused. In addition, the allocation of DataCap will be done in a phased manner. If, during the monitoring process, any misuse or abuse of the allocated DataCap is detected, we will immediately contact the customer concerned. Depending on the severity of the situation, we may take measures, including reducing or canceling the customer's future DataCap allocation, to maintain the integrity and fairness of the system

**34. Describe in as much detail as possible the tools used for: • client discoverability & applications • due diligence & investigation • bookkeeping • on-chain message construction • client deal-making behavior • tracking overall allocator health • disput:**








### Tools and Bookkeeping
**35. Will you use open-source tooling from the Fil+ team?:**
Yes, we will be using open source tools such as AC Bot, boost, lotus, singularity, CID Checker, and DataCapstats.io, among other open source tools.

**36. Where will you keep your records for bookkeeping? How will you maintain transparency in your allocation decisions?:**
We keep our allocation records publicly stored on github with real-time updates, and, if there is a dispute, we will privately provide some information to the Fil+ governance team for review after communicating with the client, and the community is always welcome to review our allocations, so feel free to contact us at any time with any questions!
### Risk Mitigation, Auditing, Compliance
**37. Describe your proposed compliance check mechanisms for your own clients.:**
To ensure the transparency and effectiveness of DataCap distribution, we will use a database or tabular system to keep detailed records of each distribution. This includes the customer's name, the amount of DataCap distributed, the date of distribution, and other key information. Such a recording system not only improves the transparency of our service, but also facilitates subsequent monitoring and management.
Next, we will use advanced tools such as CID Checker or Retrievability Bot to monitor how our customers use DataCap. with these tools, we are able to track the actual process of how our customers store their data and ensure its retrievability. Regular spot-checks will be implemented to ensure that our clients are complying with the relevant regulations and standards.
Additionally, we will have regular communication with our clients to discuss their DataCap usage and promptly address any issues or concerns that arise. This not only helps to resolve issues, but is also an important part of building and maintaining customer trust.
Also, through these records and monitoring, we are able to collect valuable data about our customers such as their industry, size, geographic location, etc. This data will provide us with deep customer insights that will help us better understand customer needs and optimize our services and support based on those needs.

**38. Describe your process for handling disputes. Highlight response times, transparency, and accountability mechanisms.:**
We are committed to responding quickly and aggressively in the event of any dispute. For disputes involving our customers, we guarantee a response within 72 hours and provide a detailed explanation to the provider via GitHub or Slack. For disputes related to our distributors, we will process and provide a reasonable explanation via email (info@titannet.io) within 72 hours. We rely on detailed records of each transaction to fully understand and review the handling of these disputes to ensure the accuracy of the explanation and effective resolution of the issue.


**39. Detail how you will announce updates to tooling, pathway guidelines, parameters, and process alterations.:**
The announcement will be emailed, a few days in advance, to my Client and Fil+ governance teams, and will be made public on GitHub, slack , TG, and other channels when we officially release it.

**40. How long will you allow the community to provide feedback before implementing changes?:**
We are committed to providing community members with one month to share their valuable feedback and insights before any major changes are formally implemented. We believe this timeframe is sufficient for the community to fully express their opinions and suggestions.
In order to communicate more efficiently, we will be posting all upcoming updates on the official Titan.com website, GitHub, and Slack channels. These platforms will serve as our primary channels for interacting with community members and discussing upcoming changes. We encourage community members to actively participate in these discussions to ensure their voices are heard.
Also, community members can provide feedback directly to us via email (info@titannet.io). Our team will carefully consider this feedback and make appropriate adjustments where necessary.
In evaluating and balancing the opinions of community members, our ultimate goal is to make decisions that best serve the interests of the Filecoin ecosystem. We are committed to combining the collective wisdom of the community with our deep understanding of the Filecoin ecosystem to collectively drive more effective and beneficial improvements.

**41. Regarding security, how will you structure and secure the on-chain notary address? If you will utilize a multisig, how will it be structured? Who will have administrative & signatory rights?:**
1. Address creation using Ledger S Plus: We will use the Ledger S Plus hardware wallet to create on-chain notarized addresses. This method ensures the security of the private key, as the private key never leaves the hardware device.
2. Private key management: The private key for the notarized address will be held by the company's legal person/legal representative, ensuring that the private key is managed and used in accordance with the highest security standards.
3. Internal Approval Process: Our internal approval process will be realized by relying on the process approval tool of office software to ensure that all DataCap distribution operations are subject to strict internal audits.

We will consider multi-signature tools in the future, using community open-source tools such as Fivetoken pro.

**42. Will you deploy smart contracts for program or policy procedures? If so, how will you track and fund them?:**
The Titan program is designed to track DataCap allocations through smart contracts and ensure compliance and fairness. The core guiding principles of this initiative are to ensure transparency and fairness. Smart contracts will support these principles by making the DataCap allocation process clearer, more consistent and auditable. The code associated with the TItan smart contract will be publicly stored on the GitHub repository page so that it can be accessed and reviewed by members of the community, and to ensure that all interested parties are able to participate in the oversight and management of DataCap allocations.
### Monetization
**43. Outline your monetization models for the services you provide as a notary allocator pathway.:**
When a client applies for Datacap through us, they will pay a base service fee, as well as a corresponding real-time gas fee. In addition, we provide the following additional services:
1. Data Packaging Service: For those customers who do not have the ability to package data, we provide professional data packaging service. Help customers efficiently prepare their data to meet storage needs.
2. Data Transfer and Labor Service Fee: We also provide the service of sending data to Storage Provider (SP), including courier and labor operation fee. This portion of the fee will be determined based on the customer's specific data volume to ensure that the fee matches the service.
We are committed to providing a transparent and reasonable pricing structure to ensure that our customers have a clear understanding of all potential costs when using our services.

**44. Describe your organization's structure, such as the legal entity and other business & market ventures.:**
Titan Network in the DePIN track is the first subnet (autonomous chain) on Filecoin. It has built an efficient and reliable decentralized cloud fog computing full resource service network.Titan is already providing low-cost, high-quality cloud resource services, such as Titan Servers(decentralized computing), Titan Storage(decentralized storage) ( (decentralized computing), Titan Storage (decentralized storage), Titan CDN, Titan Toolbox (DePIN services) and other specific services. And Titan's company is located in Singapore.

**45. Where will accounting for fees be maintained?:**
1. Network operating rules: All costs will be accurately accounted for and managed according to established network operating rules. These rules will ensure consistency and standardization in the allocation of fees, as well as provide clear guidelines for the operation of the entire system. 2. Independent Audit: To ensure a high degree of transparency and verifiability, we will commission an independent auditor to conduct a monetary audit. This step is crucial as it provides a clear and unbiased financial overview for all stakeholders. 3. Decision-making mechanism: Important matters related to cost accounting will be decided democratically through proposals and voting. To this end, rules and mechanisms will be established to ensure that each decision-making process is open, transparent and fair. 4. Technical realization: Specific costing will be automatically executed through network protocols and smart contracts to reduce human error and improve efficiency. All relevant transactions and decisions will be recorded on the blockchain to ensure data tampering and long-term storage. 5. Community Involvement: Other stakeholders in the Filecoin community, such as users, developers and investors, will be encouraged to participate in the audit process. This participation not only increases the diversity of the audit, but also helps maintain the transparency and credibility of the entire system.
### Past Experience, Affiliations, Reputation
**46. If you've received DataCap allocation privileges before, please link to prior notary applications.:**
https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/2780   Previously, TitanNetwork applied for a very small amount of DC for the testing of Titan Storage, a visualization network drive.

**47. How are you connected to the Filecoin ecosystem? Describe your (or your organization's) Filecoin relationships, investments, or ownership.:**
2021 TitanNetwork born in Filecoin retrieval market，Received a million dollar Grant from PL. With continuous development, Titan Network in the DePIN track is the first IPC-based subnetwork. Its blockchain security, network, and incentive layers rely on the IPC Cometbft consensus algorithm and build an efficient and reliable decentralized cloud fog computing full resource service network based on FVM. titan is already providing low-cost, high-quality cloud resource services, such as Titan Servers(decentralized computing), Titan Storage(decentralized storage), Titan CD-ROM, and Titan CD-ROM. computing), Titan Storage (decentralized storage), Titan CDN, Titan Toolbox (DePIN services) and other specific services.

**48. How are you estimating your client demand and pathway usage? Do you have existing clients and an onboarding funnel?:**
Technical Service Advantage: We can provide Client with a hassle-free and accessible solution for data storage through a visualization program (TitanStorage), and for developers, we will also provide an SDK for use (Titan-Storage-SDK). Let Client is senseless when accessing.  Cost-effective: TitanNetwork is committed to providing services to Clients by aggregating idle resources, because our resources mainly come from idle, so the price will be very cost-effective.

**Comment by kevzak** [comment]
## Datacap Request for Allocator
#### Address
> f2bf754c63irlnomlmaacnrq6lfreynxnkhamwh3q
#### Datacap Allocated
> 5PiB

**Comment by Kevin-FF-USA** [comment]
Hi @TitanNet 

Wanted to send a friendly check in.  
As of this comment date, haven't seen any client applications or DataCap disbursements for the organization.   Inactive organizations are in the process of being [reviewed to see if still wanting to remain in program](https://github.com/filecoin-project/Allocator-Governance/issues/6).    If you would like this pathway to remain active as an Allocator, kindly asking that you reply to [the proposal ](https://github.com/filecoin-project/Allocator-Governance/issues/6) with your timeline for onboarding pathway or plan for action to clients.

[1097](https://github.com/filecoin-project/Allocator-Registry/blob/main/Allocators/1097.json) | Titan Network | Manual | [Bookkeeping](https://github.com/TitanNet/Allocator-Pathway-Titan-Network) | Singapore | https://github.com/filecoin-project/notary-governance/issues/1097 | [f03018977](https://filecoinpulse.pages.dev/allocator/f03018977/#pageparamsallocator_id)
