### ISSUE TITLE
Modification: Notary Rubric - Introduce criteria around open source tooling

### ISSUE THREAD

**Issue by dkkapur** [filecoin-project/notary-governance#25]
## Issue Description 
Notary applicants that are actively making technical contributions or publishing reusable content that make it easier or accelerate processes for other notaries should be given credit in the rubric scoring.

## Impact
Notary applicants should be rewarded for making Filecoin Plus processes more efficient and sharing tooling or content that will help accelerate the ecosystem. Notary selection takes this into account as a good indicator of an entity that is aligned with the interests of the network. 

## Proposed Solution(s)
Some potential ways in which this can be factored into the application scoring include: 

- Introducing a new criteria (row) in the rubric for open source tooling or content contributions for Filecoin Plus Notaries
- Account for these contributions under "In-protocol reputation" explicitly

Please share additional proposals or opinions on this below.

**Comment by zixuanzh** [comment]
We can also consider adding a bonus track with points as I expect the bonus to be evolving over time or expand definitions for an existing row to include these bonuses. In general, I think we should have a high bar for adding a row to the rubric as otherwise it will expand very quickly and become increasingly cumbersome.

**Comment by dkkapur** [comment]
In the last cycles, this has been somewhat accounted for as part of "In-protocol reputation". As such, closing this out for now.
