### ISSUE TITLE
[Notary Application] Coffee Cloud

### ISSUE THREAD

**Issue by jobdeng** [filecoin-project/notary-governance#386]
# Notary Application

To apply as a notary, please fill out the following form. 

## Core Information
- Name: Coffee Cloud
- Affiliated Organization: N/A
- Website / Social Media: https://coffeecloud.io/home , Facebook: https://www.facebook.com/Coffee-Cloudio-100883849079709 , Twitter: https://twitter.com/coffeecloud_io , LinkedIn: https://www.linkedin.com/company/76643557/admin/
- On-chain Address to be Notarized: f14qmuid2b6ne4342m5dk56f4rcr7y5sz4sg5fiwy
- Region of Operation: Greater China
- Use case(s) to be supported: General
- DataCap Requested: 1PiB

_Please respond to the questions below in pargraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin project. Please include relevant Github handles, miner ids, significant projects or contributions (with links).
```
CoffeeCloud has studied IPFS and Filecoin project since 2019, and participated in the Filecoin Space Race in August 2020 with 12 Miners:
Competition Ranking(Region: Global) | Miner Name | Miner IDs
----------------------------------- | ---------- | --------
11 | Zillion-6Block | f02415, f02633, f02645, f03491, f07990, f08025
15 | Zillion-6Block | f018780, f018781, f018782, f018783, f018784, f018785
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence.
```
Up to 2022-01–22, the 12 miners participated in the Filecoin Space Race have tokens at stake about 1,660,816 FIL:
Initial Pledge: 336,655 FIL
Total Reward: 1,324,161 FIL
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
As a local Hong Kong start-up, we have been an enthusiastic participant in the Filecoin community since 2019. We participated in the Filecoin Space Race in August 2020 and were very successful, after which we continued to participate in the Filecoin mining community. With recent want to take the exciting steps into blockchain technology, developing our organization to specialize in decentralized storage and farthing our participation within Filecoin Community and ecosystem. With this in mind, we want to support projects and new technology in Hong Kong, the Greater Bay area and around the world, helping them take advantage of Filecoin’s unique decentralized storage solutions.

We are trying hard to optimize Filecoin Lotus and related projects for efficient mining, please refer to GitHub projects conducted by our teammates:

https://github.com/zhiquan911/lotus
https://github.com/jobdeng/lotus

They are not only optimizing the Lotus scheduler written in Golang but also the proving subsystem written in Rust. We are planning to contribute code to the community after testing it completely. We are expanding our team of developers to focus specifically on software and hardware optimization. And more and more manpower we are adding incrementally will support our research and develop applications built on Filecoin project. We here at Coffee Cloud believe that Filecoin should store useful data for the good of society, consequently we position out new developments and projects towards these goals. 
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references who might be able to substantiate your contributions (e.g. if you've filed several bugs, please cite who you've communicated with on the Filecoin side). 
```
Currently not yet.
```

### External Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
We are a local dynamic Hong Kong start-up, specializing in Data Centre solutions and maintenance. Our international teams support our clients here, in the Greater Bay Area, providing the ultimate data centre management solution. In addition to this, we have solutions specializing in cloud computing, web and software development. We want to be the go-to source for premium data storage in the Greater Bay Area, supporting Local Hong Kong Organizations, Relocating Chinese Enterprises or other international institutions. We are proud partners of the Hong Kong Blockchain, and look to develop further partnerships within APAC region. 

Organization: Coffee Cloud Ltd. 
Nature:  Data Centre Solutions
Registration Country: Hong Kong, SAR
Established: August 2021
Size: Under 30 employees
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
Website:  https://coffeecloud.io/home
Facebook: https://www.facebook.com/Coffee-Cloudio-100883849079709
Twitter: https://twitter.com/coffeecloud_io
Linked: https://www.linkedin.com/company/76643557/admin/

Address: 
Coffee Cloud Ltd., 
Unit 1503-05,  15/F, 
Hang Seng Mongkok Building, 
677 Nathan Road, Mong Kok,
Hong Kong
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
Limited coverage at this time.

Social Media Channels:
Facebook: https://www.facebook.com/Coffee-Cloudio-100883849079709
Twitter: https://twitter.com/coffeecloud_io
Linked: https://www.linkedin.com/company/76643557/admin/
```

### Use Case Diversity
(Optional) Any additional information you'd like to share about the use case(s) you plan to support?
```
60% - Media & entertainment (video & music & game)
20% - User content (personal user storage，such as file, photo)
20% - Scientific datasets (Health data, AI training, Meteorology data)
```

# Allocation Plan
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can.
```
We will review each individual applicant for the DataCap in detail, as well as review any historical data available. Clients will need to proceed through the verification process below, through parts 1 to 3. Any outstanding problems or issues regarding the clints answers will be given time to clarify. If the answers that raise concerns will be flagged for further review and research. Any not satisfactory answers that the client is unable to verify or provide appropriate clarification will result in the application being dismissed. 

Start Verification Process:
Part 1:
Is the client’s GitHub or Social Account older than 6 Months?
Has the client shown activity on this account over this 6 Month Period?


Part 2:
Is the Client is to answer the following questions
Where are you located? Are you located in the APAC Region? Where?

The client is required to provide the following details:
Name?
Individual / Company? (date established)
The number of employees?
Media Coverage?
Website?
Social links?
Filecoin address?
Region?
Past Projects?

Data Declaration:
Data Source? Where is come from?
Relationship to Data? 

Where are you assigned the data? 
Which miners/miner are you looking to assign it to?

Part 3:
The Client is to provide Clarity on any outstanding information so far presented.

Any queries or information presented are reviewed and the client is required to provide satisfactory explanations/answers. 

Confirm DataCap Allocation

Outside of this 3 step review process, other factors need to be considered when apply for the DataCap. These will be:

1. The DataCap will be mainly allocated to APAC customers, initially with an emphasis on other local Hong Kong and China clients. This allows for easier support and guidance with local teams. Over the coming months our service team will expand further to support even more regions and customers.

2. We will classify customers by 2 methods reputation and scale. 
Scale is broken down into 3 categories:  

Top team customers, 
medium team customers, 
small team/individual customers

Reputation will be broken down accordingly:

A: Establish business/web and social presence. Previous Filecoin Experience. Previous Datacap allocation.
B: Establish business/web and social presence. Previous Filecoin Experience. No previous Datacap allocation.
C: Establish business/web and social presence. No Filecoin Experience. No previous Datacap allocation.
D: Recently establish business/web and social presence in the last 6 months. No Filecoin or Datacap experience
E: Recently establish business/web and social presence in the last 3 months. No Filecoin or Datacap experience

3. Throughout the allocation and use of the DataCap, we will establish a corresponding review mechanism.   Good customers will be rewarded, while a bad customers will be punished and not allocated accordingly. 
```

Are there any internal processes you plan on impelementing regarding the target, amount, or rate at which you'll allocate DataCap? 
```
The few internal processes, such as the collection of confidential information or the execution of due diligence, will be kept private. Allocation of the DataCap will depend on whether there is that much demand or not, and the priority of the client against the previous priority system.

Similarly, the quantity also depends on the customer's demand, which will be determined by the nature of the usage, as well as the client’s reputation determined by the previous evaluation process. 

In addition, some third-party tools may also be used to collect the information of clients from the web, to ensure proper review and evaluation is carried out.
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
We built an internal wallet server to store the notarized address with very restricted access control, only our staff with proper permission can access the internal server via a specific machine in the whitelist. The DataCap can only be granted to clients by the notarized address completely controlled by Coffee Cloud. So, it is ensured that the DataCap can not be allocated by others unless Coffee Cloud.
```

### Client Due Diligence
How will you vet your Client to ensure they are spending that DataCap responsibly?
```
We will work closely with clients while they implement the DataCap, supporting them through every step. In order for clients to use Data Cap, they must variety and agree with specific restrictions and use. 

If they cannot agree to this, or at the initial final stages of review any criteria are not met we pause allocation. We will vet my client according to the process listed above. Looking at:

Clients Reputation (online presence, any reviews) 

Data (type of data they are using, We will vet the data from time to time to ensure it is as agreed)

Diversity and Decentralization, (how and where they are storing it, on which miner)

Allocation Strategy (should provide detailed tools and inspection strategy for inspecting the miners).

Track Record (Able to provided details on any previous projects)

If clients will be recorded and noted upon performance. Any unacceptable behaviour will be noted and blacklisted. 
```

What questions will you ask to ensure the Client can properly handle the DataCap you intend to allocate to them? 
```
We will ask customers the following questions:
Are you representing yourself as an individual or your company？
If you are representing for your company, please provide the following information:
duration of establishment, 
number of employees, 
business scope, 
users volume, 
number of social media followers, 
data size to be stored, 
products or projects, and so on. 

If you are representing for yourself, please introduce yourself, 
such as a number of social media followers, 
Filecoin activities participation with links, data size to be stored. 
Provide links to social media/news mentions.
Please provide any history working on IPFS / Filecoin,  including notable contributions to the community, 
type of engagement shown over time, etc.
Type, size, and source of the data you will be store on Filecoin
What type of data is it? Specifically is if public data or private data, etc.
IMPORTANT: Is there any sensitive or illegal content?

How do you intend to store the data on Filecoin?

Have you already apply for DataCap to another notary, and whether it is accepted or rejected? Is there any reliable DataCap left? 
Which miner/miners are you applying the DataCap to?
```

What processes will you employ to confirm that a Client is not improperly over-allocating DataCap to a single entity?
```
We will monitor and track the use of DataCap strictly. Each assignment will be used to evaluate the clients' reputations, and where they are assigning the DataCap to. This record will be taken into consideration during the review process (as mentioned above).
```

### Bookkeeping Plan
Do you plan on keeping records of your allocation decisions? If so, with what level of specificity do you intend to respond to any audit requests?
```
Yes, in addition to the DataCap allocation messages landed on-chain, we plan to keep all of our allocation records in a database, e.g. SQLite, which would be integrated with our internal asset management system. For further public allocations,  we also plan to record all activities privately, then move to publicly on GitHub project depending upon clients specifications.  
```

Do you plan on conduct your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
Initially will only focus on allocated DataCap with specific clients, either one we have a relationship with, or within the Filecoin community via slack channels. This will initially be in Private but may move to public allocation if clients find it appropriate. This will depend on the client, their needs and specific requirements (some clients may not wish for information to be public). 
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
No, we have not previously received DataCap.
```

Cumulatively, how much DataCap have you previously successfully allocated? 
```
N/A
```

Have there been (or are there still) any disputes raised against you from your previous DataCap allocations? 
```
N/A
```

**Comment by davidthoms** [comment]
As mentioned in the Notary call last week we are keen on working with educational groups or institutions such as Universities here in Hong Kong. Each project will be submitted, reviewed, graded and assigned appropriate allocation. All projects and details are submitted via Google Form, all members of the community will be able to review, comment and monitor via Google Sheet.  
Google Form For DataCap: https://forms.gle/EGyiG5aVNPAro3av9

Google Sheet List of all applications: https://docs.google.com/spreadsheets/d/1Fh1sueGzQyt6f_YqMPAQqKKEm27gNZKBPVdpgV7BBAQ/edit?usp=sharing

Any concerns, feedback or improvements, please let me know. We want to make sure we can do everything possible to be a constructive members of the community.

**Comment by Kevin-FF-USA** [comment]
Morning @jobdeng !
Wanted to confirm this application for the election as being received. Thank you.  One modification you may wish to update since there was a change in the scoring rubric since your first application.

https://github.com/filecoin-project/notary-governance/issues/391


## Service Level Agreement
### Engagement in Program
How much time per week, on average, are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), comments on discussion/issues, attendance in governance calls, messages in Slack, etc.
```
Please answer here.
```

**Comment by davidthoms** [comment]
Hi @Kevin-FF-USA  & Filecoin team,

We updated our Notary application. As recommended from discussions over the last few weeks, we took into account recommendations regarding the client review process for the data cap. We take this process and responsibility very seriously and want to provide a detailed transparent review process in line with Filecoin principles and ideals. We have created and Form in GitHub that is automatically generated when the prospective client fills it in. 

Link to GitHub form (as an issue) : 
https://github.com/davidthoms/.github/issues/new/choose 

or 

https://github.com/davidthoms/.github/issues/new?assignees=octocat&labels=data+cap%2Cclient+app.%2Cfilecoin&template=cc_client_test_application.yml&title=%5BCoffeeCloud+Client+Application%5D%3A+


Review Current Client Applications & details: https://github.com/davidthoms/.github/issues

The form is then listed on GitHub with full transparency allowing for anyone to make notes, comments or recommendations. All client evaluations will be done in public, showing step by step how we are evaluating and grading the data client appropriately. We have a detailed Client Rubric, based on Filecoin’s own review Rubric. Please see a link to the Google Doc below: 

https://docs.google.com/spreadsheets/d/1TizxLZlAuqRxUEXs5Th3UtvqHa1u26PEEZ8BJosCynE/edit?usp=sharing

This scoring system will be placed under the client application, showing how we are evaluating our clients for the community. 

We hope this helps, and there are any questions or concerns regarding this process we are open to feedback and adjustments. We look forward to the next stage in the Notary application process. 

Kind Regards,
The Coffee Cloud Team

**Comment by davidthoms** [comment]
Hi @Kevin-FF-USA Engagement in Program
How much time per week, on average, are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), comments on discussion/issues, attendance in governance calls, messages in Slack, etc.

Answer:
Regarding the time the Coffee Cloud team would be able to dedicate to Fil+ program should be available for 4 to 5 hours per week (usually about 1 hour per business day). A representative would attend the governance call and should be available to respond quite promptly within Slack conversations. We are quite a dynamic team, who work together to solve problems quickly.

**Comment by galen-mcandrew** [comment]
[Coffee Cloud - Round 3 Notary Election Scorecard.pdf](https://github.com/filecoin-project/notary-governance/files/8320934/Coffee.Cloud.-.Round.3.Notary.Election.Scorecard.pdf)

**Comment by davidthoms** [comment]
Hi Filecoin Team,

Thank you for the feedback from our Notary application. We saw the feedback and recommendations wanted we wanted to make some adjustments in line with your recommendations. 

As part of the Data Allocation and Client Review process, we create GitHub projects (which is publicly available). Here:https://bit.ly/3Is45WR

Potential Coffee Cloud Clients would be directed to here to our README file: https://github.com/davidthoms/.github/blob/main/README.md

We wanted to make it clear and easy for clients to apply for data cap and explain a little about how we are monitoring and coordinating things. Within the README section of our project (https://github.com/davidthoms/.github/blob/main/README.md), we detailed our bookkeeping process, data monitoring (for ourselves and our clients), as well as our sign off and review process. 

All of this we want to be as transparent and clear with the community as possible. We also provided a way for clients to respond and address disputes within each individual application (issue) in our system.

https://github.com/davidthoms/.github/blob/main/README.md

We hope this is helpful in the Notary election process. This is a continually evolving procedure, and we want to make improvements to it to make it more effective for all parties involved.

If there is anything else we can do or address please let us know. If there are any further questions or clarification needed, Job and myself are available here or on Slack.

Kind Regards,
Dave, Job, & Coffee Cloud Team.

**Comment by galen-mcandrew** [comment]
This looks great! Appreciate the work put into this documentation: https://github.com/davidthoms/.github/blob/main/README.md

While that process and documentation may change over time (which is normal and encouraged), I'd like to get a 'snapshot' of your current plan here in this repo and specific issue. 

Would you please copy those details over here in a comment?

**Comment by davidthoms** [comment]
Hi Galen,

Thank you so much for getting back to us. 

As a snapshot, we would initially request a client to fill in our client form. We would then break this process down into 3 stages we would review each individual project more effectively (with the details provided, links, etc).

Review and Feedback to Client
We will review the client's details submitted. Within this period we will flag issues, and allow the client, and community to respond if necessary. 

Sign off and Approval 
Sign Off requires 2 Coffee Cloud team members (myself and Job at this time) to review the client's application. We take things into consideration (data cap requested, project, data cap available, etc). If all seems appropriate and good we grant a data cap. 

Allocation and monitoring
With the allocation stage, we provide support and monitor the data cap we have available as well as clients' use. We are building tools to automate this monitoring process to help monitor things efficiently, and flag issues accordingly. Any problems we would flag in GitHub and with the community address the issue and help find a resolution. 

Coffee Cloud colleagues would try and provide quick feedback and reviews as efficiently as possible. As mentioned in the call, time frames are very important. We want to help support this, despite this larger framework and formal approach. As you mentioned, it is a “work in progress” and we will look to optimize elements over time to make things work better and faster.  

I hope that helps explain things a little clearer. We do not have any projects running currently. But we are about to launch a partnership with Hong Kong Blockchain Association, International Technological University Global and Coffee Cloud. This is an exciting opportunity for us, allowing us to support new and interesting projects for students and institutions. We’ll release a press release next week on this subject. This is in line with our initial goal of supporting educational institutions here in Hong Kong. 

If you have any questions or require further clarification on any issues, please let me know.

Kind Regards,
Dave, Job and Coffee Cloud Team

**Comment by galen-mcandrew** [comment]
[Coffee Cloud - UPDATED - Round 3 Notary Election Scorecard.pdf](https://github.com/filecoin-project/notary-governance/files/8373154/Coffee.Cloud.-.UPDATED.-.Round.3.Notary.Election.Scorecard.pdf)

**Comment by davidthoms** [comment]
Hi Galen, Kevin and the team,
Thank you for updating us this is very exciting news.
Please see our responses to the points you mentioned in your previous comments.
In order to confirm your participation as a Notary in the Fil+ ecosystem, please respond to the following:
Please confirm that the region of operation for client applications you will focus on is Greater China.
Answer: We are located in Hong Kong. Some organizations categorize our regions as “Asia Pacific” or Greater China. This comes down to you wish to designate us. We are comfortable with both categories. 
Please confirm each of the following items below (you can do this by quoting each of the following bullets and adding a line under each section agreeing that you'll abide by these operational principles).
 
• Upfront Disclosures: Prior to being confirmed as a Notary, Notaries are expected to disclose all relevant addresses which they control, have a financial stake in, or are strongly connected to by other means. For the disclosure, the Notary should state the relevant addresses and the nature of the relationship.
Answer: Here are all relevant addresses:
            Coffee Cloud currently only controls 12 miners stated in the Notary application and the relevant addresses are listed as following:      
f1z7pq4ry4wiqfh6zan2jxv2ikye4kb2dvfdswfsa 
f3qw2fvzaos4krbyfys5xpzbfmlre3ei7tncccdlvuqjxhktxghdpr3f3ecbpfkp3cgwsjrge5mdn6nggpyfna
f3r6fefj6h4nwqxoz5joh7gozn5frvf6whoocjozeh4expyksypv6ldpeugmxm744aqeq5xsi6pkki4lhinuxq
f3xdk7eclzk5va7jvijqpmvsvs4edeej7tmrg6jhubdwa3obsartpzfprzp74ift3dwbs6a64mm3tjs4ylgxxq
f3sbdk4vcfjsuwlrb2a544ty4rnlnxdcsdi7nusmafpv6h5fgw52qyxdjalimmeqf3uzba7rf5cqnytnqecdfq
f3rgvbgdvtzjl7qw6puldmkrk4746437phcqtg5i4dtwibqoahbhvb7dpbzyxau3gok4fvzvmbtiamskin32tq
f3wouownq6qxujeqtmg6jgea7kjl7chcwxquz4f2iwuy3q2n7z3lodnlnsnsa33j6v4ffkkrhcpjrfmhfv7iqa
f3ulrcz4b2ua4u3lnb34ov2bfx37rzi3nhdztmbvpknuxsiomuogx3tee3omtaytiy5w6hk7xu7wez24wlj3eq
f3rvy4noovtdsmefykcyk4bj444qcirami3hfa2uhnrj2xe6k2dfmwelkxlsykkyldcxvjelmjgfmacj75edcq
f3slovr7tffkn3ie3y7hrk3xsjlddr3p3f545fg23fuwhjbhysijr6d7certqxllovltwq2tl2poni4pndhxba
f3w2a3t62bxhvwue5xqyoiwc7j5laxtahsegtpdupx3mvldghxojapzw4dnxfxkvky3ie4cbtfqyyj55hgeica
f3wipswdmlodmr2mwan37zrdakgbwdg3htiiurayjtssgf5iq7rlz3z5pexr3y65ypdu64xlokmts7lv5j3uza
f3qkd4zh6ya42uao5mhtjczbkpgrsbliryvqyuqmwwr2kep2y37fhu565rdj544wbhtyaa5ud6bcqcg732c2ga
            
• Promoting Client Best Practices: Notaries agree to educate approved clients about the best practices for using their DataCap (e.g. how to request additional services from miners, storing data redundantly across many miners, etc). Some reference information can be found here.
Answer: This is complete, we agree and will champion these activities.
 
• Commitment to efficiently serving the Network: Notaries agree to serve as fiduciaries of the Network, striving to work towards bringing useful data onto Filecoin and improving the experience for clients to do so. Notaries should generally be able to respond to Client applications and updates within 3 days and should be comfortable communicating with Clients and Notaries if an application needs to be redirected.
 
**Answer: This should not be an issue, and will be handled promptly.**
 
• No Self Dealing: To prevent conflicts of interest, Notaries should not allocate DataCap to Clients over which they control the private keys, or to a Client who intends to specifically spend the allocated DataCap with an address affiliated with the Notary. When in doubt, Notaries should bias towards transparency (i.e. public disclosure) or getting a different Notary to handle the individual request.
 
**Answer: We understand these criteria and have specifically organized our bookkeeping to be transparent and clear in accordance with community guidelines.** 
 
• Operating in Good Faith: Notaries hold a position of trust in the network, and as such it is expected that they operate keeping the Principles of this mechanism in mind. While each form of abuse cannot be exhaustively defined, Notaries are expected to bias towards caution and act in a way that promotes transparency. Notaries should expect to potentially receive requests or questions for allocation decisions (within reason) - and should make decisions with this in mind.
 
**Answer: We understand this requirement and will act in Good Faith.** 
 
• Community Governance Participation: It is expected that you will participate in the program 4-5 hours a week. Along with data allocation, participation in Github issues and Slack conversations, Notaries are to make an effort to regularly attend the scheduled Governance calls. As these calls are a forum to shape this process, it is important to ensure Notaries are present to provide their context, with discussions and input.
 
**Answer: We will actively participate and be available for communication within the community.** 
 
Please list any addresses you are affiliated with, and state the nature of the relationship. Please refer to the first bullet point in (2) for the definition of "affiliated", and bias towards transparency when in doubt.
 
**Answer: Please refer to the answer in point 2.**
 
Please affirm that you will abide by the allocation/client due diligence plan you laid out above.
 
**Answer: We affirm that we will abide by the allocation/client due diligence plan you laid out above.**
 
(If ready) Please confirm the address that should receive DataCap. This is the address that you will use to sign messages on-chain to verify clients (through using a Ledger and the Fil+ Registry App). If you have an active (non-zero) DataCap grant from a previous election cycle, please provide a different address here.
 
 
**Answer: The address to receive DataCap is the same as stated in the application: f13weizhii77v7bp2jb3h5sjotrfmhchee5ktlnvq**
 
• If you do not have a ledger already, we recommend ordering directly from the Manufacturer for the Nano S or Nano X (link: [https://shop.ledger.com/pages/ledger-nano-x](https://shop.ledger.com/pages/ledger-nano-x)%E2%80%A8)
 
Any issues, or additional information please let us know.
 
**We noticed in the previously posted PDF we are delighted that our score increased and that we qualified to be a Filecoin Plus Notary. We were wondering when we would get official feedback if we are officially a Notary?
And what level of Data Cap? We are trying to use this provided Rubric but it is still a little unclear.**
https://docs.google.com/spreadsheets/d/1ByIU65NQoUtibdOL3R8iIrFwTV7Uy4QnwOt92szt6I0/edit?usp=sharing
 
Any clarification would be very much appreciated. 
 
Kind Regards,
Dave, Job and the Coffee Cloud Team

**Comment by galen-mcandrew** [comment]
@jobdeng 

Please fill out this form to move forwards with the ratification process: https://airtable.com/shrs55Lzbm1wJTIRw

**Comment by Kevin-FF-USA** [comment]
Hello @jobdeng!

We have your address on file as: f13weizhii77v7bp2jb3h5sjotrfmhchee5ktlnvq

We will be communicating with job deng and Dave CoffeeCloud on Slack. If there are any other handles you wish to be included, please comment them below.

**Comment by davidthoms** [comment]
Hi @Kevin-FF-USA & @galen-mcandrew I know you guys are super busy right now, as I saw from last night's governance call. I just follow up on this change of address and make sure everything is clarified as clearly as possible. 

We need to update our new address to receive the data cap. Similar to this case (https://github.com/filecoin-project/notary-governance/issues/456). We recently received our new ledger last week and are now in the process of making sure everything is set up correctly, so everything proceeds smoothly. 

Our OLD Address in the application Is: f13weizhii77v7bp2jb3h5sjotrfmhchee5ktlnvq

---> **New On-Chain Address is: f14qmuid2b6ne4342m5dk56f4rcr7y5sz4sg5fiwy** <----

I think there is confusion over Filecoin accounts being added to the Ledger Device. We are using the Ledger Nano S, as recommended. Is that correct? 

The website says, Filecoin accounts cannot be added. Is there. a workaround for this? 
![image](https://user-images.githubusercontent.com/22745254/168947036-24d313e7-f08c-4680-928e-157c395a4bfa.png)

Might be worth addressing in the next Notary governance call. We do have another Ledger Nano X if we need to use that instead.

Any help on this would be very much appreciated. Thanks, Dave & Job

@jobdeng

**Comment by jobdeng** [comment]
Hi @Kevin-FF-USA @galen-mcandrew I have updated the notarized address in the application.

**Comment by galen-mcandrew** [comment]
Hi @jobdeng sorry for the confusion. You are not able to add existing addresses to a physical ledger device (to my knowledge). 

Please confirm the default address of your ledger device, the one you would like to use as a notary.

Is that: f14qmuid2b6ne4342m5dk56f4rcr7y5sz4sg5fiwy ?

**Comment by jobdeng** [comment]
@galen-mcandrew Yes, the address, <u>f14qmuid2b6ne4342m5dk56f4rcr7y5sz4sg5fiwy</u>, is the default address of my ledger device.

**Comment by jobdeng** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacedptdrrrwsubm34y7j3uiqmkuzvypjuwokz7o2oncydssi6i3go5o
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedptdrrrwsubm34y7j3uiqmkuzvypjuwokz7o2oncydssi6i3go5o

**Comment by galen-mcandrew** [comment]
## Request Approved
#### Address 
> f14qmuid2b6ne4342m5dk56f4rcr7y5sz4sg5fiwy
#### Datacap Allocated
> 1PiB

**Comment by jobdeng** [comment]
> ## Request Approved
> #### Address
> > f14qmuid2b6ne4342m5dk56f4rcr7y5sz4sg5fiwy
> 
> #### Datacap Allocated
> > 1PiB

Hi @galen-mcandrew, I checked the notarized address: <u>f14qmuid2b6ne4342m5dk56f4rcr7y5sz4sg5fiwy</u>
i) Cannot find the notary address using the command line: <u>lotus filplus list-notaries | grep f01845670</u>
ii) Check the address on <u>https://verify.glif.io</u>: [f14qmu ... g5fiwy] is not a verified client.
iii) Login as a Notary on <u>https://plus.fil.org/wallet</u>: 
Ledger TypeError: a.ledgerApp.getAddressAndPubKey is not a function. (In 'a.ledgerApp.getAddressAndPubKey(t)', 'a.ledgerApp.getAddressAndPubKey' is undefined)
iv) My Ledgr Nano S: Firmware is up to date: 2.1.0

**Comment by jobdeng** [comment]
Hi @galen-mcandrew, I can login to notary application now, but still no DataCap allocated for the notarized address. I also tried to approve the proposal (txn: 0b6a417c-ccae-47d4-a760-5a4334c46f4e) as a RootKey Holder ID, but error prompted that the address (f01845670) is not one of the signers. How can we get the proposal signed to receive the DataCap? Please help.

<img width="1439" alt="Screen Shot 2022-05-27 at 4 31 52 PM" src="https://user-images.githubusercontent.com/71117917/170664437-1edb752e-8faf-4b57-bd88-e4e0e76446cc.png">
<img width="1440" alt="Screen Shot 2022-05-27 at 9 58 52 AM" src="https://user-images.githubusercontent.com/71117917/170664461-d8b494ae-bb5e-470c-8362-17b13fae1593.png">
<img width="1440" alt="Screen Shot 2022-05-27 at 9 59 12 AM" src="https://user-images.githubusercontent.com/71117917/170664510-6e4e664e-beef-4da5-918d-61c77c8fe594.png">
<img width="1440" alt="Screen Shot 2022-05-27 at 10 01 29 AM" src="https://user-images.githubusercontent.com/71117917/170664540-ff024338-0446-45cf-b029-cb1926d60718.png">
