### ISSUE TITLE
Discussion: Increase number of notaries and remove geo limit

### ISSUE THREAD

**Issue by Fatman13** [filecoin-project/notary-governance#428]
## Abstract 

Increase number of notaries and remove limit on number of notaries based on geolocations.

## Motivation 

Upon examining last round of rubric scores, many failed to be chosen as notary not because of low rubric score among all applicants but due to the limit on available seats of notaries based on geolocations. This greatly damaged the ability of fplus to distribute target datacap (500Pib mentioned in one of the governance call meeting) to the network and created a sense of unfairness. 

## Design

Total number of notaries to be increased and notary limit based on geolocations to be removed.

**Comment by UnionLabs2020** [comment]
Notaries need to have a better understanding of the local language and situation so that they can conduct due diligence efficiently. I think geographical attributes are still necessary.

**Comment by Kevin-FF-USA** [comment]
Hi @Fatman13  - Thanks for raising this issue.  
Will let the discussions to continue to unfold here in this issue, as well as allocate time during the upcoming Notary call on March 8th. 

[https://github.com/filecoin-project/notary-governance/issues/427]

**Comment by dkkapur** [comment]
Recording of Mar 08 Governance Call, where this was discussed: https://www.youtube.com/watch?v=CVoZx666HYE.

Notes from the discussion:
- increase number of notaries is good and the community is aligned (there was a previously proposed goal of getting to 50 notaries)
- removing geo limit is not a good thing, since it will result in over-indexing on regions in Asia and North America due to the higher average scores from applicants in those regions
- having geo distribution baked in is a good thing, ensures better client experience and higher confidence trust-building between notaries and clients (i.e., knowing local laws, speaking local language, etc.)

Proposed next steps (my opinion):
- as with #425, agree that Geo distribution as a notary selection logic needs to be tweaked, especially with continued focus on LDN
- close this issue, kick off separate discussion on how to proceed with geo-distribution for the following election cycle

**Comment by dkkapur** [comment]
Closing this one out for now based on the points flagged above and in the past few governance calls.

**Comment by dkkapur** [comment]
Discussion topic to continue conversation: https://github.com/filecoin-project/notary-governance/discussions/491
