### ISSUE TITLE
Proposal:  Add 2nd round Notaries to the v3 multisig for LDN 

### ISSUE THREAD

**Issue by Kevin-FF-USA** [filecoin-project/notary-governance#568]
### **Current Status**
Notaries who completed the disclosure as part of the 3rd round of elections were added onto the v3LDN multisig to approve large DataCap requests. There are several Notaries who were elected in the 2nd round of elections who did not reapply for DataCap in the 3rd round of election. These Notaries are active and participating in Fil+, but since they have not committed to the updated disclosure requirements they have not been able to approve LDN applications.

    

### **Proposal**
Add  **ACTIVE and PARTICIPATING** Notaries who did not reapply in the 3rd election to the v3 LDN multisig. This would allow them to perform diligence and make allocations to approved large dataset projects.

### **Requirements** 

- Notaries from the 1st or 2nd rounds would have to demonstrate ongoing participation in the Fil+ community (Slack + Governance Meetings)
- Existing Notaries would need to complete the disclosure and KYC requirements (as part of the 3rd round elections)

### **Reasoning**
We have heard from multiple Notaries that they wish to continue allocations, but are blocked by the new approval requirements. These Notaries have been participating in the Fil+ program and are actively engaged in the community. Currently they are unable to sign Large Data requests due to the lack of updated disclosure documentation.  Would provide LDN approval based on a per request bases. 

This would allow Notaries who may have not have reapplied to renew their datacap in the 3rd election, but still wished to participate in the program to continue to do so.

### **Timeline**
We plan to discuss this in the next notary governance call (July 12) for input/feedback, and depending on community opinions would like to ratify and implement in ASAP.

**Comment by UnionLabs2020** [comment]
In a nutshell, 2nd round notaries can be divided into three categories. 

A、reapplied and selected 
B、reapplied but failed 
C、did not participate in the reapplication at all 

We feel that if the notary qualification is automatically inheritable, both B & C should be added to the v3 multisig; if it is not, then they will need to wait for the next application.

**Comment by UnionLabs2020** [comment]
If we open a special window to reapply, I don't think Group C will definitely be better than Group B. Many scores will change over time, such as assets and contributions. There are many problems in comparing different objects at different times.

There is only one way. We can reopen a new round of applications for all candidates.

**Comment by neogeweb3** [comment]
I wonder how many notaries are considered as Group B. 

Given we didn't provide clear clarifications on the Inheritance of notary election, reapplication shouldn't be treated as an important metric. Instead, participation in allocation request assessments, and governance call attendance should be considered as key factors. Filtering message lists of notaries' addresses for Propose/Approve/AddVerifiedClient could be a good start, but keep in mind some notaries might barely receive any requests, and that's where governance call attendance will kick in.

**Comment by dannyob** [comment]
I think it'd be useful to know exactly who we're talking about here (and numbers). Is there a list somewhere?

**Comment by flyworker** [comment]
I was thinking I can skip the round3 application if I don't want to increased my datacap. That's the reason I think it is reasonable give  the access of LDN to notaries who did not re-apply for round 3.

however for those who failed in round3 application, should not be grant the access, the reason is simple, you failed to get the position. 

So for me , B is not qualified, C is fine

**Comment by Joss-Hua** [comment]
I don't think B should be qualified. Some members of C can be qualified, but it needs to be based on the evaluation of the government team on the previous work quality of C members.

**Comment by GaryGJG** [comment]
I think B is fine , although they lost the election, they are willing and enthusiastic to serve the community；As for C, even if let them in, maybe they won't work at all.

**Comment by flyworker** [comment]
> I think B is fine , although they lost the election, they are willing and enthusiastic to serve the community；As for C, even if let them in, maybe they won't work at all.

I don't agree, if that is the case, what is the purpose to have a notary application,anyone wiling and enthusiastic can be a notary

**Comment by liyunzhi-666** [comment]
- "ACTIVE and PARTICIPATING Notaries who did not reapply in the 3rd election" Who are they?

- If they want to be added to v3 LDN multisig, FF should announce their work efficiency and activity in the second round (not only limited to the number of governance meetings, the number of applications processed), and the community will vote on whether to add them to v3 LDN multisig.

**Comment by MetaWaveInfo** [comment]
1. If Party C participate, could they be selected in the 3rd election?
2. Was the reason why Party B failed because they did not actively participate in community activities?

**Comment by xingjitansuo** [comment]
1. How many of those notaries are we talking about here, and how will adding those notaries change the Time-to-Datacap? 
2. Before we directly add those previous notaries who meet the requirements mentioned in the proposals to the v3 Multisig for LDN, can they also specify the reasons on not applying for the new round of notary at first place, especially when they are actively engaged in the community.

**Comment by flyworker** [comment]
> 1. How many of those notaries are we talking about here, and how will adding those notaries change the Time-to-Datacap?
> 
>     2. Before we directly add those previous notaries who meet the requirements mentioned in the proposals to the v3 Multisig for LDN, can they also specify the reasons on not applying for the new round of notary at first place, especially when they are actively engaged in the community.

for 1st question, shouldn't those notaries stand out and shout for themselves? At least to show their claim

**Comment by swatchliu** [comment]
We think two points need to be clarified before discussing this proposal:

A.        Granting Party C the opportunity for multisig and whether or not he(she) is selected as  a V3 notary are currently seen as equivalent.
B.        Whether or not a v3 notary is selected is not only equivalent to being active, competent, or receiving absolute scores, but rather on the ranking of the scores he(she) received in his(her) region of application and the quota for that region (PS: if we go by absolute scores, the vast majority of Western notaries probably would have been unelected).

With the above perceptions clear, we can now look at this proposal.
What would have been the result if party C had participated in the election? 

Let's think about the following two scenarios.
1.        Will Party B change its ranking because of Party C's participation? 
The answer is yes, but Party B would still not be in the winning order, because the ranking could only be worse, so Party B should not join.
2.        Will Party A change its ranking due to the participation of Party C? 
The answer is also yes, as long as there are failed applicants in that region, then Party A may lose the election due to Party C's participation.

Therefore, ByteBase's opinion on this proposal is as follows:

**A. The conditions for adding Party C to the V3 multisig are not sufficient；
B. Even if there is any Party A willing to give up their positions forwardly, Party B 和 Party C need to participate in the election at the same time and be ranked again.**

Thanks!

**Comment by swatchliu** [comment]
We think two points need to be clarified before discussing this proposal:

A. Granting Party C the opportunity for multisig and whether or not he(she) is selected as a V3 notary are currently seen as equivalent.
B. Whether or not a v3 notary is selected is not only equivalent to being active, competent, or receiving absolute scores, but rather on the ranking of the scores he(she) received in his(her) region of application and the quota for that region (PS: if we go by absolute scores, the vast majority of Western notaries probably would have been unelected).

With the above perceptions clear, we can now look at this proposal.
What would have been the result if party C had participated in the election?

Let's think about the following two scenarios.

   Will Party B change its ranking because of Party C's participation? 
The answer is yes, but Party B would still not be in the winning order, because the ranking could only be worse, so Party B should not join.
2. Will Party A change its ranking due to the participation of Party C?
The answer is also yes, as long as there are failed applicants in that region, then Party A may lose the election due to Party C's participation.

Therefore, ByteBase's opinion on this proposal is as follows:

A. The conditions for adding Party C to the V3 multisig are not sufficient；
B. Even if there is any Party A willing to give up their positions forwardly, Party B 和 Party C need to participate in the election at the same time and be ranked again.

Thanks!

**Comment by swatchliu** [comment]
We think two points need to be clarified before discussing this proposal:

A. Granting Party C the opportunity for multisig and whether or not he(she) is selected as a V3 notary are currently seen as equivalent.
B. Whether or not a v3 notary is selected is not only equivalent to being active, competent, or receiving absolute scores, but rather on the ranking of the scores he(she) received in his(her) region of application and the quota for that region (PS: if we go by absolute scores, the vast majority of Western notaries probably would have been unelected).

With the above perceptions clear, we can now look at this proposal.
What would have been the result if party C had participated in the election?

Let's think about the following two scenarios：
1、Will Party B change its ranking because of Party C's participation?
The answer is yes, but Party B would still not be in the winning order, because the ranking could only be worse, so Party B should not join.
2、 Will Party A change its ranking due to the participation of Party C?
The answer is also yes, as long as there are failed applicants in that region, then Party A may lose the election due to Party C's participation.

Therefore, ByteBase's opinion on this proposal is as follows:
A. The conditions for adding Party C to the V3 multisig are not sufficient；
B. Even if there are any Party A willing to give up their positions forwardly or be cancelled by the community, Party B 和 Party C still need to reapply at the same time and be ranked again.

Thanks!

**Comment by fireflyHZ** [comment]
Group B reapplied but failed, indicating that they were under-committed in the community or otherwise, so they were not eligible. Group C did not apply stating that they did not care enough about fil+.

**Comment by Holiday507** [comment]
I think the reason for talking about this topic is that there are a number of notaries who are not participating in the 3rd notary election but want to have the ability to approve LDN as 3rd round of notaries. 
I do not recommend give special rights to these 2nd round of notaries, because they have abdicated their role as notaries when they do not participate in the 3rd notary election. I support they actively participation in the 4th round of notary election, when the results will determine whether they have the right to approve LDN.
-- -- -
1. Who are these notaries and why did they not participate in the 3rd round of notary election?
* If not participating in election means not actively participating in community activities, I don't think these notaries continue to have notary rights;
2. Every new notary has made some new commitments and ideas for FIL+ governance. If these 2nd notaries do not participate in the election and they can obtain the same ability, which is unfair to the notaries who actively participates in the 3rd election.
* Many aspects of the 3rd round of notary election have changed, and the situation of these 2nd round of notaries have also changed, so some aspects of them may not be eligible to be a notary.
-- -- -
Therefore, I think the community should not approve this proposal.

**Comment by Carohere** [comment]
Although they were once notaries, after a period of time there is no guarantee that they are still capable and qualified to serve the community since they are not being scored anymore.

Of course, if FF officials are able and willing to score them, then it's a different story. 

But even so, there are two issues I'm concerned about in that case. 

1) There is no point in comparing notaries from different time periods. As if I had one fil during notary application season, but now I have 100 million fil, so of course, I would get a better score now. In another word, the new notary's score is no longer accurate and objective.

2) Even if the case of 1) is not considered, the notaries are re-scored. 
In the new ranking, the already elected notaries may score lower than those who joined later, so should we disqualify those notaries who are already in multisig? Hmmm... i don't think so. 

For applicants who applied, it is reasonable that some of them got rejected for not meeting certain criteria. But for those who are not involved but are about to be automatically added to the multisig... it makes zero sense to me, and all of this seems to be a repudiation of the criteria.

If we think about the long term, why would anyone even try to put in the effort to reapply again if people just have the idea that participation or not doesn't even matter anymore? 

Again,  it doesn't matter how many members there are in category B, it doesn't matter who they are, but they should not be excluded just because they tried. I am new to filecoin and the reason why I love this community is quite simple. Here active participation is valuable, everyone has their own voice and everyone is treated fairly. If the most fundamental rules of the community will be broken like this, I don't think that's what we want...

**Comment by Carohere** [comment]
> 



> > I think B is fine , although they lost the election, they are willing and enthusiastic to serve the community；As for C, even if let them in, maybe they won't work at all.
> 
> I don't agree, if that is the case, what is the purpose to have a notary application,anyone wiling and enthusiastic can be a notary

Yes, I agree that notary application is important and its purpose is to distinguish who is qualified to be in that role. But what is the point of it if people who have not applied end up with the same authority?

**Comment by 1475Notary** [comment]
Tend NOT to support.
The rules must be general. Please don't disclose who they are.
If the 2nd notaries can inherit the qualification as long as they are  **ACTIVE** and **PARTICIPATING**, we should check whether there are some  **ACTIVE** and **PARTICIPATING** members in Group B **FIRST**.

**Comment by PluskitOfficial** [comment]
We don't quite agree.
Our main concern is fairness. Each round of notary elections means a fair selection for all applicants. It would be unfair to others to gain some rights without participating in elections.

**Comment by 1LISA2** [comment]
I think we should follow the principle of fairness, everyone should reapply, but, users who were active notaries before can enjoy certain bonus points.

**Comment by dkkapur** [comment]
Folks - at the Sept 20 governance call there was alignment that notaries that did not participate in the third round of elections will instead participate in the fourth and join the LDN v3 multisig after this (assuming they re-qualify as notaries).

Closing this out for the time being. Thank you for engaging in the conversation.
