### ISSUE TITLE
Addressing collusion b/w client and notary

### ISSUE THREAD

**Issue by raghavrmadya** [filecoin-project/notary-governance#825]
## Issue Description
There have been many flags raised recently regarding notaries signing their own applications and the community has demanded action on this behavior. 

## Impact
The client and the notary cannot have a formal relationship and a client cannot depend on a single/few notaries to sign their application

## Proposed Solution(s)
If a direct relationship is proven b/w the client and the signing notary, the application will be closed immediately, client and notary flagged, and the application will be considered for DC removal.  

### Timeline
Discussion: Feb 15th 2023 - Feb 20rd 2023
Decision by T&T WG -  Feb 21st 2023 at the T&T WG Call

### Technical dependencies 
GitHub tags. Tooling for removing DC

## Risks and mitigations 
The potential slowdown in LDN signing 

## Related Issues
A notary who is an SP can be one of the four signatories on an LDN but if the notary is found to have relationships with multiple SPs, notary will be flagged.

**Comment by raghavrmadya** [comment]
- It should be unacceptable for a client and notary to have a direct relationship. A direct relationship is when the notary is the client, and works/represents the client. **We know that SPs, who might also be notaries, have relationships with clients,I do not consider this to be a direct relationship but rather the SP being a steward of the client application**

It should also be unacceptable for a notary to favorite a client - If there is a clear pattern showing that a notary is signing/prioritizing an application for the same client/entity or for a small subset of clients, notary must be flagged and will be requested to pause signing.

**Comment by raghavrmadya** [comment]
An SP who is a notary can be 1/4 signers on an LDN. We need to be realistic and honest about the incentive for an SP to become a notary. I see this more as a collaboration than collusion. If you think differently, please voice your thoughts/opinions on the issue.

**Comment by herrehesse** [comment]
The only amendment I would recommend concerns the practice of notaries signing applications that they themselves have stored, even if the portion is less than 25%.

**Comment by kernelogic** [comment]
This idea makes sense but enforce it will need very clear rules. A voting from T&T DAO would be good. Otherwise every notary can be qualified under this "collaboration" and get kicked out.

The most active clients get signed by most active notaries, are they all working together? Definitely not.

**Comment by MianmianSH** [comment]
As a client, I want to express that there is too much resistance in promoting the project recently, and I also find that the notary system is very unreasonable.
In order to find a signed notary recently, it is almost difficult to get a response to my appeal. The enthusiastic notary who responded is almost marked as a problematic notary, and those who only maintain their own interest circle and ignore other ordinary client requests A notary is considered a good notary.
Now the trend has become: If I don't do anything, then I will not get flagged.

**Comment by xixiott** [comment]
> It should also be unacceptable for a notary to favorite a client - If there is a clear pattern showing that a notary is signing/prioritizing an application for the same client/entity or for a small subset of clients, notary must be flagged and will be requested to pause signing.

![16765180045507](https://user-images.githubusercontent.com/125453430/219262558-072689e4-bb04-4ca7-bb38-ffd586c7c752.png)
![16765180707905](https://user-images.githubusercontent.com/125453430/219262565-39c7aaac-27b6-4cbf-af72-09d2b48360e9.png)
![16765184106026](https://user-images.githubusercontent.com/125453430/219262571-bd64b2fd-8d24-4f3a-8344-f721579aa935.png)
![216968356-79b6bd17-3aea-4038-8ce9-38003cfd565e](https://user-images.githubusercontent.com/125453430/219264454-573c3e51-43c8-435a-a0c0-decdf5e87b3d.png)

@kernelogic @cryptowhizzard

**Comment by kernelogic** [comment]
This simply means we are the most active notaries. Other notaries either banned or never active.

**Comment by MianmianSH** [comment]
How to ensure that individual notaries are targeted to clients? 
Or some notaries are just suppressing the whole group in the name of "due diligence"?

It is not difficult to solve this problem. My thoughts and suggestions are as follows:
- **Each client application has the right to designate 1-3 blacklisted notaries. For the current LDN, notaries designated as blacklisted have no right to comment and sign, and the client also has the right to not respond the questions of blacklisted notaries.**

Other Details:

1. The target of the blacklist is the notary subject, not the github account. If a notary subject corresponds to multiple github accounts, then these multiple github accounts belong to the restricted queue.

2. In order to facilitate identification by the client, all notary-related account names must adopt a unified specification, such as "name - <NotaryOrgName>", and the official must publicly disclose all notary-related github accounts.

Notary Review:

1. Based on the blacklist statistics, if some notaries are blacklisted by most clients, the notaries need to be marked and investigated, and their powers should be limited. If there is an interest group for the notary, it is best to find it from the LDN that has not been added to the blacklist.

**Comment by xixiott** [comment]
> This simply means we are the most active notaries. Other notaries either banned or not as active.

https://github.com/filecoin-project/filecoin-plus-large-datasets#applying-for-a-large-datacap-allocation

"The same notary cannot sign off on immediately subsequent allocations of DataCap, i.e., you need at minimum 4 unique notaries to support your application on an ongoing basis to receive multiple tranches of DataCap."

@raghavrmadya 
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/432
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/483
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/917

**Comment by kernelogic** [comment]
Same notary or same "set" of notaries, not very clear to me. I have been following the latter rule since day 1. 

I say it's not a serious offence to sign sequentially to improve TDD. @raghavrmadya

**Comment by xixiott** [comment]
@kernelogic 
>The same notary cannot sign off on immediately subsequent allocations of DataCap.

**Comment by kernelogic** [comment]
I will try avoid it in the future

**Comment by xixiott** [comment]
![65287802168](https://user-images.githubusercontent.com/125453430/219285926-20c5a281-9f81-4115-9317-17fa6d8a9cdd.png)

![5288392626](https://user-images.githubusercontent.com/125453430/219285939-91c27dfb-b93e-46ea-a7e3-e8c5f836b469.png)

![5287223198](https://user-images.githubusercontent.com/125453430/219285915-a8321269-67a3-4a76-a6dc-6662f87465af.png)

**Comment by raghavrmadya** [comment]
This issue is forward-looking and focuses on addressing client and notary collusion. If this proposal is passed, The T&T WG will enforce addressing favoritism moving forward. 

It is important to note that until recently the program was fairly small and R4 notary election had the highest number of notaries which makes this proposal reasonable. If you believe that the aforementioned notaries colluded with the client, please open a new Notary Governance issue.

**Comment by raghavrmadya** [comment]
Thanks to all those who participated in this discussion. Seeing no significant pushback, I will assume that the community generally agrees with this proposal. 

Moving forward, if a direct relationship is proven b/w a client and a notary, with a direct relationship being as follows:

1. An active notary pretends to be a client AND signs their own application 
2. A client on an active LDN is found to be an active notary 
3. The active notary signing an LDN is found to be working for the client 

There is still some disagreement on allowing a notary who is also an SP to be 1/4 signers. This concern will be discussed in the T&T WG Call today i.e. Feb 21 2023

**Comment by kernelogic** [comment]
@raghavrmadya what does this mean? Notaries cannot apply any LDN at all? There are so many such LDNs now...
<img width="935" alt="image" src="https://github.com/filecoin-project/notary-governance/assets/3711825/24bc5f1e-1666-44c6-82bc-2999402f2e33">
