### ISSUE TITLE
Bug:  Fil-Plus Subsequent Allocation bot report wrong statistic

### ISSUE THREAD

**Issue by NiwanDao** [filecoin-project/notary-governance#840]
## Issue Description
When multiple LDN shares the same client address, the subsequent allocation miscalculates the ratio of remaining Datacap / Datacap allocation, which does not kick off the readyToSign bot appropriately. 

For example, LDN [#1143](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1143) and LDN [#1144
](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1144) share the same client address f1mmtovvurlhcvfmqbww6nzwwrse3cljccjmdftki.  As shown in the screenshot from https://filplus.d.interplanetary.one/, 3.5PiB was granted to the address, and the available Datacap is 600Tib. The ratio to trigger the next tranche of Datacap allocation is reached as current ratio is 16.7%(600Tib / 3.5Pib ) and is below 25%.  However, Filecoin Log Explorer expose the different ratio. See attached of log #1143 and #1144 below. 

<img width="1517" alt="截屏2023-03-01 下午2 48 00" src="https://user-images.githubusercontent.com/72185104/222064897-91d42f11-06ea-4173-9645-b60600863352.png">
<img width="1318" alt="截屏2023-03-01 下午2 52 45" src="https://user-images.githubusercontent.com/72185104/222065689-98c7480e-1e34-4062-a08b-09a940e08092.png">

<img width="1271" alt="截屏2023-03-01 下午2 53 14" src="https://user-images.githubusercontent.com/72185104/222065768-b3ed7dde-0d8c-4aa3-b940-0f3681f73dfd.png">

## Impact

largely increase the TTD and bad user experience. 

## Proposed Solution(s)
Manually unblock the Datacap signing process until the bug fixed.

## Related Issues
 LDN [#1143](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1143) and LDN [#1144
](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1144)

**Comment by panges2** [comment]
Hi @xingjitansuo, this error has been noted. We seem to encounter errors when different LDN applications have the same client address. We know this is not the ideal use experience, and we are trying to improve this in the future. 

This could also be because of the DMOB API migrations that happened a few days ago. There were problems with accessing the API that SA bot uses to read remaining datacap. We have already solved this problem.

For now, if you can, try switching the client address on the older application, and contact me on slack if you need help @Philippe Pangestu
