### ISSUE TITLE
Discussion: Add vote from community for nortory selection

### ISSUE THREAD

**Issue by flyworker** [filecoin-project/notary-governance#86]
## Issue Description
The current way of selection of select notary focus too much on Stake Exposure and in protocol reputation, and community reputation is measured by numbers of social media etc. Those factor cannot reflect real reputation in the community.

## Impact
Those factors are good for organizations from big groups with millions of tokens and lots of employees, however, most of them are not stand for small raw power miners.  The community lack a notary can stand from a different way of viewing of the system, which can provide diversity of the notaries. The current selection process is application-> approval by Filecoin organization, community impact is weak.

## Proposed Solution(s)

As a decentralized system, at least some seats should be elected from community, the community also have the right to cancel the seat choose another notary as well. 

For the community notary, he does not need  Stake Exposure and in protocol reputation, but he needs the widely recognition from the community. If he does not have the professional skills for the position, he need to take some training to make sure he is qualified.

**Comment by rouroumian** [comment]
None yet

**Comment by rouroumian** [comment]
I agree

**Comment by githubxwx** [comment]
I agree

**Comment by jnthnvctr** [comment]
One thought - rather than community vote, the intent of the rubric is that it should be reflective of defining (objectively) whether someone is a good community member. Is a better move not to just refactor the rubric to better align with definitions that either would qualify (or disqualify) someone? 

A pure community vote seems somewhat hard to implement - not only from the "how do we vote question" but also from the "who gets to vote" perspective. If it's anyone who is a community member (which, again how do we want to define this), we run into a potential of excluding legitimate interested folks or enabling a gaming of the vote (you could imagine paying people off the street to just hop in and vote).

It feels (relatively) easier to enumerate what are the disqualifying features of a Notary (demerits? something else?) and implement in the scoring, and the community can help source that information with proof as a part of the application.

**Comment by jnthnvctr** [comment]
We already have a component fo the rubric that emphasizes that "a pattern of impropriety" is disqualifying, so perhaps its about broadening that component to enable the community to source and provide input on applications inside the submission process? 

I think firming up the definition of pattern of impropriety (right now it is pretty vaguely defining "bad stuff") might be one tactical action, and then refactoring the sequencing of applications. It'd require likely formalizing some time windows where we say: 

By X date you must express whether you plan on submitting an application
By Y date you must submit a draft application if you'd like feedback
By Z date all applications (and community supplemented materials) must be submitted

**Comment by dkkapur** [comment]
Closing this one out for inactivity. Let's open a new issue or discussion if still relevant.
