### ISSUE TITLE
Review of NDLabs LDN Applications & Removal of Notaries from the Fil+ Program

### ISSUE THREAD

**Issue by Chris00618** [filecoin-project/notary-governance#899]
## Issue Description
[NDLABS - Hyper.ai](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues?q=is%3Aissue+Hyper.ai+is%3Aclosed) applications involve: 
- CID sharing with multiple LDNs
- Zero retrieval rate
- False claims of piece CID retrievability

The following notaries colluded with the client and disregarded the retrieval data. They failed to perform their due diligence duties by blindly signing non-compliant applications:
- [psh0691](https://github.com/psh0691)
- [1ane-1](https://github.com/1ane-1)
- [mikezli](https://github.com/mikezli)
- [NewHuoPool](https://github.com/NewHuoPool)
- [Chuangshi1](https://github.com/Chuangshi1)
- [YuanHeHK](https://github.com/YuanHeHK)
- [laurarenpanda](https://github.com/laurarenpanda)
- [DaYouGroup](https://github.com/DaYouGroup)

## Proposed Solution(s)
Community review of NDLabs LDN applications and removal of notaries from the Fil+ program

### Timeline
Discussion at June 27th 2023 WG Call
Community review until June 30th 2023 at 5 pm ET
Decision announced by the T&T WG Lead after

### Technical dependencies 
Removal from main multisig

## Related Issues
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1720#issuecomment-1608734194

**Comment by NDLABS-OFFICE** [comment]
As I disclosed above, currently we can only retrieve it with the following command：
#Search command：
lotus client retrieve --provider 节点号 --pieceCid piece_cid payload_cid ~/

#Example
lotus client retrieve --provider 38362483 --pieceCid baga6ea4seaqlfhcdf5gpxgetvnm74y3y6zfgn654a6x4flrillbrk4pugmysgjq bafykbzacedieutroihh6t3zzstdd4d2nr42t46dru7mqn2nuru6abl3jq2tw4 ~/

---------------------------------------------------------------------------
We have located that the reason why ND and the SPs we cooperate with cannot be searched and sampled by Filplus RetrievalBot is that our code is not synchronized with the latest boost code, so the payloadCID (rootCID) cannot be retrieved. However, pieceCID can be retrieved.

The above notaries are all active notaries in the community and they can all be contacted through slack. And I have provided them all with the cid documentation before signing, but because of technical issues that are currently being adjusted, as we currently only support the following search methods:
#Search command:
lotus client retrieve --provider node number -- pieceCid piece_cid payload_cid ~/

So we can't see the exact retrieval rate in check bot, hopefully it will give us time to adjust it.

**Comment by NDLABS-OFFICE** [comment]
The piece_cid+payload_cid match is not a bad way to go, as we think it allows for more accurate retrieval. But we are adjusting it in order to make it easier for notaries to use check bot to review.

**Comment by NDLABS-OFFICE** [comment]
[psh0691](https://github.com/psh0691)
[1ane-1](https://github.com/1ane-1)
[mikezli](https://github.com/mikezli)
[NewHuoPool](https://github.com/NewHuoPool)
[Chuangshi1](https://github.com/Chuangshi1)
[YuanHeHK](https://github.com/YuanHeHK)
[laurarenpanda](https://github.com/laurarenpanda)
[DaYouGroup](https://github.com/DaYouGroup)

---
The above notaries are active notaries and they are not signing without review, we provide a cid list during the contact process. Please do not feel free to remove a notary public who is doing work.

**Comment by Chris00618** [comment]
@NDLABS-OFFICE you should check out the LDN README first.

**Comment by kernelogic** [comment]
There are more than one ways to do retrievals. Notaries have the freedom to execute their own due diligence to determine whether it's acceptable.

**Comment by raghavrmadya** [comment]
Given the holistic reply of the notary and no further follow up from the OP, this issue is being closed.
