### ISSUE TITLE
[DataCap Removal Proposal] Self-dealing, Fake distribution and Merged Datasets #1755

### ISSUE THREAD

**Issue by herrehesse** [filecoin-project/notary-governance#923]
### Client Application URL or Application Number

https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1755

### Client Name

StoneMoonGalaxy 

### Client Address

f1zz7tilbyzlrrzcgzrac4yuyv6ykxgdc5tfll5ei

### Amount of DataCap to be removed

All Remaining

**Comment by herrehesse** [comment]
Notaries who are involved in this are serial offenders, having seen them signing on an exxessive amount of abusive applications, no end in sight.

3DirectionTechnology
1igoovo
1METAVERSEDATAMINING
1NewHuoPool
1newwebgroup
1NiwanDao


@StoneMoonGalaxy, it is evident from our analysis that you are engaged in self-dealing by exclusively providing data to your own miners through VPN, falsely creating the appearance of global distribution. Deal amounts are perfectly similar and minerID's are following up. The chance that these are separate entities is zero.

Additionally, the merging of datasets violates our guidelines.

sp | client | totaldeals | ipadres | location | vpnresults | percent
-- | -- | -- | -- | -- | -- | --
f0442671 | f02063280 | 109882443300864 | 18.162.90.101 | US , Central and Western , Hong Kong | TRUE with fraudscore 75 | 5
f02031264 | f02063280 | 109951162777600 | 52.77.205.10 | SG , Singapore , Singapore | TRUE with fraudscore 75 | 5
f02032453 | f02063280 | 503919922905088 | 3.28.28.100 | AE , Dubai , Dubai | TRUE with fraudscore 75 | 23
f02048808 | f02063280 | 503919922905088 | 54.207.232.14 | BR , Sao Paulo , So Paulo | TRUE with fraudscore 75 | 23
f02052252 | f02063280 | 503919922905088 | 44.231.31.109 | US , Oregon , Boardman | TRUE with fraudscore 75 | 23
f01980952 | f02063280 | 505294312439808 | 183.222.164.239 | CN , Sichuan , Chengdu | FALSE with fraudscore 0 | 23


We recommend closing your application and revoking your remaining datacap.

**Comment by StoneMoonGalaxy** [comment]
> @StoneMoonGalaxy, it is evident from our analysis that you are engaged in self-dealing by exclusively providing data to your own miners through VPN, falsely creating the appearance of global distribution. Deal amounts are perfectly similar and minerID's are following up. The chance that these are separate entities is zero.

Thank you for your question.
1.After studying the community rules, We have implemented strict decentralized deal allocation in order to comply with these rules:
--the storage providers should not exceed 30% of the total data limit,
--duplicate storage should not exceed 20%, 
--unique data storage should not exceed 30%.
The purpose  is to ensure that our data is stored in the correct manner.
2.Regarding the issue of SPs using VPNs, as the data storage provider, we are unable to accurately identify whether they use VPNs. In the situation where we are unable to verify, we have decided to terminate our cooperation with these SPs and suspend storage until we find new ones.
3.Regarding the merging of datasets, it is important to note that at the time of our application, the community did not explicitly state that datasets cannot be merged.
we have applied for and stored data in accordance with community rules.

**Comment by herrehesse** [comment]
1. It is essential to familiarize yourself with the community rules and guidelines prior to requesting PiB's of datacap. Merely stating that you have reviewed them recently is not a valid excuse.
2. Your claim is entirely false. As the data preparer, it is your responsibility to choose appropriate storage locations. However, it appears that all your storage locations have been falsified and are likely located in the same datacenter. Therefore, your excuse holds no validity.
3. Similarly, your excuse is completely baseless. The rule regarding merged datasets was addressed on February 22nd of this year, yet you were granted a datacap approval of 1.75 PiB on June 8th.

Since there is no evidence supporting your claims and all of your responses lack validity, I suggest that @raghavrmadya remove your application and revoke your datacap. The community can no longer tolerate such abusive behaviour.

**Comment by StoneMoonGalaxy** [comment]
1.I am the data owner, not an SP. As of now, I have disclosed all the entity information of the SPs I have collaborated with, fully complying with the application process.
2.The use of VPN by SPs does not necessarily mean that they are engaging in regional deception. The usage of VPN does not directly indicate a mismatch between their actual location and the disclosed address. These are two separate issues.
3.The similar deal amounts and consecutive increment of miner IDs are a result of our intentional assignment of orders to SPs according to the rules and the requirement for them to package at approximately the same time. SPs specifically apply for IDs during this period to ensure coordination. There shouldn't be any issue with this approach as long as it is part of the established guidelines and requirements.
4.Regarding the merging of datasets, I have seen the latest discussions go like this:
![abc](https://github.com/filecoin-project/notary-governance/assets/114480622/10556d1e-556c-4923-8338-4f969b3ae520)

Reject arbitrary bans! We demand targeted and constructive guidance and suggestions. The establishment of order is gradually defined through the continuous practices of various parties and cannot be unilaterally predicted and decided by any one person.

**Comment by herrehesse** [comment]
@StoneMoonGalaxy, I am once again surprised by your response.

1. No, it's not you who are the owner, it's the United States government. Please refrain from spreading misinformation.
2. Yes, it's evident that these entities are interconnected and falsely distributing with VPNs.
3. Sure buddy, that is how distribution works in a perfect world with 6 seperate mining entities around the globe. Dream on. We have send lots of deals and this simply does not work.
4. Continuing to merge old datasets won't change the fact that you are not genuinely present in "multiple locations" as RG is requiring you to.

The suggestion to close this LDN remains unchanged.

**Comment by StoneMoonGalaxy** [comment]
Regarding your main objections about :the VPN , we believe that the presumption of guilt against SP is not consistent with our approach, and we have provided our resolution.As for the issue of merging datasets, we will not explain it further here. Currently, these are not reasons for closing Ldn based on community rules. We will continue to adjust and improve as usual according to community rules, and welcome community supervision.
