### ISSUE TITLE
[DataCap Removal Proposal]Abusive Behaviour Detected on 2008

### ISSUE THREAD

**Issue by dikemm** [filecoin-project/notary-governance#935]
### Client Application URL or Application Number

https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2008

### Client Name

Dcent

### Client Address

f1mgnwoczfj25foxn4555wvwyak6rsynzy7z73azy

### Amount of DataCap to be removed

105PiB

**Comment by dikemm** [comment]
https://github.com/filecoin-project/notary-governance/issues/930#issuecomment-1641565097
2 Fatman13
3 laurarenpanda
2 liyunzhi-666

**Comment by dikemm** [comment]
<img width="1300" alt="WX20230720-161429@2x" src="https://github.com/filecoin-project/notary-governance/assets/138772951/13029ca8-4024-49c7-b924-2a747adc1027">
<img width="1142" alt="254259998-eafe8c10-920b-4ce0-8e69-4885360b9484" src="https://github.com/filecoin-project/notary-governance/assets/138772951/24b7cf0d-4018-423e-8def-1156966330aa">

**Comment by herrehesse** [comment]
To provide transparency, I want to reiterate that your previous accusations have been addressed and answered more than seven times in the past six months. I am more than willing to provide you with links to these responses, as it seems you may have been unable to find them yourself:

- Regarding duplicate data (0.04% of the application size), the explanation can be found here: [[link 1](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2008#issuecomment-1567958183)] and [[link 2](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/488#issuecomment-1410486103)].

- Regarding CID sharing (0.02% of the application size), it was a fault on our end six months ago, and it has not occurred since. 

- CID sharing 0.02% of the application was a fault at our end 6 months ago, has not happened since. 
Unique bytes [[link 3](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2008#issuecomment-1640145893)]

I hope these resources will help clarify any misconceptions and promote a better understanding of the situation.

**Comment by dikemm** [comment]
Really, don't do this.
Others have problems, and theirs is problematic no matter how they are interpreted.
If you have a problem, if you explain it, there will be no problem. If you have any problem, you can use the next round of corrections to easily get DC. It’s so funny!

**Comment by dikemm** [comment]
According to the current statement, problematic LDNs and controversial LDNs cannot be signed by a notary unless the dispute is resolved. In the face of CID, I think that the controversy can never be resolved, because people have to face the facts! And not a lie!

**Comment by ars-bubu** [comment]
> To provide transparency, I want to reiterate that your previous accusations have been addressed and answered more than seven times in the past six months. I am more than willing to provide you with links to these responses, as it seems you may have been unable to find them yourself:
> 
> * Regarding duplicate data (0.04% of the application size), the explanation can be found here: [[link 1](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2008#issuecomment-1567958183)] and [[link 2](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/488#issuecomment-1410486103)].
> * Regarding CID sharing (0.02% of the application size), it was a fault on our end six months ago, and it has not occurred since.
> * CID sharing 0.02% of the application was a fault at our end 6 months ago, has not happened since.
>   Unique bytes [[link 3](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2008#issuecomment-1640145893)]
> 
> I hope these resources will help clarify any misconceptions and promote a better understanding of the situation.

@Kevin-FF-USA @raghavrmadya The explanation is invalid, if there is a problem, it is a problem. Also ask the community to audit this person @herrehesse

**Comment by herrehesse** [comment]
![Screenshot 2023-07-20 at 12 15 54](https://github.com/filecoin-project/notary-governance/assets/70132857/122898bd-f354-49ba-b751-b2450a350ef0)

@dikemm almost seems like you have a lot of experience in this ecosystem for many years.

![Screenshot 2023-07-20 at 12 18 21](https://github.com/filecoin-project/notary-governance/assets/70132857/3bf6c33f-f3a8-413e-a0ee-68814d982b23)

@ars-bubu You are now disputing an explained question from Speedium while you are fully self-dealing #1408?

**Comment by herrehesse** [comment]
@0xXPunkX Thank you for asking the same question again, if you would have scrolled up a little bit you would have found the answer: https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2008#issuecomment-1640145893

**Comment by herrehesse** [comment]
@0xXPunkX What you are saying is so far from the truth. This application was signed already for over 40 times on different LDN requests due to its size. Here you can take a look: https://github.com/filecoin-project/filecoin-plus-large-datasets/issues?q=is%3Aissue+speedium+nih

"The difference should not be so large in the stage of the uncontrollable data of a small amount of data" what does this even mean?

- Our application has a total size of 15PiB * 10 = 150PiB or 153.600TiB
- The "CID" duplicate problem is 44 TiB = 0.02% of the complete application

**Comment by max1015070108** [comment]
#930

**Comment by The-Wayvy** [comment]
Make Filecoin Permissionless Again!

FIL+ is a con

**Comment by Filplus-govteam** [comment]
Hello @dikemm - this proposal was reviewed.

It seems the client has explained every instance under scrutiny clearly and transparently. There were some errors early on, as many clients have learning the processes to onboard data. There has been nothing since that we can tell. 

Additionally, this client has undergone all KYC and KYB standards of E-Fil+ to comply with requirements of the program. 

This is a transparent client looking to onboard data in a distributed manner that meets the guidelines of the Fil+ program. There are no major abuse flags here.

**Comment by jamerduhgamer** [comment]
> <img alt="WX20230720-161429@2x" width="1300" src="https://user-images.githubusercontent.com/138772951/254819095-13029ca8-4024-49c7-b924-2a747adc1027.png"> <img alt="254259998-eafe8c10-920b-4ce0-8e69-4885360b9484" width="1142" src="https://user-images.githubusercontent.com/138772951/254819112-24b7cf0d-4018-423e-8def-1156966330aa.png">

Like @Filplus-govteam has already mentioned in their comment, all of the highlighted issues above have already been explained by the client [here](https://github.com/filecoin-project/notary-governance/issues/935#issuecomment-1643561442)

1. For everyone's convenience here are the quoted response to the first highlighted issue:
>Just addressing the duplicate data on miners f01208803 and f01208189.
>Over the Xmas period, both these miners had issues while snapping. A small number of files had permission issues (i.e. could not be removed from the file system) and were not cleaned up from the ingest pipeline. While our ingest code normally performs a check to ensure a file has not been previously ingested, this check failed with these files.
>This has since been sorted.
2. Second highlighted issue's quoted response:
> Regarding CID sharing (0.02% of the application size), it was a fault on our end six months ago, and it has not occurred since.
> CID sharing 0.02% of the application was a fault at our end 6 months ago, has not happened since.
3. Third highlighted issue's quoted response:
> One organization is ahead with the sealing plan. We will pause them so things will balance out over the course of next tranche of datacap.

Extra note, retrievability of the dataset has been increasing between datacap report summaries proving the client has been actively working on this as well.

**Comment by lyjmry** [comment]
> > <img alt="WX20230720-161429@2x" width="1300" src="https://user-images.githubusercontent.com/138772951/254819095-13029ca8-4024-49c7-b924-2a747adc1027.png"> <img alt="254259998-eafe8c10-920b-4ce0-8e69-4885360b9484" width="1142" src="https://user-images.githubusercontent.com/138772951/254819112-24b7cf0d-4018-423e-8def-1156966330aa.png">
> 
> 喜欢@Filplus-govteam在他们的评论中已经提到，上面所有突出的问题已经由客户[在这里解释过](https://github.com/filecoin-project/notary-governance/issues/935#issuecomment-1643561442)
> 
> 1. 为了方便大家，这里引用了对第一个突出问题的回应：
> 
> > 只是解决矿工 f01208803 和 f01208189 上的重复数据。
> > 在圣诞节期间，这两个矿工在抢购时都遇到了问题。少数文件存在权限问题（即无法从文件系统中删除）并且未从摄取管道中清除。虽然我们的摄取代码通常会执行检查以确保之前没有摄取过文件，但对这些文件的检查失败了。
> > 此后此问题已得到解决。
> 
> 2. 第二个突出问题引用的回应：
> 
> > 关于CID共享（应用程序大小的0.02%），这是六个月前我们端的一个错误，此后就没有再出现过。
> > 6 个月前，CID 共享 0.02% 的应用程序是我们的一个错误，此后就再也没有发生过。
> 
> 3. 第三个突出问题引用的回应：
> 
> > 一个组织正在推进密封计划。我们将暂停它们，以便在下一阶段的 datacap 过程中保持平衡。
> 
> 额外注意的是，数据集的可检索性在 datacap 报告摘要之间一直在增加，证明客户也一直在积极致力于这方面的工作。

You seem to have forgotten about their notary problem with irregular signatures.

**Comment by dikemm** [comment]
I agree with you @Filplus-govteam , but there is another problem with Dcent, which is the concatenation of notary signatures, in 2008, fildrive signed three times in a row, which is already against the regulations.RG once pointed out that fildrive's LDN has major problems, a large number of CID sharing, but because fildrive actively helps Dcent to sign, fildrive's LDN can see a lot of problems at a glance, but Dcent never post dispute.

**Comment by dikemm** [comment]
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1623
<img width="1091" alt="WX20230722-124845@2x" src="https://github.com/filecoin-project/notary-governance/assets/138772951/143fa87b-79c0-472d-8839-76c6bc517b92">
<img width="885" alt="WX20230722-124957@2x" src="https://github.com/filecoin-project/notary-governance/assets/138772951/55e1aa28-281c-4d74-a557-de4ef805a933">

https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1624
<img width="960" alt="WX20230722-125045@2x" src="https://github.com/filecoin-project/notary-governance/assets/138772951/db55c369-6a46-49d6-851e-678e4
<img width="1029" alt="WX20230722-125103@2x" src="https://github.com/filecoin-project/notary-governance/assets/138772951/75ad0053-1d86-448e-bc0a-0cdf7be5d921">
0de93a4">

https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1625

<img width="1068" alt="WX20230722-125132@2x" src="https://github.com/filecoin-project/notary-governance/assets/138772951/f48e19dd-ea16-4491-898e-473e99876fdc">
<img width="1104" alt="WX20230722-125200@2x" src="https://github.com/filecoin-project/notary-governance/assets/138772951/ac2bc88f-bfae-420b-8c5c-46ca5ae77fee">

https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1626
<img width="841" alt="WX20230722-125221@2x" src="https://github.com/filecoin-project/notary-governance/assets/138772951/02c69195-34b6-41bf-ab23-0ffe0d8ab85f">
<img width="1142" alt="WX20230722-125245@2x" src="https://github.com/filecoin-project/notary-governance/assets/138772951/751615f3-b015-4e83-9d4d-c3ba2615dc7a">

https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1627
<img width="1126" alt="WX20230722-125307@2x" src="https://github.com/filecoin-project/notary-governance/assets/138772951/b0c567f1-92fa-4ef5-a34b-fbea5c74a381">

**Comment by dikemm** [comment]
The LDN of the fildrive series, 1623-1627, has a lot of abuse and cid sharing. As for whether VPN is used, I will investigate if necessary, but 1623-1627DCENT are all signed, and fildrive is also actively helping DCENT sign 2008.

**Comment by herrehesse** [comment]
![Screenshot 2023-07-24 at 12 02 02](https://github.com/filecoin-project/notary-governance/assets/70132857/c9ef597c-2eba-4ead-8096-27f89f68ff03)

Everyone has the right to inquire or challenge entities, but let's focus on cutting through the clutter. Speedium and Cryptowhizzard have been active members of this community since its inception, consistently displaying openness and transparency. They have addressed all the questions raised in this thread in great detail. However, it appears that certain newly created throwaway accounts are not genuinely seeking answers, but merely attempting to undermine our credibility by creating noise.

The Fil+ T&T team, PIKNIK, and HOLON have all provided their responses as well, yet the noise persists.

In essence, it all boils down to noise. If you are actually interested in answers on your questions, I would suggest you to take a proper look inside their LDN issues.

**Comment by dikemm** [comment]
I don't intend to attack you, but from the point of view of signatures, you have helped every LDN of fildrive to sign, and they are actively helping you to sign. You still have many LDNs who can see their signatures, especially in 2008. The signatures are too frequent, which has violated the rules. In addition, RG has indeed questioned the LDN of fildrive. And I believe it is easy to find evidence of your signatures with PIKNIK.

**Comment by kevzak** [comment]
Hello I can add my notes about this situation as this is an E-Fil project.

This client has done all they can to make their application meet the Fil+ requirements. 
- We asked clients with larger than 15PiB datasets to stop creating separate applications and to instead utilize E-Fil+ and create one application that is easier for the community to monitor. They did that.
- We asked them to abide by E-Fil+ upfront requirements. They did that.
- We asked them to share distributed SP entities they are working with. They did that.
- We asked them to redistribute their DataCap so SPs are storing more evenly. They are in the process of doing so currently.
- The community has asked questions and they have responded to every question with a clear answer why.

Regarding notary signing trends. It looks like seven different notaries have signed this application. That seems like a solid distribution to me.  Yes, I see Laurapanda has signed 3 times and it was made clear that she will not sign any more subsequent allocations in a row. 

Please note: Currently in the E-Fil multisig we only have around 8-10 active notaries of the 35 which means notaries will have to sign multiple times to support applications. And these notaries are not always active recently. The client has reached out to all notaries and is currently stuck looking for additional support see [here](https://filecoinproject.slack.com/archives/C03MHVAABFV/p1690012763512099). We should not have situations where this occurs and I am in the process of adding additional notaries to the multisig in the [next few weeks ](https://filecoinproject.slack.com/archives/C03MHVAABFV/p1689874514496109) to allow for more to be available since the current majority are inactive and will be soon removed. 

Regarding Filedrive. I too had questions about their CID reports. They responded and had community support for their answers. https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1626#issuecomment-1562142515 
However, there storage activity is not this client's issue. In my opinion, if you have a dispute, you can open a separate file regarding any specific findings.

Regarding @cryptowhizzard signing for Filedrive. I reviewed and it looks like he signed initially on several of Filedrive application. But, it also it looks like he was active on over 200 LDN applications and has awarded over 1PiB of DataCap as a notary. Remember, the majority of active notaries sign on many applications, so of course there will be repeat signings, it has to for the system to work and applications to receive DataCap. But it still takes 4-20 signatures to get substantial DataCap, he signed once on each applications, still requiring many notaries to support and to be involved. So to say by signing once on a specific application while he also signs on 75+ other applications also means he is in collusion with one SP is a bit of a stretch don't you think? 

After review, I see no major flags, communication is active and completely transparent. I think there are many claims here that are completely unrelated to this specific application. I'd ask @raghavrmadya and T&T WG to review and close this so the client can move on.

**Comment by lyjmry** [comment]
> Hello I can add my notes about this situation as this is an E-Fil project.
> 
> This client has done all they can to make their application meet the Fil+ requirements.
> 
> * We asked clients with larger than 15PiB datasets to stop creating separate applications and to instead utilize E-Fil+ and create one application that is easier for the community to monitor. They did that.
> * We asked them to abide by E-Fil+ upfront requirements. They did that.
> * We asked them to share distributed SP entities they are working with. They did that.
> * We asked them to redistribute their DataCap so SPs are storing more evenly. They are in the process of doing so currently.
> * The community has asked questions and they have responded to every question with a clear answer why.
> 
> Regarding notary signing trends. It looks like seven different notaries have signed this application. That seems like a solid distribution to me. Yes, I see Laurapanda has signed 3 times and it was made clear that she will not sign any more subsequent allocations in a row.
> 
> Please note: Currently in the E-Fil multisig we only have around 8-10 active notaries of the 35 which means notaries will have to sign multiple times to support applications. And these notaries are not always active recently. The client has reached out to all notaries and is currently stuck looking for additional support see [here](https://filecoinproject.slack.com/archives/C03MHVAABFV/p1690012763512099). We should not have situations where this occurs and I am in the process of adding additional notaries to the multisig in the [next few weeks ](https://filecoinproject.slack.com/archives/C03MHVAABFV/p1689874514496109) to allow for more to be available since the current majority are inactive and will be soon removed.
> 
> Regarding Filedrive. I too had questions about their CID reports. They responded and had community support for their answers. [filecoin-project/filecoin-plus-large-datasets#1626 (comment)](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1626#issuecomment-1562142515) However, there storage activity is not this client's issue. In my opinion, if you have a dispute, you can open a separate file regarding any specific findings.
> 
> Regarding @cryptowhizzard signing for Filedrive. I reviewed and it looks like he signed initially on several of Filedrive application. But, it also it looks like he was active on over 200 LDN applications and has awarded over 1PiB of DataCap as a notary. Remember, the majority of active notaries sign on many applications, so of course there will be repeat signings, it has to for the system to work and applications to receive DataCap. But it still takes 4-20 signatures to get substantial DataCap, he signed once on each applications, still requiring many notaries to support and to be involved. So to say by signing once on a specific application while he also signs on 75+ other applications also means he is in collusion with one SP is a bit of a stretch don't you think?
> 
> After review, I see no major flags, communication is active and completely transparent. I think there are many claims here that are completely unrelated to this specific application. I'd ask @raghavrmadya and T&T WG to review and close this so the client can move on.

@ Laurapanda does not sign the follow-up, but he has violated the notary signature rules. As you can see, the signatures were concentrated on three of the eight people.

**Comment by lyjmry** [comment]
A team that has made multiple glaring errors in its LDN also bills itself as "the judge of the world enforcing the law everywhere." Isn't this a big joke?

**Comment by lyjmry** [comment]
> @lyjmry，很明显你决心要让其他人都跟着你一起垮掉。然而，我必须承认，我很欣赏您没有像大多数其他人那样躲在一次性帐户后面。我真的很好奇你是否完全理解什么@kevzak已写在这里，或者如果您只是提出问题而没有想到可能的答案。

I'm not trying to drag anyone down. It's not in any of my interests. I just think your team goes around picking on other LDNS. And to others pointing out your violations described as noise. It's not in keeping with the fairness of the community.

**Comment by lyjmry** [comment]
And, obviously. Your LDN did have multiple violations.

**Comment by herrehesse** [comment]
> "picking on" 

We don't randomly select disputes. Instead, we meticulously provide transparent and concrete on-chain evidence for each of our cases.

**Comment by herrehesse** [comment]
> And, obviously. Your LDN did have multiple violations.

The key distinction lies in our transparency – we back our claims with solid evidence, offer clear explanations, and refrain from engaging in actions like extensive self-dealing with hundreds of PiB's while falsely distributing them through VPN services, which seems to be the practice of about 95% of the LDN's currently. Go out there and take a look for yourself.

Labeling us as similar to those is a result of your perspective, not mine, as our approach and actions speak for themselves.  As for your suggestion, would active PL members and large public companies be willing to defend us if we were genuinely the abusive entity here? It seems highly unlikely to me.

**Comment by lyjmry** [comment]
> > And, obviously. Your LDN did have multiple violations.
> 
> The key distinction lies in our transparency – we back our claims with solid evidence, offer clear explanations, and refrain from engaging in actions like extensive self-dealing with hundreds of PiB's while falsely distributing them through VPN services, which seems to be the practice of about 95% of the LDN's currently. Go out there and take a look for yourself.
> 
> Labeling us as similar to those is a result of your perspective, not mine, as our approach and actions speak for themselves. As for your suggestion, would active PL members and large public companies be willing to defend us if we were genuinely the abusive entity here? It seems highly unlikely to me.

NO NO NO! It's not as noble as you say! I've been watching for a while. Every time your team started a fight, it was after you were no longer able to sell data profitably on Bigdata.

**Comment by lyjmry** [comment]
Because after the community shuts down because of the tools you make, you profit for a long time. But after the community implements your standards, you will upgrade them again.

**Comment by lyjmry** [comment]
Your intent seems to be not to better the community, but to prevent others from taking your share of the market pie on Datacap.

**Comment by cryptowhizzard** [comment]
> Because after the community shuts down because of the tools you make, you profit for a long time. But after the community implements your standards, you will upgrade them again.

Why don't you just buzz off with your blackmailing tactics and shit. You won't get me to approve your LDN, Period.

![Scherm­afbeelding 2023-07-24 om 15 20 24](https://github.com/filecoin-project/notary-governance/assets/36404435/3a97bd78-a0a7-4f4a-bbbe-758ba710ec8a)

**Comment by lyjmry** [comment]
If you want to prove that you really do care about community development, you can stop distributing LDN. One heart to guide the community to do compliance things! That's beautiful.

**Comment by cryptowhizzard** [comment]
> If you want to prove that you really do care about community development, you can stop distributing LDN. One heart to guide the community to do compliance things! That's beautiful.

Buzz off. Go away.

**Comment by herrehesse** [comment]
Which “pie” are you referring too? There is over 1EiB of datacap out there we barely hold 0.2% per accepted trench for our single application.

**Comment by herrehesse** [comment]
@lyjmry why are you blackmailing @cryptowhizzard ? This is extremely illegal.

**Comment by herrehesse** [comment]
@raghavrmadya @kevzak @dkkapur Asking for dispute closure.

**Comment by hcgun** [comment]
hello, as you are a notary, we need an explanation why do you sent so many deals of data to only one/two/three SPs?
<img width="991" alt="image" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/138212354/fee7ac5e-9bb0-422e-a01e-db7bf5d21797">
This goes against what you said in your application.If it is a small amount of excusable, there is a huge deviation.
<img width="243" alt="image" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/138212354/9ab04334-764a-40b4-8639-909b77f91ada">
