### ISSUE TITLE
Proposal for T&T Committee

### ISSUE THREAD

**Issue by Filplus-govteam** [filecoin-project/notary-governance#940]
## Issue Description
Fil+ is a social trust layer on top of the permissionless Filecoin network and requires transparency in the allocation & spending of DC. 

In the past few months, we have made progress on how disputes are raised with the launch of the [dispute tracker ](https://www.notion.so/filecoin/T-T-Dispute-Tracker-d28b93677cb544b48e77b585856601cf?pvs=32) as well as tools for diligence such as:

CID Checker Bot
Retrieval Bot
[Starboard dashboard} (https://filplus.starboard.ventures/)

Still, how disputes are closed/decided on has been controversial and requires a more systemized way to reach a consensus.

## Impact

More decentralized decision-making and transparency in the Fil+ prgram

## Proposed Solution(s)

This issue proposes the creation of a T&T Committee which will precede once a week and vote on open issues related to DC abuse, notary-client collusion etc. 

The proposed design of this committee is as follows:

5 notaries 
5 community members 
5 active SPs ( SPs that have made a deal in the <3 months)
T&T WG Lead

Proposal on how the committee should be elected - 

Each individual who wishes to be part of this committee has to be publicly elected by voting

### Porposed Timeline

Discussion of the creation of a T&T committee - Fri July 21st 2023 to Wednesday 26th 2023

We will be opening an issue to [kick off the election process](https://github.com/filecoin-project/notary-governance/issues/941) in parallel and should this proposal receive positive feedback from the community, it will help us accelerate the formation of the committee

Create the GitHub issue for the community to express interest in being part of the T&T Committee 0 Fri Jul 21 2023

Voting period - Until Tuesday Aug 1st 2023

The decision was announced based on public voting - Monday August 7th 2023

**Comment by Filplus-govteam** [comment]
Future iterations should introduce staking the governance team is of the opinion that we need to initiate the process toward decentralized decision-making on open issues from the T&T WG Lead to an independent committee that votes on open issues

**Comment by Filplus-govteam** [comment]
We would also love to hear the communities opinion on having each person elected on this committee to do KYC/KYB

**Comment by kernelogic** [comment]
Who can vote in this case?

**Comment by herrehesse** [comment]
Definitely 100% do active KYC/KYB on these entities. We should do all we can to reduce fraud and increase trust. This starts with knowing who you are dealing with.

**Comment by Filplus-govteam** [comment]
Good question @kernelogic. At this time, we will require everyone to do KYC/KYB to participate in the voting process.

**Comment by Filplus-govteam** [comment]
The proposed committee meets once a week for 30 minutes to discuss open disputes, vote on them, and provide decisions to the community, driven by T&T WG Lead

**Comment by MarshLin88** [comment]
1、We'd like to know on which dimensions elections are scored. Not whether to do KYC/KYB or not. 
2、How can these people be restrained from doing evil? Do we need another new team to audit T&T Committee?
3、Why don't we encourage public votes on open issues related to DC abuse, notary-client collusion etc?

**Comment by The-Wayvy** [comment]
The core issue is that we have a permissioned blockchain.

Bitcoin, Ethereum, et al never had a permissioned mechanism in place. 

We don't need one either.

Building additional bureaucratic structures is not the solution.

A public commitment to a schedule for reducing the power multiplier, datacap quota and notary count is.

**Comment by The-Wayvy** [comment]
> Future iterations should introduce staking the governance team is of the opinion that we need to initiate the process toward decentralized decision-making on open issues from the T&T WG Lead to an independent committee that votes on open issues

Decentralization = 0 human notaries

Anything else is totally out of step with best practices

Bitcoin, Ethereum, Avalanche, Solana, Uniswap, ...............

**Comment by kenzz45** [comment]
Creating a more centralized T&T  Committee to andit Notaries... 
then some guys can control community through T&T Committee easily...

Have you guys forgotten what made you join the blockchain world initially?
It will only make fil+ worse... @jbenet

**Comment by flyworker** [comment]
The first issue now is

Should we set up a Committee?


A vote about it should be presented first. it is changing the governance model to delegation now.

**Comment by flyworker** [comment]
It is also funny to see in https://github.com/filecoin-project/notary-governance/issues/941

`Based on issue https://github.com/filecoin-project/notary-governance/issues/940, we are kicking off the election issue parallel given the urgency of the matter. While this issue is dependent on the outcome of issue 940, it is in the community's interest to initiate this process`

Now a new created github account can represent everyone.

**Comment by kernelogic** [comment]
There are several categories of disputes right now, I wonder how having a "committee" going to solve these:
1. Notary related: lack of DD, sign too little, sign too much, sign together, play favourites
2. Client related: fake data, inflated data, wrong data, low value data, distribution ratio
3. SP related: unretrievable, fake entity, fake location, VPN usage

Will the 15+1 people vote on all these issues one by one? Is everybody have the same power or the T&T lead has the ultimate veto power?

**Comment by dahuajishu** [comment]
Filecoin will gradually become a game of power, won't it?

**Comment by 15012700225** [comment]
Dancing with the devil and blending in, that's how I see FIL+.

**Comment by MetaWaveInfo** [comment]
> It is also funny to see in #941
> 
> `Based on issue https://github.com/filecoin-project/notary-governance/issues/940, we are kicking off the election issue parallel given the urgency of the matter. While this issue is dependent on the outcome of issue 940, it is in the community's interest to initiate this process`
> 
> Now a new created github account can represent everyone.

No problem using a new account to post your opinion, but it doesn't represent the majority opinion.
Why don't other members have the right to vote on controversies?  More participation and different opinions is what the web3 community should be.

**Comment by c12xf** [comment]
This is an unreliable proposal. Looking back at the current issue, you suspect that the notary directly colluded, so you are preparing to establish a committee. After the establishment of the committee, you suspected collusion among the members of the committee. Okay, here's another new proposal to establish the highest level committee to govern it. Can I imagine it this way?

**Comment by Filplus-govteam** [comment]
T&T Lead will not have a voting power. The proposed committee will meet once a week for 30 minutes to discuss the open disputes and vote on them and it will be an open meeting. 

If people here have a better proposal to resolve open disputes without the T&T Lead being the judge based on discussion, please propose

**Comment by Filplus-govteam** [comment]
To address problems of collusion in the committee, we can use incentives. Here's an idea by the T&T WG Lead:

A one-time grant of 250 FIL to each of the 10 members upfront + requirement for staking 300 FIL during their tenure on the committee. The proposed tenure is minimum of 3 months and maximum 6 months. 

If committee member stops engaging within 3 months, 250 FIL is slashed and 50 FIL is returned

If committee member completes at least 3 months, they get to keep the 250 FIL

If committee member would like to run again, they are welcome to stake 300 more FIL and earn 250 more FIL for the next 3 months.

**Comment by Filplus-govteam** [comment]
@flyworker that's exactly what we are doing. Other issue is dependent on this passing and it has been clearly outlined

**Comment by Filplus-govteam** [comment]
@kernelogic , T&T Lead has not power. That's the whole point. Today the T&T Lead is being used as a scapegoat and there is no definitive timeline on when DC will be removed, when a dispute will be resolved. Having a committee distributes the duty of decision to a group

**Comment by Filplus-govteam** [comment]
> The proposed committee meets once a week for 30 minutes to discuss open disputes, vote on them, and provide decisions to the community, driven by T&T WG Lead

Not sure if it was clear but this will be a public meeting and not behind closed doors.

**Comment by The-Wayvy** [comment]
I see 2 problems in your current design.

First 

Notaries and SPs cannot be on the committee because they are personally involved in the disputes they will be adjudicating.

Just as conflict of interest disqualifies a citizen from jury duty, being a party to the dispute definitely disqualifies notaries and SPs from committee membership.

It is worth investigating how a notary committee member would behave in the following situations   

they themselves are under investigation
another notary on the board is under investigation 
a notary not on the board is under investigation 

Likewise with SPs

they got the deal and were subsidized 
they didn’t get the deal and were taxed 

Second

The person who has authority to slash a committee member’s stake can pressure them to vote a certain way by threatening to get them slashed if they don’t.

**Comment by The-Wayvy** [comment]
If you really want the good-will and trust of the community :
1.) cut the power multiplier
2.) cut the data cap quota

**Comment by The-Wayvy** [comment]
As an alternative, I propose on-chain voting weighted by RBP

**Comment by perfectyc** [comment]
It is really ridiculous to use one organization to censor another power organization, if the new organization is corrupt, then whether to set up another organization to censor! PL This is playing "matryoshka dolls "? Or a successor to the socialist system?

**Comment by litai686** [comment]
The simplest way is to cancel the DC. SPs wants to obtain more fils and determines the multiple of the profits by promising the duration of the pledge period.   Resist centralized management !!!

**Comment by raghavrmadya** [comment]
@The-Wayvy , thanks. appreciate your points above and will do further research and thinking on on-chain voting.

**Comment by liyunzhi-666** [comment]
There are quite a few dissenting voices and emoji's here. maybe we should revisit this proposal and the specific implementation plan.

**Comment by NDLABS-Leo** [comment]
Oppose the proposal.

**Comment by 1ane-1** [comment]
It‘s a bad proposal. Object！

**Comment by Destore2023** [comment]
Please take a look at [Juan's AMA](https://www.youtube.com/watch?v=JFypZjgB7Ig) and see what he thinks about the situation of FIL+ and what we should do as Filecoin community members.

Such a high centralization of power and bureaucracy should not happen in the world of blockchain, this proposal is a complete rejection of the notary voting system after V1.

**Comment by newwebgroup** [comment]
While the proposal aims to resolve disputes on the Filecoin network, its approach may give rise to new problems. The voting system might be susceptible to manipulation, and the members elected to the committee may lack sufficient capability and experience to handle complex issues. Additionally, this proposal could potentially reduce decision-making efficiency. Therefore, I oppose this proposal.

**Concerns:**
- Election Fairness: The proposal mentions that members of the committee are to be elected publicly through voting. However, if the voting process is unjust, or susceptible to manipulation, it may create controversy. For example, how will voter identity verification be handled? What measures will be taken to prevent one person from casting multiple votes? Without sufficient mechanisms to prevent manipulation, the voting system could be exploited by a minority to advance their private interests rather than those of the entire community.

- Decision Transparency, Fairness, and Representativeness: Key questions revolve around how decisions will be made by the committee, whether the decision-making process is transparent, and whether all members have an equal opportunity to participate. If the decision-making process is not transparent, it may cause disputes or skepticism. Moreover, the committee composition proposed may not fully represent the entire community's interests. For example, active large-scale Service Providers (SPs) might have different objectives or motivations, leading their decisions not to align with the best interests of all users or smaller SPs.

- Challenges in Rule Determination and Implementation: Establishing a new committee to review and decide on disputes could lead to difficulties in interpreting and executing rules, especially in the absence of explicit regulations or guidelines.

- Committee Members' Capability and Experience: This proposal assumes that the elected committee members can fully understand and address the issues they face, but this may not always be the case, particularly in highly specialized or complex issues. If committee members lack the capability and experience to handle complex issues, they may not effectively resolve disputes.

- Participation Issues: The proposal suggests a weekly meeting, which might require considerable time and energy from participants. If members cannot maintain high participation, it could affect the committee's effective operation.

- Speed of Dispute Resolution: If meetings are held only once a week, dispute resolution might be slow, especially when the number of disputes is high. This could lead to some disputes remaining unresolved for a long time, impacting the harmony of the community.

- Decision Efficiency: Having the committee vote on all decisions could reduce decision efficiency, which might pose a problem for issues that need to be resolved quickly.

**Comment by Destore2023** [comment]
> @Filplus-govteam
> 
> I see 2 problems in your current design.
> 
> ### **First**
> Notaries and SPs cannot be on the committee because they are personally involved in the disputes they will be adjudicating.
> 
> Just as conflict of interest disqualifies a citizen from jury duty, being a party to the dispute definitely disqualifies notaries and SPs from committee membership.
> 
> Imagine someone charged with embezzling funds being on the jury of their own case. Or a protestor adjudicating the trial of a police officer charged with assaulting them during the protest.
> 
> Every single miner is directly involved in every single dispute. Either the miner got subsidized or they were taxed to fund the subsidy of their competitors. Plaintiffs can't serve on a jury. Neither can defendants.
> 
> With our 'uncompensated' notaries, things are even shadier. Nobody works for free.
> 
> It is worth debating how a notary committee member would behave in the following situations
> 
> 1.) they themselves are under investigation 2.) another notary on the board is under investigation 3.) a notary not on the board is under investigation
> 
> Likewise with SPs
> 
> 1.) they got the deal and were subsidized 2.) they didn’t get the deal and were taxed
> 
> ### **Second**
> The person who has authority to slash a committee member’s stake can pressure them to vote a certain way by threatening to get them slashed if they don’t. "when you've got them by the balls, their hearts and minds will follow"
> 
> ### **Conclusion**
> A committee one third of whose members are a direct party to every single dispute they will be adjudicating will not increase trust in the integrity of FIL+. The participation of notaries in the committee is also inappropriate and the slashing mechanism is a centralization vector.
> 
> This committee would result in even more drama and politics.
> 
> I don't want to keep repeating myself like a robot, but we all know what needs to be done: Make Filecoin Permissionless Again.

Totally agree with @The-Wayvy  This proposal will only make the community more acrimonious instead of calming it down. I permissionless ecosystem should be code-based, especially in the blockchain world.

I do suggest @Filplus-govteam  take a look at this [Discussions](https://github.com/filecoin-project/FIPs/discussions/725)

**Comment by ars-bubu** [comment]
Fil+is a joke that violates the decentralization protocol. Now it is proposed to centralize management and stop talking nonsense. It is recommended to cancel fil+.

Filecoin is such a great project, such a great track. Don't be managed by a few ignorant people and lead to destruction.

**Comment by ars-bubu** [comment]
> Filecoin将逐渐成为权力的游戏，不是吗？



> Filecoin将逐渐成为权力的游戏，不是吗？

I really agree with that

**Comment by herrehesse** [comment]
Upon closer examination of the individuals and entities driving the Filecoin ecosystem, it is evident that some members are dedicating significant time and resources to its enhancement. Based on my observations, I would like to offer the following recommendations:

**5 Notaries:**

- Patrick-Li: Among the few notaries diligently conducting thorough due diligence on each application before providing their signature. Well respected. @liyunzhi-666 
- Jamerduhgamer: A trusted and long-standing member of the community, actively onboard new clients with real data. @jamerduhgamer
- Twinquasar: One of the earliest and most respected notaries in the community, renowned for developing numerous applications for the ecosystem. @s0nik42
- Joss Hua: A core member of the Asian community and a highly esteemed participant of the Venus team, whose inclusion in the group is highly recommended. @Joss-Hua
- Cryptowhizzard: An exceptionally passionate and proactive notary, actively involved in improving the ecosystem since Filecoin's inception, boasting the most extensive experience among them. @cryptowhizzard

**5 Community Members:**

The majority of community members I've encountered are either Notaries or part of storage provider operations.

**5 Active Storage Providers (SPs):**

- HOLON: One of the largest and most respected miners from Australia.
- PIKNIK: An exceptionally active SP based in the USA and the founder of ESPA, earning trust and recognition as a reliable entity.
- SEAL: Known for fostering the best collaborations in global data storage, with a deep understanding of valuable data.
- GREATER HEAT: Highly respected among large enterprise miners in Asia, serving as the host for the prestigious DSPA event and a trusted community player.
- DCENT: One of the most well known European miners since Filecoin's inception, possessing a wealth of experience as a data preparer and demonstrating excellent networking and distribution skills. Furthermore, they are vocal and actively engaged members of the community.

These individuals and entities are vital contributors to the growth and advancement of the Filecoin ecosystem. Recognizing their efforts and encouraging collaboration among them will undoubtedly lead to further progress and success.

_(DSS/DLTX are also on this list)_

**Comment by Tom-OriginStorage** [comment]
As stated previously, there might be a conflict of interest if this proposal is approved : notaries and service providers should not be on the committee because they are involved in the dispute. This could lead / threaten members to vote a certain way and  influence the decision-making process.

**Comment by herrehesse** [comment]
@Tom-OriginStorage Currently, it appears that nearly 100% of the notaries are involved in abusive practices. To address this issue, the committee should redirect its focus towards introducing accountability, a crucial aspect that seems to be lacking among individual notaries. Instances of threats have already occurred, and there are reports of notaries attempting to sell their signatures. We are already at the absolute worst.

A viable way to progress would be to establish a committee that represents the voices of all community members. As mentioned earlier, selecting well-known and public entities, as advised above, would be beneficial. **These entities are more likely to be open to public scrutiny and are motivated to maintain a positive reputation.** Fake accounts get us to where we are currently.

@sonicking1777 The concept of " full decentralization & trust" has faced significant challenges over the past six months, resulting in the onboarding of nearly 1 EiB (exbibyte) of fake data on the chain. To address these issues effectively, we require the implementation of a committee, similar to the one proposed, which can oversee and regulate the ecosystem before any further progress can be made.

**Comment by herrehesse** [comment]
> @sonicking1777 I think your obversations are meaningless

My friend, everyone is entitled to their own thoughts and beliefs. It's important to clarify that the view I'm expressing is solely my own perspective. I welcome and value the opinions of others on this matter and would be interested to hear what they have to say about it.

**Comment by herrehesse** [comment]
Dear friend, you are welcome to nominate anyone, as long as you are able to explain your rationale.

**Comment by ars-bubu** [comment]
> There is a huge unknown conspiracy behind this proposal, which I will reveal to you when i am free.

@SmallMiner  I am looking forward to your next speech

**Comment by ars-bubu** [comment]
> Upon closer examination of the individuals and entities driving the Filecoin ecosystem, it is evident that some members are dedicating significant time and resources to its enhancement. Based on my observations, I would like to offer the following recommendations:
> 
> **5 Notaries:**
> 
> * Patrick-Li: Among the few notaries diligently conducting thorough due diligence on each application before providing their signature. Well respected. @liyunzhi-666
> * Jamerduhgamer: A trusted and long-standing member of the community, actively onboard new clients with real data. @jamerduhgamer
> * Twinquasar: One of the earliest and most respected notaries in the community, renowned for developing numerous applications for the ecosystem. @s0nik42
> * Joss Hua: A core member of the Asian community and a highly esteemed participant of the Venus team, whose inclusion in the group is highly recommended. @Joss-Hua
> * Cryptowhizzard: An exceptionally passionate and proactive notary, actively involved in improving the ecosystem since Filecoin's inception, boasting the most extensive experience among them. @cryptowhizzard
> 
> **5 Community Members:**
> 
> The majority of community members I've encountered are either Notaries or part of storage provider operations.
> 
> **5 Active Storage Providers (SPs):**
> 
> * HOLON: One of the largest and most respected miners from Australia.
> * PIKNIK: An exceptionally active SP based in the USA and the founder of ESPA, earning trust and recognition as a reliable entity.
> * SEAL: Known for fostering the best collaborations in global data storage, with a deep understanding of valuable data.
> * GREATER HEAT: Highly respected among large enterprise miners in Asia, serving as the host for the prestigious DSPA event and a trusted community player.
> * DCENT: One of the most well known European miners since Filecoin's inception, possessing a wealth of experience as a data preparer and demonstrating excellent networking and distribution skills. Furthermore, they are vocal and actively engaged members of the community.
> 
> These individuals and entities are vital contributors to the growth and advancement of the Filecoin ecosystem. Recognizing their efforts and encouraging collaboration among them will undoubtedly lead to further progress and success.
> 
> _(DSS/DLTX are also on this list)_

@herrehesse How can you be like a frog in a well !

**Comment by junyaoren** [comment]
I think this proposal is a pretty good starting point for better governance! But a lot more need to be optimized, for example: 
1. Why only 5 * 3 + 1 people in the commitee? And sometimes there are overlaps among different roles, and why not more?
2. How often shall the members of the committee be updated? How the act of the committee be corrected when needed? 
3. How does the voting process work? Vote in a meeting? On-chain signature? Who are going to vote and how the result will be checked and guaranteed to be fraud-proof?



Meanwhile, I would suggest two possible alternatives (though both of them are very preliminary for now)
1. Maybe try something like the governance system in GovernorAlpha from Compoud community and use contract to propose/execute
2. Set up a jury-like mechanism. Instead of only 5 of each, for every round of decision (of removal of notary or Datacap), we can randomly choose like 100 clients/SP's/notaries each to form a jury and those chosen submit their opinion by signing with their private key on FVM. 

Hope this might help!

**Comment by coinmini** [comment]
> As stated previously, there might be a conflict of interest if this proposal is approved : notaries and service providers should not be on the committee because they are involved in the dispute. This could lead / threaten members to vote a certain way and influence the decision-making process.

oppose the proposal

**Comment by junyaoren** [comment]
Basically, probably we need a "United Nation" here, but definitely, we do not want to have the "Big Five", LoL.

**Comment by nothingjustaminer** [comment]
A blockchain should trust no one. Not notaries, not filplus gov team, not even PL. 

**If you think we need to trust PL, I'd suggest trusting AWS instead.** 

There are always people who benefit from social trust layer and others who suffer from it. Thats why, we need code to have a unified standard and make the execution of the standard trustlessly. 

This is also the original reason for the existence of blockchain. **Decentralisation is not the exact goal of blockchain, trustless is the goal.** 

It is impossible for trustless and social trust layer to exist in Filecoin core protocol at the same time. It's an unsolvable paradox. 

Hope all notaries and storage providers will join in the cancellation of Fil plus. Please make Filecoin trustless again.

**Comment by Dave-lgtm** [comment]
We're against this proposal. 
Too much of our energy is spent here for KYC/KYB,  and it's not the right direction.

**Comment by Chris00618** [comment]
> If you really want the good-will and trust of the community : 1.) cut the power multiplier 2.) cut the data cap quota
> 
> Blockchains are meant to be permissionless. We all know that. Just declare FIL+ a success and phase it out completely over 6 to 12 months. The longer this drags on the more people will get involved.

That's exactly what I want to express, and have already submitted the proposal as below:
https://github.com/filecoin-project/notary-governance/issues/928

Feel free to comment please.

**Comment by jennijuju** [comment]
(Discalimer: pinions expressed below are my own & do not express the views of the teams/people I work with).


Imho,  this proposal as it is is lack of a lot of details & vote on such proposals is counterproductive. So far, I personally dont think the current proposal should pass.


If the problem is defined as

> Still, how disputes are closed/decided on has been controversial and requires a more systemized way to reach a consensus.

Im not too sure how creating a decision making committee with an even smaller sampled group will resolve this issue effectively. This seems to me has a risk of adding bureaucracy to the system and I personally think both notary & SP group has conflict of interest on this matter. 

It also doesn't fully follow the following[ principles]https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0003.md#principles) of FIL+:

>  Filecoin Plus should strive to promote greater decentralization of control and points of failure

The small size of the group creates centralization of the control & low cost (close to 0) for being a bad actor in the system drastically increases points of failure.


> Low-Cost Dispute Resolution

I foresee challenges in disputing the committee's well behaving in the future. 


> Parties in Filecoin Plus (Root Key Holders, Notaries, and Clients) all start with a limited amount of trust and power

This is a new group in the FIL+ program, however how much power they will get instantly is unknown and could be potentially huge.

> The ultimate goal of Filecoin Plus is to accelerate the timeframe over which storage goods and services on Filecoin become more useful and attractive.

I am not sure if this service will make Filecoin a more attractive storage network, or how it contributes to it. 

> There are five main stakeholder roles in the Filecoin ecosystem: clients, miners, developers, token holders, and ecosystem partners.

I think the above five main stakeholders of Filecoin still remains, and this proposal excluded > 50% stakeholder coverage.

> The scope of community governance involves shaping the rubrics, rules and processes, rather than specific cases.

The rubric of how this committee election is going to be is unclear.

**Comment by lyjmry** [comment]
Remove the phasing out fil+ and let this damn fight end. Where there are people involved, there is chaos.

**Comment by lyjmry** [comment]
Phase out fil+ and get this fucking fight over with. Where there are people involved, there is chaos.

**Comment by YuanHeHK** [comment]
I understand that disputes in this kind of public blockchain project should be implemented through agreements, and code is the law. FIL+ is now clearly becoming more and more centralized. This runs counter to the goals and vision of distributed storage.

I strongly disagree with this proposal.

**Comment by The-Wayvy** [comment]
This really is absurd

We invented blockchains to have a neutral and transparent way of incentivizing 
servers.

Filecoin then appointed a bureaucracy to redistribute block rewards in spite of there being no precedent or principled argument in favor of doing so. 

The bureaucracy has proven corruptible and has centralized the network to the surprise of absolutely nobody.

Instead of acknowledging their mistake and agreeing to wind down FIL+, the bureaucracy is suggesting the exact opposite, that it be expanded.

Again, this comes as a surprise to absolutely no one.

Juan is already having to defend FIL+ in public forums like he did a few days ago at ETHCC.

Public awareness of this mistake will continue to grow.

**Comment by cycpilies** [comment]
> Fil+is a joke that violates the decentralization protocol. Now it is proposed to centralize management and stop talking nonsense. It is recommended to cancel fil+.
> 
> Filecoin is such a great project, such a great track. Don't be managed by a few ignorant people and lead to destruction.

Yes, U are right!

**Comment by flyworker** [comment]
![image](https://github.com/filecoin-project/notary-governance/assets/8363795/07e7c950-75e7-45c5-940a-ac7b42af2a4f)

**Comment by miao198822** [comment]
> It is not suitable to recommend anyone at this time

**Comment by herrehesse** [comment]
@0xXPunkX, I want to express my gratitude for your immense kindness and for reminding me that abusive behavior should never be tolerated. For the longest time, I mistakenly believed that such behavior was acceptable as long as it led to financial gain.

Additionally, it seems that you overlooked the word "nearly" in my initial sentence. Please allow me to kindly point out this oversight.

**Comment by miao198822** [comment]
This can only make FIL+ more corrupt！！

**Comment by spaceT9** [comment]
This is not a good idea, it makes more complicated.

**Comment by Chuangshi1** [comment]
Bad proposal！

**Comment by nothingjustaminer** [comment]
Hello @herrehesse , let's think differently. 

I see many notaries and storage providers are not your fans and will probably not sign your datacap applications in the future. Only if you somehow organize a committee to support your applications, you may be end up quitting the network because of the 10x multiplier made your future CC sectors not competitive at all. 

However, if we terminate the filplus program on Filecoin L1, you will still have fair chances to serve the Filecoin network and earn block reward.
 
With that being said, would you consider letting the filplus end?

**Comment by herrehesse** [comment]
![Screenshot 2023-07-26 at 12 05 54](https://github.com/filecoin-project/notary-governance/assets/70132857/5d591bd0-b539-45a3-beee-75b80ea5cc9d)

I notice that you're expressing many ideas and suspicions for someone who recently joined this party, especially considering our longstanding involvement of over two years. I must reject such statements coming from an unfamiliar account. I hope you understand, my friend @nothingjustaminer.

**Comment by herrehesse** [comment]
I can mostly agree with your above statements @nothingjustaminer

**Comment by Filplus-govteam** [comment]
Seeing widespread pushback to this proposal, the proposal has been rejected by the community
