### ISSUE TITLE
T&T Committee - Open election process

### ISSUE THREAD

**Issue by Filplus-govteam** [filecoin-project/notary-governance#941]
## Issue Description
Based on issue #940, we are kicking off the election issue parallel given the urgency of the matter. While this issue is dependent on the outcome of issue 940, it is in the community's interest to initiate this process

## Proposed Solution(s)

In the comments below, we encourage candidates that would like to be part of the T&T Committee to answer the following questions:

Are you a current active notary? - Yes/No
Have you previously been a notary? - Yes/No

Please share a pitch, either in the video (less than 1 minute), ppt/pdf (less than 5 slides) or text form (less than 150 words) why the community should elect you to the T&T Committee

Would you like to share evidence of your past Due Diligence? - Yes/No 

### Proposed Timeline

Create the GitHub issue for the community to express interest in being part of the T&T Committee 0 Fri Jul 21 2023

Voting period - Until Tuesday, Aug 1st 2023

The decision was announced based on public voting - Monday, August 7th 2023

**Comment by flyworker** [comment]
> 

I don't see in #940 community's interests is to initiate the process. 
Can you cancel this process?

**Comment by The-Wayvy** [comment]
We need less bureaucracy, not more.

Start cutting data cap quotas and the power multiplier. 

No one outside of Filecoin is working on a Permissioned L1

**Comment by kenzz45** [comment]
It is very disrespectful to the community to post this content before https://github.com/filecoin-project/notary-governance/issues/940 receives majority support.

**Comment by cryptowhizzard** [comment]
> It is very disrespectful to the community to post this content before #940 receives majority support.

For someone being around for 1 day in this community i guess some humbleness will suit better

**Comment by The-Wayvy** [comment]
@Filplus-govteam 

It is premature to discuss elections until all flaws in the proposed committee's design are addressed. 

**### First**
Notaries and SPs cannot be on the committee because they are personally involved in the disputes they will be adjudicating.

Just as conflict of interest disqualifies a citizen from jury duty, being a party to the dispute definitely disqualifies notaries and SPs from committee membership.

Imagine someone who embezzled funds being on the jury of their own case. Likewise for someone whose funds were embezzled. This applies to every single miner in every single dispute. Either you got subsidized or you were taxed to fund the subsidy of your competitors.

With our 'uncompensated' notaries, things are even shadier. 

It is worth investigating how a notary committee member would behave in the following situations

1.) they themselves are under investigation
2.) another notary on the board is under investigation
3.) a notary not on the board is under investigation

Likewise with SPs

1.) they got the deal and were subsidized
2.) they didn’t get the deal and were taxed

### **Second**
The person who has authority to slash a committee member’s stake can pressure them to vote a certain way by threatening to get them slashed if they don’t.

**Comment by kenzz45** [comment]
> > It is very disrespectful to the community to post this content before #940 receives majority support.
> 
> For someone being around for 1 day in this community i guess some humbleness will suit better

For someone who is loathed by members of the community i guess shutting up will suit them better.

**Comment by jennijuju** [comment]
While I have strong reservation against the current proposal in #940, I can see how this process can be orthogonal (even tho it might result in wasted effort across the community if #940 doesnt pass). Review this process alone, it is unclear to me on who can be on this committee & is there an election rubric:
- Can one be applying as an individual / entity?
- whats the qualification requirement?
- how long would the status last?
- whats responsibilities?
- what are the guidelines one should follow with this power?
- do I have to be a notary once to join this committee?
-... and much more

> Voting period - Until Tuesday, Aug 1st 2023

This is a a large change to the FIL+ governance - Is this widely announced in the Filecoin community? I can only find one mention in[ Filecoin slack](https://filecoinproject.slack.com/archives/C0405HANNBT/p1689950392925779) (the channel only has ~400 members & only got two reactions) & I expect more network stakeholder groups to be aware and express their opinion on this proposal before we move forwards.

**Comment by spaceT9** [comment]
#940 should be finalized before the selection process, otherwise, it is meaningless.

**Comment by Filplus-govteam** [comment]
Seeing widespread pushback, this issue is being closed
