### ISSUE TITLE
[Appeal] Request to remain active Notary

### ISSUE THREAD

**Issue by joshua-ne** [filecoin-project/notary-governance#950]
This is josh from NonEntropy Tech, and I am appealing to remain active notary. 

1. For the past months, we have attended some governance calls. Though we missed some of them due to conflicts of schedule, we did checked the recordings afterwards. We might have done little on LDN due diligence and signing, and here are a few points that I want to explain: a. previously, we thought as a notary, our main job was to verify random regular client and allocate small scale (10-50TB) Datacap to them and do track record of the usage. And for this, we have designed a whole process and evaluation system during and after the notary application. We did not pay enough attention to LDN part at first and it's our bad. b. Our group of limited size had to put more attention to software development, and the reason was that more and more of our clients (SP's) need to optimize the system to better adapt to large scale of application of DC deals. The good news that the new system is now done and we have more time to fulfil our due diligence. 

2.  In the next 30 days, actually starting from  past week, we have been doing and will keep doing the following things: a. Check LDN applications, including their proposed data (the content, the size, etc.), the storage providers who are storing their data (we are using a sophisticated system to do this, tracking and linking the SP's, and we are still optimizing the system). b. We have also signed a few of the LDN's that look good to us. c. We are developing tools to check the retrievability of the data (since we've found that every now and then, or from some special occasions, the bot does not give perfectly accurate result) d. We are participating more and more on community discussions, including in GitHub, slack channels and on notary governance and T&T WG calls. 

To conclude, we are such a notary that is neutral (that's also why we are not engaging in any LDN disputes yet) and that we care enough about Filecoin/Fil+/Fil-community (because we have been working full time on Filecoin for more then 3 years and that's also why we are filing this appeal). We believe we can have a positive impact in the notary community, especially for the time being, when there are a lot of arguments and disputes. 

Thanks for reading and please let me know if you have any questions or need any further information.

**Comment by raghavrmadya** [comment]
If you are able to provide evidence and objectivity to support what you said above, it would be more reasonable to consider this appeal. Here is an [example ](https://github.com/filecoin-project/notary-governance/issues/959)from another notary that was flagged for inactivity. 

Your 2nd point isn't valid here as it posts dates when the inactivity issue was passed. Taking your activity AFTER missing the SLA is unfair to other notaries who actively engage consistently.

Attending gov calls is a very low bar to appeal. Your [application](https://github.com/filecoin-project/notary-governance/issues/445) makes big claims and promises that you used to get elected but you say you have done little on LDN due diligence and signing. 

This is hard to believe - "previously, we thought as a notary, our main job was to verify random regular client and allocate small scale (10-50TB) Datacap to them and do track record of the usage"
<img width="1015" alt="Screenshot 2023-08-11 at 1 50 02 PM" src="https://github.com/filecoin-project/notary-governance/assets/91579519/35436777-0243-4e2c-9508-e2981f6d21d9">

You've been around for a long time. How can we trust this claim?

**Comment by junyaoren** [comment]
Thank you for your questions and here is my response to them:

1. I made my 2nd point because, during the governance meeting on July 25, 2023, Kevin @Kevin-FF-USA  made it quite clear that in the appeal, one should include "detail how the SLA level committed to in application will be met in the next 30 days". And now it has been almost 3 weeks since that claim, we believe that we are doing a pretty good job since then. 
2. If you could read our application you quoted above more carefully, you may notice that most part of the application (except providing our information) is about allocating datacap to clients (as in the "Allocation Plan" part). And our designing and thinking were also around this task, which spend us quite a lot of time to construct, discuss and optimize, as you can still see them (links from our application: https://drive.google.com/file/d/1aTtr4W-MawoKB7O9ozrnZdLC_eU9Lhll/view and https://docs.google.com/spreadsheets/d/14xLS4HucccTDkx2JK60uYBa-q6UiJrZo/edit#gid=1000875936). And this is why "previously, we thought as a notary, our main job was to verify random regular client and allocate small scale (10-50TB) Datacap to them and do track record of the usage". 

Again, thanks for reading and reconsidering our appeal

**Comment by raghavrmadya** [comment]
Thanks for clarifying. Willing to support your appeal  to remain an active notary

**Comment by junyaoren** [comment]
Thank you very much, @raghavrmadya for your support! We will try our best to contribute to the FIL+ community.
