### ISSUE TITLE
[Appeal] Request to remain active Notary

### ISSUE THREAD

**Issue by Holiday507** [filecoin-project/notary-governance#954]
Hi, my name is holiday, I'm in charge of Filecoin Plus project of CodoonHealth.
I am proud of being a notary since the fourth round of notary election.
We participated in the Summit as eco-partners in 2020 and being active in the Filecoin community for 3 years. I introduce Filecoin to my partners in our industry.
I attended almost every notary meeting and learned a lot about what a notary should do.
At first, the Filecoin Plus APP had some procedural problems, affecting the approval. The community have some discussions on the approval, and many rules are not very clear. Now the rules of the community are becoming more and more perfect, and I have learned a lot about what to do as a notary, I think I can do well as a notary in the future. 
I hope Filecoin plus governance team give us the opportunity to retain our notary status.
```[tasklist]
### Tasks
```

**Comment by raghavrmadya** [comment]
If you are able to provide evidence and objectivity to support what you said above, it would be more reasonable to consider this appeal. Here is an https://github.com/filecoin-project/notary-governance/issues/959from another notary that was flagged for inactivity.

Your appeal is merely claims and words without any substantial proof for comments like " community has some discussions on the approval, and many rules are not very clear" is not a sufficient argument. It is your job as a notary to reach out for support instead of being inactive.

Without evidence of engaging in due diligence, even if you did not sign, the appeal is very weak IMO
