### ISSUE TITLE
Discussion: Greater China - HUGE datacap discrepancy between 1st time application in China and rest of the world

### ISSUE THREAD

**Issue by Fatman13** [filecoin-project/notary-governance#96]
## Issue Description
For 1st time datacap requester, applicants in China is getting `10Gib` compared with others in different regions getting `1Tib`. That is about **100X** difference.  

## Impact
This creates a lot of overheads in getting datacap in China while applicants are required to constantly engage with notary for applications especially when the review process of the notary itself is fairly long given no incentives and notaries have their own regular daily job.

## Proposed Solution(s)
Unify 1st time datacap allocation quantity across regions. Besides, according to this [thread in slack](https://filecoinproject.slack.com/archives/C01KCAAURAN/p1613071045190700?thread_ts=1613014815.155600&cid=C01KCAAURAN), datacap is designed to be abundant not scarce.

## Related Issues
CN
https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/127

EU
https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/136

**Comment by NeoGe-IPFSMain** [comment]
Hi @Fatman13, I am afraid the amount of DataCap allocated to clients highly depends on the notary. Each notary has different approaches on DataCap allocation. As far as I know, some notaries in the China area are willing to allocate a larger amount of DataCap to the 1st request clients: https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/72 

I encourage you to try to request DataCap from other notaries if single notary couldn't meet your request at this time.

**Comment by Fatman13** [comment]
Hello, @NeoGe-IPFSMain,

Thanks for the reply!

> I am afraid the amount of DataCap allocated to clients highly depends on the notary.

That is exactly what I propose to fix. To me, it doesn't make too much sense when only one notary out all is allocating 100X less datacap to 1st time applicants. Plus, it goes against the design that datacap should be abundant. I guess it will be up to community to decide what is best for fplus in the next governance call.

**Comment by Eliovp** [comment]
This is a good thing.
Compare the Chinese region to every other region in the world. Yes, that's correct, it's xxx times bigger.
If we want to create a decentralized network, allocation to China should be much much smaller.
If it was up to me, notaries for the Chinese region should be capped entirely.

**Comment by seniorgalvarez** [comment]
Could not agree more with the statement Eliovp just made. Let's be real here, we need a decent balance of storage power around the globe. As long as 99% of this power is located in one region, that specific region should be capped or completely disabled.

**Comment by Fatman13** [comment]
The idea of forcing equal outcome is just bad. We see how that played out in identity politics. The governance should strive to achieve equal opportunities not equal outcome.

**Comment by seniorgalvarez** [comment]
Almost all of the major choices so far where in the advantage of Greater China. Let's be a bit honest here, maybe not your personally, but most large chinese miners don't actually give a damn about storing any data. They are here to make a huge amount of profit from block mining, and I totally understand that. They have invested a lot and took a risk, and now want the playoff. But then don't give me a sad talk about datacap when real EU/US companies are trying to work with Filecoin storing real data and getting incentives for it. It's totally fair.

Also, how are chinese going to cope with a "open" storage network while the chinese government has a tight grip on everything data related? This seems like a unsolvable issue heading into the future. Please help me understand.

**Comment by Fatman13** [comment]
> Almost all of the major choices so far where in the advantage of Greater China.

What major choices are you referring to?

> But then don't give me a sad talk about datacap when real EU/US companies are trying to work with Filecoin storing real data and getting incentives for it.

Are you saying that any Chinese company should not be allocated datacap because they will just store fake data?

> Also, how are chinese going to cope with a "open" storage network while the chinese government has a tight grip on everything data related?

There are plenty of classified data released by whistle blowers which is deemed illegal to disclose could potentially seek asylum in China. Just my 2 cents.

**Comment by seniorgalvarez** [comment]
Do you want my 2 cents?
You try and store this data on your server:

https://en.wikipedia.org/wiki/1989_Tiananmen_Square_protests

**Comment by Eliovp** [comment]
> Do you want my 2 cents?
> You try and store this data on your server:
> 
> https://en.wikipedia.org/wiki/1989_Tiananmen_Square_protests

I have a feeling you triggered the GFW right there 🤷‍♂️

**Comment by Fatman13** [comment]
Okay. If you think those are legit reasons Chinese companies should receive discriminative datacap allocation, I encourage you to create a discussion thread to propose so.

**Comment by cryptowhizzard** [comment]
The word discriminative is, in my humble opinion, not chosen wisely and to quick.

This is not all crypto. This is filecoin, with data storage. Europe stastics for example are are smucked with China miners VPN'ning their 1U Haproxy rented Hetzner machines towards their miners in China ( See attachment ). This has been the case since SR1 and this is done with 2 apparant reasons. One to falsely profit from the rewards beloning to EU miners and two to hide the fact that they are located in China because they know that US company's probably do not want to store data on China miners and they still want to profit from it as they see market and $$$$.

We are now in the next stage of Filecoin, where it is about professional storage and business, the goal of the project. This needs to be done in a professional way as there are company's actively looking to store their data and reading in this topics. 
Exactly this *real* and valuable data is rewarded in Fil+ and this data is carefully screened and scrutinised. This is the whole meaning of Fil+ ... it ain't about block mining and it ain't about storing satelite data already 25000x on the network from SR1.

So my 2 cnts are that if you want to play the game, just play it according to the rules. If played faul then don't yell "discrimination" because that is really cheap. If a GC company needs datacap for a real project there are always notary's who welcome them and when thrust is there, they will get what they need to bring Filecoin and their company forward.

**Comment by Fatman13** [comment]
The word `played faul` is, in my humble opinion, not chosen wisely and to quick.

> This is not all crypto. This is filecoin, with data storage. Europe stastics for example are are smucked with China miners VPN'ning their 1U Haproxy rented Hetzner machines towards their miners in China. This has been the case since SR1 and this is done with 2 apparant reasons. One to falsely profit from the rewards beloning to EU miners and two to hide the fact that they are located in China because they know that US company's probably do not want to store data on China miners and they still want to profit from it as they see market and $$$$.

I have no idea what you talked about here is true or not and its out of the scope of this repo. You should probably create another thread in related channel.

> We are now in the next stage of Filecoin, where it is about professional storage and business, the goal of the project. This needs to be done in a professional way as there are company's actively looking to store their data and reading in this topics.
> Exactly this real and valuable data is rewarded in Fil+ and this data is carefully screened and scrutinised. This is the whole meaning of Fil+ ... it ain't about block mining and it ain't about storing satelite data already 25000x on the network from SR1.

If I am not mistaken, are you assuming that no Chinese company has real and valuable data?

> So my 2 cnts are that if you want to play the game, just play it according to the rules. If played faul then don't yell "discrimination" because that is really cheap. If a GC company needs datacap for a real project there are always notary's who welcome them and when thrust is there, they will get what they need to bring Filecoin and their company forward.

You seem to just assume that others played foul. Besides, isn't this the exact forum to propose amendment to existing rules?

**Comment by dkkapur** [comment]
@Fatman13 - thanks for starting this discussion! Would like to bring this back to the original issues raised:
- The initial issue was on the topic of different data cap allocations per region, which I believe @NeoGe-IPFSMain addressed fairly [here](https://github.com/filecoin-project/notary-governance/issues/96#issuecomment-782552952).
- Re "The amount allocated should be following community guideline not to be incorporated into notary strategy. To me, it doesn't make too much sense when only one notary out of all is allocating 100X less datacap to 1st time applicants": IMO, enabling notaries to make educated decisions weighing various factors about a client plus having the flexibility in the system to serve a variety of different needs/scenarios with different notaries is very valuable as well. With a community guideline across all notaries, we could not easily have automated verifiers, or bring in experts in areas that involve very small or very large sets of data to serve as notaries and make decisions on making the most of Filecoin. I think that the current model of letting notaries specify this in their strategy serves the Network and potential clients/services being built on Filecoin.
- Your point on data cap supply being limited is a fair one, though perhaps the solution is to instead increase the # of notaries quickly + provide them with the tools necessary to allocate data cap faster?
- On this notion that data cap should be restricted in certain geographies, my opinion is that this should not be the case. There is a reason why notaries are and should be geo-distributed, because storage needs themselves are and will be disparate across geo-political boundaries. We're trying to build something that is useful for the world here, and should account for varying requirements from clients across boundaries.

**Comment by Fatman13** [comment]
Hello, @dkkapur, thank you for the reply!

Couldn't agree more with you on all your points!

> Your point on data cap supply being limited is a fair one, though perhaps the solution is to instead increase the # of notaries quickly + provide them with the tools necessary to allocate data cap faster?

I think the overarching goal of this thread boils down to how we can make datacap abundant to everyone fairly. If we can have datacap applications approval go faster, then surely that could work too.

**Comment by dkkapur** [comment]
@Fatman13 - given the activity recently from Notaries in the China region (Fenbushi, XnMatrix, 1475, etc.) making a fair bit of progress on DataCap allocations, I'm closing this issue out for the time being. Please feel free to re-open again if there are additional points to discuss. I do generally think we are headed towards another set of notary elections in the near future!
