### ISSUE TITLE
Proposal：Request to remain active Fil+ Notary for POWPOWER

### ISSUE THREAD

**Issue by powpower2022** [filecoin-project/notary-governance#964]
Hi this is POWPOWER and We just attend a governance call in Aug 9th 1:00 UTC.
We am proud of being a notary since the fourth round of notary election.
Thanks for reminding and all the welcome and we are really sorry for the late reply. The POWPOWER account will continue to be used. Due to internal reasons within the company which includes Project manager resignment and site relocation, we missed a lot and caused the lack of signature before. During this period, we have been tightly following up the situation of the community in a timely manner, and we have seen the latest rules. In the future, we will have positive activity against the rules with our SLA. Please don't remove us, thanks!
I hope Filecoin plus governance team give us the opportunity to retain our notary status.

**Comment by raghavrmadya** [comment]
Hi @powpower2022, unfortunately, the failure to flag the aforementioned internal reasons mentioned above to the governance team, is unfair to other notaries if your status as a notary remains active. 

We understand that things happen and situations evolve but because you did not meet your SLA, I do not see a strong reason why the community should allow you to retain your notary status.

You are welcome to apply again in the next round but a violation of an SLA is objective measure and basis for inactivity and removal

**Comment by raghavrmadya** [comment]
If you are able to provide evidence and objectivity to support what you said above, it would be more reasonable to consider this appeal. Here is an [example ](https://github.com/filecoin-project/notary-governance/issues/959)from another notary that was flagged for inactivity
