### ISSUE TITLE
Discussion: decentralization requirements for deal-making / self-dealing limits

### ISSUE THREAD

**Issue by dkkapur** [filecoin-project/notary-governance#98]
Issue to discuss ecosystem stakeholders that are both Clients and Miners and receive DataCap that they spend on deals with themselves - raised in #66 and various discussions on Slack and governance calls.

I'd like to start by scoping this conversation specifically to the interaction between a Client that has received DataCap and is making a verified deal with themselves as a Miner. Explicitly, this discussion assumes that Notaries are allocating DataCap in a way that aligns with the principles of the program and are making an ongoing effort to take the "right" decisions. This implies that the Client/Miner entity that indeed have a legitimate use case that is valuable for the network to serve.

Given that - a few opinions: 
- the network should not subsidize deals that are wholly made by an entity with themselves (i.e., if you already have something on your hard disk, why should the network subsidize your continued storage of that data?)
- FIL+ should not be biased towards/against Clients based on the other roles they play in the ecosystem. Each decision point in the flow of DataCap should be independent and as objective as possible (of course, Notaries may add nuance / subjectivity to the system when verifying Clients)
- "decentralization" is a core principle of FIL+, and should be applied to using a set of miners to store valuable data in way that its longevity / long-term retrievability are maximized

Current deals in the FIL+ ecosystem show that Clients value storing data with themselves, since they can guarantee that the Miner meets their requirements / standards / all the liability is on themselves. Considerations for such deals often include:
- latency (distance between Client and Miner)
- reliability
- availability

Proposal:
Clients can store a subset of their DataCap allocated storage deals with themselves. with the following limits in place (defined as DataCap allocated to themselves in deals / total DataCap received from Notaries, at any given point in time):
* <= 100% if they are the only known miner in their region and their data cannot be stored outside of it (as publicly disclosed in their DataCap application)
* <= 50% if they are the only known miner in their region but their data can be stored or backed up in other regions (the remaining DataCap can be used to create 
* <= 33% if there are <= 3 known miners in their region 
* <= 25%

This should be observed through the various efforts on bringing transparency to the FIL+ ecosystem (dashboards, etc. that are being built) and enforced by Notaries in their ability to not grant additional DataCap to Clients that exploit the system. 

This ensures that DataCap is being distributed across Miners, upholds the principle of decentralization, continues to reward real use cases / enables them to come onto the Network, and creates incentivizes for Miners to strive for a higher bar of storage services offered on the network.

**Comment by cryptowhizzard** [comment]
The Fil+ incentive has been established to help incentivize the storage of real data. Therefore new proposals should be properly aligned with the wishes and needs of customers or clients, avoiding creating gaps where it is not interesting anymore for clients to store actual real data on the network.

The current state of the Filecoin network makes it difficult for clients to come across with good ideas and implement them in their current storage structure. Filecoin has not developed far enough to really compete with anything out there.

The main issues from a clients perspective are trust and reliability.

The trust issue can be explained as “the onboarded data should be available at all times for retrieval”. At the current state there is no incentive for miners to make the storage retrievable or available, thus most clients store a copy of the data on their own servers. Applications and user experience thrive on the availability of data. You can not onboard Sterling as a client without this availability, what will you do when Netflix comes knocking at your door?

Reliability is also a large issue for clients. The flow of datacap from notaries to clients to eventually miners has not become steady and stable yet. Miners are unable to process a stable inflow of deals or deals can get lost because of Lotus issues. At this early stage, most miners are far from enterprise level, this causes issues with business clients trying to increase the real data storage on the network.

The miners experience difficulties keeping up with the huge amount of software updates, problems with paying for collateral for TiB’s of daily deals, 10Gbit/s connectivity requests, open-peering networking or even simple chat or email contact. 

There is a lot needed before large clients will onboard with most risks covered. Most miners are simple not “fit” for the job. Some miners focus on high storage capacity with low bandwidth and speed, some miners focus on higher bandwidth with lower storage capacity and some are aiming for the middle ground. Also the Notice & Takedown Policy differs from region to region, making storing certain content difficult for clients in certain regions.

This should all be perfectly fine in a decentralized storage network, but then the clients MUST decide were and how to store their valuable data. Who else can indicate the importance of the data but the client themself? This should not be intertwined percentage-wise into the Filecoin network. This will scare off most client’s trying to onboard onto the Filecoin network, not able to pick their own “quality” of Filecoin miner.

**Comment by benjaminh83** [comment]
I would like to point out another angle to this “issue”. Although the scope of this discussion have been nicely narrowed down to “a Client that has received DataCap and is making a verified deal with themselves as a Miner”, it seems like assumptions already has been made about the client-role, and that might been based on a too simple understanding of the client. 

If we are to make restrictions on self-dealing, then I would prefer to divide the client-role into a “lotus-client” (Operator) role and an end user role. In simple usage of Filecoin for demo and test, it might be the same person, but for real applications on top of Filecoin, it probably is not the case. Let me give you examples and what I think this should reflect on self-dealing limits: 

**A. Simple use case: User has some data on the local disks and want to try out Filecoin/IPFS and saving it on Lotus-miner.** 
1. Lotus-Client operator and end user is the same person.
2. Filecoin is providing trustless storage through use of DLT. Only reason for engaging in a DLT based storage system (including the large overhead in doing so), is to overcome the lag of trust when storing data at some random/no-name storage provider.  
3. We should be able to assume that the user does not have any schizophrenic disease, and therefore should have trust in himself. 
4. In this case, the client should **NOT be allowed to do any self-dealing at all!** Filecoin provides no value to the security of the data, and could just as well just be kept on the users local disks.   
    
**B. Real use case: End-users are storing content with a company, that is using Filecoin as backend, and is offering the end-user a DLT based trustless storage solution, as part of their value proposition.**
1. Lotus-Client operator is the company. End users are the 3rd-party who provides the real data.
2. Filecoin is providing trustless storage through use of DLT. Lotus-Client operator has promised the end user that all data is stored on Filecoin, but also promised that their data is accessible at any time for retrieval.
3. The Lotus-Client operator needs to ensure that data is always accessible from the Filecoin backend. 
4. Multiple copies of the data is needed, but also the required latency, reliability, availability is decided by the Lotus-Client operator, so they will be able to always deliver data access to their 3rd-party (end users). 
5. In this case, the **Lotus-Client operator should be allowed to do some self-dealing, to ensure the availability for the (3rd party) end-user**. That said, self-dealing should never be higher than 50%, as we must assume a minimum of 2 copies on the Filecoin network. So, Lotus-Client operators should be allowed to keep one copy of the content locally (but on chain - as promised to the end user), when they at the same time distribute copies to other miners on the network for backup / disaster recovery purposes. 

I hope this can help to open the definition of client-miner self-dealing, as its not easy for outsiders to understand the business that the Client is doing with their DataCap, but very easy to complain in general. This is why we have the notary function in place… They need to look into the business of the Client, and decide if this is a good REAL use case for Filecoin, and should be rewarded datacap, or if it’s a single entity solely trying to take advantage of self dealing.

**Comment by Eliovp** [comment]
The easiest solution and most probably the only one to avoid self-dealing is to limit the number of Verified deals per miner per day.

If it was up to me, I would **limit it to 1**.

Yes, I know, what if a client wants to store bigger amounts of data with a trusted miner?
Yes, Exceptions should be able to be made.
I guess there are ways around that, exceptions such as making this a one-time thing.
Or to gradually decrease the power increase.

Deal 1 = x 10
Deal 2 = x 7
Deal 3 = x 4
Deal 4 = x 2
Deal 5-.... = x 1

What this also would do, the limitation per verified deal per miner is to force **decentralization**.
Isn't that what it's all about in the first place?

https://filfox.info/en/deal

Have a look at how it's going right now. 
Those verified deals. 
Not very decentralized if you ask me.

@dkkapur

**Comment by NSC-FIL** [comment]
Some mechanism like Eliovp has suggested should be considered IMO.  At the very least an audit/complaint process should be set up for disputes against excessive self-dealing behavior.  Unless clients/miners have a legitimate case (open to scrutiny by the community) for self-dealing verified deals, they should be put on a watchlist or blacklist for Notaries and community members to see.

**Comment by dkkapur** [comment]
@NSC-FIL what are your thoughts around the current audit process: https://github.com/filecoin-project/notary-governance#dispute--audit-framework? Let's discuss more in the upcoming Governance Call if you can make it!
